(function(r){
'use strict';
if(!r||!r.document)return;
const d=r.document;
const S={version:'2.1.0-beta.1',root:null,bar:null,worldEngine:null,worldSession:null,canonEngine:null,canonSession:null,observer:null};
const STYLE=`
.seven-rpg-chatbar{margin:8px 12px 4px;border:1px solid var(--sb-b);border-radius:16px;background:color-mix(in srgb,var(--sb-s) 96%,transparent);color:var(--sb-t);overflow:hidden}
.seven-rpg-chatbar-main{min-height:58px;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 10px}
.seven-rpg-brand{min-width:0;display:flex;align-items:center;gap:10px}.seven-rpg-logo{width:34px;height:34px;object-fit:contain;border-radius:9px;flex:none}.seven-rpg-brand>div{min-width:0;display:flex;flex-direction:column;gap:2px}.seven-rpg-brand strong{font-size:.82rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.seven-rpg-meta{display:flex!important;flex-direction:row!important;align-items:center;gap:5px!important;min-width:0}.seven-rpg-brand span{font-size:.66rem;color:var(--sb-m)}.seven-rpg-current-title{max-width:170px;padding:2px 6px;border:1px solid var(--sb-b);border-radius:999px;background:var(--sb-s2);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--sb-t)!important}
.seven-rpg-chat-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.seven-rpg-mini{min-height:38px;padding:7px 10px;border:1px solid var(--sb-b);border-radius:10px;background:var(--sb-s2);color:var(--sb-t);font:inherit;font-size:.7rem;font-weight:700;cursor:pointer}.seven-rpg-mini[aria-expanded=true]{border-color:color-mix(in srgb,var(--sb-mode) 45%,var(--sb-b));background:color-mix(in srgb,var(--sb-mode) 10%,var(--sb-s2))}
.seven-rpg-drawer{border-top:1px solid var(--sb-b);padding:10px}.seven-rpg-drawer-grid{display:grid;grid-template-columns:1fr 70px minmax(120px,1.5fr) auto;gap:7px}.seven-rpg-title-preview{grid-column:1/-1;min-height:26px;padding:5px 8px;border-radius:8px;background:color-mix(in srgb,var(--sb-mode) 7%,var(--sb-s2));color:var(--sb-m);font-size:.68rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.seven-rpg-title-preview strong{color:var(--sb-t)}.seven-rpg-pack-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.seven-rpg-title-list{display:grid;gap:5px;margin-top:9px}.seven-rpg-title-row{display:flex;align-items:center;gap:7px;padding:7px 8px;border-radius:9px;background:var(--sb-s2);font-size:.72rem}.seven-rpg-title-index{flex:none;min-width:20px;height:20px;display:inline-flex;align-items:center;justify-content:center;border-radius:7px;background:color-mix(in srgb,var(--sb-mode) 12%,transparent);color:var(--sb-m);font-size:.62rem}.seven-rpg-title-list:empty{display:none}.seven-rpg-notice{min-height:0;margin-top:7px;font-size:.68rem;color:var(--sb-m)}.seven-rpg-notice[data-state=ok]{color:#69dbb1}.seven-rpg-notice[data-state=warn]{color:#ffc65c}.seven-rpg-notice[data-state=error]{color:#ff8793}
.seven-rpg-copy-host{position:relative}.seven-rpg-copy{margin:7px 4px 2px auto;min-width:44px;min-height:36px;padding:6px 9px;display:flex;align-items:center;justify-content:center;gap:5px;border:1px solid var(--sb-b);border-radius:10px;background:var(--sb-s2);color:var(--sb-m);font:inherit;font-size:.66rem;font-weight:650;cursor:pointer;touch-action:manipulation}.seven-rpg-copy:hover,.seven-rpg-copy.copied{color:var(--sb-t);border-color:color-mix(in srgb,var(--sb-mode) 45%,var(--sb-b))}.seven-rpg-copy.failed{color:#ff8793}
@media(max-width:620px){.seven-rpg-chatbar{margin:6px 8px 2px;border-radius:14px}.seven-rpg-chatbar-main{padding:7px 8px}.seven-rpg-chat-actions [data-rpg-more]{display:none}.seven-rpg-mini{padding:6px 8px}.seven-rpg-drawer-grid{grid-template-columns:1fr 64px}.seven-rpg-drawer-grid [data-title-name]{grid-column:1/-1}.seven-rpg-drawer-grid [data-title-record]{grid-column:1/-1}.seven-rpg-logo{width:30px;height:30px}.seven-rpg-current-title{max-width:110px}}
@media(prefers-reduced-motion:reduce){.seven-rpg-chatbar,.seven-rpg-mini,.seven-rpg-copy{transition:none!important;animation:none!important}}
`;
const $=s=>d.querySelector(s);
function ensureStyle(){if(d.getElementById('seven-rpg-chat-style'))return;const s=d.createElement('style');s.id='seven-rpg-chat-style';s.textContent=STYLE;d.head.appendChild(s)}
function text(v){return String(v==null?'':v)}
function aura(){const a=S.canonEngine&&S.canonSession?S.canonEngine.audit(S.canonSession):null;const w=a&&((a.characterKnowledge&&a.characterKnowledge.status)==='FAIL'||(a.invariants&&a.invariants.status)==='FAIL'||(a.futureAnchors&&a.futureAnchors.status)==='AT_RISK');r.SevenAurora&&r.SevenAurora.set(w?'warning':'rpg','medium')}
function snapshot(){return{work:S.worldEngine?S.worldEngine.work:null,worldSession:S.worldSession,canonPack:S.canonEngine?S.canonEngine.pack:null,canonSession:S.canonSession}}
function loadWork(pack,opts){if(!r.SevenWorld||typeof r.SevenWorld.createEngine!=='function')throw Error('SevenWorld runtime unavailable');S.worldEngine=r.SevenWorld.createEngine(pack);S.worldSession=S.worldEngine.createSession(opts||{});renderStatus();return snapshot()}
function loadCanon(pack,opts){if(!r.SevenCanon||typeof r.SevenCanon.createEngine!=='function')throw Error('SevenCanon runtime unavailable');S.canonEngine=r.SevenCanon.createEngine(pack);S.canonSession=S.canonEngine.createSession(opts||{});renderStatus();return snapshot()}
function currentContract(){return S.worldEngine&&S.worldSession?S.worldEngine.sceneContract(S.worldSession):null}
function commitVerifiedBeat(input){input=input||{};if(input.verified!==true)return{status:'BLOCKED',reason:'verification-required',session:S.worldSession};if(!S.worldEngine||!S.worldSession)return{status:'BLOCKED',reason:'world-not-loaded'};const out=S.worldEngine.commitBeat(S.worldSession,{beatId:input.beatId,allowBranch:input.allowBranch===true,branchId:input.branchId,playerAction:input.playerAction,playerActionSource:input.playerActionSource,id:input.id});if(out.session)S.worldSession=out.session;renderStatus();return out}
function applyVerifiedDelta(delta,meta){meta=meta||{};if(meta.verified!==true)return{status:'BLOCKED',reason:'verification-required',session:S.canonSession};if(!S.canonEngine||!S.canonSession)return{status:'BLOCKED',reason:'canon-not-loaded'};const out=S.canonEngine.applySceneDelta(S.canonSession,delta||{},{id:meta.id,source:meta.source,authority:meta.authority,transformation:meta.transformation,forceBranch:meta.forceBranch,branchId:meta.branchId});S.canonSession=out.session;renderStatus();return out}
function titleItems(){return S.worldSession&&Array.isArray(S.worldSession.titles)?S.worldSession.titles:[]}
function nextTitleNumber(kind){return titleItems().filter(x=>String(x&&x.kind||'')===String(kind||'episode')).length+1}
function normalizedTitleMeta(kind,meta){meta=Object.assign({},meta||{});if(meta.number==null||!String(meta.number).trim())meta.number=nextTitleNumber(kind);return meta}
function recordTitle(kind,meta){if(!S.worldEngine||!S.worldSession)return{status:'BLOCKED',reason:'world-not-loaded'};kind=String(kind||'episode');meta=normalizedTitleMeta(kind,meta);const preview=S.worldEngine.formatTitle(kind,meta);if(titleItems().some(x=>String(x&&x.title||'').trim().toLocaleLowerCase()===preview.trim().toLocaleLowerCase()))return{status:'BLOCKED',reason:'duplicate-title',title:preview,session:S.worldSession};const out=S.worldEngine.recordTitle(S.worldSession,kind,meta);S.worldSession=out.session;renderTitles();return out}
function logo(){const day=d.documentElement.dataset.sevenTheme==='day';return'./brand/'+(day?'seven-day-white.svg':'seven-night-black.svg')}
function notice(msg,type){const n=S.bar&&S.bar.querySelector('[data-rpg-notice]');if(!n)return;n.textContent=msg;n.dataset.state=type||'info'}
function renderStatus(){if(!S.bar)return;const name=S.bar.querySelector('[data-rpg-world-name]'),state=S.bar.querySelector('[data-rpg-state]');if(name)name.textContent=S.worldEngine?(S.worldEngine.work.title||'Real Works'):'Freeform RPG';if(state){const c=currentContract();state.textContent=c?(c.status==='COMPLETE'?'Complete':c.status):'Chat mode'}renderTitles();aura()}
function renderTitles(){if(!S.bar)return;const out=S.bar.querySelector('[data-rpg-titles]'),current=S.bar.querySelector('[data-rpg-current-title]');const arr=titleItems();if(current){const latest=arr[arr.length-1];current.hidden=!latest;current.textContent=latest?(latest.title||text(latest)):'';current.title=current.textContent}if(!out)return;out.innerHTML='';if(!arr.length){out.textContent='No titles recorded yet.';return}arr.slice(-8).reverse().forEach((item,index)=>{const row=d.createElement('div');row.className='seven-rpg-title-row';const badge=d.createElement('span');badge.className='seven-rpg-title-index';badge.textContent=String(arr.length-index);const label=d.createElement('span');label.textContent=item.title||text(item);row.appendChild(badge);row.appendChild(label);out.appendChild(row)})}
async function jsonFile(file,kind){if(!file)return;try{const data=JSON.parse(await file.text());kind==='world'?loadWork(data):loadCanon(data);notice((kind==='world'?'Real Works':'Canon')+' pack loaded.','ok')}catch(e){notice('Pack rejected: '+e.message,'error')}}
function titlePreview(){if(!S.bar)return;const kindEl=S.bar.querySelector('[data-title-kind]'),numEl=S.bar.querySelector('[data-title-num]'),nameEl=S.bar.querySelector('[data-title-name]'),box=S.bar.querySelector('[data-title-preview]');const kind=kindEl?kindEl.value:'episode',num=numEl?numEl.value:'',name=nameEl?nameEl.value.trim():'';if(!box)return;const number=String(num||'').trim()||String(nextTitleNumber(kind));let title;if(S.worldEngine)title=S.worldEngine.formatTitle(kind,{number,name});else{const labels={episode:'Episode',chapter:'Chapter',arc:'Arc',sideStory:'Side Story',special:'Special',whatIf:'What If',filler:'Filler',game:'Game'};title=(labels[kind]||kind)+' '+number+(name?' — '+name:'')}box.innerHTML='Next: <strong></strong>';box.querySelector('strong').textContent=title}
function titleFromUi(){if(!S.bar)return;const kind=S.bar.querySelector('[data-title-kind]').value,num=S.bar.querySelector('[data-title-num]').value,name=S.bar.querySelector('[data-title-name]').value.trim(),out=recordTitle(kind,{number:num,name});if(out.status==='BLOCKED'){notice(out.reason==='duplicate-title'?'That title already exists.':'Load a Real Works pack before recording a title.','warn')}else{notice('Recorded: '+out.title,'ok');S.bar.querySelector('[data-title-name]').value='';S.bar.querySelector('[data-title-num]').value='';titlePreview()}}
const MSG_SELECTOR='.message,[data-message],.assistant-message,.user-message,.bot-message,.ai-message';
function messageNodes(){const chat=$('#chat');if(!chat)return[];let nodes=[...chat.querySelectorAll(MSG_SELECTOR)];if(!nodes.length)nodes=[...chat.children];return nodes.filter(n=>{if(!n||n.nodeType!==1||!n.textContent||!n.textContent.trim())return false;const p=n.parentElement&&n.parentElement.closest(MSG_SELECTOR);return !p||!chat.contains(p)})}
function hasDirectCopy(n){return[...n.children].some(x=>x.classList&&x.classList.contains('seven-rpg-copy'))}
function copyText(n){const clone=n.cloneNode(true);clone.querySelectorAll('.seven-rpg-copy,.message-actions,[data-copy-ignore]').forEach(x=>x.remove());return String(clone.innerText||clone.textContent||'').trim()}
async function writeClipboard(value){if(!value)return false;if(navigator.clipboard&&typeof navigator.clipboard.writeText==='function'){try{await navigator.clipboard.writeText(value);return true}catch(_){}}
const ta=d.createElement('textarea');ta.value=value;ta.setAttribute('readonly','');ta.setAttribute('aria-hidden','true');ta.style.cssText='position:fixed;inset:auto auto -1000px -1000px;opacity:0;pointer-events:none';d.body.appendChild(ta);try{ta.focus({preventScroll:true})}catch(_){ta.focus()}ta.select();try{ta.setSelectionRange(0,ta.value.length)}catch(_){}let ok=false;try{ok=!!d.execCommand&&d.execCommand('copy')}catch(_){}ta.remove();return ok}
function addCopy(n){if(hasDirectCopy(n))return;const b=d.createElement('button');b.type='button';b.className='seven-rpg-copy';b.setAttribute('aria-label','Copy message');b.title='Copy';b.innerHTML='<span aria-hidden="true">⧉</span><span>Copy</span>';b.onclick=async e=>{e.stopPropagation();const value=copyText(n),label=b.lastElementChild;b.disabled=true;const ok=await writeClipboard(value);b.disabled=false;b.classList.toggle('copied',ok);b.classList.toggle('failed',!ok);label.textContent=ok?'Copied':'Try again';setTimeout(()=>{b.classList.remove('copied','failed');label.textContent='Copy'},1100);if(!ok)notice('Could not copy this message.','error')};n.appendChild(b);n.classList.add('seven-rpg-copy-host')}
function scanCopy(){messageNodes().forEach(addCopy)}
function observeChat(){const chat=$('#chat');if(!chat)return;scanCopy();S.observer&&S.observer.disconnect();S.observer=new MutationObserver(scanCopy);S.observer.observe(chat,{childList:true,subtree:true})}
function setDrawer(open){if(!S.bar)return;const drawer=S.bar.querySelector('[data-rpg-drawer]'),buttons=S.bar.querySelectorAll('[data-rpg-title-toggle],[data-rpg-more]');drawer.hidden=!open;buttons.forEach(b=>b.setAttribute('aria-expanded',open?'true':'false'));if(open)titlePreview()}
function buildBar(){const old=$('.seven-rpg-chatbar');old&&old.remove();const bar=d.createElement('section');bar.className='seven-rpg-chatbar';bar.setAttribute('aria-label','RPG chat controls');bar.innerHTML='<div class="seven-rpg-chatbar-main"><div class="seven-rpg-brand"><img class="seven-rpg-logo app-icon" src="'+logo()+'" alt="Seven"><div><strong data-rpg-world-name>Freeform RPG</strong><div class="seven-rpg-meta"><span data-rpg-state>Chat mode</span><span class="seven-rpg-current-title" data-rpg-current-title hidden></span></div></div></div><div class="seven-rpg-chat-actions"><button class="seven-rpg-mini" data-rpg-title-toggle aria-expanded="false">Titles</button><button class="seven-rpg-mini" data-rpg-more aria-label="RPG options" aria-expanded="false">•••</button><button class="seven-rpg-mini" data-rpg-exit>Exit RPG</button></div></div><div class="seven-rpg-drawer" data-rpg-drawer hidden><div class="seven-rpg-drawer-grid"><select class="seven-ws-field" data-title-kind aria-label="Title type"><option value="episode">Episode</option><option value="chapter">Chapter</option><option value="arc">Arc</option><option value="sideStory">Side story</option><option value="special">Special</option><option value="whatIf">What if</option><option value="filler">Filler</option><option value="game">Game</option></select><input class="seven-ws-field" data-title-num inputmode="numeric" placeholder="Auto #" aria-label="Title number"><input class="seven-ws-field" data-title-name placeholder="Title name" aria-label="Title name"><button class="seven-ws-btn primary" data-title-record>Record</button><div class="seven-rpg-title-preview" data-title-preview></div></div><div class="seven-rpg-pack-actions"><button class="seven-ws-btn" data-rpg-world>Load Real Works</button><button class="seven-ws-btn" data-rpg-canon-file>Load Canon</button></div><div class="seven-rpg-title-list" data-rpg-titles>No titles recorded yet.</div><div class="seven-rpg-notice" data-rpg-notice></div><input type="file" accept="application/json,.json" data-world-file hidden><input type="file" accept="application/json,.json" data-canon-file hidden></div>';
const input=$('.input-area'),chat=$('#chat'),main=$('.main');if(input&&input.parentNode)input.parentNode.insertBefore(bar,input);else if(chat&&chat.parentNode)chat.parentNode.insertBefore(bar,chat);else(main||d.body).appendChild(bar);S.bar=bar;const drawer=bar.querySelector('[data-rpg-drawer]'),wf=bar.querySelector('[data-world-file]'),cf=bar.querySelector('[data-canon-file]');bar.querySelector('[data-rpg-title-toggle]').onclick=()=>setDrawer(drawer.hidden);bar.querySelector('[data-rpg-more]').onclick=()=>setDrawer(drawer.hidden);bar.querySelector('[data-rpg-exit]').onclick=()=>r.SevenWorkspaces&&r.SevenWorkspaces.close();bar.querySelector('[data-rpg-world]').onclick=()=>wf.click();bar.querySelector('[data-rpg-canon-file]').onclick=()=>cf.click();wf.onchange=()=>jsonFile(wf.files[0],'world');cf.onchange=()=>jsonFile(cf.files[0],'canon');bar.querySelector('[data-title-record]').onclick=titleFromUi;['[data-title-kind]','[data-title-num]','[data-title-name]'].forEach(sel=>{const el=bar.querySelector(sel);el.addEventListener(el.tagName==='SELECT'?'change':'input',titlePreview)});bar.querySelector('[data-title-name]').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();titleFromUi()}});titlePreview();return bar}
function mount(root){S.root=root||null;ensureStyle();buildBar();observeChat();renderStatus();d.addEventListener('seven:themechange',themeSync);return S}
function themeSync(){const img=S.bar&&S.bar.querySelector('.seven-rpg-logo');if(img)img.src=logo()}
function unmount(){S.observer&&S.observer.disconnect();S.observer=null;d.removeEventListener('seven:themechange',themeSync);S.bar&&S.bar.remove();S.bar=null;S.root=null;d.querySelectorAll('.seven-rpg-copy').forEach(x=>x.remove());d.querySelectorAll('.seven-rpg-copy-host').forEach(x=>x.classList.remove('seven-rpg-copy-host'))}
r.SevenRpgWorkspace={version:S.version,state:S,mount,unmount,loadWork,loadCanon,currentContract,commitVerifiedBeat,applyVerifiedDelta,recordTitle,snapshot};
})(typeof globalThis!='undefined'?globalThis:this);
