(function(r){
'use strict';
if(!r||!r.document)return;
const d=r.document,$=s=>d.querySelector(s),S={version:'1.0.0',ready:false,observer:null,viewportBound:false};
function qAll(s){return Array.from(d.querySelectorAll(s))}
function visible(el){if(!el||el.hidden)return false;const cs=r.getComputedStyle?getComputedStyle(el):null;return !cs||cs.display!=='none'}
function mark(){const h=d.documentElement;h.dataset.sevenShell='1';h.classList.add('seven-shell-ready');if(d.body)d.body.dataset.sevenShell='1'}
function roomRows(){const list=$('#roomList');if(!list)return[];return qAll('#roomList .room-item').filter(visible)}
function ensureEmpty(){const h=d.documentElement,chat=$('#chat');if(!chat)return;const rows=roomRows(),messages=qAll('#chat .message').filter(visible),empty=!rows.length&&!messages.length;h.dataset.sevenShellEmpty=empty?'1':'0';let node=$('.seven-shell-empty');if(!empty){if(node)node.remove();return}if(node)return;node=d.createElement('div');node.className='seven-shell-empty';node.setAttribute('role','status');node.innerHTML='<strong>What can Seven do for you?</strong><span>Start a new conversation, or just type below. Seven will create the chat when you send.</span><div><button type="button" class="seven-shell-new" aria-label="New chat">New chat</button></div>';const btn=node.querySelector('button');btn.style.cssText='margin-top:18px;min-height:42px;padding:0 16px;border-radius:13px;border:1px solid var(--sb-b);background:var(--sb-s2);color:var(--sb-t);font:inherit;font-weight:700';btn.onclick=function(){const native=qAll('button,[role="button"]').find(x=>/new chat/i.test(String(x.textContent||x.getAttribute('aria-label')||x.title||''))&&!x.classList.contains('seven-shell-new'));if(native){native.click();return}try{if(typeof r.createNewChat==='function')r.createNewChat()}catch(_){}};chat.appendChild(node)}
function sidebarOpen(sidebar){if(!sidebar)return false;return sidebar.classList.contains('open')||sidebar.classList.contains('active')||d.body&&d.body.classList.contains('sidebar-open')||d.documentElement.dataset.sevenShellSidebar==='open'}
function ensureBackdrop(){let b=$('.seven-shell-backdrop');if(b)return b;b=d.createElement('button');b.type='button';b.className='seven-shell-backdrop';b.setAttribute('aria-label','Close navigation');b.style.cssText='display:none;position:fixed;inset:0;z-index:70;border:0;background:rgba(0,0,0,.38);padding:0';b.onclick=function(){const toggle=$('.menu-toggle,[data-seven-menu-toggle]');if(toggle&&visible(toggle))toggle.click();const side=$('.sidebar');if(side){side.classList.remove('open','active')}if(d.body)d.body.classList.remove('sidebar-open');d.documentElement.dataset.sevenShellSidebar='closed';syncSidebar()};d.body&&d.body.appendChild(b);return b}
function syncSidebar(){const side=$('.sidebar'),b=ensureBackdrop();if(!side||!b)return;const mobile=matchMedia('(max-width:820px)').matches,open=mobile&&sidebarOpen(side);d.documentElement.dataset.sevenShellSidebar=open?'open':'closed';b.style.display=open?'block':'none';b.setAttribute('aria-hidden',open?'false':'true')}
function bindSidebar(){const side=$('.sidebar');if(side&&!side.dataset.sevenShellObserved){side.dataset.sevenShellObserved='1';new MutationObserver(syncSidebar).observe(side,{attributes:true,attributeFilter:['class','style']})}if(d.body&&!d.body.dataset.sevenShellSidebarBound){d.body.dataset.sevenShellSidebarBound='1';d.addEventListener('click',function(ev){if(ev.target&&ev.target.closest&&ev.target.closest('.menu-toggle,[data-seven-menu-toggle]'))setTimeout(syncSidebar,0);if(matchMedia('(max-width:820px)').matches&&ev.target&&ev.target.closest&&ev.target.closest('#roomList .room-item'))setTimeout(function(){const toggle=$('.menu-toggle,[data-seven-menu-toggle]');if(sidebarOpen($('.sidebar'))&&toggle)toggle.click();syncSidebar()},0)},true);d.addEventListener('keydown',function(ev){if(ev.key==='Escape'&&sidebarOpen($('.sidebar'))){const toggle=$('.menu-toggle,[data-seven-menu-toggle]');if(toggle)toggle.click();syncSidebar()}})}syncSidebar()}
function viewport(){const vv=r.visualViewport,h=d.documentElement;if(!vv){h.style.setProperty('--seven-shell-vh',(r.innerHeight||0)+'px');return}h.style.setProperty('--seven-shell-vh',Math.round(vv.height)+'px');h.style.setProperty('--seven-shell-vtop',Math.round(vv.offsetTop||0)+'px')}
function bindViewport(){if(S.viewportBound)return;S.viewportBound=true;viewport();r.addEventListener('resize',viewport,{passive:true});if(r.visualViewport){r.visualViewport.addEventListener('resize',viewport,{passive:true});r.visualViewport.addEventListener('scroll',viewport,{passive:true})}}
function label(){qAll('.app-name').forEach(function(el){if(/^seven(?:\s+ai|\.ai)?$/i.test(String(el.textContent||'').trim()))el.textContent='seven.ai'});const t=d.querySelector('title');if(t&&/^Seven(?:\s+AI|\.ai)?/i.test(t.textContent))t.textContent=t.textContent.replace(/^Seven(?:\s+AI|\.ai)?/i,'seven.ai')}
let scheduled=false;function sync(){if(scheduled)return;scheduled=true;queueMicrotask(function(){scheduled=false;mark();label();bindSidebar();ensureEmpty()})}
function boot(){if(S.ready){sync();return S}mark();label();bindViewport();bindSidebar();ensureEmpty();if(d.body&&!S.observer){S.observer=new MutationObserver(sync);S.observer.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','hidden']})}d.addEventListener('seven:workspacechange',sync);d.addEventListener('seven:themechange',sync);S.ready=true;d.dispatchEvent(new CustomEvent('seven:shellready',{detail:{version:S.version}}));return S}
d.readyState==='loading'?d.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
r.SevenShell={version:S.version,state:S,boot:boot,sync:sync};
})(typeof globalThis!='undefined'?globalThis:this);
