(function(r){
'use strict';
if(!r||!r.document)return;
const d=r.document,$=s=>d.querySelector(s),qa=s=>Array.from(d.querySelectorAll(s));
const S={version:'2.0.0',ready:false,observer:null,viewportBound:false,chat:null,model:null};
function visible(el){if(!el||el.hidden)return false;const cs=r.getComputedStyle?r.getComputedStyle(el):null;return !cs||cs.display!=='none'}
function reduced(){return !!(r.matchMedia&&r.matchMedia('(prefers-reduced-motion: reduce)').matches)}
function mark(){const h=d.documentElement;h.dataset.sevenShell='2';h.classList.add('seven-shell-ready');if(d.body)d.body.dataset.sevenShell='2'}
function roomRows(){const list=$('#roomList');return list?qa('#roomList .room-item').filter(visible):[]}
function label(){qa('.app-name').forEach(el=>{if(/^seven(?:\s+ai|\.ai)?$/i.test(String(el.textContent||'').trim()))el.textContent='seven.ai'});const t=d.querySelector('title');if(t&&/^Seven(?:\s+AI|\.ai)?/i.test(t.textContent))t.textContent=t.textContent.replace(/^Seven(?:\s+AI|\.ai)?/i,'seven.ai')}
function ensureEmpty(){const h=d.documentElement,chat=$('#chat');if(!chat)return;const rows=roomRows(),messages=qa('#chat .message').filter(visible),empty=!rows.length&&!messages.length;h.dataset.sevenShellEmpty=empty?'1':'0';let node=$('.seven-shell-empty');if(!empty){if(node)node.remove();return}if(node)return;node=d.createElement('section');node.className='seven-shell-empty';node.setAttribute('role','status');node.innerHTML='<div class="seven-shell-empty-mark" aria-hidden="true">7</div><strong>What can Seven do for you?</strong><span>Start a new conversation, or type below. Seven will create the chat when you send.</span><button type="button" class="seven-shell-new" aria-label="New chat">New chat</button>';node.querySelector('button').onclick=function(){const native=qa('button,[role="button"]').find(x=>/new chat/i.test(String(x.textContent||x.getAttribute('aria-label')||x.title||''))&&!x.classList.contains('seven-shell-new'));if(native){native.click();return}try{if(typeof r.createNewChat==='function')r.createNewChat()}catch(_){}};chat.appendChild(node)}
function sidebarOpen(side){return !!(side&&(side.classList.contains('open')||side.classList.contains('active')||(d.body&&d.body.classList.contains('sidebar-open'))||d.documentElement.dataset.sevenShellSidebar==='open'))}
function ensureBackdrop(){let b=$('.seven-shell-backdrop');if(b)return b;b=d.createElement('button');b.type='button';b.className='seven-shell-backdrop';b.setAttribute('aria-label','Close navigation');b.onclick=function(){const toggle=$('.menu-toggle,[data-seven-menu-toggle]');if(toggle&&visible(toggle))toggle.click();const side=$('.sidebar');if(side)side.classList.remove('open','active');if(d.body)d.body.classList.remove('sidebar-open');d.documentElement.dataset.sevenShellSidebar='closed';syncSidebar()};d.body&&d.body.appendChild(b);return b}
function syncSidebar(){const side=$('.sidebar'),b=ensureBackdrop();if(!side||!b)return;const mobile=matchMedia('(max-width:820px)').matches,open=mobile&&sidebarOpen(side);d.documentElement.dataset.sevenShellSidebar=open?'open':'closed';b.hidden=!open;b.setAttribute('aria-hidden',open?'false':'true')}
function bindSidebar(){const side=$('.sidebar');if(side&&!side.dataset.sevenShellObserved){side.dataset.sevenShellObserved='1';new MutationObserver(syncSidebar).observe(side,{attributes:true,attributeFilter:['class','style']})}if(d.body&&!d.body.dataset.sevenShellSidebarBound){d.body.dataset.sevenShellSidebarBound='1';d.addEventListener('click',ev=>{const target=ev.target&&ev.target.closest?ev.target.closest('.menu-toggle,[data-seven-menu-toggle]'):null;if(target)setTimeout(syncSidebar,0);if(matchMedia('(max-width:820px)').matches&&ev.target&&ev.target.closest&&ev.target.closest('#roomList .room-item'))setTimeout(()=>{const toggle=$('.menu-toggle,[data-seven-menu-toggle]');if(sidebarOpen($('.sidebar'))&&toggle)toggle.click();syncSidebar()},0)},true);d.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&sidebarOpen($('.sidebar'))){const toggle=$('.menu-toggle,[data-seven-menu-toggle]');if(toggle)toggle.click();syncSidebar()}})}syncSidebar()}
function sidebarMeta(){const list=$('#roomList');if(list&&list.parentNode&&!$('.seven-shell-section-label')){const n=d.createElement('div');n.className='seven-shell-section-label';n.textContent=/^ar\b/i.test(d.documentElement.lang)?'المحادثات':'Chats';list.parentNode.insertBefore(n,list)}qa('button,[role="button"]').forEach(x=>{const s=String(x.textContent||x.getAttribute('aria-label')||x.title||'').trim();if(/^new chat$/i.test(s))x.classList.add('seven-shell-native-new')})}
function viewport(){const vv=r.visualViewport,h=d.documentElement;if(!vv){h.style.setProperty('--seven-shell-vh',(r.innerHeight||0)+'px');return}h.style.setProperty('--seven-shell-vh',Math.round(vv.height)+'px');h.style.setProperty('--seven-shell-vtop',Math.round(vv.offsetTop||0)+'px')}
function bindViewport(){if(S.viewportBound)return;S.viewportBound=true;viewport();r.addEventListener('resize',viewport,{passive:true});if(r.visualViewport){r.visualViewport.addEventListener('resize',viewport,{passive:true});r.visualViewport.addEventListener('scroll',viewport,{passive:true})}}
function copyText(text){text=String(text||'').trim();if(!text)return Promise.resolve(false);if(r.navigator&&r.navigator.clipboard&&typeof r.navigator.clipboard.writeText==='function')return r.navigator.clipboard.writeText(text).then(()=>true).catch(()=>fallbackCopy(text));return Promise.resolve(fallbackCopy(text))}
function fallbackCopy(text){try{const ta=d.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.cssText='position:fixed;opacity:0;pointer-events:none;inset:0';d.body.appendChild(ta);ta.select();const ok=d.execCommand&&d.execCommand('copy');ta.remove();return !!ok}catch(_){return false}}
function messageText(msg){const src=msg.querySelector('.message-content,.content,.bubble')||msg,clone=src.cloneNode(true);clone.querySelectorAll('.seven-shell-message-actions,.seven-rpg-copy,.copy-btn,[data-copy],[data-seven-copy],button,script,style').forEach(x=>x.remove());return String(clone.innerText||clone.textContent||'').trim()}
function ensureMessageActions(){qa('#chat .message.user,#chat .message.assistant').forEach(msg=>{if(msg.dataset.sevenShellActions==='1')return;msg.dataset.sevenShellActions='1';if(msg.querySelector('.copy-btn,[data-copy],[data-seven-copy],[aria-label^="Copy" i],[title^="Copy" i]'))return;const bar=d.createElement('div');bar.className='seven-shell-message-actions';const copy=d.createElement('button');copy.type='button';copy.className='seven-shell-copy';copy.setAttribute('aria-label','Copy message');copy.title='Copy';copy.innerHTML='<span aria-hidden="true">⧉</span><span>Copy</span>';copy.onclick=async ev=>{ev.preventDefault();ev.stopPropagation();const ok=await copyText(messageText(msg));const label=copy.lastElementChild;if(label){label.textContent=ok?'Copied':'Copy';setTimeout(()=>{if(label.isConnected)label.textContent='Copy'},1100)}};bar.appendChild(copy);msg.appendChild(bar)})}
function ensureJump(){const chat=$('#chat');if(!chat)return;let b=$('.seven-shell-jump');if(!b){b=d.createElement('button');b.type='button';b.className='seven-shell-jump';b.setAttribute('aria-label','Jump to latest message');b.title='Latest';b.innerHTML='<span aria-hidden="true">↓</span>';b.onclick=()=>chat.scrollTo({top:chat.scrollHeight,behavior:reduced()?'auto':'smooth'});(d.body||d.documentElement).appendChild(b)}const sync=()=>{const far=chat.scrollHeight-chat.scrollTop-chat.clientHeight>260;b.classList.toggle('show',far);b.setAttribute('aria-hidden',far?'false':'true')};if(S.chat!==chat){S.chat=chat;chat.addEventListener('scroll',sync,{passive:true})}sync()}
function resizeInput(){const el=$('#userInput');if(!el||!('scrollHeight'in el))return;const max=Math.max(120,Math.min((r.visualViewport?r.visualViewport.height:r.innerHeight||600)*.34,320));el.style.height='auto';el.style.height=Math.min(Math.max(48,el.scrollHeight),max)+'px'}
function bindComposer(){const el=$('#userInput');if(el&&!el.dataset.sevenShellInput){el.dataset.sevenShellInput='1';el.addEventListener('input',resizeInput,{passive:true});el.addEventListener('focus',()=>d.documentElement.dataset.sevenShellKeyboard='1');el.addEventListener('blur',()=>{d.documentElement.dataset.sevenShellKeyboard='0';setTimeout(viewport,50)});if(!el.getAttribute('placeholder'))el.setAttribute('placeholder',/^ar\b/i.test(d.documentElement.lang)?'اكتب إلى seven.ai':'Message seven.ai');resizeInput()}const composer=$('.composer');if(composer)composer.dataset.sevenShellComposer='1'}
function ensureModelChip(){const select=$('#modelSelect'),top=$('.topbar');if(!select||!top)return;let chip=$('.seven-shell-model-chip');if(!chip){chip=d.createElement('button');chip.type='button';chip.className='seven-shell-model-chip';chip.setAttribute('aria-label','Choose model');chip.innerHTML='<span class="seven-shell-model-dot" aria-hidden="true"></span><span data-seven-shell-model>Model</span><span aria-hidden="true">⌄</span>';const title=top.querySelector('.title,#roomTitle');title?title.insertAdjacentElement('afterend',chip):top.appendChild(chip);chip.onclick=()=>{const custom=$('.seven-model-trigger');if(custom){custom.click();return}try{select.focus();select.dispatchEvent(new MouseEvent('click',{bubbles:true}))}catch(_){}}}const opt=select.selectedOptions&&select.selectedOptions[0],name=opt?String(opt.textContent||opt.value||'Model').trim():'Model';const label=chip.querySelector('[data-seven-shell-model]');if(label&&label.textContent!==name)label.textContent=name;if(S.model!==select){S.model=select;select.addEventListener('change',sync,{passive:true})}}
function tuneTools(){const picker=$('.seven-mode-picker');if(picker)d.documentElement.classList.add('seven-shell-mode-ready');const attach=$('[data-seven-attach-trigger],.composer-tools .tool-btn:not(.toggle)');if(attach)attach.classList.add('seven-shell-attach-trigger');const send=$('#sendBtn,.input-area .send');if(send&&!send.getAttribute('aria-label'))send.setAttribute('aria-label','Send message')}
let scheduled=false;function sync(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;mark();label();bindSidebar();sidebarMeta();bindComposer();ensureModelChip();tuneTools();ensureEmpty();ensureMessageActions();ensureJump()})}
function boot(){if(S.ready){sync();return S}mark();label();bindViewport();bindSidebar();sidebarMeta();bindComposer();ensureModelChip();tuneTools();ensureEmpty();ensureMessageActions();ensureJump();if(d.body&&!S.observer){S.observer=new MutationObserver(sync);S.observer.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','hidden']})}d.addEventListener('seven:workspacechange',sync);d.addEventListener('seven:themechange',sync);S.ready=true;d.dispatchEvent(new CustomEvent('seven:shellready',{detail:{version:S.version}}));return S}
d.readyState==='loading'?d.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
r.SevenShell={version:S.version,state:S,boot,sync};
})(typeof globalThis!='undefined'?globalThis:this);
