(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateCanonJourney=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const check=(v,m)=>{if(!v)throw new Error(m)};
const ROLES=Object.freeze(['witness','helper','parallel_actor','companion','investigator','rival','outsider','protector','messenger','student','specialist']);
const PHASES=Object.freeze(['arrival','attachment','entanglement','trial','turning_point','climax_proximity','resolution','epilogue']);
class CanonJourneyEngine{
 constructor(input={}){check(input.universeId,'CANON_JOURNEY_UNIVERSE_REQUIRED');this.universeId=input.universeId;this.continuityId=input.continuityId||'main';this.strict=input.strict!==false;this.units=new Map();this.events=new Map();this.expectedUnits=[];this.playerRuns=new Map();this.policy={neverInventCanon:true,anchorsImmutable:true,branchOnAnchorBreak:true,requirePrimaryEvidence:true,playerNeverRetroactivelyReplacesCanonActor:true,...clone(input.policy||{})};}
 setExpectedUnits(ids=[]){this.expectedUnits=[...new Set(ids)];return[...this.expectedUnits];}
 addUnit(input={}){check(input.id&&!this.units.has(input.id),'CANON_UNIT_ID_REQUIRED');check(input.order!=null,'CANON_UNIT_ORDER_REQUIRED');check(Array.isArray(input.sourceRefs)&&input.sourceRefs.length,'CANON_UNIT_SOURCE_REQUIRED');const row={id:input.id,order:Number(input.order),kind:input.kind||'episode',sourceTitle:input.sourceTitle||null,sourceRefs:[...input.sourceRefs],continuityId:input.continuityId||this.continuityId,eventIds:[],status:input.status||'verified',ambiguities:[...(input.ambiguities||[])],metadata:clone(input.metadata||{})};this.units.set(row.id,row);return clone(row);}
 addEvent(input={}){check(input.id&&!this.events.has(input.id),'CANON_EVENT_ID_REQUIRED');check(input.unitId&&this.units.has(input.unitId),'CANON_EVENT_UNIT_REQUIRED');check(input.order!=null,'CANON_EVENT_ORDER_REQUIRED');check(Array.isArray(input.sourceRefs)&&input.sourceRefs.length,'CANON_EVENT_SOURCE_REQUIRED');const row={id:input.id,unitId:input.unitId,order:Number(input.order),summary:String(input.summary||''),participants:[...(input.participants||[])],locations:[...(input.locations||[])],causes:[...(input.causes||[])],requiredOutcomes:[...(input.requiredOutcomes||[])],facts:[...(input.facts||[])],sourceRefs:[...input.sourceRefs],anchor:input.anchor!==false,spoilerRank:Number(input.spoilerRank||0),knownBy:[...(input.knownBy||[])],ambiguities:[...(input.ambiguities||[])],insertionSlots:(input.insertionSlots||[]).map((s,i)=>({id:s.id||`${input.id}:slot:${i}`,position:s.position||'after',roles:(s.roles||ROLES).filter(r=>ROLES.includes(r)),locationId:s.locationId||input.locations?.[0]||null,participants:[...(s.participants||[])],purpose:s.purpose||'interstitial',maxImpact:s.maxImpact||'supportive',constraints:[...(s.constraints||[])],sourceEventRef:input.id}))};this.events.set(row.id,row);this.units.get(row.unitId).eventIds.push(row.id);return clone(row);}
 orderedUnits(){return[...this.units.values()].sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id)).map(clone);}
 _unitRank(){return new Map(this.orderedUnits().map((u,i)=>[u.id,i]));}
 orderedEvents(){const rank=this._unitRank();return[...this.events.values()].sort((a,b)=>(rank.get(a.unitId)-rank.get(b.unitId))||a.order-b.order||a.id.localeCompare(b.id)).map(clone);}
 coverageAudit(){const issues=[],expected=this.expectedUnits.length?this.expectedUnits:[...this.units.keys()];for(const id of expected)if(!this.units.has(id))issues.push({code:'MISSING_CANON_UNIT',id});for(const u of this.units.values()){if(!u.sourceRefs.length)issues.push({code:'UNSOURCED_UNIT',id:u.id});if(!u.eventIds.length)issues.push({code:'UNIT_WITHOUT_EVENTS',id:u.id});if(u.status!=='verified')issues.push({code:'UNVERIFIED_UNIT',id:u.id,status:u.status});if(u.ambiguities.length)issues.push({code:'UNIT_AMBIGUITY',id:u.id,count:u.ambiguities.length});}for(const e of this.events.values()){if(!e.sourceRefs.length)issues.push({code:'UNSOURCED_EVENT',id:e.id});for(const c of e.causes)if(!this.events.has(c))issues.push({code:'MISSING_CAUSAL_EVENT',id:e.id,cause:c});if(e.ambiguities.length)issues.push({code:'EVENT_AMBIGUITY',id:e.id,count:e.ambiguities.length});}const sorted=this.orderedUnits();for(let i=1;i<sorted.length;i++)if(sorted[i].order===sorted[i-1].order)issues.push({code:'DUPLICATE_UNIT_ORDER',ids:[sorted[i-1].id,sorted[i].id]});const hard=issues.filter(x=>!['UNIT_AMBIGUITY','EVENT_AMBIGUITY'].includes(x.code));return{pass:hard.length===0&&(!this.strict||issues.length===0),strict:this.strict,expectedUnits:expected.length,loadedUnits:this.units.size,events:this.events.size,issues,authority:'canon_coverage_audit'};}
 assertReady(){const audit=this.coverageAudit();if(!audit.pass)throw Object.assign(new Error('CANON_COVERAGE_INCOMPLETE'),{audit});return audit;}
 canonBackbone(input={}){if(this.strict)this.assertReady();const maxSpoiler=input.spoilerRank??Infinity;return this.orderedEvents().filter(e=>e.spoilerRank<=maxSpoiler).map(e=>({id:e.id,unitId:e.unitId,summary:e.summary,participants:[...e.participants],locations:[...e.locations],causes:[...e.causes],requiredOutcomes:[...e.requiredOutcomes],facts:clone(e.facts),anchor:e.anchor,sourceRefs:[...e.sourceRefs],authority:'verified_canon_event'}));}
 _allSlots(){const rows=[];const rank=this._unitRank();for(const e of this.orderedEvents())for(const slot of e.insertionSlots)rows.push({...clone(slot),eventId:e.id,unitId:e.unitId,unitRank:rank.get(e.unitId),eventOrder:e.order});return rows;}
 weavePlayer(player={},input={}){check(player.id,'PLAYER_ENTITY_REQUIRED');if(this.strict)this.assertReady();const slots=this._allSlots();check(slots.length||!this.strict,'NO_VERIFIED_PLAYER_INSERTION_SLOTS');const desired=new Set((input.roles||ROLES).filter(r=>ROLES.includes(r))),known=new Set(input.knownCharacterIds||[]),preferredLocations=new Set(input.preferredLocations||[]);const scored=slots.map((s,index)=>{let score=50;if(s.roles.some(r=>desired.has(r)))score+=20;if(s.participants.some(p=>known.has(p)))score+=14;if(s.locationId&&preferredLocations.has(s.locationId))score+=10;if(s.maxImpact==='supportive')score+=8;if(s.maxImpact==='observational')score+=4;score-=Math.min(20,index*.15);return{...s,score:+score.toFixed(2)}});const chronological=scored.slice().sort((a,b)=>a.unitRank-b.unitRank||a.eventOrder-b.eventOrder||a.id.localeCompare(b.id));const count=Math.min(Math.max(1,Number(input.beats||8)),chronological.length||1),selected=[];if(chronological.length){for(let i=0;i<count;i++){const idx=Math.round(i*(chronological.length-1)/Math.max(1,count-1));const s=chronological[idx];if(s&&!selected.some(x=>x.id===s.id))selected.push(s);}}const beats=selected.map((s,i)=>({id:`${player.id}:beat:${i}`,phase:PHASES[Math.min(PHASES.length-1,Math.round(i*(PHASES.length-1)/Math.max(1,selected.length-1)))],eventId:s.eventId,unitId:s.unitId,slotId:s.id,role:(s.roles.find(r=>desired.has(r))||s.roles[0]||'witness'),locationId:s.locationId,canonImpact:'interstitial_only',mustPreserve:[...this.events.get(s.eventId).requiredOutcomes],constraints:[...s.constraints],sourceEventRef:s.sourceEventRef,fitScore:s.score}));const run={id:input.runId||`${this.universeId}:${player.id}:${Date.now()}`,playerId:player.id,continuityId:this.continuityId,entry:beats[0]||null,beats,canonEvents:this.events.size,policy:clone(this.policy),authority:'derived_player_weave'};this.playerRuns.set(run.id,run);return clone(run);}
 mediateAction(eventId,action={}){const e=this.events.get(eventId);check(e,'CANON_EVENT_NOT_FOUND');const touched=new Set(action.affects||[]),fixed=new Set(e.requiredOutcomes),breaks=[...fixed].filter(x=>touched.has(x)&&action.effect==='negate'),replaces=action.replacesCanonActor&&this.policy.playerNeverRetroactivelyReplacesCanonActor;if((breaks.length||replaces)&&this.policy.branchOnAnchorBreak)return{mode:'branch_required',eventId,breaks,replacesCanonActor:!!replaces,reason:breaks.length?'CANON_ANCHOR_OUTCOME_CHANGED':'CANON_ACTOR_REPLACEMENT',preserveOriginal:true};if(action.unsourcedCanonClaim&&this.policy.neverInventCanon)return{mode:'reject_as_canon',eventId,reason:'UNSOURCED_CANON_CLAIM'};return{mode:'accommodate_interstitial',eventId,preserveOutcomes:[...e.requiredOutcomes],anchor:e.anchor,allowedImpact:action.impact||'supportive'};}
 accuracyContract(){return{universeId:this.universeId,continuityId:this.continuityId,strict:this.strict,guarantees:['NO_UNSOURCED_CANON_GENERATION','SOURCE_LINEAGE_PER_UNIT','SOURCE_LINEAGE_PER_EVENT','CHRONOLOGY_AUDIT','CAUSAL_REFERENCE_AUDIT','ANCHOR_OUTCOMES_PRESERVED','PLAYER_DIVERGENCE_BRANCHES'],limitation:'Accuracy is bounded by the completeness and correctness of the loaded source evidence; strict mode fails closed on missing, unverified, or ambiguous canon instead of inventing.'};}
}
return{ROLES,PHASES,CanonJourneyEngine};
});