(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateCharacterMind=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};const clamp=(n,a=-100,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
class BeliefLedger{
 constructor(){this.rows=new Map();this.history=[];}
 set(input={}){check(input.id&&input.sourceEventRef,'BELIEF_SOURCE_REQUIRED');const before=this.rows.get(input.id)||null,confidence=Math.max(0,Math.min(100,Number(input.confidence??50))),row={id:input.id,proposition:input.proposition||input.id,stance:clamp(input.stance??0,-100,100),confidence,sourceEventRefs:[...(before?.sourceEventRefs||[]),input.sourceEventRef],updatedAt:input.updatedAt||Date.now(),status:input.status||'held'};this.rows.set(row.id,row);this.history.push({id:row.id,before:clone(before),after:clone(row),sourceEventRef:input.sourceEventRef});return clone(row);}
 pressure(id,input={}){const row=this.rows.get(id);check(row,'BELIEF_NOT_FOUND');check(input.sourceEventRef,'BELIEF_SOURCE_REQUIRED');const resistance=Math.max(.1,Math.min(1,Number(input.inertia??.7))),evidence=clamp(input.evidenceStrength??0),credibility=Math.max(0,Math.min(1,Number(input.credibility??.7))),delta=evidence*credibility*(1-resistance),next=clamp(row.stance+delta);return this.set({id,proposition:row.proposition,stance:next,confidence:Math.min(100,row.confidence+Math.abs(delta)*.2),sourceEventRef:input.sourceEventRef,status:Math.sign(next)!==Math.sign(row.stance)&&Math.abs(next)>20?'reconsidered':row.status});}
 get(id){const r=this.rows.get(id);return r?clone(r):null;}
 view(){return[...this.rows.values()].map(clone);}
}
class EmotionState{
 constructor(input={}){this.axes={calm:clamp(input.calm??50,0,100),fear:clamp(input.fear??0,0,100),anger:clamp(input.anger??0,0,100),hope:clamp(input.hope??50,0,100),sadness:clamp(input.sadness??0,0,100),curiosity:clamp(input.curiosity??50,0,100)};this.lastUpdate=Date.now();}
 apply(delta={}){for(const [k,v] of Object.entries(delta))if(k in this.axes)this.axes[k]=clamp(this.axes[k]+Number(v||0),0,100);this.lastUpdate=Date.now();return clone(this.axes);}
 decay(factor=.08){for(const k of Object.keys(this.axes)){const baseline=['calm','hope','curiosity'].includes(k)?50:0;this.axes[k]+=(baseline-this.axes[k])*Math.max(0,Math.min(1,factor));}return clone(this.axes);}
}
class CharacterMind{
 constructor(input={}){check(input.entityId,'CHARACTER_MIND_ENTITY_REQUIRED');this.entityId=input.entityId;this.values=(input.values||[]).map((v,i)=>typeof v==='string'?{name:v,weight:100-i*8}:{name:v.name,weight:Number(v.weight??50)});this.philosophy=[...(input.philosophy||[])];this.goals=(input.goals||[]).map((g,i)=>typeof g==='string'?{id:g,text:g,weight:80-i*5,status:'active'}:{id:g.id||g.text,text:g.text||g.id,weight:Number(g.weight??50),status:g.status||'active'});this.contradictions=clone(input.contradictions||[]);this.boundaries=[...(input.boundaries||[])];this.riskTolerance=Math.max(0,Math.min(100,Number(input.riskTolerance??50)));this.trustStyle=input.trustStyle||'earned';this.identityInertia=Math.max(0,Math.min(1,Number(input.identityInertia??.8)));this.voice=clone(input.voice||{});this.beliefs=new BeliefLedger();this.emotion=new EmotionState(input.emotion||{});this.logicProofs=[];}
 value(name){return this.values.find(v=>v.name===name)?.weight||0;}
 decide(situation={},candidates=[]){check(candidates.length,'DECISION_CANDIDATES_REQUIRED');const rows=[];for(const c of candidates){const blockers=[];if((c.requiredKnowledge||[]).some(k=>!(situation.knownFacts||[]).includes(k)))blockers.push('MISSING_KNOWLEDGE');if((c.violatesBoundaries||[]).some(b=>this.boundaries.includes(b)))blockers.push('MORAL_BOUNDARY');if(c.impossible)blockers.push('IMPOSSIBLE');let score=-Infinity,features={};if(!blockers.length){let values=0;for(const [name,effect] of Object.entries(c.valueEffects||{}))values+=(this.value(name)/100)*Number(effect||0)*30;let goals=0;for(const [id,effect] of Object.entries(c.goalEffects||{})){const g=this.goals.find(x=>x.id===id&&x.status==='active');if(g)goals+=(g.weight/100)*Number(effect||0)*28;}let beliefs=0;for(const [id,effect] of Object.entries(c.beliefEffects||{})){const b=this.beliefs.get(id);if(b)beliefs+=(b.stance/100)*(b.confidence/100)*Number(effect||0)*18;}const relationships=Object.entries(c.relationshipEffects||{}).reduce((n,[id,e])=>n+((situation.relationships||{})[id]??50)/100*Number(e||0)*15,0);const emotion=(this.emotion.axes.anger/100)*(c.confrontational?10:0)+(this.emotion.axes.fear/100)*(c.dangerous?-14:0)+(this.emotion.axes.curiosity/100)*(c.exploratory?8:0);const risk=Number(c.risk||0)*(this.riskTolerance/100-.5)*.3;const expected=Number(c.expectedUtility||0)*.2;score=values+goals+beliefs+relationships+emotion+risk+expected;features={values:+values.toFixed(2),goals:+goals.toFixed(2),beliefs:+beliefs.toFixed(2),relationships:+relationships.toFixed(2),emotion:+emotion.toFixed(2),risk:+risk.toFixed(2),expected:+expected.toFixed(2)};}rows.push({id:c.id,score:Number.isFinite(score)?+score.toFixed(3):score,blockers,features});}
 rows.sort((a,b)=>b.score-a.score);const chosen=rows.find(x=>Number.isFinite(x.score))||null,proof={entityId:this.entityId,choice:chosen?.id||null,considered:rows.map(r=>({id:r.id,score:r.score,blockers:r.blockers})),decisiveFeatures:chosen?Object.entries(chosen.features).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,3).map(([name,value])=>({name,value})):[],sourceEventRefs:[...(situation.sourceEventRefs||[])],createdAt:Date.now(),kind:'decision_logic_proof'};this.logicProofs.push(proof);return{choice:chosen?.id||null,candidates:rows,proof:clone(proof)};}
 activeMind(memoryItems=[],situation={}){return{entityId:this.entityId,values:clone(this.values),goals:this.goals.filter(g=>g.status==='active').map(clone),philosophy:[...this.philosophy],beliefs:this.beliefs.view(),emotion:clone(this.emotion.axes),relevantMemories:clone(memoryItems),knownFacts:[...(situation.knownFacts||[])],relationships:clone(situation.relationships||{}),voice:clone(this.voice),authority:'derived_character_state'};}
}
class CharacterMindRegistry{
 constructor(){this.minds=new Map();}
 key(gameId,entityId){return`${gameId}|${entityId}`;}
 create(gameId,entityId,input={}){const key=this.key(gameId,entityId);check(!this.minds.has(key),'CHARACTER_MIND_EXISTS');const m=new CharacterMind({entityId,...input});this.minds.set(key,m);return m;}
 get(gameId,entityId){const m=this.minds.get(this.key(gameId,entityId));check(m,'CHARACTER_MIND_NOT_FOUND');return m;}
 similarity(a,b){const A=this.get(...a),B=this.get(...b),av=new Set(A.values.slice(0,5).map(x=>x.name)),bv=new Set(B.values.slice(0,5).map(x=>x.name)),intersection=[...av].filter(x=>bv.has(x)).length,union=new Set([...av,...bv]).size||1;const valueOverlap=intersection/union,voiceKeys=new Set([...Object.keys(A.voice),...Object.keys(B.voice)]),voiceSame=voiceKeys.size?[...voiceKeys].filter(k=>A.voice[k]===B.voice[k]).length/voiceKeys.size:0,philosophySame=A.philosophy.join('|')===B.philosophy.join('|')&&A.philosophy.length?1:0;return+(valueOverlap*.5+voiceSame*.3+philosophySame*.2).toFixed(3);}
 distinctiveness(gameId,entityId,threshold=.82){const target=this.get(gameId,entityId),matches=[];for(const [key] of this.minds){const [g,id]=key.split('|');if(g!==gameId||id===entityId)continue;const similarity=this.similarity([gameId,entityId],[g,id]);if(similarity>=threshold)matches.push({entityId:id,similarity});}return{pass:matches.length===0,matches,entityId:target.entityId};}
}
return{BeliefLedger,EmotionState,CharacterMind,CharacterMindRegistry};
});