(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateCharacters=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};const TIERS=['background','supporting','major','core'];
class CharacterGenesis{
 constructor(runtime,characterEngine){this.runtime=runtime;this.characters=characterEngine;this.records=new Map();}
 draft(gameId,input={}){check(input.need&&input.function,'CHARACTER_PURPOSE_REQUIRED');check(input.origin&&input.whyNow,'CHARACTER_WORLD_ORIGIN_REQUIRED');const record={id:input.id||null,name:input.name||'Unnamed',need:input.need,function:input.function,origin:clone(input.origin),whyNow:input.whyNow,existingConnections:[...(input.existingConnections||[])],tier:input.tier||'supporting',profile:clone(input.profile||{}),visual:clone(input.visual||{}),introduction:clone(input.introduction||{}),status:'draft'};check(TIERS.includes(record.tier),'CHARACTER_TIER');return record;}
 validate(gameId,draft){const issues=[];if(!String(draft.need||'').trim())issues.push('NO_NARRATIVE_OR_WORLD_NEED');if(!String(draft.function||'').trim())issues.push('NO_FUNCTION');if(!draft.origin)issues.push('NO_WORLD_ORIGIN');if(!String(draft.whyNow||'').trim())issues.push('NO_REASON_TO_APPEAR_NOW');for(const id of draft.existingConnections||[])if(!this.runtime.game(gameId).entities.has(id))issues.push(`CONNECTION_MISSING:${id}`);let distinctiveness={pass:true,collisions:[]};if(draft.profile&&Object.keys(draft.profile).length){const temp={gameId,entityId:'__candidate__',values:(draft.profile.values||[]).map((x,i)=>typeof x==='string'?{name:x,weight:100-i*10}:x),philosophy:[...(draft.profile.philosophy||[])],goals:(draft.profile.goals||[]).map((g,i)=>typeof g==='string'?{id:`g${i}`,text:g,weight:70}:g),voice:clone(draft.profile.voice||{})};distinctiveness=this.characters.distinctivenessReport(gameId,temp,draft.distinctivenessThreshold??.82);if(!distinctiveness.pass)issues.push('TOO_SIMILAR_TO_EXISTING_CHARACTER');}return{pass:issues.length===0,issues,distinctiveness};}
 commit(gameId,draft){const gate=this.validate(gameId,draft);check(gate.pass,`CHARACTER_GENESIS_FAILED:${gate.issues.join(',')}`);const entity=this.runtime.registerEntity(gameId,{id:draft.id,name:draft.name,tier:draft.tier,createdFrom:{need:draft.need,function:draft.function,origin:draft.origin,whyNow:draft.whyNow},visualCanon:draft.visual});if(draft.profile&&Object.keys(draft.profile).length)this.characters.createProfile(gameId,entity.id,draft.profile);const rec={entityId:entity.id,gameId,tier:draft.tier,introduction:clone(draft.introduction),createdAt:Date.now(),promotions:[]};this.records.set(`${gameId}:${entity.id}`,rec);return{entity:clone(entity),record:clone(rec)};}
 promote(gameId,entityId,newTier,input={}){check(TIERS.includes(newTier),'CHARACTER_TIER');const entity=this.runtime.game(gameId).entities.get(entityId);check(entity,'ENTITY_NOT_FOUND');const oldIndex=TIERS.indexOf(entity.tier),newIndex=TIERS.indexOf(newTier);check(newIndex>oldIndex,'PROMOTION_MUST_INCREASE_TIER');const key=`${gameId}:${entityId}`,r=this.records.get(key)||{entityId,gameId,tier:entity.tier,promotions:[]};r.promotions.push({from:entity.tier,to:newTier,sourceEventRef:input.sourceEventRef||null,reason:input.reason||null,at:Date.now()});r.tier=newTier;this.records.set(key,r);return clone(r);}
}
class VoiceFingerprint{
 fingerprint(profile={}){const v=profile.voice||{};return{formality:v.formality||'medium',directness:v.directness||'medium',humor:v.humor||'medium',verbosity:v.verbosity||'medium',metaphor:v.metaphor||'medium',hesitation:v.hesitation||'medium',sarcasm:v.sarcasm||'medium',sentencePattern:v.sentencePattern||null};}
 compare(expected={},observed={}){const keys=['formality','directness','humor','verbosity','metaphor','hesitation','sarcasm','sentencePattern'];let matches=0,used=0;for(const k of keys){if(expected[k]==null)continue;used++;if(expected[k]===observed[k])matches++;}const similarity=used?matches/used:1;return{similarity:+similarity.toFixed(3),drift:similarity<.6};}
}
class CharacterSpotlightScheduler{
 constructor(){this.rows=new Map();}
 record(entityId,input={}){this.rows.set(entityId,{entityId,lastMeaningfulEpisode:Number(input.episode||0),importance:Number(input.importance||50),openArc:!!input.openArc,worldRelevance:Number(input.worldRelevance||0),relationshipRelevance:Number(input.relationshipRelevance||0)});}
 candidates(currentEpisode){return[...this.rows.values()].map(x=>{const absence=Math.max(0,currentEpisode-x.lastMeaningfulEpisode);const score=absence*.8+x.importance*.3+(x.openArc?20:0)+x.worldRelevance*.2+x.relationshipRelevance*.2;return{...clone(x),absence,score:+score.toFixed(2)}}).sort((a,b)=>b.score-a.score);}
}
return{CHARACTER_TIERS:Object.freeze(TIERS),CharacterGenesis,VoiceFingerprint,CharacterSpotlightScheduler};
});
