(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateChronicle=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};
class Chronicle{
 constructor(runtime){this.runtime=runtime;}
 events(gameId,campaignId,timelineId,filter={}){let rows=this.runtime.visibleEvents(gameId,campaignId,timelineId);if(filter.trackId)rows=rows.filter(e=>e.trackId===filter.trackId);if(filter.seasonId)rows=rows.filter(e=>e.seasonId===filter.seasonId);if(filter.episodeId)rows=rows.filter(e=>e.episodeId===filter.episodeId);if(filter.sceneId)rows=rows.filter(e=>e.sceneId===filter.sceneId);if(filter.entityId)rows=rows.filter(e=>e.actorIds.includes(filter.entityId)||e.witnessIds.includes(filter.entityId));if(filter.tag)rows=rows.filter(e=>e.tags.includes(filter.tag));if(filter.type)rows=rows.filter(e=>e.type===filter.type);if(filter.arcId)rows=rows.filter(e=>e.arcIds.includes(filter.arcId));return rows.sort((a,b)=>a.seq-b.seq).map(clone);}
 episode(gameId,campaignId,timelineId,episodeId){const events=this.events(gameId,campaignId,timelineId,{episodeId}),scenes=new Map();for(const e of events){const id=e.sceneId||'unscened';const arr=scenes.get(id)||[];arr.push(e);scenes.set(id,arr);}return{episodeId,eventCount:events.length,scenes:[...scenes.entries()].map(([sceneId,rows])=>({sceneId,eventCount:rows.length,events:rows})),characters:[...new Set(events.flatMap(e=>[...e.actorIds,...e.witnessIds]))],locations:[...new Set(events.map(e=>e.locationId).filter(Boolean))],arcIds:[...new Set(events.flatMap(e=>e.arcIds))]};}
 arc(gameId,campaignId,timelineId,arcId){const events=this.events(gameId,campaignId,timelineId,{arcId});return{arcId,eventCount:events.length,episodes:[...new Set(events.map(e=>e.episodeId).filter(Boolean))],events};}
 characterLife(gameId,campaignId,timelineId,entityId){const g=this.runtime.game(gameId),memories=this.runtime.memories(gameId,campaignId,timelineId,entityId);return memories.map(m=>({memory:clone(m),event:clone(g.events.get(m.sourceEventRef)||null)})).filter(x=>x.event).sort((a,b)=>a.event.seq-b.event.seq);}
 causes(gameId,eventRef){const g=this.runtime.game(gameId),out=[],seen=new Set();const walk=(ref,depth)=>{if(seen.has(ref))return;seen.add(ref);const e=g.events.get(ref);if(!e)return;for(const c of e.causeRefs||[]){const ce=g.events.get(c);if(ce){out.push({depth,event:clone(ce)});walk(c,depth+1);}}};walk(eventRef,1);return out;}
 effects(gameId,eventRef){const g=this.runtime.game(gameId),all=[...g.events.values()],out=[],seen=new Set();const walk=(ref,depth)=>{if(seen.has(ref))return;seen.add(ref);for(const e of all.filter(x=>(x.causeRefs||[]).includes(ref))){out.push({depth,event:clone(e)});walk(e.ref,depth+1);}};walk(eventRef,1);return out;}
 explain(gameId,eventRef){const g=this.runtime.game(gameId),event=g.events.get(eventRef);check(event,'EVENT_NOT_FOUND');return{event:clone(event),causes:this.causes(gameId,eventRef),effects:this.effects(gameId,eventRef)};}
 hierarchy(gameId,campaignId,timelineId){const events=this.events(gameId,campaignId,timelineId),tracks={};for(const e of events){const track=e.trackId||'untracked',season=e.seasonId||'unseasoned',episode=e.episodeId||'unepisoded',scene=e.sceneId||'unscened';tracks[track]??={};tracks[track][season]??={};tracks[track][season][episode]??={};tracks[track][season][episode][scene]??=[];tracks[track][season][episode][scene].push(e.ref);}return tracks;}
}
return{Chronicle};
});
