(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateKnowledge=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};const words=s=>String(s||'').toLowerCase().normalize('NFKC').match(/[\p{L}\p{N}_-]+/gu)||[];
function checksum(text){let h=2166136261,s=String(text||'');for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0');}
function chunkText(text,{maxChars=1600,overlap=160}={}){text=String(text||'');if(!text)return[];const chunks=[];let start=0,index=0;while(start<text.length){let end=Math.min(text.length,start+maxChars);if(end<text.length){const window=text.slice(start,end),cut=Math.max(window.lastIndexOf('\n\n'),window.lastIndexOf('. '),window.lastIndexOf(' '));if(cut>maxChars*.55)end=start+cut+1;}const content=text.slice(start,end).trim();if(content)chunks.push({index:index++,start,end,content});if(end>=text.length)break;start=Math.max(start+1,end-overlap);}return chunks;}
class KnowledgeFabric{
 constructor(opts={}){this.local=opts.local||null;this.sources=new Map();this.chunks=new Map();this.sourceChunks=new Map();this.versions=new Map();}
 addSource(input={}){check(input.id&&!this.sources.has(input.id),'KNOWLEDGE_SOURCE_EXISTS');const source={id:input.id,title:input.title||input.id,kind:input.kind||'document',sourceRef:input.sourceRef||input.id,mime:input.mime||'text/plain',createdAt:input.createdAt||Date.now(),metadata:clone(input.metadata||{}),authority:'authoritative_source',currentVersion:null};this.sources.set(source.id,source);this.versions.set(source.id,[]);return clone(source);}
 ingestText(sourceId,text,input={}){const source=this.sources.get(sourceId);check(source,'KNOWLEDGE_SOURCE_NOT_FOUND');const digest=checksum(text),versions=this.versions.get(sourceId)||[];const existing=versions.find(v=>v.digest===digest);if(existing)return{version:clone(existing),deduplicated:true,chunks:(this.sourceChunks.get(existing.id)||[]).length};const version={id:input.versionId||`${sourceId}:v${versions.length+1}`,sourceId,digest,createdAt:input.createdAt||Date.now(),length:String(text||'').length,sourceRef:input.sourceRef||source.sourceRef,authority:'authoritative_version'};versions.push(version);this.versions.set(sourceId,versions);source.currentVersion=version.id;const ids=[];for(const part of chunkText(text,input.chunking||{})){const id=`${version.id}:c${part.index+1}`,tokens=words(part.content),chunk={id,sourceId,versionId:version.id,index:part.index,start:part.start,end:part.end,content:part.content,tokenCount:tokens.length,authority:'derived',lineage:{sourceRef:version.sourceRef,sourceId,versionId:version.id,transform:'text_chunk',range:[part.start,part.end]}};this.chunks.set(id,chunk);ids.push(id);}this.sourceChunks.set(version.id,ids);return{version:clone(version),deduplicated:false,chunks:ids.length};}
 query(text,input={}){const sourceFilter=input.sourceIds?new Set(input.sourceIds):null,rows=[];const q=new Set(words(text));for(const c of this.chunks.values()){if(sourceFilter&&!sourceFilter.has(c.sourceId))continue;if(input.currentOnly!==false&&this.sources.get(c.sourceId)?.currentVersion!==c.versionId)continue;const d=new Set(words(c.content));let lexical=0;for(const w of q)if(d.has(w))lexical++;lexical=q.size?lexical/q.size:0;const semantic=this.local&&text?this.local.similarity(text,c.content):0;const score=lexical*.45+Math.max(0,semantic)*.55;if(score>0||!text)rows.push({chunk:clone(c),score:+score.toFixed(5),lexical:+lexical.toFixed(5),semantic:+semantic.toFixed(5)});}rows.sort((a,b)=>b.score-a.score||a.chunk.id.localeCompare(b.chunk.id));const selected=rows.slice(0,input.limit||10);return{query:String(text||''),items:selected,citations:selected.map(x=>({sourceId:x.chunk.sourceId,versionId:x.chunk.versionId,range:x.chunk.lineage.range,sourceRef:x.chunk.lineage.sourceRef})),authority:'derived_retrieval'};}
 sourceView(sourceId){const s=this.sources.get(sourceId);check(s,'KNOWLEDGE_SOURCE_NOT_FOUND');return{source:clone(s),versions:clone(this.versions.get(sourceId)||[]),currentChunks:[...(this.sourceChunks.get(s.currentVersion)||[])].map(id=>clone(this.chunks.get(id)))};}
 removeSource(sourceId){const s=this.sources.get(sourceId);if(!s)return false;for(const v of this.versions.get(sourceId)||[])for(const id of this.sourceChunks.get(v.id)||[])this.chunks.delete(id);for(const v of this.versions.get(sourceId)||[])this.sourceChunks.delete(v.id);this.versions.delete(sourceId);this.sources.delete(sourceId);return true;}
 stats(){return{sources:this.sources.size,versions:[...this.versions.values()].reduce((n,v)=>n+v.length,0),chunks:this.chunks.size};}
}
return{checksum,chunkText,KnowledgeFabric};
});