(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateAgency=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
const OWNED=new Set(['dialogue','decision','opinion','private_thought','intentional_action','irreversible_action']);
class AgencyRiskDetector{
 score(input={}){let n=0;if(input.directQuestion)n+=40;if(input.opinionRequested)n+=35;if(input.decisionRequired)n+=45;if(input.irreversible)n+=55;if(input.personalInterpretation)n+=35;if(input.immediateThreat)n+=25;if(input.playerActionAboutToBeInvented)n+=60;if(input.meaningfulOpportunity)n+=20;return clamp(n);}
 needsGate(input={},threshold=60){return{score:this.score(input),gate:this.score(input)>=threshold};}
}
function parsePlayerInput(text){const raw=String(text||'').trim();const out={say:[],act:[],think:[],ooc:[],raw};if(!raw)return out;const think=[...raw.matchAll(/\[\s*think\s*:\s*([^\]]+)\]/gi)].map(x=>x[1].trim());const ooc=[...raw.matchAll(/\[\s*ooc\s*:\s*([^\]]+)\]/gi)].map(x=>x[1].trim());out.think.push(...think);out.ooc.push(...ooc);let remaining=raw.replace(/\[\s*(think|ooc)\s*:[^\]]+\]/gi,' ').trim();const actions=[...remaining.matchAll(/\*([^*]+)\*/g)].map(x=>x[1].trim());out.act.push(...actions);remaining=remaining.replace(/\*[^*]+\*/g,' ').trim();const quoted=[...remaining.matchAll(/"([^"]+)"/g)].map(x=>x[1].trim());out.say.push(...quoted);remaining=remaining.replace(/"[^"]+"/g,' ').trim();if(remaining){if(/^ooc\s*:/i.test(remaining))out.ooc.push(remaining.replace(/^ooc\s*:/i,'').trim());else if(/^think\s*:/i.test(remaining))out.think.push(remaining.replace(/^think\s*:/i,'').trim());else out.act.push(remaining);}return out;}
class LiveSceneSession{
 constructor(opts={}){check(opts.playerEntityId,'PLAYER_ENTITY_REQUIRED');this.playerEntityId=opts.playerEntityId;this.mode=opts.mode||'sovereign';this.threshold=opts.threshold??60;this.detector=opts.detector||new AgencyRiskDetector();this.committed=[];this.speculative=[];this.state='running';this.pendingGate=null;this.interruptRequested=false;}
 canNarratorOwn(actionType){if(this.mode==='sovereign')return !OWNED.has(actionType);if(this.mode==='assisted')return !['decision','opinion','private_thought','irreversible_action','dialogue'].includes(actionType);return !['decision','opinion','irreversible_action'].includes(actionType);}
 proposeBeat(beat={}){check(this.state==='running','SCENE_NOT_RUNNING');const playerOwned=beat.actorEntityId===this.playerEntityId&&!this.canNarratorOwn(beat.actionType);const risk=this.detector.needsGate(beat.agencySignals||{},this.threshold);if(playerOwned||risk.gate||beat.forceGate){this.pendingGate={reason:playerOwned?'PLAYER_OWNERSHIP':'AGENCY_RISK',risk:risk.score,beat:clone(beat)};this.state='waiting_player';return{state:'gate',gate:clone(this.pendingGate)};}this.speculative.push(clone(beat));return{state:'speculative',beat:clone(beat)};}
 commitSpeculative(count=this.speculative.length){check(this.state==='running','SCENE_NOT_RUNNING');const n=Math.max(0,Math.min(count,this.speculative.length));const moved=this.speculative.splice(0,n);this.committed.push(...moved);return clone(moved);}
 interrupt(){if(this.state==='waiting_player')return{state:'already_waiting'};this.interruptRequested=true;const discarded=this.speculative.splice(0);this.state='waiting_player';this.pendingGate={reason:'USER_INTERRUPT',risk:100,beat:null};return{state:'interrupted',discarded:clone(discarded),committed:clone(this.committed)};}
 playerInput(text){check(this.state==='waiting_player','PLAYER_INPUT_NOT_EXPECTED');const parsed=parsePlayerInput(text);this.pendingGate=null;this.state='running';this.interruptRequested=false;return parsed;}
 continueWithoutActing(){check(this.state==='waiting_player','CONTINUE_NOT_EXPECTED');const gate=this.pendingGate;this.pendingGate=null;this.state='running';return{continued:true,reason:gate?.reason||null};}
 finish(){check(this.state!=='waiting_player','PLAYER_RESPONSE_PENDING');this.commitSpeculative();this.state='complete';return this.snapshot();}
 snapshot(){return{playerEntityId:this.playerEntityId,mode:this.mode,state:this.state,committed:clone(this.committed),speculative:clone(this.speculative),pendingGate:clone(this.pendingGate)};}
}
return{PLAYER_OWNED_ACTIONS:Object.freeze([...OWNED]),AgencyRiskDetector,parsePlayerInput,LiveSceneSession};
});
