(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateMemory=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};const words=s=>String(s||'').toLowerCase().normalize('NFKC').match(/[\p{L}\p{N}_-]+/gu)||[];
class MemoryFabric{
 constructor(runtime,local=null){check(runtime,'MEMORY_RUNTIME_REQUIRED');this.runtime=runtime;this.local=local;this.games=new Map();}
 rebuild(gameId){const g=this.runtime.game(gameId),idx={event:new Map(),entity:new Map(),lexical:new Map(),temporal:[],causalParents:new Map(),causalChildren:new Map(),semantic:new Map(),builtAt:Date.now(),sourceEventCount:g.events.size};for(const e of g.events.values()){const derived={ref:e.ref,seq:e.seq||0,type:e.type,worldTime:e.worldTime||null,actorIds:[...(e.actorIds||[])],witnessIds:[...(e.witnessIds||[])],sourceRef:e.ref,lineage:{sourceRef:e.ref,transform:'memory_index'},authority:'derived'};idx.event.set(e.ref,derived);idx.temporal.push({ref:e.ref,seq:e.seq||0,worldTime:e.worldTime||null});for(const id of new Set([...(e.actorIds||[]),...(e.witnessIds||[])])){if(!idx.entity.has(id))idx.entity.set(id,new Set());idx.entity.get(id).add(e.ref);}for(const w of new Set(words(JSON.stringify({type:e.type,payload:e.payload,tags:e.tags,location:e.locationId})))){if(!idx.lexical.has(w))idx.lexical.set(w,new Set());idx.lexical.get(w).add(e.ref);}idx.causalParents.set(e.ref,[...(e.causeRefs||[])]);for(const p of e.causeRefs||[]){if(!idx.causalChildren.has(p))idx.causalChildren.set(p,new Set());idx.causalChildren.get(p).add(e.ref);}if(this.local)idx.semantic.set(e.ref,this.local.embed(JSON.stringify({type:e.type,payload:e.payload,tags:e.tags,location:e.locationId})));}idx.temporal.sort((a,b)=>a.seq-b.seq);this.games.set(gameId,idx);return this.stats(gameId);}
 ensure(gameId){const g=this.runtime.game(gameId),idx=this.games.get(gameId);if(!idx||idx.sourceEventCount!==g.events.size)this.rebuild(gameId);return this.games.get(gameId);}
 visibleSet(gameId,campaignId,timelineId){return new Set(this.runtime.visibleEvents(gameId,campaignId,timelineId).map(e=>e.ref));}
 characterKnowledgeSet(gameId,campaignId,timelineId,entityId){return new Set(this.runtime.memories(gameId,campaignId,timelineId,entityId).map(m=>m.sourceEventRef));}
 query(input={}){const {gameId,campaignId,timelineId}=input;check(gameId&&campaignId&&timelineId,'MEMORY_SCOPE_REQUIRED');const idx=this.ensure(gameId),visible=this.visibleSet(gameId,campaignId,timelineId),allowed=input.entityId?this.characterKnowledgeSet(gameId,campaignId,timelineId,input.entityId):visible,qWords=new Set(words(input.text||'')),scores=new Map(),latest=Math.max(1,...idx.temporal.map(x=>x.seq));const bump=(ref,n,why)=>{if(!visible.has(ref)||!allowed.has(ref))return;const r=scores.get(ref)||{ref,score:0,reasons:[]};r.score+=n;r.reasons.push(why);scores.set(ref,r);};for(const w of qWords)for(const ref of idx.lexical.get(w)||[])bump(ref,2,'lexical');if(input.entityId)for(const ref of idx.entity.get(input.entityId)||[])bump(ref,.35,'entity');if(input.causeOf){for(const ref of idx.causalParents.get(input.causeOf)||[])bump(ref,2.5,'cause');for(const ref of idx.causalChildren.get(input.causeOf)||[])bump(ref,1.5,'effect');}if(this.local&&input.text){const q=this.local.embed(input.text);for(const ref of allowed){const v=idx.semantic.get(ref);if(v){const s=this.local.constructor&&typeof this.local.similarity==='function'?this.local.similarity(input.text,JSON.stringify(this.runtime.game(gameId).events.get(ref)?.payload||{})):0;if(s>0)bump(ref,s*1.4,'semantic');}}}for(const row of idx.temporal){if(allowed.has(row.ref))bump(row.ref,(row.seq/latest)*.25,'recency');}const g=this.runtime.game(gameId),rows=[...scores.values()].sort((a,b)=>b.score-a.score).slice(0,input.limit||12).map(r=>({event:clone(g.events.get(r.ref)),score:+r.score.toFixed(4),reasons:[...new Set(r.reasons)],authority:'derived_retrieval',lineage:{sourceRef:r.ref,transform:'memory_query'}}));return{items:rows,totalCandidates:scores.size,scope:{gameId,campaignId,timelineId,entityId:input.entityId||null}};}
 chain(input={}){const first=this.query({...input,limit:input.seedLimit||4}),idx=this.ensure(input.gameId),visible=this.visibleSet(input.gameId,input.campaignId,input.timelineId),seen=new Set(first.items.map(x=>x.event.ref)),queue=[...seen],depth=Math.max(0,input.depth??2);let level=0;while(queue.length&&level<depth){const next=[];for(const ref of queue){for(const p of idx.causalParents.get(ref)||[])if(visible.has(p)&&!seen.has(p)){seen.add(p);next.push(p);}for(const c of idx.causalChildren.get(ref)||[])if(visible.has(c)&&!seen.has(c)){seen.add(c);next.push(c);}}queue.splice(0,queue.length,...next);level++;}const g=this.runtime.game(input.gameId);return{seed:first.items,chain:[...seen].map(ref=>clone(g.events.get(ref))).filter(Boolean),authority:'derived_retrieval',lineage:{transform:'chain_of_memory',sourceRefs:[...seen]}};}
 entityView(gameId,entityId){const idx=this.ensure(gameId);return{entityId,eventRefs:[...(idx.entity.get(entityId)||[])],authority:'derived',lineage:{transform:'entity_memory_view'}};}
 stats(gameId){const idx=this.games.get(gameId);if(!idx)return{events:0};return{events:idx.event.size,entities:idx.entity.size,lexicalTerms:idx.lexical.size,causalNodes:idx.causalParents.size,semanticVectors:idx.semantic.size,builtAt:idx.builtAt};}
 invalidate(gameId){this.games.delete(gameId);}
}
return{MemoryFabric};
});