(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateNPCLife=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const check=(v,m)=>{if(!v)throw new Error(m)};const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
const LIFE_STAGES=Object.freeze(['origin','childhood','adolescence','young_adult','adult','older_adult','legacy']);
const DEFAULT_NEEDS=Object.freeze({autonomy:50,competence:50,relatedness:50,security:50,status:35,meaning:50,novelty:45,rest:50});
class LifeEventLedger{
 constructor(){this.events=[];this.ids=new Set();}
 add(input={}){check(input.id&&!this.ids.has(input.id),'LIFE_EVENT_ID_REQUIRED');check(input.kind,'LIFE_EVENT_KIND_REQUIRED');const row=Object.freeze({id:input.id,kind:input.kind,worldTime:input.worldTime??null,stage:input.stage||null,locationId:input.locationId||null,people:[...(input.people||[])],roles:[...(input.roles||[])],tags:[...(input.tags||[])],summary:String(input.summary||''),impact:clone(input.impact||{}),sourceEventRef:input.sourceEventRef||null,canonLevel:input.canonLevel||'canon'});this.events.push(row);this.ids.add(row.id);return clone(row);}
 list(filter={}){return this.events.filter(e=>(!filter.kind||e.kind===filter.kind)&&(!filter.stage||e.stage===filter.stage)&&(!filter.tag||e.tags.includes(filter.tag))).map(clone);}
}
class GoalContinuityEngine{
 constructor(opts={}){this.goals=new Map();this.history=[];this.policy={preserveUnresolved:true,allowAntagonistic:true,rendering:'non_graphic',...clone(opts.policy||{})};}
 add(input={}){check(input.id&&!this.goals.has(input.id),'GOAL_ID_REQUIRED');const goal={id:input.id,text:String(input.text||input.id),kind:input.kind||'personal',priority:clamp(input.priority??60),commitment:clamp(input.commitment??65),urgency:clamp(input.urgency??40),status:'active',parentId:input.parentId||null,methods:[...(input.methods||[])],constraints:[...(input.constraints||[])],startedFrom:input.startedFrom||null,sourceEventRefs:[...(input.sourceEventRefs||[])],progress:clamp(input.progress??0),abandonmentThreshold:clamp(input.abandonmentThreshold??75),metadata:clone(input.metadata||{})};this.goals.set(goal.id,goal);this.history.push({type:'goal_added',goalId:goal.id,sourceEventRef:input.sourceEventRef||null});return clone(goal);}
 get(id){const g=this.goals.get(id);check(g,'GOAL_NOT_FOUND');return clone(g);}
 active(){return[...this.goals.values()].filter(g=>g.status==='active').sort((a,b)=>b.priority*b.commitment-a.priority*a.commitment).map(clone);}
 progress(id,input={}){const g=this.goals.get(id);check(g,'GOAL_NOT_FOUND');check(input.sourceEventRef,'GOAL_CHANGE_SOURCE_REQUIRED');g.progress=clamp(input.progress??g.progress);g.sourceEventRefs.push(input.sourceEventRef);if(g.progress>=100)g.status='fulfilled';this.history.push({type:'goal_progress',goalId:id,progress:g.progress,status:g.status,sourceEventRef:input.sourceEventRef});return clone(g);}
 reconsider(id,input={}){const g=this.goals.get(id);check(g,'GOAL_NOT_FOUND');check(input.sourceEventRef,'GOAL_CHANGE_SOURCE_REQUIRED');const reasons=[...(input.reasons||[])],worldImpossible=!!input.worldImpossible,identityShift=clamp(input.identityShift??0),superseded=!!input.superseded,fulfilled=!!input.fulfilled;if(fulfilled){g.status='fulfilled';g.progress=100;}else if(worldImpossible){g.status='blocked';}else if(superseded||identityShift>=g.abandonmentThreshold){g.status='abandoned';}else if(input.pause){g.status='paused';}g.sourceEventRefs.push(input.sourceEventRef);this.history.push({type:'goal_reconsidered',goalId:id,status:g.status,reasons,sourceEventRef:input.sourceEventRef});return clone(g);}
 resume(id,input={}){const g=this.goals.get(id);check(g,'GOAL_NOT_FOUND');check(input.sourceEventRef,'GOAL_CHANGE_SOURCE_REQUIRED');check(['paused','blocked'].includes(g.status),'GOAL_NOT_RESUMABLE');g.status='active';g.sourceEventRefs.push(input.sourceEventRef);this.history.push({type:'goal_resumed',goalId:id,sourceEventRef:input.sourceEventRef});return clone(g);}
 continuityAudit(){const unresolved=[...this.goals.values()].filter(g=>['active','paused','blocked'].includes(g.status));return{pass:true,unresolved:unresolved.map(g=>({id:g.id,status:g.status,priority:g.priority,commitment:g.commitment})),policy:clone(this.policy)};}
}
class TheoryOfMindModel{
 constructor(){this.people=new Map();}
 observe(entityId,input={}){check(entityId,'TOM_ENTITY_REQUIRED');const row=this.people.get(entityId)||{entityId,beliefs:{},goals:{},traits:{},trust:50,certainty:20,lastSourceRefs:[]};if(input.beliefs)Object.assign(row.beliefs,clone(input.beliefs));if(input.goals)Object.assign(row.goals,clone(input.goals));if(input.traits)Object.assign(row.traits,clone(input.traits));if(input.trust!=null)row.trust=clamp(input.trust);if(input.certainty!=null)row.certainty=clamp(input.certainty);if(input.sourceEventRef)row.lastSourceRefs=[...new Set([...row.lastSourceRefs,input.sourceEventRef])];this.people.set(entityId,row);return clone(row);}
 model(entityId){const row=this.people.get(entityId);return row?clone(row):null;}
}
class RoutineModel{
 constructor(input={}){this.blocks=(input.blocks||[]).map((b,i)=>({id:b.id||`routine_${i}`,start:Number(b.start??0),end:Number(b.end??24),days:[...(b.days||[])],activity:b.activity||'unstructured',locationId:b.locationId||null,role:b.role||null,priority:Number(b.priority||0)}));}
 at(hour,day=null){const h=((Number(hour)||0)%24+24)%24;return this.blocks.filter(b=>(!b.days.length||day==null||b.days.includes(day))&&((b.start<=b.end&&h>=b.start&&h<b.end)||(b.start>b.end&&(h>=b.start||h<b.end)))).sort((a,b)=>b.priority-a.priority).map(clone);}
 add(block){this.blocks.push({id:block.id||`routine_${this.blocks.length}`,start:Number(block.start??0),end:Number(block.end??24),days:[...(block.days||[])],activity:block.activity||'unstructured',locationId:block.locationId||null,role:block.role||null,priority:Number(block.priority||0)});return clone(this.blocks[this.blocks.length-1]);}
}
class NarrativeIdentity{
 constructor(input={}){this.selfConcept=[...(input.selfConcept||[])];this.roles=(input.roles||[]).map(clone);this.chapters=(input.chapters||[]).map(clone);this.contradictions=(input.contradictions||[]).map(clone);this.masks=(input.masks||[]).map(clone);this.history=[];}
 addChapter(input={}){check(input.id&&input.sourceEventRef,'IDENTITY_CHAPTER_SOURCE_REQUIRED');const row={id:input.id,label:input.label||input.id,meaning:input.meaning||'',valence:Number(input.valence||0),sourceEventRef:input.sourceEventRef,active:input.active!==false};this.chapters.push(row);this.history.push({type:'chapter_added',id:row.id,sourceEventRef:row.sourceEventRef});return clone(row);}
 reviseSelf(input={}){check(input.sourceEventRef,'IDENTITY_CHANGE_SOURCE_REQUIRED');const before=[...this.selfConcept];if(input.remove)this.selfConcept=this.selfConcept.filter(x=>!input.remove.includes(x));for(const x of input.add||[])if(!this.selfConcept.includes(x))this.selfConcept.push(x);this.history.push({type:'self_revision',before,after:[...this.selfConcept],sourceEventRef:input.sourceEventRef,reason:input.reason||null});return[...this.selfConcept];}
}
class NPCLife{
 constructor(input={}){check(input.id,'NPC_ID_REQUIRED');this.id=input.id;this.name=input.name||input.id;this.status=input.status||'alive';this.origin=clone(input.origin||{});this.species=input.species||'human';this.birth=clone(input.birth||{});this.stage=input.stage||'adult';check(LIFE_STAGES.includes(this.stage),'NPC_LIFE_STAGE');this.traits={openness:clamp(input.traits?.openness??50),conscientiousness:clamp(input.traits?.conscientiousness??50),extraversion:clamp(input.traits?.extraversion??50),agreeableness:clamp(input.traits?.agreeableness??50),emotionalSensitivity:clamp(input.traits?.emotionalSensitivity??50),impulsivity:clamp(input.traits?.impulsivity??40),dominance:clamp(input.traits?.dominance??50),patience:clamp(input.traits?.patience??50)};this.values=(input.values||[]).map((v,i)=>typeof v==='string'?{name:v,weight:100-i*7}:{name:v.name,weight:clamp(v.weight??50)});this.needs={...DEFAULT_NEEDS,...clone(input.needs||{})};for(const k of Object.keys(this.needs))this.needs[k]=clamp(this.needs[k]);this.worldview=[...(input.worldview||[])];this.culture=clone(input.culture||{});this.education=(input.education||[]).map(clone);this.occupations=(input.occupations||[]).map(clone);this.skills=clone(input.skills||{});this.habits=(input.habits||[]).map(clone);this.preferences=clone(input.preferences||{});this.relationships=new Map();for(const r of input.relationships||[])this.relationships.set(r.entityId,clone(r));this.identity=new NarrativeIdentity(input.identity||{});this.goals=new GoalContinuityEngine({policy:input.goalPolicy});for(const g of input.goals||[])this.goals.add(g);this.theoryOfMind=new TheoryOfMindModel();this.routine=new RoutineModel(input.routine||{});this.life=new LifeEventLedger();for(const e of input.lifeEvents||[])this.life.add(e);this.current={locationId:input.locationId||null,activity:input.activity||null,mood:clone(input.mood||{}),roleContext:input.roleContext||null,lastUpdate:input.lastUpdate||Date.now()};this.futureBranches=[];this.reflections=[];}
 value(name){return this.values.find(v=>v.name===name)?.weight||0;}
 relationship(entityId){return clone(this.relationships.get(entityId)||{entityId,trust:50,respect:50,affection:0,fear:0,obligation:0,familiarity:0});}
 updateRelationship(entityId,input={}){const r=this.relationship(entityId);for(const k of['trust','respect','affection','fear','obligation','familiarity'])if(input[k]!=null)r[k]=clamp(input[k]);if(input.role)r.role=input.role;if(input.sourceEventRef)r.sourceEventRefs=[...new Set([...(r.sourceEventRefs||[]),input.sourceEventRef])];this.relationships.set(entityId,r);return clone(r);}
 observe(input={}){const event=this.life.add(input);for(const [need,delta] of Object.entries(input.impact?.needs||{}))if(need in this.needs)this.needs[need]=clamp(this.needs[need]+Number(delta||0));if(input.impact?.relationship){const r=input.impact.relationship;this.updateRelationship(r.entityId,{...r,sourceEventRef:input.sourceEventRef});}return event;}
 tick(input={}){const hours=Math.max(0,Number(input.hours??1));const drift=Math.min(1,hours/24);this.needs.rest=clamp(this.needs.rest-(input.awake===false?-12:8)*drift);this.needs.novelty=clamp(this.needs.novelty+2*drift);this.needs.relatedness=clamp(this.needs.relatedness-(input.social===true?-4:2)*drift);const block=this.routine.at(input.hour??0,input.day??null)[0];if(block){this.current.activity=block.activity;this.current.locationId=block.locationId||this.current.locationId;this.current.roleContext=block.role||this.current.roleContext;}this.current.lastUpdate=input.now||Date.now();return this.snapshot('light');}
 choose(candidates=[],context={}){check(candidates.length,'NPC_DECISION_CANDIDATES_REQUIRED');const activeGoals=this.goals.active(),rows=[];for(const c of candidates){const blockers=[];if(c.impossible)blockers.push('WORLD_IMPOSSIBLE');for(const req of c.requiredFacts||[])if(!(context.knownFacts||[]).includes(req))blockers.push(`UNKNOWN:${req}`);let score=-Infinity;if(!blockers.length){let valueScore=0;for(const [name,effect] of Object.entries(c.valueEffects||{}))valueScore+=(this.value(name)/100)*Number(effect||0)*25;let goalScore=0;for(const [id,effect] of Object.entries(c.goalEffects||{})){const g=activeGoals.find(x=>x.id===id);if(g)goalScore+=(g.priority/100)*(g.commitment/100)*Number(effect||0)*30;}let needScore=0;for(const [name,effect] of Object.entries(c.needEffects||{}))needScore+=((100-(this.needs[name]??50))/100)*Number(effect||0)*18;let socialScore=0;for(const [entityId,effect] of Object.entries(c.relationshipEffects||{}))socialScore+=(this.relationship(entityId).trust/100)*Number(effect||0)*15;const impulse=(this.traits.impulsivity/100)*Number(c.immediacy||0)*8;const patience=(this.traits.patience/100)*Number(c.longTerm||0)*8;const dominance=(this.traits.dominance/100)*Number(c.assertive||0)*8;const uncertaintyPenalty=(100-clamp(c.certainty??70))/100*Number(c.risk||0)*8;score=valueScore+goalScore+needScore+socialScore+impulse+patience+dominance-uncertaintyPenalty;}rows.push({id:c.id,score:Number.isFinite(score)?+score.toFixed(3):score,blockers});}rows.sort((a,b)=>b.score-a.score);return{choice:rows.find(r=>Number.isFinite(r.score))?.id||null,candidates:rows,goalContinuity:this.goals.continuityAudit(),authority:'derived_npc_decision'};}
 planFuture(input={}){const branches=(input.branches||[]).map((b,i)=>({id:b.id||`future_${this.futureBranches.length+i}`,label:b.label||b.id||`Future ${i+1}`,probability:Math.max(0,Math.min(1,Number(b.probability??0))),goalAlignment:Number(b.goalAlignment||0),identityFit:Number(b.identityFit||0),worldFeasibility:Number(b.worldFeasibility||0),canon:false,assumptions:[...(b.assumptions||[])]}));this.futureBranches=branches;return clone(branches.sort((a,b)=>(b.probability+b.goalAlignment/100)-(a.probability+a.goalAlignment/100)));}
 activeMind(input={}){return{id:this.id,name:this.name,stage:this.stage,current:clone(this.current),traits:clone(this.traits),values:clone(this.values),needs:clone(this.needs),worldview:[...this.worldview],identity:{selfConcept:[...this.identity.selfConcept],roles:clone(this.identity.roles),contradictions:clone(this.identity.contradictions),masks:clone(this.identity.masks)},goals:this.goals.active(),relationships:(input.relevantPeople||[]).map(id=>this.relationship(id)),theoryOfMind:(input.relevantPeople||[]).map(id=>this.theoryOfMind.model(id)).filter(Boolean),memories:clone(input.memories||[]),routine:this.routine.at(input.hour??0,input.day??null),authority:'derived_active_mind'};}
 auditDepth(){const checks={traits:Object.keys(this.traits).length>=6,values:this.values.length>=3,goals:this.goals.active().length>=1,worldview:this.worldview.length>=1,identity:this.identity.selfConcept.length>=1||this.identity.chapters.length>=1,relationships:this.relationships.size>=1,routine:this.routine.blocks.length>=1,lifeEvents:this.life.events.length>=2,contradiction:this.identity.contradictions.length>=1};const score=Object.values(checks).filter(Boolean).length/Object.keys(checks).length;return{pass:score>=.7,score:+score.toFixed(3),checks,missing:Object.entries(checks).filter(([,v])=>!v).map(([k])=>k)};}
 snapshot(level='full'){const base={id:this.id,name:this.name,status:this.status,stage:this.stage,current:clone(this.current),goals:this.goals.active(),needs:clone(this.needs)};if(level==='light')return base;return{...base,origin:clone(this.origin),birth:clone(this.birth),traits:clone(this.traits),values:clone(this.values),worldview:[...this.worldview],culture:clone(this.culture),education:clone(this.education),occupations:clone(this.occupations),skills:clone(this.skills),habits:clone(this.habits),preferences:clone(this.preferences),identity:{selfConcept:[...this.identity.selfConcept],roles:clone(this.identity.roles),chapters:clone(this.identity.chapters),contradictions:clone(this.identity.contradictions),masks:clone(this.identity.masks)},relationships:[...this.relationships.values()].map(clone),lifeEvents:this.life.list(),futureBranches:clone(this.futureBranches)};}
}
class NPCPopulation{
 constructor(opts={}){this.people=new Map();this.tiers=new Map();this.hotLimit=opts.hotLimit??12;this.warmLimit=opts.warmLimit??80;}
 create(input={}){check(input.id&&!this.people.has(input.id),'NPC_EXISTS');const npc=new NPCLife(input);this.people.set(npc.id,npc);this.tiers.set(npc.id,input.tier||'cold');return npc;}
 get(id){const npc=this.people.get(id);check(npc,'NPC_NOT_FOUND');return npc;}
 setTier(id,tier){check(['hot','warm','cold'].includes(tier),'NPC_TIER');this.get(id);this.tiers.set(id,tier);return{entityId:id,tier};}
 promoteForScene(ids=[]){const unique=[...new Set(ids)].slice(0,this.hotLimit);for(const id of unique)if(this.people.has(id))this.tiers.set(id,'hot');return unique;}
 tick(input={}){const results=[];for(const [id,npc] of this.people){const tier=this.tiers.get(id)||'cold';if(tier==='cold'&&!input.wakeIds?.includes(id))continue;if(tier==='warm'&&(Number(input.tick||0)%Math.max(1,Number(input.warmEvery||5)))!==0)continue;results.push({id,tier,state:npc.tick(input)});}return results;}
 audit(){const rows=[...this.people.values()].map(n=>({id:n.id,tier:this.tiers.get(n.id)||'cold',depth:n.auditDepth()}));return{count:rows.length,hot:rows.filter(r=>r.tier==='hot').length,warm:rows.filter(r=>r.tier==='warm').length,cold:rows.filter(r=>r.tier==='cold').length,rows};}
}
return{LIFE_STAGES,DEFAULT_NEEDS,LifeEventLedger,GoalContinuityEngine,TheoryOfMindModel,RoutineModel,NarrativeIdentity,NPCLife,NPCPopulation};
});
