(function(root,factory){
 const deps=(typeof module==='object'&&module.exports)?{
  Core:require('./core.js'),Persistence:require('./persistence.js'),SystemPersistence:require('./system-persistence.js'),Context:require('./context.js'),RPG:require('./rpg-engine.js'),RPGState:require('./rpg-state.js'),Requests:require('./request-runtime.js'),Models:require('./model-fabric.js'),Tools:require('./tool-fabric.js'),Research:require('./research.js'),Visual:require('./visual-canon.js'),UI:require('./ui-system.js')
 }:{Core:root.SevenUltimateCore,Persistence:root.SevenUltimatePersistence,SystemPersistence:root.SevenUltimateSystemPersistence,Context:root.SevenUltimateContext,RPG:root.SevenUltimateRPG,RPGState:root.SevenUltimateRPGState,Requests:root.SevenUltimateRequests,Models:root.SevenUltimateModels,Tools:root.SevenUltimateTools,Research:root.SevenUltimateResearch,Visual:root.SevenUltimateVisualCanon,UI:root.SevenUltimateUI};
 const api=factory(deps);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimate=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(D){
'use strict';
const check=(v,m)=>{if(!v)throw new Error(m)};const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
class SevenUltimateOS{
 constructor(opts={}){this.core=opts.core||new D.Core.SevenUltimateRuntime({clock:opts.clock});this._initSubsystems(opts);this.persistence=opts.persistence||new D.Persistence.RevisionedMemoryStore();this.active={gameId:null,campaignId:null,timelineId:null};}
 _initSubsystems(opts={}){this.characters=new D.RPG.CharacterEngine(this.core);this.story=new D.RPG.StoryArchitect();this.tone=new D.RPG.ToneDirector();this.flashbacks=new D.RPG.FlashbackDirector();this.contextCache=new D.Context.ActiveContextCache(opts.cache||{});this.latency=new D.Context.LatencyTracker();this.tools=new D.Tools.ToolFabric();this.permissions=new D.Tools.PermissionLedger();this.models=new D.Models.ModelFabric();this.compute=new D.Models.AdaptiveCompute();this.intelligence=new D.Models.IntelligenceAmplifier(this.models,this.compute);this.research=new D.Research.ResearchController();this.visuals=new D.Visual.VisualCanonVault();this.motion=new D.UI.MotionScheduler();this.knowledge=new D.RPGState.KnowledgeFirewall(this.core);this.relationships=new D.RPGState.RelationshipGraph();this.plots=new D.RPGState.PlotRegistry(this.core);this.world=new D.RPGState.WorldState();this.causal=new D.RPGState.CausalLogicEngine(this.core,this.knowledge,this.world);this.requests=new D.Requests.RequestRuntime();}
 createRpg(input={}){const game=this.core.createGame({id:input.gameId,name:input.name,rules:input.rules,tone:input.tone});const campaign=this.core.createCampaign(game.id,{id:input.campaignId,name:input.campaignName||'Main Campaign'});const timeline=this.core.createTimeline(game.id,campaign.id,{id:input.timelineId,name:input.timelineName||'Main Timeline'});this.active={gameId:game.id,campaignId:campaign.id,timelineId:timeline.id};return clone(this.active);}
 activate(gameId,campaignId,timelineId){this.core.timeline(gameId,campaignId,timelineId);this.active={gameId,campaignId,timelineId};return clone(this.active);}
 ids(input={}){const x={gameId:input.gameId||this.active.gameId,campaignId:input.campaignId||this.active.campaignId,timelineId:input.timelineId||this.active.timelineId};check(x.gameId&&x.campaignId&&x.timelineId,'ACTIVE_RPG_REQUIRED');return x;}
 prepareRpgTurn(input={}){const ids=this.ids(input),workspace=new D.Context.ContextWorkspace(),activeCharacters=[...(input.activeCharacters||[])],query=input.query||input.userInput||'';workspace.add({id:'scene',category:'scene',content:clone(input.scene||{}),priority:100,pinned:true,sourceRefs:[...(input.sceneSourceRefs||[])]});const retriever=new D.Context.MemoryRetriever(this.core),recall={},knowledge={};for(const entityId of activeCharacters){const r=retriever.searchCharacter(ids.gameId,ids.campaignId,ids.timelineId,entityId,query,{limit:input.memoryLimit||8,tokenBudget:input.memoryBudgetPerCharacter||1200});recall[entityId]=r;knowledge[entityId]=this.knowledge.facts(ids.gameId,ids.timelineId,entityId);workspace.add({id:`memory:${entityId}`,category:'memory',content:r.items,priority:80,sourceRefs:r.items.map(x=>x.memory.sourceEventRef)});workspace.add({id:`knowledge:${entityId}`,category:'knowledge',content:knowledge[entityId],priority:85,sourceRefs:knowledge[entityId].map(x=>x.sourceEventRef)});}const compiled=workspace.compile({totalBudget:input.totalBudget||6000,categoryBudgets:{scene:1800,memory:3000,knowledge:1800,...input.categoryBudgets}});const tone=this.tone.resolve(input.tone||this.core.game(ids.gameId).tone||{},input.playerTone||{});const compute=this.compute.decide({complexity:input.complexity??.35,uncertainty:input.uncertainty??.25,risk:input.risk??.2,latencyPriority:input.latencyPriority??.6});const packet={ids,userInput:String(input.userInput||''),activeCharacters,context:compiled,recall,knowledge,tone,compute,agencyMode:input.agencyMode||'sovereign',preparedAt:new Date().toISOString()};this.contextCache.set(ids.gameId,ids.campaignId,ids.timelineId,{lastTurn:packet});return packet;}
 commitBeat(input={}){const ids=this.ids(input);if(input.actorEntityId===input.playerEntityId&&this.core.requiresAgencyGate({playerEntityId:input.playerEntityId,actorEntityId:input.actorEntityId,actionType:input.actionType,force:input.forceAgencyGate})&&!input.userAuthored)throw new Error('PLAYER_AGENCY_REQUIRED');const ev=this.core.appendEvent(ids.gameId,ids.campaignId,ids.timelineId,{id:input.id,type:input.type||input.actionType||'beat',worldTime:input.worldTime,actorIds:input.actorEntityId?[input.actorEntityId]:input.actorIds,witnessIds:input.witnessIds||[],payload:clone(input.payload||{}),causeRefs:input.causeRefs||[]});for(const entityId of input.rememberBy||[])this.core.remember(ids.gameId,ids.campaignId,ids.timelineId,entityId,{sourceEventRef:ev.ref,interpretation:clone((input.interpretations||{})[entityId]||null),emotionalWeight:Number((input.emotionalWeights||{})[entityId]||0)});for(const k of input.knowledge||[])this.knowledge.learn(ids.gameId,ids.campaignId,ids.timelineId,k.entityId,{...clone(k),sourceEventRef:ev.ref});for(const r of input.relationshipChanges||[])this.relationships.apply(r.a,r.b,{...clone(r),sourceEventRef:ev.ref});for(const p of input.plotAdvances||[])this.plots.advance(ids.gameId,ids.campaignId,ids.timelineId,p.plotId,{...clone(p),sourceEventRef:ev.ref});this.contextCache.patch(ids.gameId,ids.campaignId,ids.timelineId,{lastCommittedEventRef:ev.ref});return ev;}
 resolveAction(input={}){const ids=this.ids(input);return this.causal.commit({...clone(input),...ids});}
 async runRequest(input={}){return this.requests.run(input);}
 async save(key='ultimate-state',expectedRevision=null){return D.SystemPersistence.persistSystem(this.persistence,key,this,expectedRevision);}
 async load(key='ultimate-state'){return D.SystemPersistence.loadSystem(this.persistence,key,this);}
 theme(input={}){return D.UI.themeFor(input);}
 snapshot(){return {core:this.core.snapshot(),active:clone(this.active),latency:this.latency.summary(),tools:this.tools.tools.size,models:this.models.models.size,researchSaturation:this.research.saturation(),motion:this.motion.snapshot(),knowledgeBuckets:this.knowledge.rows.size,relationshipEdges:this.relationships.edges.size,plots:this.plots.rows.size};}
}
return {SevenUltimateOS,modules:D};
});
