(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenToolIR=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const check=(v,m)=>{if(!v)throw new Error(m)};
const now=()=>Date.now();
const stable=v=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(stable).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';};
const fastHash=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return('00000000'+(h>>>0).toString(16)).slice(-8);};
const TYPES=new Set(['null','boolean','object','array','number','integer','string']);

class SchemaFirewall{
 constructor(input={}){this.maxDepth=Math.max(2,Number(input.maxDepth||16));this.maxNodes=Math.max(16,Number(input.maxNodes||4096));this.maxProperties=Math.max(1,Number(input.maxProperties||512));this.maxEnum=Math.max(1,Number(input.maxEnum||512));this.allowExternalRefs=input.allowExternalRefs===true;}
 inspect(schema={}){let nodes=0,properties=0;const seen=new Set(),walk=(x,depth,path)=>{check(depth<=this.maxDepth,'SCHEMA_DEPTH_LIMIT:'+path);check(++nodes<=this.maxNodes,'SCHEMA_NODE_LIMIT');if(x==null||typeof x!=='object')return;if(seen.has(x))throw new Error('SCHEMA_CYCLE:'+path);seen.add(x);if(x.$ref){const r=String(x.$ref);if(!r.startsWith('#/')&&!this.allowExternalRefs)throw new Error('SCHEMA_EXTERNAL_REF_BLOCKED:'+r);}if(x.type){const ts=Array.isArray(x.type)?x.type:[x.type];for(const t of ts)check(TYPES.has(t),'SCHEMA_TYPE_INVALID:'+t);}if(x.properties){const ks=Object.keys(x.properties);properties+=ks.length;check(properties<=this.maxProperties,'SCHEMA_PROPERTY_LIMIT');for(const k of ks)walk(x.properties[k],depth+1,path+'.properties.'+k);}if(x.items)walk(x.items,depth+1,path+'.items');for(const key of['allOf','anyOf','oneOf','prefixItems'])if(Array.isArray(x[key]))x[key].forEach((y,i)=>walk(y,depth+1,`${path}.${key}[${i}]`));if(x.not)walk(x.not,depth+1,path+'.not');if(x.additionalProperties&&typeof x.additionalProperties==='object')walk(x.additionalProperties,depth+1,path+'.additionalProperties');if(Array.isArray(x.enum))check(x.enum.length<=this.maxEnum,'SCHEMA_ENUM_LIMIT');seen.delete(x);};walk(schema,0,'$');return{ok:true,nodes,properties,hash:fastHash(schema)};}
 validate(schema={},value,path='$'){const t=schema.type,allowed=Array.isArray(t)?t:t?[t]:[];if(allowed.length){const actual=value===null?'null':Array.isArray(value)?'array':Number.isInteger(value)?'integer':typeof value;const numeric=actual==='integer'&&allowed.includes('number');check(allowed.includes(actual)||numeric,`SCHEMA_VALUE_TYPE:${path}`);}if(schema.enum)check(schema.enum.some(x=>stable(x)===stable(value)),`SCHEMA_VALUE_ENUM:${path}`);if(schema.const!==undefined)check(stable(schema.const)===stable(value),`SCHEMA_VALUE_CONST:${path}`);if(value&&typeof value==='object'&&!Array.isArray(value)){for(const k of schema.required||[])check(Object.prototype.hasOwnProperty.call(value,k),`SCHEMA_VALUE_REQUIRED:${path}.${k}`);const props=schema.properties||{};for(const[k,v]of Object.entries(value)){if(props[k])this.validate(props[k],v,path+'.'+k);else if(schema.additionalProperties===false)throw new Error(`SCHEMA_VALUE_UNKNOWN:${path}.${k}`);else if(schema.additionalProperties&&typeof schema.additionalProperties==='object')this.validate(schema.additionalProperties,v,path+'.'+k);}}if(Array.isArray(value)&&schema.items)for(let i=0;i<value.length;i++)this.validate(schema.items,value[i],`${path}[${i}]`);if(typeof value==='string'){if(schema.minLength!=null)check(value.length>=schema.minLength,`SCHEMA_VALUE_MIN_LENGTH:${path}`);if(schema.maxLength!=null)check(value.length<=schema.maxLength,`SCHEMA_VALUE_MAX_LENGTH:${path}`);if(schema.pattern)check(new RegExp(schema.pattern).test(value),`SCHEMA_VALUE_PATTERN:${path}`);}if(typeof value==='number'){if(schema.minimum!=null)check(value>=schema.minimum,`SCHEMA_VALUE_MIN:${path}`);if(schema.maximum!=null)check(value<=schema.maximum,`SCHEMA_VALUE_MAX:${path}`);}return true;}
}

class ToolIR{
 constructor(input={}){this.firewall=input.firewall||new SchemaFirewall();}
 normalize(x={}){check(x.id||x.name,'TOOL_IR_ID_REQUIRED');const inputSchema=clone(x.inputSchema||x.schema||{type:'object',properties:{},additionalProperties:false}),outputSchema=clone(x.outputSchema||null);this.firewall.inspect(inputSchema);if(outputSchema)this.firewall.inspect(outputSchema);const id=String(x.id||x.name);return Object.freeze({irVersion:'1',id,name:String(x.name||id),namespace:String(x.namespace||id.split('.')[0]||'general'),description:String(x.description||''),capabilities:[...new Set((x.capabilities||[id]).map(String))],protocol:String(x.protocol||'local'),providerId:String(x.providerId||'seven'),providerOperation:String(x.providerOperation||x.originalName||id),version:String(x.version||'1'),inputSchema,outputSchema,actionClass:String(x.actionClass||'read'),sideEffects:clone(x.sideEffects||[]),idempotent:x.idempotent!==false,reversible:x.reversible!==false,deterministic:!!x.deterministic,network:String(x.network||'optional'),privacy:String(x.privacy||'private'),permissions:clone(x.permissions||[]),trustZone:Number.isFinite(x.trustZone)?x.trustZone:4,authority:Math.max(0,Number(x.authority||0)),preconditions:clone(x.preconditions||[]),postconditions:clone(x.postconditions||[]),verification:clone(x.verification||[]),cache:clone(x.cache||{}),resources:clone(x.resources||{}),examples:clone(x.examples||[]),metadata:clone(x.metadata||{}),schemaFingerprint:fastHash(inputSchema),definitionFingerprint:fastHash({id,description:x.description||'',protocol:x.protocol||'local',providerId:x.providerId||'seven',inputSchema,outputSchema,actionClass:x.actionClass||'read',permissions:x.permissions||[],network:x.network||'optional',trustZone:x.trustZone??4})});}
 fromGenome(g){return this.normalize(g);}
 fromMCP(tool={},input={}){check(tool.name,'MCP_TOOL_NAME_REQUIRED');return this.normalize({id:input.id||`mcp.${input.serverId||'server'}.${tool.name}`,name:tool.title||tool.name,namespace:input.namespace||`mcp.${input.serverId||'server'}`,description:tool.description||'',capabilities:tool.capabilities||[tool.name],protocol:'mcp',providerId:input.serverId||'server',providerOperation:tool.name,version:tool.version||'1',inputSchema:tool.inputSchema,outputSchema:tool.outputSchema,actionClass:tool.annotations?.readOnlyHint?'read':input.actionClass||'external_action',reversible:!!tool.annotations?.readOnlyHint,permissions:input.permissions||[`mcp:${input.serverId||'server'}:${tool.name}`],trustZone:input.trustZone??3,metadata:{annotations:clone(tool.annotations||{}),source:'mcp'}});}
 fromOpenAPI(operation={},input={}){check(operation.operationId,'OPENAPI_OPERATION_ID_REQUIRED');const method=String(input.method||operation.method||'GET').toUpperCase();return this.normalize({id:input.id||`openapi.${input.providerId||'api'}.${operation.operationId}`,name:operation.summary||operation.operationId,description:operation.description||'',namespace:input.namespace||`openapi.${input.providerId||'api'}`,protocol:'openapi',providerId:input.providerId||'api',providerOperation:operation.operationId,inputSchema:input.inputSchema||operation.inputSchema||{type:'object',properties:{},additionalProperties:true},outputSchema:input.outputSchema||operation.outputSchema||null,actionClass:['GET','HEAD','OPTIONS'].includes(method)?'read':input.actionClass||'external_action',network:'required',trustZone:input.trustZone??3,permissions:input.permissions||[`api:${input.providerId||'api'}:${operation.operationId}`],metadata:{method,path:input.path||operation.path||null,source:'openapi'}});}
 fromGraphQL(field={},input={}){check(field.name,'GRAPHQL_FIELD_REQUIRED');const mutation=input.operationType==='mutation';return this.normalize({id:input.id||`graphql.${input.providerId||'api'}.${field.name}`,name:field.name,description:field.description||'',namespace:input.namespace||`graphql.${input.providerId||'api'}`,protocol:'graphql',providerId:input.providerId||'api',providerOperation:field.name,inputSchema:input.inputSchema||{type:'object',properties:{},additionalProperties:true},outputSchema:input.outputSchema||null,actionClass:mutation?'external_action':'read',network:'required',trustZone:input.trustZone??3,metadata:{operationType:input.operationType||'query',source:'graphql'}});}
 fromCLI(command={},input={}){check(command.name,'CLI_COMMAND_REQUIRED');return this.normalize({id:input.id||`cli.${command.name}`,name:command.title||command.name,description:command.description||'',namespace:input.namespace||'cli',protocol:'cli',providerId:input.providerId||'local',providerOperation:command.name,inputSchema:input.inputSchema||command.inputSchema||{type:'object',properties:{args:{type:'array',items:{type:'string'}}},additionalProperties:false},outputSchema:input.outputSchema||null,actionClass:input.actionClass||'read',network:input.network||'optional',trustZone:input.trustZone??1,permissions:input.permissions||[`cli:${command.name}`],metadata:{source:'cli'}});}
}

class ProviderSchemaCompiler{
 constructor(input={}){this.ir=input.ir||new ToolIR();}
 openAI(tool){const t=tool.irVersion?tool:this.ir.normalize(tool);return{type:'function',function:{name:t.id,description:t.description||t.name,parameters:clone(t.inputSchema)}};}
 anthropic(tool){const t=tool.irVersion?tool:this.ir.normalize(tool);return{name:t.id,description:t.description||t.name,input_schema:clone(t.inputSchema)};}
 mcp(tool){const t=tool.irVersion?tool:this.ir.normalize(tool);return{name:t.providerOperation||t.id,title:t.name,description:t.description,inputSchema:clone(t.inputSchema),...(t.outputSchema?{outputSchema:clone(t.outputSchema)}:{})};}
 minimal(tool,level=1){const t=tool.irVersion?tool:this.ir.normalize(tool),o={id:t.id,name:t.name};if(level>=1)o.description=t.description;if(level>=2)o.capabilities=clone(t.capabilities);if(level>=3)o.inputSchema=clone(t.inputSchema);if(level>=4){o.outputSchema=clone(t.outputSchema);o.examples=clone(t.examples);o.verification=clone(t.verification);}return o;}
}

class InvocationIR{
 constructor(input={}){check(input.capabilityId||input.toolId,'INVOCATION_CAPABILITY_REQUIRED');this.version='1';this.id=String(input.id||`invoke_${now()}_${fastHash({r:Math.random(),t:now()})}`);this.capabilityId=String(input.capabilityId||input.toolId);this.args=clone(input.args||{});this.scope=String(input.scope||'*');this.taskId=input.taskId||null;this.idempotencyKey=input.idempotencyKey||null;this.inputLabels=[...new Set(input.inputLabels||[])];this.expectedType=input.expectedType||null;this.deadlineMs=input.deadlineMs||null;this.generation=input.generation??null;this.lineage=clone(input.lineage||[]);this.createdAt=now();Object.freeze(this);}
}

class TypedResultBus{
 constructor(input={}){this.limit=Math.max(16,Number(input.limit||2048));this.rows=new Map();this.order=[];}
 publish(input={}){check(input.type&&input.source,'RESULT_BUS_FIELDS_REQUIRED');const id=input.id||`result_${now()}_${fastHash({n:this.order.length,source:input.source})}`,row={id,type:input.type,source:clone(input.source),value:clone(input.value),artifactRef:input.artifactRef||null,labels:[...new Set(input.labels||[])],lineage:clone(input.lineage||[]),authority:Math.max(0,Number(input.authority||0)),verified:input.verified===true,createdAt:now()};this.rows.set(id,row);this.order.push(id);while(this.order.length>this.limit){const old=this.order.shift();this.rows.delete(old);}return clone(row);}
 get(id){return clone(this.rows.get(id)||null);}
 project(id,projector){const row=this.rows.get(id);check(row,'RESULT_NOT_FOUND');return typeof projector==='function'?projector(clone(row)):clone(row);}
}

class ArtifactRefStore{
 constructor(input={}){this.maxInlineBytes=Math.max(128,Number(input.maxInlineBytes||4096));this.artifacts=new Map();}
 put(value,input={}){const serialized=typeof value==='string'?value:JSON.stringify(value),bytes=typeof TextEncoder!=='undefined'?new TextEncoder().encode(serialized).length:serialized.length,id=`artifact:${fastHash(serialized)}:${bytes}`;if(!this.artifacts.has(id))this.artifacts.set(id,{id,type:input.type||'Artifact',mediaType:input.mediaType||'application/json',bytes,value:clone(value),createdAt:now(),lineage:clone(input.lineage||[])});return{id,type:input.type||'Artifact',mediaType:input.mediaType||'application/json',bytes};}
 get(ref){const id=typeof ref==='string'?ref:ref?.id,x=this.artifacts.get(id);check(x,'ARTIFACT_NOT_FOUND');return clone(x);}
 maybeExternalize(value,input={}){const s=typeof value==='string'?value:JSON.stringify(value);return s.length>this.maxInlineBytes?{artifactRef:this.put(value,input),inline:false}:{value:clone(value),inline:true};}
}

class CapabilityLockfile{
 constructor(){this.rows=new Map();}
 pin(tool){const t=tool.irVersion?tool:new ToolIR().normalize(tool),row={id:t.id,version:t.version,providerId:t.providerId,schemaFingerprint:t.schemaFingerprint,definitionFingerprint:t.definitionFingerprint};this.rows.set(t.id,row);return clone(row);}
 verify(tool){const t=tool.irVersion?tool:new ToolIR().normalize(tool),p=this.rows.get(t.id);if(!p)return{ok:false,reason:'UNPINNED'};for(const k of['version','providerId','schemaFingerprint','definitionFingerprint'])if(p[k]!==t[k])return{ok:false,reason:'LOCKFILE_MISMATCH',field:k,expected:p[k],actual:t[k]};return{ok:true};}
 snapshot(){return[...this.rows.values()].map(clone);}
}

return{SchemaFirewall,ToolIR,ProviderSchemaCompiler,InvocationIR,TypedResultBus,ArtifactRefStore,CapabilityLockfile,fastHash,stable};
});