(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateUI=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const PALETTE=Object.freeze({midnight:'#07111F',obsidian:'#101A2A',graphite:'#263247',pearl:'#F7F8FA',mist:'#FFFFFF',sevenBlue:'#4D7CFE',auroraBlue:'#70C7FF',sevenViolet:'#8068FF',pearlPeach:'#FFC8AF',softSilver:'#A9B4C6'});
const SPACING=Object.freeze([0,4,8,12,16,20,24,32,40,48,64,80]);
const BREAKPOINTS=Object.freeze({small:480,medium:640,large:1024,xlarge:1366,xxlarge:1920});
const CONTROL=Object.freeze({minimum:44,compact:36,comfortable:44,touch:48,focusRing:2});
const MOTION=Object.freeze({instant:[70,90],quick:[110,140],standard:[160,200],spatial:[210,260],expressive:[280,380],ambient:[2000,8000]});
const EASING=Object.freeze({standard:'cubic-bezier(.2,.8,.2,1)',emphasized:'cubic-bezier(.16,1,.3,1)',exit:'cubic-bezier(.4,0,1,1)',linear:'linear'});
const AURORA=Object.freeze({idle:'sevenBlue',thinking:'blue-violet',research:'auroraBlue',coding:'sevenBlue',rpg:'sevenViolet',success:'semantic-green',warning:'semantic-amber',error:'semantic-coral'});
const TYPE=Object.freeze({caption:10,small:11,body:13,bodyLarge:15,title:24,hero:28});
function clamp(n,a,b){return Math.max(a,Math.min(b,Number(n)||0));}
function periodFor(date=new Date(),opts={}){const h=date.getHours()+date.getMinutes()/60;const dawnStart=opts.dawnStart??5,dawnEnd=opts.dawnEnd??7,duskStart=opts.duskStart??17.5,duskEnd=opts.duskEnd??19;if(h>=dawnStart&&h<dawnEnd)return'dawn';if(h>=dawnEnd&&h<duskStart)return'day';if(h>=duskStart&&h<duskEnd)return'dusk';return'night';}
function themeFor(input={}){const mode=input.mode||'automatic';let period=input.period||periodFor(input.date||new Date(),input.schedule||{});if(mode==='day')period='day';if(mode==='night')period='night';if(mode==='system')period=input.systemDark?'night':'day';const dark=period==='night'||period==='dusk';return {mode,period,dark,launcherIcon:dark?'seven-night':'seven-day',logoTreatment:dark?'night':'day',tokens:dark?{background:PALETTE.midnight,surface:PALETTE.obsidian,raised:'#172338',text:'#F6F8FC',secondary:'#9CA9BD',accent:PALETTE.auroraBlue}:{background:PALETTE.pearl,surface:PALETTE.mist,raised:'#F1F4F8',text:'#111827',secondary:'#657085',accent:PALETTE.sevenBlue}};}
function responsiveMode(width=0){const w=Math.max(0,Number(width)||0);if(w<BREAKPOINTS.small)return'compact';if(w<BREAKPOINTS.medium)return'small';if(w<BREAKPOINTS.large)return'medium';if(w<BREAKPOINTS.xlarge)return'large';if(w<BREAKPOINTS.xxlarge)return'xlarge';return'xxlarge';}
function motionContract(input={}){const reduced=!!input.reducedMotion,low=!!input.lowPower;const base={appearance:'stable',enter:'standard-fade-rise',active:'state-specific',success:'check-morph',failure:'semantic-coral-once',cancel:'stop-and-fade',exit:'quick-fade'};if(reduced)return {...base,enter:'opacity-only',active:'static-state',success:'opacity-only',failure:'semantic-color-only',cancel:'opacity-only',exit:'opacity-only'};if(low)return {...base,enter:'quick-fade',active:'minimal-progress',success:'quick-fade',failure:'semantic-color-once',cancel:'quick-fade',exit:'quick-fade'};return base;}
function resolveMotion(kind='standard',input={}){const reduced=!!input.reducedMotion,low=!!input.lowPower,size=clamp(input.size??.5,0,1),importance=clamp(input.importance??.5,0,1);if(reduced)return{kind:'reduced',duration:0,easing:EASING.standard,properties:['opacity']};let range=MOTION[kind]||MOTION.standard;if(low&&['expressive','ambient'].includes(kind))range=MOTION.quick;const duration=Math.round(range[0]+(range[1]-range[0])*Math.max(size,importance));const properties=kind==='ambient'?['opacity','transform']:['opacity','transform'];return{kind,duration,easing:kind==='expressive'?EASING.emphasized:EASING.standard,properties};}
function interactionProfile(input={}){const coarse=!!input.coarsePointer,reduced=!!input.reducedMotion,low=!!input.lowPower,width=Number(input.width||0),mode=responsiveMode(width);return{mode,minTarget:coarse?CONTROL.touch:CONTROL.minimum,density:mode==='compact'?'comfortable':input.density||'comfortable',hover:!coarse,glass:!low,ambient:!reduced&&!low,containerTransforms:!reduced,focusRing:CONTROL.focusRing};}
function accessibilityContract(input={}){return{minimumTarget:Number(input.minimumTarget||CONTROL.minimum),keyboard:true,visibleFocus:true,colorIndependentState:true,reducedMotion:true,reflow320:true,textZoom200:true,ariaLive:input.ariaLive||'polite',role:input.role||null};}
class MotionScheduler{
 constructor(opts={}){this.maxExpressive=opts.maxExpressive||2;this.maxAmbient=opts.maxAmbient||2;this.active=[];this.queue=[];}
 request(input={}){const item={id:input.id||`motion_${Date.now()}_${Math.random()}`,kind:input.kind||'standard',priority:Number(input.priority||0),critical:!!input.critical};const limit=item.kind==='expressive'?this.maxExpressive:item.kind==='ambient'?this.maxAmbient:Infinity;const same=this.active.filter(x=>x.kind===item.kind).length;if(same<limit||item.critical){this.active.push(item);return {state:'active',item};}this.queue.push(item);this.queue.sort((a,b)=>b.priority-a.priority);return {state:'queued',item};}
 complete(id){this.active=this.active.filter(x=>x.id!==id);for(const kind of['expressive','ambient']){const limit=kind==='expressive'?this.maxExpressive:this.maxAmbient;while(this.active.filter(x=>x.kind===kind).length<limit){const i=this.queue.findIndex(x=>x.kind===kind);if(i<0)break;this.active.push(this.queue.splice(i,1)[0]);}}return this.snapshot();}
 snapshot(){return {active:this.active.map(x=>({...x})),queued:this.queue.map(x=>({...x}))};}
}
return {PALETTE,SPACING,BREAKPOINTS,CONTROL,MOTION,EASING,AURORA,TYPE,periodFor,themeFor,responsiveMode,motionContract,resolveMotion,interactionProfile,accessibilityContract,MotionScheduler};
});