(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateUI=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const PALETTE=Object.freeze({midnight:'#07111F',obsidian:'#101A2A',graphite:'#263247',pearl:'#F7F8FA',mist:'#FFFFFF',sevenBlue:'#4D7CFE',auroraBlue:'#70C7FF',sevenViolet:'#8068FF',pearlPeach:'#FFC8AF',softSilver:'#A9B4C6'});
const MOTION=Object.freeze({instant:[70,90],quick:[110,140],standard:[160,200],spatial:[210,260],expressive:[280,380],ambient:[2000,8000]});
const AURORA=Object.freeze({idle:'sevenBlue',thinking:'blue-violet',research:'auroraBlue',coding:'sevenBlue',rpg:'sevenViolet',success:'semantic-green',warning:'semantic-amber',error:'semantic-coral'});
function periodFor(date=new Date(),opts={}){const h=date.getHours()+date.getMinutes()/60;const dawnStart=opts.dawnStart??5,dawnEnd=opts.dawnEnd??7,duskStart=opts.duskStart??17.5,duskEnd=opts.duskEnd??19;if(h>=dawnStart&&h<dawnEnd)return'dawn';if(h>=dawnEnd&&h<duskStart)return'day';if(h>=duskStart&&h<duskEnd)return'dusk';return'night';}
function themeFor(input={}){const mode=input.mode||'automatic';let period=input.period||periodFor(input.date||new Date(),input.schedule||{});if(mode==='day')period='day';if(mode==='night')period='night';if(mode==='system')period=input.systemDark?'night':'day';const dark=period==='night'||period==='dusk';return {mode,period,dark,launcherIcon:dark?'seven-night':'seven-day',logoTreatment:dark?'night':'day',tokens:dark?{background:PALETTE.midnight,surface:PALETTE.obsidian,raised:'#172338',text:'#F6F8FC',secondary:'#9CA9BD',accent:PALETTE.auroraBlue}:{background:PALETTE.pearl,surface:PALETTE.mist,raised:'#F1F4F8',text:'#111827',secondary:'#657085',accent:PALETTE.sevenBlue}};}
function motionContract(input={}){const reduced=!!input.reducedMotion,low=!!input.lowPower;const base={appearance:'stable',enter:'standard-fade-rise',active:'state-specific',success:'check-morph',failure:'semantic-coral-once',cancel:'stop-and-fade',exit:'quick-fade'};if(reduced)return {...base,enter:'opacity-only',active:'static-state',success:'opacity-only',failure:'semantic-color-only',cancel:'opacity-only',exit:'opacity-only'};if(low)return {...base,enter:'quick-fade',active:'minimal-progress',success:'quick-fade',failure:'semantic-color-once',cancel:'quick-fade',exit:'quick-fade'};return base;}
class MotionScheduler{
 constructor(opts={}){this.maxExpressive=opts.maxExpressive||2;this.maxAmbient=opts.maxAmbient||2;this.active=[];this.queue=[];}
 request(input={}){const item={id:input.id||`motion_${Date.now()}_${Math.random()}`,kind:input.kind||'standard',priority:Number(input.priority||0),critical:!!input.critical};const limit=item.kind==='expressive'?this.maxExpressive:item.kind==='ambient'?this.maxAmbient:Infinity;const same=this.active.filter(x=>x.kind===item.kind).length;if(same<limit||item.critical){this.active.push(item);return {state:'active',item};}this.queue.push(item);this.queue.sort((a,b)=>b.priority-a.priority);return {state:'queued',item};}
 complete(id){this.active=this.active.filter(x=>x.id!==id);for(const kind of['expressive','ambient']){const limit=kind==='expressive'?this.maxExpressive:this.maxAmbient;while(this.active.filter(x=>x.kind===kind).length<limit){const i=this.queue.findIndex(x=>x.kind===kind);if(i<0)break;this.active.push(this.queue.splice(i,1)[0]);}}return this.snapshot();}
 snapshot(){return {active:this.active.map(x=>({...x})),queued:this.queue.map(x=>({...x}))};}
}
return {PALETTE,MOTION,AURORA,periodFor,themeFor,motionContract,MotionScheduler};
});
