(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateVisualCanon=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const check=(v,m)=>{if(!v)throw new Error(m)};
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
class VisualCanonVault{
 constructor(){this.characters=new Map();this.images=new Map();}
 key(gameId,entityId){return `${gameId}:${entityId}`;}
 registerCharacter(gameId,entityId,input={}){const k=this.key(gameId,entityId);check(!this.characters.has(k),'VISUAL_CHARACTER_EXISTS');const c={gameId,entityId,version:1,identity:clone(input.identity||{}),palette:clone(input.palette||{}),hair:clone(input.hair||{}),eyes:clone(input.eyes||{}),body:clone(input.body||{}),defaultOutfit:input.defaultOutfit||null,outfits:new Map(),accessories:new Map(),references:[],currentState:{outfitId:input.defaultOutfit||null,hairState:input.hairState||'default',accessoryIds:[],notes:[]},history:[]};this.characters.set(k,c);return this.summary(gameId,entityId);}
 get(gameId,entityId){const c=this.characters.get(this.key(gameId,entityId));check(c,'VISUAL_CHARACTER_NOT_FOUND');return c;}
 addOutfit(gameId,entityId,input={}){const c=this.get(gameId,entityId);check(input.id,'OUTFIT_ID_REQUIRED');check(!c.outfits.has(input.id),'OUTFIT_EXISTS');c.outfits.set(input.id,clone(input));if(!c.defaultOutfit)c.defaultOutfit=input.id;if(!c.currentState.outfitId)c.currentState.outfitId=input.id;return clone(input);}
 addAccessory(gameId,entityId,input={}){const c=this.get(gameId,entityId);check(input.id,'ACCESSORY_ID_REQUIRED');check(!c.accessories.has(input.id),'ACCESSORY_EXISTS');c.accessories.set(input.id,clone(input));return clone(input);}
 addReference(gameId,entityId,input={}){const c=this.get(gameId,entityId);check(input.id&&input.kind,'REFERENCE_REQUIRED');check(!c.references.some(x=>x.id===input.id),'REFERENCE_EXISTS');const r={id:input.id,kind:input.kind,uri:input.uri||null,episodeId:input.episodeId||null,sceneId:input.sceneId||null,canonVersion:c.version,notes:input.notes||null};c.references.push(r);return clone(r);}
 transition(gameId,entityId,input={}){const c=this.get(gameId,entityId),before=clone(c.currentState);if(input.outfitId!=null){check(c.outfits.has(input.outfitId),'OUTFIT_NOT_FOUND');c.currentState.outfitId=input.outfitId;}if(input.hairState!=null)c.currentState.hairState=input.hairState;if(input.accessoryIds){for(const id of input.accessoryIds)check(c.accessories.has(id),'ACCESSORY_NOT_FOUND');c.currentState.accessoryIds=[...input.accessoryIds];}if(input.notes)c.currentState.notes=[...input.notes];c.version++;const ev={id:input.id||`visual_${c.version}`,episodeId:input.episodeId||null,sceneId:input.sceneId||null,worldTime:input.worldTime||null,before,after:clone(c.currentState),version:c.version,sourceEventRef:input.sourceEventRef||null};c.history.push(ev);return clone(ev);}
 referencePack(gameId,entityId){const c=this.get(gameId,entityId);const priority=['main_portrait','three_quarter','side_view','full_body','neutral','expression_sheet','outfit'];const refs=[...c.references].sort((a,b)=>priority.indexOf(a.kind)-priority.indexOf(b.kind));return {entityId,version:c.version,identity:clone(c.identity),palette:clone(c.palette),hair:clone(c.hair),eyes:clone(c.eyes),body:clone(c.body),state:clone(c.currentState),outfit:clone(c.outfits.get(c.currentState.outfitId)||null),accessories:c.currentState.accessoryIds.map(id=>clone(c.accessories.get(id))),references:clone(refs)};}
 registerGeneratedImage(input={}){check(input.id&&input.gameId,'IMAGE_REQUIRED');check(!this.images.has(input.id),'IMAGE_EXISTS');const chars=(input.characters||[]).map(x=>{const c=this.get(input.gameId,x.entityId);return {entityId:x.entityId,visualCanonVersion:x.visualCanonVersion||c.version,outfitId:x.outfitId||c.currentState.outfitId,slot:x.slot||null};});const row={id:input.id,gameId:input.gameId,campaignId:input.campaignId||null,timelineId:input.timelineId||null,episodeId:input.episodeId||null,sceneId:input.sceneId||null,worldTime:input.worldTime||null,locationId:input.locationId||null,characters:chars,model:input.model||null,seed:input.seed||null,workflow:input.workflow||null,uri:input.uri||null,accepted:false,scores:null};this.images.set(row.id,row);return clone(row);}
 evaluateImage(imageId,scores={}){const row=this.images.get(imageId);check(row,'IMAGE_NOT_FOUND');const normalized={identity:clamp(scores.identity),hair:clamp(scores.hair),eyes:clamp(scores.eyes),outfit:clamp(scores.outfit),accessories:clamp(scores.accessories),style:clamp(scores.style),pose:clamp(scores.pose),scene:clamp(scores.scene)};const critical=Math.min(normalized.identity,normalized.hair,normalized.outfit,normalized.scene),average=Object.values(normalized).reduce((a,b)=>a+b,0)/Object.keys(normalized).length;row.scores=normalized;row.accepted=critical>=85&&average>=88;return {accepted:row.accepted,critical,average:+average.toFixed(1),scores:clone(normalized),action:row.accepted?'pass':'repair_or_regenerate'};}
 summary(gameId,entityId){const c=this.get(gameId,entityId);return {gameId,entityId,version:c.version,outfits:c.outfits.size,accessories:c.accessories.size,references:c.references.length,currentState:clone(c.currentState),historyCount:c.history.length};}
}
return {VisualCanonVault};
});
