(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateShell=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const VIEW_META={home:['Home',''],chat:['Chat',''],research:['Research Studio','Evidence first'],coding:['Coding Studio','Agent workspace'],projects:['Projects','Persistent context'],memory:['Memory','Continuity'],tools:['Tools','Capabilities'],models:['Models','Intelligence'],rpg:['Storyworld','RPG'],storyatlas:['Story Atlas','Valen'],cast:['Cast Atlas','Valen'],settings:['Settings','Seven']};
class SevenShell{
 constructor(rootEl,opts={}){if(!rootEl)throw new Error('SHELL_ROOT_REQUIRED');this.root=rootEl;this.opts=opts;this.runtime=opts.runtime||null;this.state={view:opts.initialView||'home',theme:opts.theme||'automatic',sidebar:false,workbench:false,halo:'idle',lowPower:false};this.elements={};this._bind();this.applyTheme();this.navigate(this.state.view,{replace:true});this.refreshClock();this.clockTimer=setInterval(()=>this.refreshClock(),30000);}
 _bind(){const r=this.root;this.elements.stage=qs('.seven-stage',r);this.elements.title=qs('.seven-title',r);this.elements.breadcrumb=qs('.seven-breadcrumb',r);this.elements.halo=qs('.seven-halo',r);this.elements.haloText=qs('.seven-halo-text',r);this.elements.composer=qs('.seven-composer textarea',r);this.elements.overlay=qs('.seven-overlay',r);qsa('[data-view-target]',r).forEach(b=>b.addEventListener('click',()=>this.navigate(b.dataset.viewTarget)));qsa('[data-action="menu"]',r).forEach(b=>b.addEventListener('click',()=>this.toggleSidebar()));qsa('[data-action="workbench"]',r).forEach(b=>b.addEventListener('click',()=>this.toggleWorkbench()));qsa('[data-action="overlay"]',r).forEach(b=>b.addEventListener('click',()=>this.closeSheets()));qsa('[data-action="theme"]',r).forEach(b=>b.addEventListener('click',()=>this.cycleTheme()));qsa('[data-action="send"]',r).forEach(b=>b.addEventListener('click',()=>this.send()));this.elements.composer?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();this.send();}});this.elements.composer?.addEventListener('input',e=>{e.target.style.height='36px';e.target.style.height=Math.min(160,e.target.scrollHeight)+'px';});qsa('.seven-switch',r).forEach(s=>s.addEventListener('click',()=>{s.dataset.on=s.dataset.on==='true'?'false':'true';s.setAttribute('aria-checked',s.dataset.on);}));window.addEventListener('resize',()=>{if(innerWidth>760){this.state.sidebar=false;this.root.dataset.sidebar='closed';}});}
 destroy(){clearInterval(this.clockTimer);}
 resolveTheme(date=new Date()){if(this.state.theme==='day'||this.state.theme==='light')return'day';if(this.state.theme==='night'||this.state.theme==='dark')return'night';if(this.state.theme==='system')return matchMedia('(prefers-color-scheme: dark)').matches?'night':'day';return(date.getHours()<7||date.getHours()>=19)?'night':'day';}
 applyTheme(date=new Date()){const theme=this.resolveTheme(date);this.root.dataset.theme=theme;document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme==='night'?'dark':'light';const mode=qs('[data-theme-label]',this.root);if(mode)mode.textContent=this.state.theme==='automatic'?`Auto · ${theme}`:this.state.theme;return theme;}
 cycleTheme(){const list=['automatic','day','night','system'],i=list.indexOf(this.state.theme);this.state.theme=list[(i+1)%list.length];this.applyTheme();}
 refreshClock(){const d=new Date();this.applyTheme(d);qsa('[data-local-time]',this.root).forEach(x=>x.textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));qsa('[data-greeting]',this.root).forEach(x=>x.textContent=d.getHours()<12?'Good morning.':d.getHours()<18?'Good afternoon.':'Good evening.');}
 navigate(view,opts={}){if(!VIEW_META[view])view='home';this.state.view=view;qsa('.seven-view',this.root).forEach(v=>v.dataset.active=String(v.dataset.view===view));qsa('[data-view-target]',this.root).forEach(b=>b.setAttribute('aria-current',b.dataset.viewTarget===view?'page':'false'));const [title,crumb]=VIEW_META[view];if(this.elements.title)this.elements.title.textContent=title;if(this.elements.breadcrumb)this.elements.breadcrumb.textContent=crumb;this.closeSheets();this.setHalo(view==='research'?'research':view==='coding'?'coding':['rpg','storyatlas','cast'].includes(view)?'rpg':'idle',view==='rpg'?'Valen · Episode 14':null);if(!opts.replace&&history?.pushState)history.pushState({view},'',`#${view}`);this.elements.stage?.scrollTo?.({top:0,behavior:'instant'});return view;}
 setHalo(mode,label=null,count=null){this.state.halo=mode;this.elements.halo?.setAttribute('data-halo',mode);if(this.elements.haloText){const base=label||({idle:'Seven',thinking:'Thinking',research:'Research',coding:'Agent',rpg:'RPG',success:'Completed',error:'Error'}[mode]||'Seven');this.elements.haloText.textContent=count==null?base:`${base} · ${count}`;}}
 toggleSidebar(force){this.state.sidebar=force??!this.state.sidebar;this.root.dataset.sidebar=this.state.sidebar?'open':'closed';if(this.state.sidebar)this.state.workbench=false;this.root.dataset.workbench=this.state.workbench?'open':'closed';}
 toggleWorkbench(force){this.state.workbench=force??!this.state.workbench;this.root.dataset.workbench=this.state.workbench?'open':'closed';if(innerWidth<=760&&this.state.workbench)this.state.sidebar=false;this.root.dataset.sidebar=this.state.sidebar?'open':'closed';}
 closeSheets(){this.state.sidebar=false;this.state.workbench=false;this.root.dataset.sidebar='closed';this.root.dataset.workbench='closed';}
 setLowPower(on){this.state.lowPower=!!on;this.root.dataset.lowPower=String(this.state.lowPower);}
 addMessage(role,text){const stream=qs('[data-chat-stream]',this.root);if(!stream)return null;const wrapper=document.createElement('div');wrapper.className=`seven-message seven-message-${role==='user'?'user':'ai'}`;if(role==='user')wrapper.innerHTML=`<div class="seven-message-body"></div>`;else wrapper.innerHTML=`<div class="seven-mark seven-mini-mark">7</div><div><div class="seven-message-name">Seven</div><div class="seven-message-body"></div><div class="seven-message-actions"><button class="seven-action">Copy</button><button class="seven-action">Retry</button><button class="seven-action">Branch</button></div></div>`;qs('.seven-message-body',wrapper).textContent=text;stream.appendChild(wrapper);stream.scrollTop=stream.scrollHeight;return wrapper;}
 async send(){const box=this.elements.composer;if(!box)return;const text=box.value.trim();if(!text)return;box.value='';box.style.height='36px';if(this.state.view!=='chat')this.navigate('chat');this.addMessage('user',text);this.setHalo('thinking');if(this.runtime?.chat){const message=this.addMessage('ai',''),body=qs('.seven-message-body',message);let output='';try{const messages=[{role:'user',content:text}];const response=await this.runtime.chat({text,messages,onChunk:chunk=>{output+=chunk;body.textContent=output;}});if(!output)body.textContent=response?.run?.output||'Completed.';this.setHalo(response?.run?.status==='completed'?'success':'error');}catch(e){body.textContent=`Request failed: ${String(e?.message||e)}`;this.setHalo('error');}}else{setTimeout(()=>{this.addMessage('ai','Ultimate runtime is ready for provider connection. This preview is currently using the UI shell without a live model.');this.setHalo('idle');},220);}}
 renderToolActivity(items=[]){const box=qs('[data-activity-stack]',this.root);if(!box)return;box.innerHTML='';for(const item of items){const el=document.createElement('div');el.className='seven-activity';el.dataset.state=item.state||'running';el.textContent=`${item.state==='success'?'✓':item.state==='error'?'!':'◌'} ${item.title||item.id}`;box.appendChild(el);}}
 renderStoryAtlas(atlas){const box=qs('[data-story-atlas]',this.root);if(!box||!atlas)return;box.innerHTML='';for(const ep of atlas.episodes||[]){const row=document.createElement('div');row.className='seven-timeline-item';row.innerHTML=`<div class="seven-timeline-rail"><i class="seven-timeline-dot"></i></div><div class="seven-timeline-body"><strong></strong><span></span></div>`;qs('strong',row).textContent=`Episode ${ep.number||''} · ${ep.title||ep.id}`;qs('span',row).textContent=ep.canonical?`${ep.eventCount||0} canonical events`:'Planned possibility';box.appendChild(row);}}
 renderCast(cast=[]){const box=qs('[data-cast-atlas]',this.root);if(!box)return;box.innerHTML='';for(const c of cast){const row=document.createElement('div');row.className='seven-character-row';row.innerHTML=`<div class="seven-character-portrait"></div><div><strong></strong><span></span></div>`;qs('.seven-character-portrait',row).textContent=(c.name||'?').slice(0,1).toUpperCase();qs('strong',row).textContent=c.name||c.id;qs('span',row).textContent=`${c.tier||'character'} · ${c.memoryCount||0} memories`;box.appendChild(row);}}
 hydrateRuntime(){if(!this.runtime)return;try{const ids=this.runtime.active;if(ids?.gameId&&this.runtime.rpgUI){this.renderStoryAtlas(this.runtime.rpgUI.storyAtlas.build(ids.gameId,ids.campaignId,ids.timelineId,{mode:'player'}));this.renderCast(this.runtime.rpgUI.castAtlas.list(ids.gameId,ids.campaignId,ids.timelineId,{mode:'player'}));}const activity=this.runtime.activity?.summary?.();if(activity)this.renderToolActivity(activity.items);}catch(e){console.warn('Seven UI hydrate skipped',e);}}
}
function mount(selector='#seven-app',opts={}){const el=typeof selector==='string'?document.querySelector(selector):selector;if(!el)throw new Error('SEVEN_APP_NOT_FOUND');const shell=new SevenShell(el,opts);window.addEventListener('popstate',e=>shell.navigate(e.state?.view||location.hash.slice(1)||'home',{replace:true}));shell.hydrateRuntime();return shell;}
return{VIEW_META,SevenShell,mount};
});