(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SevenUltimateShell=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE_KEY='seven_ultimate_ui_v1';
const VIEW_META={home:['Home',''],chat:['Chat',''],research:['Research Studio','Evidence first'],coding:['Coding Studio','Agent workspace'],projects:['Projects','Persistent context'],memory:['Memory','Continuity'],tools:['Tools','Capabilities'],models:['Models','Intelligence'],rpg:['Storyworld','RPG'],storyatlas:['Story Atlas','Valen'],cast:['Cast Atlas','Valen'],settings:['Settings','Seven']};
const COMMANDS=[
 ['home','Home','⌂'],['chat','Chat','◫'],['research','Research Studio','◎'],['coding','Coding Studio','⌘'],['rpg','Storyworld','◇'],['storyatlas','Story Atlas','⌁'],['cast','Cast Atlas','♙'],['projects','Projects','▣'],['memory','Memory','◉'],['tools','Tools','⌗'],['models','Models','◆'],['settings','Settings','⚙']
];
class SevenShell{
 constructor(rootEl,opts={}){if(!rootEl)throw new Error('SHELL_ROOT_REQUIRED');this.root=rootEl;this.opts=opts;this.runtime=opts.runtime||null;this.prefersReduced=matchMedia?.('(prefers-reduced-motion: reduce)')||null;this.systemDark=matchMedia?.('(prefers-color-scheme: dark)')||null;const saved=this._loadPrefs();this.state={view:opts.initialView||location.hash.slice(1)||'home',theme:opts.theme||saved.theme||'automatic',sidebar:false,workbench:false,halo:'idle',lowPower:opts.lowPower??saved.lowPower??this._detectLowPower(),density:saved.density||'comfortable',command:false};this.elements={};this.lastFocus=null;this._ensurePolish();this._ensureInfrastructure();this._bind();this._applySystemState();this.applyTheme();this.navigate(this.state.view,{replace:true});this.refreshClock();this.clockTimer=setInterval(()=>this.refreshClock(),30000);}
 _loadPrefs(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch{return{}}}
 _savePrefs(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({theme:this.state.theme,lowPower:this.state.lowPower,density:this.state.density}))}catch{}}
 _detectLowPower(){const connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;return !!connection?.saveData;}
 _ensurePolish(){if(document.querySelector('link[data-seven-polish]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='src/ultimate/ui/ultimate-polish.css';link.dataset.sevenPolish='true';document.head.appendChild(link);}
 _ensureInfrastructure(){
  if(!qs('.seven-skip-link')){const a=document.createElement('a');a.className='seven-skip-link';a.href='#seven-stage';a.textContent='Skip to content';document.body.prepend(a);}
  if(!qs('[data-seven-live]')){const live=document.createElement('div');live.className='seven-visually-hidden';live.dataset.sevenLive='';live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');document.body.appendChild(live);}
  if(!qs('[data-toast-stack]')){const stack=document.createElement('div');stack.className='seven-toast-stack';stack.dataset.toastStack='';stack.setAttribute('aria-live','polite');document.body.appendChild(stack);}
  if(!qs('[data-command-layer]')){const layer=document.createElement('div');layer.className='seven-command-layer';layer.dataset.commandLayer='';layer.dataset.open='false';layer.setAttribute('role','presentation');layer.innerHTML='<section class="seven-command" role="dialog" aria-modal="true" aria-label="Seven command palette"><label class="seven-command-search"><span>⌕</span><input type="search" autocomplete="off" spellcheck="false" placeholder="Go anywhere or run a command" aria-label="Search commands"></label><div class="seven-command-list" role="listbox"></div></section>';document.body.appendChild(layer);}
  this.root.querySelector('.seven-stage')?.setAttribute('id','seven-stage');this.root.querySelector('.seven-stage')?.setAttribute('tabindex','-1');this.root.dataset.density=this.state.density;
 }
 _bind(){const r=this.root;this.elements.stage=qs('.seven-stage',r);this.elements.title=qs('.seven-title',r);this.elements.breadcrumb=qs('.seven-breadcrumb',r);this.elements.halo=qs('.seven-halo',r);this.elements.haloText=qs('.seven-halo-text',r);this.elements.composer=qs('.seven-composer textarea',r);this.elements.overlay=qs('.seven-overlay',r);this.elements.commandLayer=qs('[data-command-layer]');this.elements.commandInput=qs('.seven-command-search input');this.elements.commandList=qs('.seven-command-list');this.elements.live=qs('[data-seven-live]');
  qsa('[data-view-target]',r).forEach(b=>b.addEventListener('click',()=>this.navigate(b.dataset.viewTarget)));
  qsa('[data-action="menu"]',r).forEach(b=>b.addEventListener('click',()=>this.toggleSidebar()));qsa('[data-action="workbench"]',r).forEach(b=>b.addEventListener('click',()=>this.toggleWorkbench()));qsa('[data-action="overlay"]',r).forEach(b=>b.addEventListener('click',()=>this.closeSheets()));qsa('[data-action="theme"]',r).forEach(b=>b.addEventListener('click',()=>this.cycleTheme()));qsa('[data-action="send"]',r).forEach(b=>b.addEventListener('click',()=>this.send()));
  this.elements.composer?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();this.send();}});this.elements.composer?.addEventListener('input',e=>{e.target.style.height='36px';e.target.style.height=Math.min(160,e.target.scrollHeight)+'px';});
  qsa('.seven-switch',r).forEach(s=>{s.setAttribute('role','switch');s.setAttribute('tabindex',s.tabIndex>=0?String(s.tabIndex):'0');s.addEventListener('click',()=>this._toggleSwitch(s));s.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();this._toggleSwitch(s);}})});
  document.addEventListener('keydown',e=>this._onKeydown(e));window.addEventListener('resize',()=>this._onResize());document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.refreshClock();});this.prefersReduced?.addEventListener?.('change',()=>this._applySystemState());this.systemDark?.addEventListener?.('change',()=>{if(this.state.theme==='system')this.applyTheme();});
  this.elements.commandLayer?.addEventListener('click',e=>{if(e.target===this.elements.commandLayer)this.closeCommandPalette();});this.elements.commandInput?.addEventListener('input',()=>this._renderCommands(this.elements.commandInput.value));this.elements.commandInput?.addEventListener('keydown',e=>this._commandKeys(e));qsa('.seven-action',r).forEach(b=>this._bindAction(b));this._onResize();
 }
 _toggleSwitch(s){s.dataset.on=s.dataset.on==='true'?'false':'true';s.setAttribute('aria-checked',s.dataset.on);this.announce(`${s.getAttribute('aria-label')||'Setting'} ${s.dataset.on==='true'?'on':'off'}`);}
 _bindAction(button){if(button.dataset.bound)return;button.dataset.bound='true';button.addEventListener('click',async()=>{const label=button.textContent.trim().toLowerCase();const message=button.closest('.seven-message');if(label==='copy'&&message){const text=qs('.seven-message-body',message)?.textContent||'';try{await navigator.clipboard?.writeText?.(text);this.toast('Copied to clipboard','success');}catch{this.toast('Copy unavailable','error');}}});}
 _onKeydown(e){const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='k'){e.preventDefault();this.openCommandPalette();return;}if(e.key==='Escape'){if(this.state.command)this.closeCommandPalette();else this.closeSheets();return;}if(mod&&e.key==='/'){e.preventDefault();this.elements.composer?.focus();}}
 _commandKeys(e){const items=qsa('.seven-command-item',this.elements.commandList);if(!items.length)return;let i=items.findIndex(x=>x.dataset.active==='true');if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();i=e.key==='ArrowDown'?Math.min(items.length-1,i+1):Math.max(0,i<0?0:i-1);items.forEach((x,n)=>x.dataset.active=String(n===i));items[i]?.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'){e.preventDefault();(items[i>=0?i:0])?.click();}}
 _onResize(){const width=innerWidth;this.root.dataset.viewport=width<480?'compact':width<640?'small':width<1024?'medium':'large';if(width>760){this.state.sidebar=false;this.root.dataset.sidebar='closed';}this._syncExpanded();}
 _applySystemState(){const reduced=!!this.prefersReduced?.matches;this.root.dataset.reducedMotion=String(reduced);this.setLowPower(this.state.lowPower,{silent:true});}
 destroy(){clearInterval(this.clockTimer);}
 resolveTheme(date=new Date()){if(this.state.theme==='day'||this.state.theme==='light')return'day';if(this.state.theme==='night'||this.state.theme==='dark')return'night';if(this.state.theme==='system')return this.systemDark?.matches?'night':'day';return(date.getHours()<7||date.getHours()>=19)?'night':'day';}
 applyTheme(date=new Date()){const theme=this.resolveTheme(date);this.root.dataset.theme=theme;document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme==='night'?'dark':'light';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='night'?'#07111F':'#F7F8FA');const mode=qs('[data-theme-label]',this.root);if(mode)mode.textContent=this.state.theme==='automatic'?`Auto · ${theme}`:this.state.theme;return theme;}
 cycleTheme(){const list=['automatic','day','night','system'],i=list.indexOf(this.state.theme);this.state.theme=list[(i+1)%list.length];this.applyTheme();this._savePrefs();this.toast(`Theme: ${this.state.theme}`,'info');}
 refreshClock(){const d=new Date();this.applyTheme(d);qsa('[data-local-time]',this.root).forEach(x=>x.textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));qsa('[data-greeting]',this.root).forEach(x=>x.textContent=d.getHours()<12?'Good morning.':d.getHours()<18?'Good afternoon.':'Good evening.');}
 navigate(view,opts={}){if(!VIEW_META[view])view='home';const activate=()=>{this.state.view=view;qsa('.seven-view',this.root).forEach(v=>v.dataset.active=String(v.dataset.view===view));qsa('[data-view-target]',this.root).forEach(b=>b.setAttribute('aria-current',b.dataset.viewTarget===view?'page':'false'));const [title,crumb]=VIEW_META[view];if(this.elements.title)this.elements.title.textContent=title;if(this.elements.breadcrumb)this.elements.breadcrumb.textContent=crumb;document.title=`${title} · Seven AI`;this.closeSheets({restoreFocus:false});this.setHalo(view==='research'?'research':view==='coding'?'coding':['rpg','storyatlas','cast'].includes(view)?'rpg':'idle',view==='rpg'?'Valen · Episode 14':null);this.elements.stage?.scrollTo?.({top:0,behavior:'instant'});};const reduced=this.root.dataset.reducedMotion==='true';if(document.startViewTransition&&!reduced&&!opts.replace)document.startViewTransition(activate);else activate();if(!opts.replace&&history?.pushState)history.pushState({view},'',`#${view}`);this.announce(`${VIEW_META[view][0]} opened`);return view;}
 setHalo(mode,label=null,count=null){this.state.halo=mode;this.elements.halo?.setAttribute('data-halo',mode);if(this.elements.haloText){const base=label||({idle:'Seven',thinking:'Thinking',research:'Research',coding:'Agent',rpg:'RPG',success:'Completed',error:'Error'}[mode]||'Seven');this.elements.haloText.textContent=count==null?base:`${base} · ${count}`;}}
 _syncExpanded(){qsa('[data-action="menu"]',this.root).forEach(b=>b.setAttribute('aria-expanded',String(this.state.sidebar)));qsa('[data-action="workbench"]',this.root).forEach(b=>b.setAttribute('aria-expanded',String(this.state.workbench)));}
 toggleSidebar(force){this.lastFocus=document.activeElement;this.state.sidebar=force??!this.state.sidebar;this.root.dataset.sidebar=this.state.sidebar?'open':'closed';if(this.state.sidebar)this.state.workbench=false;this.root.dataset.workbench=this.state.workbench?'open':'closed';this._syncExpanded();if(this.state.sidebar&&innerWidth<=760)setTimeout(()=>qs('.seven-sidebar [data-view-target]',this.root)?.focus(),0);}
 toggleWorkbench(force){this.lastFocus=document.activeElement;this.state.workbench=force??!this.state.workbench;this.root.dataset.workbench=this.state.workbench?'open':'closed';if(innerWidth<=760&&this.state.workbench)this.state.sidebar=false;this.root.dataset.sidebar=this.state.sidebar?'open':'closed';this._syncExpanded();if(this.state.workbench&&innerWidth<=760)setTimeout(()=>qs('.seven-workbench button,.seven-workbench [tabindex="0"]',this.root)?.focus(),0);}
 closeSheets(opts={}){const wasOpen=this.state.sidebar||this.state.workbench;this.state.sidebar=false;this.state.workbench=false;this.root.dataset.sidebar='closed';this.root.dataset.workbench='closed';this._syncExpanded();if(wasOpen&&opts.restoreFocus!==false&&this.lastFocus?.focus)setTimeout(()=>this.lastFocus.focus(),0);}
 setLowPower(on,opts={}){this.state.lowPower=!!on;this.root.dataset.lowPower=String(this.state.lowPower);if(!opts.silent)this.toast(this.state.lowPower?'Low power UI enabled':'Full motion UI enabled');this._savePrefs();}
 setDensity(density='comfortable'){this.state.density=['compact','comfortable'].includes(density)?density:'comfortable';this.root.dataset.density=this.state.density;this._savePrefs();}
 announce(text){if(!this.elements.live)return;this.elements.live.textContent='';requestAnimationFrame(()=>{this.elements.live.textContent=String(text||'');});}
 toast(text,kind='info',opts={}){const stack=qs('[data-toast-stack]');if(!stack)return null;const el=document.createElement('div');el.className='seven-toast';el.dataset.kind=kind;el.innerHTML='<span aria-hidden="true"></span><div></div><button type="button" aria-label="Dismiss">×</button>';qs('span',el).textContent=kind==='success'?'✓':kind==='error'?'!':'•';qs('div',el).textContent=text;qs('button',el).addEventListener('click',()=>el.remove());stack.appendChild(el);const timeout=opts.timeout??(kind==='error'?7000:3500);if(timeout>0)setTimeout(()=>el.remove(),timeout);return el;}
 openCommandPalette(){if(this.state.command)return;this.lastFocus=document.activeElement;this.state.command=true;this.elements.commandLayer.dataset.open='true';this._renderCommands('');setTimeout(()=>this.elements.commandInput?.focus(),0);}
 closeCommandPalette(){if(!this.state.command)return;this.state.command=false;this.elements.commandLayer.dataset.open='false';if(this.elements.commandInput)this.elements.commandInput.value='';this.lastFocus?.focus?.();}
 _renderCommands(query=''){const q=String(query).trim().toLowerCase(),list=COMMANDS.filter(([,label])=>!q||label.toLowerCase().includes(q));this.elements.commandList.innerHTML='';for(const [view,label,icon] of list){const b=document.createElement('button');b.type='button';b.className='seven-command-item';b.setAttribute('role','option');b.dataset.active='false';b.innerHTML='<span></span><strong></strong><small>Open</small>';b.children[0].textContent=icon;b.children[1].textContent=label;b.addEventListener('click',()=>{this.navigate(view);this.closeCommandPalette();});this.elements.commandList.appendChild(b);}if(list.length)this.elements.commandList.firstElementChild.dataset.active='true';}
 addMessage(role,text){const stream=qs('[data-chat-stream]',this.root);if(!stream)return null;const wrapper=document.createElement('div');wrapper.className=`seven-message seven-message-${role==='user'?'user':'ai'}`;if(role==='user')wrapper.innerHTML='<div class="seven-message-body"></div>';else wrapper.innerHTML='<div class="seven-mark seven-mini-mark">7</div><div><div class="seven-message-name">Seven</div><div class="seven-message-body"></div><div class="seven-message-actions"><button class="seven-action">Copy</button><button class="seven-action">Retry</button><button class="seven-action">Branch</button></div></div>';qs('.seven-message-body',wrapper).textContent=text;stream.appendChild(wrapper);qsa('.seven-action',wrapper).forEach(b=>this._bindAction(b));stream.scrollTop=stream.scrollHeight;return wrapper;}
 async send(){const box=this.elements.composer;if(!box)return;const text=box.value.trim();if(!text)return;box.value='';box.style.height='36px';if(this.state.view!=='chat')this.navigate('chat');this.addMessage('user',text);this.setHalo('thinking');this.announce('Seven is thinking');if(this.runtime?.chat){const message=this.addMessage('ai',''),body=qs('.seven-message-body',message);let output='';try{const messages=[{role:'user',content:text}];const response=await this.runtime.chat({text,messages,onChunk:chunk=>{output+=chunk;body.textContent=output;}});if(!output)body.textContent=response?.run?.output||'Completed.';const ok=response?.run?.status==='completed';this.setHalo(ok?'success':'error');this.announce(ok?'Seven finished responding':'Seven request failed');}catch(e){body.textContent=`Request failed: ${String(e?.message||e)}`;this.setHalo('error');this.toast('Request failed','error');}}else{setTimeout(()=>{this.addMessage('ai','Ultimate runtime is ready for provider connection. This preview is currently using the UI shell without a live model.');this.setHalo('idle');},220);}}
 renderToolActivity(items=[]){const box=qs('[data-activity-stack]',this.root);if(!box)return;box.innerHTML='';for(const item of items){const el=document.createElement('div');el.className='seven-activity';el.dataset.state=item.state||'running';el.innerHTML='<span class="seven-visually-hidden"></span><div><div class="seven-activity-title"></div><div class="seven-progress-track" hidden><i></i></div></div><span class="seven-activity-meta"></span>';qs('.seven-visually-hidden',el).textContent=item.state||'running';qs('.seven-activity-title',el).textContent=item.title||item.id;qs('.seven-activity-meta',el).textContent=item.summary||String(item.state||'running').replaceAll('_',' ');if(item.progress!=null){const track=qs('.seven-progress-track',el);track.hidden=false;track.firstElementChild.style.transform=`scaleX(${Math.max(0,Math.min(1,Number(item.progress)||0))})`;}box.appendChild(el);}}
 renderStoryAtlas(atlas){const box=qs('[data-story-atlas]',this.root);if(!box||!atlas)return;box.innerHTML='';for(const ep of atlas.episodes||[]){const row=document.createElement('div');row.className='seven-timeline-item';row.innerHTML='<div class="seven-timeline-rail"><i class="seven-timeline-dot"></i></div><div class="seven-timeline-body"><strong></strong><span></span></div>';qs('strong',row).textContent=`Episode ${ep.number||''} · ${ep.title||ep.id}`;qs('span',row).textContent=ep.canonical?`${ep.eventCount||0} canonical events`:'Planned possibility';box.appendChild(row);}}
 renderCast(cast=[]){const box=qs('[data-cast-atlas]',this.root);if(!box)return;box.innerHTML='';for(const c of cast){const row=document.createElement('div');row.className='seven-character-row';row.innerHTML='<div class="seven-character-portrait"></div><div><strong></strong><span></span></div>';qs('.seven-character-portrait',row).textContent=(c.name||'?').slice(0,1).toUpperCase();qs('strong',row).textContent=c.name||c.id;qs('span',row).textContent=`${c.tier||'character'} · ${c.memoryCount||0} memories`;box.appendChild(row);}}
 hydrateRuntime(){if(!this.runtime)return;try{const ids=this.runtime.active;if(ids?.gameId&&this.runtime.rpgUI){this.renderStoryAtlas(this.runtime.rpgUI.storyAtlas.build(ids.gameId,ids.campaignId,ids.timelineId,{mode:'player'}));this.renderCast(this.runtime.rpgUI.castAtlas.list(ids.gameId,ids.campaignId,ids.timelineId,{mode:'player'}));}const activity=this.runtime.activity?.summary?.();if(activity)this.renderToolActivity(activity.items);}catch(e){console.warn('Seven UI hydrate skipped',e);}}
}
function mount(selector='#seven-app',opts={}){const el=typeof selector==='string'?document.querySelector(selector):selector;if(!el)throw new Error('SEVEN_APP_NOT_FOUND');const shell=new SevenShell(el,opts);window.addEventListener('popstate',e=>shell.navigate(e.state?.view||location.hash.slice(1)||'home',{replace:true}));shell.hydrateRuntime();return shell;}
return{STORAGE_KEY,VIEW_META,COMMANDS,SevenShell,mount};
});