"use strict";
const crypto=require("crypto"),base=require("./accessibility-contract.cjs"),VERSION="1.0.0",H40=/^[0-9a-f]{40}$/i,H64=/^[0-9a-f]{64}$/i;
function arr(v){return Array.isArray(v)?v:[]}function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};for(const k of Object.keys(v).sort())if(v[k]!==undefined)o[k]=stable(v[k]);return o}return v}function hash(v){return crypto.createHash("sha256").update(typeof v==="string"?v:JSON.stringify(stable(v))).digest("hex")}function seal(b){return Object.freeze({...b,seal:hash(b)})}function verify(x,s){if(!x||x.schema!==s||!H64.test(String(x.seal||"")))return false;const{seal:q,...b}=x;return q===hash(b)}function req(v,n){const s=String(v??"").trim();if(!s)throw Error(`${n} required`);return s}
function audit({baseAudit,betaRuntime="",uiRuntime="",hubRuntime="",generatedJs="",generatedCss="",betaCss="",hubCss="",finalCss="",rtlCss=""}={}){if(!base.verifyAudit(baseAudit)||baseAudit.status==="FAIL")throw Error("non-failing verified base accessibility audit required");const fail=[],warn=[],info=[],need=(v,id)=>(v?info:fail).push(id),note=(v,id)=>(v?info:warn).push(id),css=generatedCss+betaCss+hubCss+finalCss+rtlCss;
 need(uiRuntime.includes("setAttribute('role','log')")&&uiRuntime.includes("setAttribute('aria-live','polite')")&&uiRuntime.includes("aria-relevant"),"conversation:log-live");need(uiRuntime.includes("aria-pressed")&&uiRuntime.includes("aria-busy"),"state:pressed-busy");need(uiRuntime.includes("textarea.dir='auto'"),"bidi:composer-auto");
 need(betaRuntime.includes("role','navigation'")&&betaRuntime.includes("role','banner'")&&betaRuntime.includes("role','group'"),"landmarks:global");need(betaRuntime.includes("aria-live','polite'"),"status:live");
 need(hubRuntime.includes("aria-labelledby")&&hubRuntime.includes("seven-ws-launcher-title"),"dialog:named-by-heading");need(hubRuntime.includes("launcherIsolation")&&hubRuntime.includes(".inert=true"),"dialog:background-isolation");need(hubRuntime.includes("e.key==='Tab'")&&hubRuntime.includes("e.shiftKey"),"dialog:bidirectional-trap");need(hubRuntime.includes("e.key==='Escape'")&&hubRuntime.includes("launcherOpener.focus()"),"dialog:escape-return");
 need(generatedJs.includes("setAttribute('role','region')")&&generatedJs.includes("setAttribute('aria-label',doc.title)"),"generated:region-name");need(generatedJs.includes("wrap=el('label'")&&generatedJs.includes("wrap.append(lab,x)"),"generated:label-association");need(generatedJs.includes("setAttribute('aria-label',n.label)"),"generated:progress-name");need(generatedJs.includes("x.type='button'"),"generated:safe-button");
 need(css.includes(":focus-visible"),"focus:visible");need(/min-(?:width|height):44px/.test(css)&&/min-(?:width|height):48px/.test(css),"target:44-48");need(css.includes("prefers-reduced-motion:reduce"),"motion:reduced");need(rtlCss.includes("unicode-bidi:plaintext")&&generatedCss.includes("unicode-bidi:plaintext"),"bidi:dynamic-plaintext");need(generatedCss.includes("direction:ltr;unicode-bidi:isolate"),"bidi:code-isolation");
 note(!/aria-label','Seven navigation'/.test(betaRuntime)&&!/Message composer/.test(betaRuntime)&&!/Choose a workspace/.test(hubRuntime),"localization:accessible-names-externalized");
 const body={schema:"seven.accessibility-passb-audit.v1",version:VERSION,baseAuditSeal:baseAudit.seal,status:fail.length?"FAIL":warn.length?"WARN":"PASS",fail:[...new Set(fail)].sort(),warn:[...new Set(warn)].sort(),info:[...new Set(info)].sort(),truthBoundary:"HOST_STRUCTURAL_ACCESSIBILITY_PASSB_NOT_WCAG_NOT_SCREEN_READER_DEVICE_CERTIFICATION"};return seal(body)}
function verifyAudit(x){return verify(x,"seven.accessibility-passb-audit.v1")}
function manifest({branch,commitSha,audit:a,sources}={}){branch=req(branch,"branch");commitSha=req(commitSha,"commitSha");if(!H40.test(commitSha))throw Error("commitSha invalid");if(!verifyAudit(a)||a.status==="FAIL")throw Error("non-failing PassB audit required");const seen=new Set(),rows=[];for(const x of arr(sources)){const p=req(x.path,"source.path");if(p.startsWith("/")||p.includes("..")||seen.has(p))throw Error("unsafe or duplicate source path");seen.add(p);const c=String(x.content??"");rows.push({path:p,sha256:hash(c),bytes:Buffer.byteLength(c)})}const required=["release/accessibility-contract.cjs","release/beta-ui-runtime.js","release/ui-runtime.js","release/beta-ui.css","release/seven-final.css","release/workspaces/hub.js","release/workspaces/hub.css","release/workspaces/generated-ui.js","release/workspaces/generated-ui.css","release/workspaces/rtl.css"];for(const p of required)if(!seen.has(p))throw Error(`missing source:${p}`);const body={schema:"seven.accessibility-passb-manifest.v1",version:VERSION,branch,commitSha:commitSha.toLowerCase(),auditSeal:a.seal,sources:rows.sort((x,y)=>x.path.localeCompare(y.path)),claim:"HOST_ACCESSIBILITY_PASSB_FOUNDATION"};return seal(body)}
function verifyManifest(x){return verify(x,"seven.accessibility-passb-manifest.v1")&&x.claim==="HOST_ACCESSIBILITY_PASSB_FOUNDATION"}
function hostReceipt({manifest:m,startupBefore,startupAfter,lazyBytes,browser}={}){if(!verifyManifest(m))throw Error("verified PassB manifest required");startupBefore=Number(startupBefore);startupAfter=Number(startupAfter);lazyBytes=Number(lazyBytes);if(![startupBefore,startupAfter,lazyBytes].every(Number.isFinite))throw Error("finite byte evidence required");if(startupAfter>startupBefore)throw Error("accessibility PassB may not increase startup bytes");if(startupAfter>100000)throw Error("startup cap exceeded");if(lazyBytes>65536)throw Error("lazy workspace cap exceeded");const b=browser||{},required=["conversationSemantics","controlNames","stateSemantics","dialogIsolation","dialogTrap","focusReturn","specialistNames","generatedLabels","keyboardActivation","focusVisible","touchTargets","text200","rtlBidi","reducedMotion","noOverflow","noPageErrors"];for(const k of required)if(b[k]!==true)throw Error(`browser ${k} required`);const body={schema:"seven.accessibility-passb-host-receipt.v1",version:VERSION,manifestSeal:m.seal,startupBefore,startupAfter,lazyBytes,browser:Object.fromEntries(required.map(k=>[k,true])),evidenceTier:"HOST",claim:"ACCESSIBILITY_PASSB_HOST_ONLY_NOT_WCAG_CERTIFIED"};return seal(body)}
function verifyHostReceipt(x){return verify(x,"seven.accessibility-passb-host-receipt.v1")&&x.evidenceTier==="HOST"&&x.claim==="ACCESSIBILITY_PASSB_HOST_ONLY_NOT_WCAG_CERTIFIED"}
module.exports=Object.freeze({VERSION,hash,audit,verifyAudit,manifest,verifyManifest,hostReceipt,verifyHostReceipt});
