"use strict";
const assert=require("assert/strict"),t=require("./android-visual-certification.cjs");let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++},throws=(f,re,m)=>{assert.throws(f,re,m);n++},H=x=>t.hash(x),COMMIT="a".repeat(40);
const build=t.createBuildIdentity({branch:"ultimate-polish-v1",commitSha:COMMIT,applicationId:"ai.seven.app",versionName:"1.0.0",versionCode:100,artifactKind:"APK",artifactSha256:H("apk"),candidateSeal:H("candidate"),exportReceiptSeal:H("export")});ok(t.verifyBuildIdentity(build));eq(build.buildType,"RELEASE");throws(()=>t.createBuildIdentity({...build,seal:undefined,commitSha:"x"}),/invalid build hash/);throws(()=>t.createBuildIdentity({branch:"b",commitSha:COMMIT,applicationId:"a",versionName:"1",versionCode:1,artifactKind:"ZIP",artifactSha256:H("a"),candidateSeal:H("b"),exportReceiptSeal:H("c")}),/artifactKind/);
function dev(id,{api=35,width=360,env="EMULATOR",identity=null}={}){return t.createDeviceProof({environmentType:env,deviceIdentityHash:identity||H("device:"+id),manufacturer:"SevenLab",model:id,androidVersion:"15",apiLevel:api,widthDp:width,heightDp:800,density:2.75,proofHash:H("proof:"+id),sourceRef:"device-farm:"+id,capturedBy:"android-release-ci"})}const d1=dev("compact"),d2=dev("wide",{width:412,env:"DEVICE_FARM"});ok(t.verifyDeviceProof(d1));ok(t.verifyDeviceProof(d2));eq(d1.tier,"RELEASE_BUILD_DEVICE");throws(()=>dev("old",{api:25}),/device metrics/);throws(()=>t.createDeviceProof({environmentType:"HOST",deviceIdentityHash:H("x"),manufacturer:"x",model:"x",androidVersion:"1",apiLevel:35,widthDp:360,heightDp:800,density:3,proofHash:H("p"),sourceRef:"x",capturedBy:"x"}),/environmentType/);
function cap(s,d=d1,extra={}){const base={build,device:d,scenario:s,captureMethod:"adb-screencap",screenshotSha256:H(`shot:${s}:${d.model}`),width:1080,height:2400,locale:"en-US",direction:"ltr",theme:"night",reducedMotion:false,sourceRef:`android:${s}:${d.model}`};if(s==="chat-day")base.theme="day";if(s==="arabic-rtl"){base.locale="ar-IQ";base.direction="rtl"}if(s==="reduced-motion")base.reducedMotion=true;return t.createCaptureReceipt({...base,...extra})}
let c=cap("coding");ok(t.verifyCaptureReceipt(c,{build,device:d1}));eq(t.verifyCaptureReceipt({...c,artifactSha256:H("other")},{build,device:d1}),false);throws(()=>cap("arabic-rtl",d1,{locale:"en-US"}),/arabic-rtl/);throws(()=>cap("reduced-motion",d1,{reducedMotion:false}),/reduced-motion/);throws(()=>cap("chat-day",d1,{theme:"night"}),/chat-day/);const old=dev("api32",{api:32});throws(()=>cap("launcher-themed",old),/API 33/);throws(()=>cap("coding",d1,{captureMethod:"playwright-host"}),/captureMethod/);
const captures=t.SCENARIOS.map((s,i)=>cap(s,i%2?d2:d1));let cert=t.certify({build,devices:[d1,d2],captures});ok(t.verifyCertification(cert));eq(cert.verdict,"PASS");eq(cert.missing.length,0);eq(cert.physicalDeviceIncluded,false);eq(cert.claim,"ANDROID_RELEASE_VISUAL_MATRIX_NO_PHYSICAL_DEVICE_CLAIM");
cert=t.certify({build,devices:[d1,d2],captures:captures.slice(1)});eq(cert.verdict,"INCONCLUSIVE");ok(cert.missing.includes(t.SCENARIOS[0]));cert=t.certify({build,devices:[d1,d2],captures:[...captures,captures[0]]});eq(cert.verdict,"BLOCK");ok(cert.failures.some(x=>x.startsWith("duplicate-capture:")));throws(()=>t.certify({build,devices:[d1],captures}),/two release device/);const sameIdentity=dev("same-identity",{width:412,identity:d1.deviceIdentityHash});throws(()=>t.certify({build,devices:[d1,sameIdentity],captures:[]}),/distinct/);
const noCompact1=dev("w1",{width:412}),noCompact2=dev("w2",{width:480});cert=t.certify({build,devices:[noCompact1,noCompact2],captures:[]});eq(cert.verdict,"BLOCK");ok(cert.failures.includes("compact-device-profile-required"));const p=dev("physical",{env:"PHYSICAL_DEVICE"}),capsP=t.SCENARIOS.map((s,i)=>cap(s,i%2?p:d1));cert=t.certify({build,devices:[d1,p],captures:capsP});eq(cert.verdict,"PASS");eq(cert.physicalDeviceIncluded,true);eq(cert.claim,"ANDROID_RELEASE_VISUAL_MATRIX_WITH_PHYSICAL_DEVICE");const forged={...cert,claim:"PHYSICAL_DEVICE_CERTIFIED_FOREVER"};eq(t.verifyCertification(forged),false);
console.log(`Android Visual Certification Foundation: PASS (${n} assertions; ${t.SCENARIOS.length} required release scenarios, anti-host-laundering)`);
