"use strict";
const assert=require("assert/strict"),fs=require("fs"),path=require("path");
const ROOT=path.resolve(__dirname,"..");
const file=path.join(ROOT,"apk","capture-android-legacy-launcher-ui.cjs");
const source=fs.readFileSync(file,"utf8"),legacy=require(file);
let n=0;
const has=(x,m)=>{assert.ok(source.includes(x),m||`missing ${x}`);n++};
const not=(x,m)=>{assert.ok(!source.includes(x),m||`forbidden ${x}`);n++};
const xml=`<hierarchy><node text="" content-desc="Apps" resource-id="com.android.launcher3:id/all_apps_handle" bounds="[400,1700][680,1980]" clickable="true"/><node text="Seven AI" content-desc="Seven AI" resource-id="" bounds="[50,500][250,760]" clickable="true"/><node text="Search Apps" content-desc="" resource-id="com.android.launcher3:id/search_box_input" bounds="[40,80][1000,220]" focusable="true"/></hierarchy>`;
assert.equal(legacy.nodes(xml).length,3);n++;
assert.equal(legacy.sevenNode(xml)["content-desc"],"Seven AI");n++;
assert.equal(legacy.appsNode(xml)["resource-id"],"com.android.launcher3:id/all_apps_handle");n++;
assert.equal(legacy.searchNode(xml)["resource-id"],"com.android.launcher3:id/search_box_input");n++;
assert.deepEqual(legacy.bounds("[10,20][110,220]"),{x1:10,y1:20,x2:110,y2:220,cx:60,cy:120});n++;
has('uiautomator","dump","--compressed"');
has('KEYCODE_HOME');
has('KEYCODE_WAKEUP');
has('wm","dismiss-keyguard');
has('tap-explicit-all-apps');
has('tap-center-hotseat');
has('swipe-up-drawer');
has('scroll-all-apps-vertical');
has('page-all-apps-horizontal');
has('search-apps');
has('input","text","Seven"');
has('foreground().includes(launcherPackage)');
has('Seven launcher node not found after bounded genuine API24 launcher navigation');
has('legacy launcher proof requires pre-API26 device');
has('requireResourceWitness(apk,"launcher-legacy"');
has('captureMethod:"adb-screencap"');
has('proof:"genuine-uiautomator-plus-visible-input"');
has('GENUINE_RELEASE_BUILD_API24_LEGACY_LAUNCHER_UI_EVIDENCE');
has('exact APK hash/build identity mismatch');
not('content","update');
not('run-as');
not('monkey');
not('playwright');
not('seven_ai-final.html');
not('synthetic');
console.log(`Android Legacy Launcher Contract: PASS (${n} assertions; pre-API26 exact-release resource proof + bounded genuine launcher UI navigation)`);
