"use strict";
const assert=require("assert/strict"),t=require("./android-visual-certification.cjs");let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++},throws=(f,re,m)=>{assert.throws(f,re,m);n++},H=x=>t.hash(x),COMMIT="a".repeat(40);
const build=t.createBuildIdentity({branch:"ultimate-polish-v1",commitSha:COMMIT,applicationId:"ai.seven.app",versionName:"1.0.0",versionCode:100,artifactKind:"APK",artifactSha256:H("apk"),candidateSeal:H("candidate"),exportReceiptSeal:H("export")});ok(t.verifyBuildIdentity(build));eq(build.buildType,"RELEASE");throws(()=>t.createBuildIdentity({...build,seal:undefined,commitSha:"x"}),/invalid build hash/);throws(()=>t.createBuildIdentity({branch:"b",commitSha:COMMIT,applicationId:"a",versionName:"1",versionCode:1,artifactKind:"ZIP",artifactSha256:H("a"),candidateSeal:H("b"),exportReceiptSeal:H("c")}),/artifactKind/);
function dev(id,{api=35,width=360,env="EMULATOR",identity=null}={}){return t.createDeviceProof({environmentType:env,deviceIdentityHash:identity||H("device:"+id),manufacturer:"SevenLab",model:id,androidVersion:String(api),apiLevel:api,widthDp:width,heightDp:800,density:2.75,proofHash:H("proof:"+id),sourceRef:"device-farm:"+id,capturedBy:"android-release-ci"})}
const dCompact=dev("compact-api33",{api:33,width:360}),dModern=dev("modern-api36",{api:36,width:412,env:"DEVICE_FARM"}),dLegacy=dev("legacy-api24",{api:24,width:360});ok(t.verifyDeviceProof(dCompact));ok(t.verifyDeviceProof(dModern));ok(t.verifyDeviceProof(dLegacy));eq(dLegacy.apiLevel,24);throws(()=>dev("too-old",{api:23}),/device metrics/);throws(()=>t.createDeviceProof({environmentType:"HOST",deviceIdentityHash:H("x"),manufacturer:"x",model:"x",androidVersion:"1",apiLevel:35,widthDp:360,heightDp:800,density:3,proofHash:H("p"),sourceRef:"x",capturedBy:"x"}),/environmentType/);
function cap(s,d=dCompact,extra={}){const base={build,device:d,scenario:s,captureMethod:"adb-screencap",screenshotSha256:H(`shot:${s}:${d.model}`),width:1080,height:2400,locale:"en-US",direction:"ltr",theme:"night",reducedMotion:false,sourceRef:`android:${s}:${d.model}`};if(s==="chat-day")base.theme="day";if(s==="arabic-rtl"){base.locale="ar-IQ";base.direction="rtl"}if(s==="reduced-motion")base.reducedMotion=true;if(s.startsWith("launcher-")||s==="splash")base.theme="system";return t.createCaptureReceipt({...base,...extra})}
let c=cap("coding");ok(t.verifyCaptureReceipt(c,{build,device:dCompact}));eq(t.verifyCaptureReceipt({...c,artifactSha256:H("other")},{build,device:dCompact}),false);throws(()=>cap("arabic-rtl",dCompact,{locale:"en-US"}),/arabic-rtl/);throws(()=>cap("reduced-motion",dCompact,{reducedMotion:false}),/reduced-motion/);throws(()=>cap("chat-day",dCompact,{theme:"night"}),/chat-day/);const api32=dev("api32",{api:32});throws(()=>cap("launcher-themed",api32),/API 33/);throws(()=>cap("launcher-adaptive",dLegacy),/API 26/);throws(()=>cap("launcher-legacy",dCompact),/pre-API26/);ok(t.verifyCaptureReceipt(cap("launcher-legacy",dLegacy),{build,device:dLegacy}));throws(()=>cap("coding",dCompact,{captureMethod:"playwright-host"}),/captureMethod/);
const assignment={"launcher-legacy":dLegacy,"launcher-adaptive":dCompact,"launcher-themed":dModern,"splash":dModern};const captures=t.SCENARIOS.map(s=>cap(s,assignment[s]||dCompact));let cert=t.certify({build,devices:[dLegacy,dCompact,dModern],captures});ok(t.verifyCertification(cert));eq(cert.verdict,"PASS");eq(cert.missing.length,0);eq(cert.physicalDeviceIncluded,false);eq(cert.claim,"ANDROID_RELEASE_VISUAL_MATRIX_NO_PHYSICAL_DEVICE_CLAIM");
cert=t.certify({build,devices:[dLegacy,dCompact,dModern],captures:captures.slice(1)});eq(cert.verdict,"INCONCLUSIVE");ok(cert.missing.includes(t.SCENARIOS[0]));cert=t.certify({build,devices:[dLegacy,dCompact,dModern],captures:[...captures,captures[0]]});eq(cert.verdict,"BLOCK");ok(cert.failures.some(x=>x.startsWith("duplicate-capture:")));throws(()=>t.certify({build,devices:[dCompact],captures}),/two release device/);const sameIdentity=dev("same-identity",{width:412,identity:dCompact.deviceIdentityHash});throws(()=>t.certify({build,devices:[dCompact,sameIdentity],captures:[]}),/distinct/);
const noCompact1=dev("w1",{width:412}),noCompact2=dev("w2",{width:480});cert=t.certify({build,devices:[noCompact1,noCompact2],captures:[]});eq(cert.verdict,"BLOCK");ok(cert.failures.includes("compact-device-profile-required"));const p=dev("physical",{api:36,env:"PHYSICAL_DEVICE"}),capsP=t.SCENARIOS.map(s=>cap(s,s==="launcher-legacy"?dLegacy:(s==="launcher-themed"?p:dCompact)));cert=t.certify({build,devices:[dLegacy,dCompact,p],captures:capsP});eq(cert.verdict,"PASS");eq(cert.physicalDeviceIncluded,true);eq(cert.claim,"ANDROID_RELEASE_VISUAL_MATRIX_WITH_PHYSICAL_DEVICE");const forged={...cert,claim:"PHYSICAL_DEVICE_CERTIFIED_FOREVER"};eq(t.verifyCertification(forged),false);
console.log(`Android Visual Certification Foundation: PASS (${n} assertions; ${t.SCENARIOS.length} required release scenarios, API24 legacy plus API26+/API33+ semantic guards, anti-host-laundering)`);
