"use strict";
const assert=require("assert/strict"),fs=require("fs"),path=require("path");
const ROOT=path.resolve(__dirname,"..");let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},match=(v,re,m)=>{assert.match(v,re,m);n++};
const pkg=JSON.parse(fs.readFileSync(path.join(ROOT,"package.json"),"utf8")),wf=fs.readFileSync(path.join(ROOT,".github","workflows","android-apk.yml"),"utf8"),patch=fs.readFileSync(path.join(ROOT,"apk","patch-android.cjs"),"utf8"),mat=fs.readFileSync(path.join(ROOT,"apk","materialize-android-visual-test.cjs"),"utf8"),cap=fs.readFileSync(path.join(ROOT,"apk","capture-android-release-profile.cjs"),"utf8"),id=fs.readFileSync(path.join(__dirname,"android-ci-release-artifact.cjs"),"utf8"),merge=fs.readFileSync(path.join(__dirname,"merge-android-visual-evidence.cjs"),"utf8");
match(pkg.scripts["android:generate"],/materialize-android-visual-test\.cjs/);match(wf,/:app:assembleRelease/);match(wf,/:app:assembleReleaseAndroidTest/);match(wf,/apksigner/);match(wf,/api36-modern/);match(wf,/api28-compact/);match(wf,/merge-android-visual-evidence\.cjs/);
ok(!/(?:^|\s)assembleAndroidTest(?:\s|\\)/m.test(wf),"root-level AndroidTest assembly must stay disabled to avoid unrelated plugin test graphs");
ok(!wf.includes(":app:assembleDebugAndroidTest"),"release-device visual evidence must not be assembled from the debug AndroidTest variant");
match(wf,/android\.testInstrumentationRunnerArguments\.class=ai\.seven\.app\.SevenSmokeTest/,"release WebView smoke must select only SevenSmokeTest so visual capture cannot contaminate the smoke gate");
match(wf,/:app:connectedReleaseAndroidTest/,"CI smoke must exercise the release-bound AndroidTest variant");
match(wf,/script: cd android && \.\/gradlew --no-daemon :app:connectedReleaseAndroidTest/,"emulator-runner smoke must keep cd and Gradle in one shell command because multiline script lines do not share cwd");
match(wf,/awk -F': ' '\/certificate SHA-256 digest\//,"CI release identity must parse modern apksigner certificate output");
ok(!wf.includes("Signer #1 certificate SHA-256 digest"),"signer parsing must not depend on the obsolete Signer #1 prefix");
match(patch,/def sevenCiKeystore = project\.findProperty\("sevenCiKeystore"\)/,"generated Gradle must accept an explicit CI keystore without embedding credentials");
match(patch,/if \(sevenCiKeystore\) \{\\n        testBuildType = \"release\"/,"release AndroidTest selection must be conditional on the explicit CI signing path");
match(patch,/signingConfig signingConfigs\.sevenCi/g,"generated debug and release build types must share the explicit CI signing identity");
ok(!/debuggable|isDebuggable\s*=\s*true/.test(patch),"visual evidence must never make the release target debuggable to export test evidence");
match(wf,/-PsevenCiKeystore="\$HOME\/\.android\/debug\.keystore"/,"CI build must opt into explicit generated-project signing");
ok(!wf.includes("android.injected.signing"),"CI must not mix AGP injected signing with the explicit test/release signing contract");
match(wf,/Verify CI signer parity for release instrumentation/);match(wf,/test "\$RELEASE_SIGNER" = "\$DEBUG_SIGNER"/);match(wf,/test "\$RELEASE_SIGNER" = "\$TEST_SIGNER"/);
match(wf,/android\/app\/build\/outputs\/apk\/androidTest\/release\/app-release-androidTest\.apk/,"signer parity must inspect the release AndroidTest APK");
match(cap,/DEFAULT_RELEASE_APK="android\/app\/build\/outputs\/apk\/release\/app-release\.apk"/,"capture runner must have a deterministic release APK fallback because emulator-runner may execute script lines independently");
match(cap,/DEFAULT_TEST_APK="android\/app\/build\/outputs\/apk\/androidTest\/release\/app-release-androidTest\.apk"/,"capture runner must bind instrumentation to the release AndroidTest variant");
match(cap,/DEFAULT_BUILD_IDENTITY="evidence\/android\/build-identity\.json"/,"capture runner must have a deterministic build-identity fallback");
match(cap,/function inferProfileId/);match(cap,/api===28\)return"api28-compact"/);match(cap,/api===36\)return"api36-modern"/);
match(cap,/SEVEN_ANDROID_PROFILE_OUT\|\|`evidence\/android\/profiles\/\$\{profileId\}`/,"profile output must remain deterministic even when shell exports are not persistent");
match(mat,/UiAutomation\(\)\.takeScreenshot|UiAutomation\(\).*takeScreenshot|UiAutomation.*takeScreenshot/);match(mat,/theme\(webView,"day"\)/);match(mat,/theme\(webView,"night"\)/);match(mat,/SevenWorkspaces\.open/);match(mat,/ar-IQ/);
match(mat,/testContext\.getFilesDir\(\)/,"visual evidence staging must use instrumentation-private storage so API 28 does not depend on external storage availability");
ok(!mat.includes("getExternalFilesDir"),"visual evidence staging must not regress to nullable external files storage");
match(mat,/class SevenEvidenceProvider extends ContentProvider/,"test-only provider must own evidence export without requiring debuggability");
match(mat,/Binder\.getCallingUid\(\)!=SHELL_UID/,"evidence provider must reject callers other than Android shell");
match(mat,/ParcelFileDescriptor\.MODE_READ_ONLY/,"evidence provider must be read only");
match(mat,/getCanonicalFile\(\)/,"evidence provider must canonicalize the private evidence path");
match(mat,/android:authorities="ai\.seven\.app\.test\.sevenevidence"/,"AndroidTest manifest must expose only the dedicated evidence authority");
match(mat,/android:grantUriPermissions="false"/,"evidence provider must not grant arbitrary URI permissions");
match(cap,/EVIDENCE_AUTHORITY="ai\.seven\.app\.test\.sevenevidence"/,"collector and AndroidTest provider must share an exact authority");
match(cap,/"exec-out","content","read","--uri",uri/,"host collector must export private visual evidence through the shell-only test provider without changing screenshot bytes");
ok(!cap.includes("run-as"),"collector must not require a debuggable release-bound AndroidTest package");
ok(!cap.includes("/sdcard/Android/data/ai.seven.app.test/files/seven-visual"),"collector must not depend on external test-app storage");
match(mat,/settings put global window_animation_scale 0/);match(mat,/settings put global transition_animation_scale 0/);match(mat,/settings put global animator_duration_scale 0/);match(mat,/prefers-reduced-motion: reduce/);match(mat,/SevenPerformance\.reconsiderTier/);match(mat,/shot\("reduced-motion"\)/);
ok(!/SevenPerformance\.state\.reducedMotion\s*=\s*true/.test(mat),"Reduced Motion evidence must come from Android/WebView preference state, not direct runtime mutation");
ok(!/dataset\.sevenReducedMotion\s*=\s*['\"]1['\"]/.test(mat),"Reduced Motion DOM evidence must not be manually forged");
for(const s of ["chat-day","chat-night","coding","research","rpg","arabic-rtl","reduced-motion"])match(cap,new RegExp(`scenario:"${s}"`));
ok(!/deviceIdentityHash:android\.hash\(\{profileId/.test(cap),"device identity must derive from observed device facts, not a caller-supplied profile label");
ok(!/scenario:"launcher-/.test(cap),"in-app collector must not fabricate launcher scenarios");ok(!/scenario:"splash"/.test(cap),"in-app collector must not fabricate splash evidence");
match(cap,/GENUINE_RELEASE_APP_DEVICE_CAPTURES_FOR_IN_APP_STATES_ONLY_NO_LAUNCHER_OR_SPLASH_CLAIM/);match(id,/RELEASE_VARIANT_CI_SIGNED_NOT_STORE_PRODUCTION_SIGNING/);match(merge,/PARTIAL_RELEASE_DEVICE_EVIDENCE_ONLY/);
ok(!patch.includes("seven_ai-final.html"),"Android shell patch must not touch protected source");ok(!mat.includes("seven_ai-final.html"),"visual materializer must not touch protected source");ok(!cap.includes("seven_ai-final.html"),"capture collector must not touch protected source");
console.log(`Android Release Capture Contract: PASS (${n} assertions; release-variant instrumentation, shell-only private evidence export, signer parity and truthful visual evidence)`);
