"use strict";
const assert=require("assert/strict"),fs=require("fs"),path=require("path");
const {build}=require("./build-release.cjs");
const built=build();
const html=fs.readFileSync(built.output,"utf8");
const runtime=fs.readFileSync(path.join(__dirname,"attachment-runtime.js"),"utf8");
const loader=fs.readFileSync(path.join(__dirname,"attachment-loader.js"),"utf8");
const lazyPath=path.join(path.dirname(built.output),'attachment-runtime.js');
const night=fs.readFileSync(path.join(__dirname,"brand","seven-night-black.svg"),"utf8");
const day=fs.readFileSync(path.join(__dirname,"brand","seven-day-white.svg"),"utf8");
assert.ok(html.includes('id="seven-attachment-loader"'),"attachment lazy loader is not packaged");
assert.ok(!html.includes('id="seven-attachment-runtime"'),"full attachment runtime must stay out of hot startup HTML");
assert.equal(built.attachmentLoadMode,'lazy-local');
assert.ok(built.attachmentRuntimeBytes>0&&fs.existsSync(lazyPath),"lazy attachment runtime asset missing");
assert.match(loader,/SevenAttachmentLoader/,"attachment loader API missing");
assert.match(loader,/\.\/attachment-runtime\.js/,"attachment loader does not point at local runtime");
assert.ok(html.includes('accept="*/*" multiple'),"release input does not accept universal files");
assert.ok(html.includes('title="Attach photos or files"'),"release attach control was not relabeled");
assert.ok(html.includes('<label>Attachments and knowledge files</label>'),"settings attachment label was not upgraded");
assert.ok(html.includes('window.SevenAttachments.extractForKnowledge'),"knowledge loader is not routed through attachment classifier");
assert.ok(html.includes('window.SevenAttachmentLoader.load'),"knowledge loader does not lazy-load attachment capability");
assert.ok(!html.includes('accept=".txt,.pdf"'),"legacy txt/pdf-only accept filter survived release packaging");
assert.match(runtime,/version:'1\.2\.0-beta\.1'/,"attachment runtime version was not advanced with the UX contract");
assert.match(runtime,/data-seven-attach=["']?photos|dataset\.sevenAttach='photos'/,"Photos attachment route missing");
assert.match(runtime,/data-seven-attach=["']?files|dataset\.sevenAttach='files'/,"Files attachment route missing");
assert.match(runtime,/kind==='photos'\?'image\/\*':'\*\/\*'/,"Photos route must prefer the Android image picker while Files remains universal");
assert.match(runtime,/attachment_metadata_/,"binary metadata safety path missing");
assert.match(runtime,/MAX_TEXT_BYTES=8\*1024\*1024/,"mobile text extraction guard missing");
assert.match(runtime,/addEventListener\('paste'/,"clipboard file ingestion path missing");
assert.match(runtime,/addEventListener\('drop'/,"drag-and-drop file ingestion path missing");
assert.match(runtime,/ingestFiles:applyFiles/,"programmatic attachment ingestion API missing");
assert.match(runtime,/seven-attachment-style/,"attachment UI style contract missing");
assert.match(runtime,/seven-attachment-chip-icon/,"typed attachment chip affordance missing");
assert.match(runtime,/Binary format kept as an attachment/,"unsupported binary files must not be decoded as fake text");
for(const svg of [night,day]){
  assert.match(svg,/<linearGradient/,"brand gradient missing");
  assert.match(svg,/#32BECF/i,"cyan identity stop missing");
  assert.match(svg,/#4166F5/i,"blue identity stop missing");
  assert.match(svg,/#8265DC/i,"violet identity stop missing");
  assert.match(svg,/viewBox="0 0 108 108"/,"adaptive logo canvas changed");
}
assert.match(night,/#0A1022/i,"night logo surface missing");
assert.match(day,/#F4F6FB/i,"day logo surface missing");
assert.notEqual(night,day,"day and night logo assets must remain distinct");
console.log("Universal attachments + refreshed Seven logo: PASS (lazy-local runtime)");