"use strict";
const {chromium}=require("playwright"),http=require("http"),fs=require("fs"),path=require("path"),assert=require("assert/strict"),{build}=require("./build-release.cjs");
(async()=>{
  const built=build(),html=fs.readFileSync(built.output,"utf8"),dist=path.dirname(built.output);
  assert.equal(built.workspaceLoadMode,"lazy-local");
  const server=http.createServer((req,res)=>{const p=new URL(req.url,"http://127.0.0.1").pathname;if(p!=="/"&&p!=="/index.html"){const f=path.resolve(dist,"."+p);if(!f.startsWith(path.resolve(dist)+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end("not found")}res.setHeader("Content-Type",f.endsWith(".js")?"text/javascript; charset=utf-8":f.endsWith(".css")?"text/css; charset=utf-8":"application/octet-stream");return fs.createReadStream(f).pipe(res)}res.setHeader("Content-Type","text/html; charset=utf-8");res.end(html)});
  await new Promise(r=>server.listen(0,"127.0.0.1",r));
  const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true});let n=0;
  const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++};
  try{
    const c=await browser.newContext({viewport:{width:390,height:844}});await c.addInitScript(()=>localStorage.setItem("user_name_asked","1"));await c.route("**/*",x=>x.request().url().startsWith(origin)?x.continue():x.abort());
    const p=await c.newPage(),traffic=[],errors=[];p.on("request",x=>traffic.push(x.url()));p.on("pageerror",e=>errors.push(e.message));
    await p.goto(origin,{waitUntil:"domcontentloaded"});await p.waitForFunction(()=>window.SevenBetaUI?.state.ready);
    eq(await p.evaluate(()=>!!window.SevenGeneratedUI),false);ok(!traffic.some(x=>x.includes("generated-ui")),"generated UI must remain cold at startup");
    await p.click(".seven-beta-status");await p.waitForFunction(()=>window.SevenWorkspaces);await p.evaluate(()=>SevenWorkspaces.loadGeneratedUi());await p.waitForFunction(()=>window.SevenGeneratedUI);
    ok(traffic.some(x=>x.endsWith("/workspaces/generated-ui.js")));ok(traffic.some(x=>x.endsWith("/workspaces/generated-ui.css")));
    const all=await p.evaluate(()=>{
      window.__gEvents=[];window.__gActions=[];const host=document.createElement("div");host.id="wave17-generated-host";document.body.appendChild(host);host.addEventListener("seven:generated-ui-action",e=>__gEvents.push(e.detail));
      const doc={version:1,id:"wave17",title:"Typed result",direction:"inherit",nodes:[{type:"section",id:"section",children:[{type:"heading",id:"heading",text:"Result",level:1},{type:"stack",id:"stack",children:[{type:"text",id:"text",text:"Safe <script>window.__bad=1</script>",tone:"muted"},{type:"row",id:"row",children:[{type:"badge",id:"badge",text:"Verified",tone:"success"},{type:"divider",id:"divider"}]},{type:"card",id:"card",children:[{type:"input",id:"input",label:"Question",key:"question",placeholder:"Ask",value:"before",required:true},{type:"input",id:"notes",label:"Notes",key:"notes",value:"line one",multiline:true},{type:"progress",id:"progress",label:"Coverage",value:.5},{type:"code",id:"code",text:"const x = '<b>safe</b>';",language:"js"},{type:"evidence",id:"evidence",text:"Evidence is displayed, not promoted to authority.",status:"supported",source:"source-1"},{type:"button",id:"go",label:"Continue",action:"continue",tone:"primary"},{type:"button",id:"disabled",label:"Disabled",action:"disabled",disabled:true}]}]}]}]};
      const h=SevenGeneratedUI.mount(doc,host,{actions:{continue:d=>__gActions.push(d),disabled:()=>__gActions.push("disabled")}});const input=host.querySelector('[data-generated-key="question"]');input.value="after";host.querySelector('[data-generated-action="continue"]').click();host.querySelector('[data-generated-action="disabled"]').click();return{types:SevenGeneratedUI.TYPES.slice(),limits:SevenGeneratedUI.LIMITS,role:h.root.getAttribute("role"),label:h.root.getAttribute("aria-label"),dir:h.root.getAttribute("dir"),values:h.values(),events:__gEvents,actions:__gActions,scriptCount:host.querySelectorAll("script").length,boldCount:host.querySelectorAll("b").length,code:host.querySelector("code").textContent,codeDir:host.querySelector("code").dir,evidence:host.querySelector(".seven-generated-evidence").className,required:input.required,textarea:host.querySelector("textarea").value,progress:{max:host.querySelector("progress").max,value:host.querySelector("progress").value,aria:host.querySelector("progress").getAttribute("aria-label")},destroy:()=>h.destroy()};
    });
    ok(all.types.includes("evidence")&&all.types.includes("button")&&all.types.includes("code"));eq(all.limits.nodes,120);eq(all.limits.depth,8);eq(all.role,"region");eq(all.label,"Typed result");eq(all.dir,null);eq(all.values.question,"after");eq(all.values.notes,"line one");eq(all.events.length,1);eq(all.actions.length,1);eq(all.events[0].documentId,"wave17");eq(all.events[0].nodeId,"go");eq(all.events[0].action,"continue");eq(all.events[0].values.question,"after");eq(all.actions[0].values.question,"after");eq(all.scriptCount,0);eq(all.boldCount,0);ok(all.code.includes("<b>safe</b>"));eq(all.codeDir,"ltr");ok(all.evidence.includes("status-supported"));eq(all.required,true);eq(all.textarea,"line one");eq(all.progress.max,1);eq(all.progress.value,.5);eq(all.progress.aria,"Coverage");eq(await p.evaluate(()=>window.__bad===1),false);
    const reject=await p.evaluate(()=>{const cases={version:{version:2,id:"x",title:"x",nodes:[]},direction:{version:1,id:"x",title:"x",direction:"sideways",nodes:[]},duplicate:{version:1,id:"x",title:"x",nodes:[{type:"text",id:"a",text:"1"},{type:"text",id:"a",text:"2"}]},inputKey:{version:1,id:"x",title:"x",nodes:[{type:"input",id:"a",label:"A",key:"same"},{type:"input",id:"b",label:"B",key:"same"}]},progress:{version:1,id:"x",title:"x",nodes:[{type:"progress",id:"p",label:"P",value:1.1}]},status:{version:1,id:"x",title:"x",nodes:[{type:"evidence",id:"e",text:"E",status:"official"}]},tone:{version:1,id:"x",title:"x",nodes:[{type:"text",id:"t",text:"T",tone:"rainbow"}]},field:{version:1,id:"x",title:"x",nodes:[{type:"button",id:"b",label:"B",action:"go",href:"https://evil.test"}]},children:{version:1,id:"x",title:"x",nodes:[{type:"row",id:"r",children:Array.from({length:41},(_,i)=>({type:"divider",id:"d"+i}))}]},text:{version:1,id:"x",title:"x",nodes:[{type:"text",id:"t",text:"x".repeat(4001)}]}};const out={};for(const [k,v] of Object.entries(cases)){try{SevenGeneratedUI.validate(v);out[k]=false}catch{out[k]=true}}let nodes=[];for(let i=0;i<121;i++)nodes.push({type:"divider",id:"n"+i});try{SevenGeneratedUI.validate({version:1,id:"many",title:"many",nodes});out.nodes=false}catch{out.nodes=true}let deep={type:"divider",id:"leaf"};for(let i=0;i<9;i++)deep={type:"stack",id:"deep"+i,children:[deep]};try{SevenGeneratedUI.validate({version:1,id:"deep",title:"deep",nodes:[deep]});out.depth=false}catch{out.depth=true}return out});
    for(const [k,v] of Object.entries(reject))ok(v,"reject "+k);
    const lifecycle=await p.evaluate(()=>{const host=document.getElementById("wave17-generated-host"),first=host.firstElementChild;const h=SevenGeneratedUI.mount({version:1,id:"replacement",title:"Replacement",direction:"ltr",nodes:[{type:"button",id:"b",label:"Done",action:"done"}]},host);const replaced=!host.contains(first)&&host.children.length===1&&host.firstElementChild===h.root;const dir=h.root.dir;h.destroy();return{replaced,dir,empty:host.children.length===0}});ok(lifecycle.replaced);eq(lifecycle.dir,"ltr");eq(lifecycle.empty,true);
    for(const width of [320,360,390,720]){await p.evaluate(()=>{const host=document.getElementById("wave17-generated-host");SevenGeneratedUI.mount({version:1,id:"responsive",title:"Responsive",direction:"rtl",nodes:[{type:"section",id:"s",children:[{type:"heading",id:"h",text:"عنوان",level:2},{type:"input",id:"i",label:"سؤال",key:"q",value:"نص mixed 123"},{type:"button",id:"b",label:"متابعة",action:"go"}]}]},host)});await p.setViewportSize({width,height:820});const v=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,dir:document.querySelector('.seven-generated-ui').dir,button:document.querySelector('.seven-generated-button').getBoundingClientRect(),input:document.querySelector('.seven-generated-input').getBoundingClientRect()}));ok(v.sw<=v.cw+2,`${width}:${JSON.stringify(v)}`);eq(v.dir,"rtl");ok(v.button.width>=44&&v.button.height>=48,`${width}:button`);ok(v.input.width>0&&v.input.right<=v.cw+2,`${width}:input`)}
    eq(errors.length,0,errors.join("\n"));await c.close();
    const rc=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});await rc.addInitScript(()=>localStorage.setItem("user_name_asked","1"));await rc.route("**/*",x=>x.request().url().startsWith(origin)?x.continue():x.abort());const rp=await rc.newPage();await rp.goto(origin,{waitUntil:"domcontentloaded"});await rp.click(".seven-beta-status");await rp.waitForFunction(()=>window.SevenWorkspaces);await rp.evaluate(()=>SevenWorkspaces.loadGeneratedUi());await rp.waitForFunction(()=>window.SevenGeneratedUI);await rp.evaluate(()=>{const m=document.createElement("div");document.body.appendChild(m);SevenGeneratedUI.mount({version:1,id:"reduce",title:"Reduce",nodes:[{type:"button",id:"b",label:"Go",action:"go"}]},m)});const dur=await rp.evaluate(()=>getComputedStyle(document.querySelector('.seven-generated-button')).transitionDuration);ok(dur==="0s"||parseFloat(dur)<=.001,dur);await rc.close();
    console.log(`Wave 17 Typed Generated UI Browser: PASS (${n} assertions; lifecycle, type coverage, events/forms, fail-closed limits, injection safety, mobile/RTL/reduced-motion)`);
  }finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exit(1)});
