"use strict";
const assert=require("assert");
const crypto=require("crypto");
const t=require("./logo-tournament.cjs");
const passb=require("./logo-tournament-passb.cjs");
const portfolioRuntime=require("./logo-candidate-portfolio.cjs");
const host=require("./logo-host-evidence.cjs");
const visual=require("./visual-evidence-runtime-final.cjs");
const reviewPackRuntime=require("./logo-review-pack.cjs");
const handoff=require("./logo-review-handoff.cjs");
const closure=require("./logo-tournament-closure.cjs");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.strictEqual(a,b,m);n++},throws=(fn,re)=>{assert.throws(fn,re);n++};
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");
function hostFixturePackage(record,descriptor,{branch,commitSha}){
  const captureMethod="unit-host-fixture",scenario=host.createScenario(record.candidate,descriptor,{branch,commitSha,captureMethod}),bytes=Buffer.from(`HOST-FIXTURE:${record.candidate.seal}:${descriptor.stage}:${descriptor.variant}`);
  const artifact=visual.createArtifact(scenario,{path:`unit-host/${record.candidate.id}/${descriptor.stage}/${descriptor.variant}.png`,sha256:sha(bytes),byteSize:bytes.length,width:scenario.viewport.width,height:scenario.viewport.height,captureMethod,sourceRef:passb.sourceRef(record.candidate,descriptor.stage,descriptor.variant)});
  const evidence=visual.createEvidence(scenario,artifact,{tier:visual.EVIDENCE_TIER.HOST,environmentIdentity:"unit-host-fixture-not-release-device",commitSha,branch,audits:host.auditsForScenario(scenario),policy:"OBSERVE",notes:["unit-test-only","render-integrity-only","not-release-device"]});
  const binding=passb.createVisualEvidenceBinding({candidate:record.candidate,stage:descriptor.stage,variant:descriptor.variant,scenario,artifact,evidence});return Object.freeze({binding,scenario,artifact,evidence});
}
function hostPackFixture(portfolio){const branch="unit-branch",commitSha="a".repeat(40),candidates=portfolio.records.map(record=>{const packages=host.matrix().map(d=>hostFixturePackage(record,d,{branch,commitSha})),coverage=passb.evaluateVisualEvidenceCoverage({candidate:record.candidate,packages});if(coverage.verdict!=="PASS")throw new Error("unit host coverage failed");return {candidateId:record.candidate.id,candidateSeal:record.candidate.seal,coverage,packages}});const body={schema:"seven-logo-host-visual-evidence-pack",version:host.VERSION,branch,commitSha,environmentIdentity:"unit-host-fixture-not-release-device",tier:"HOST",candidateCount:candidates.length,packageCount:candidates.reduce((x,c)=>x+c.packages.length,0),candidates,authorityBoundary:{renderIntegrityOnly:true,doesNotProveIdentifiability:true,doesNotReplaceIndependentReview:true,doesNotQualifyReleaseBuildDevice:true}};return Object.freeze({...body,packHash:t.sha(body)})}
function allPassFindings(){return {silhouetteIdentifiable:true,tinySizes:Object.fromEntries(t.REQUIRED_SIZES.map(x=>[String(x),true])),adaptiveMasks:Object.fromEntries(t.REQUIRED_MASKS.map(x=>[x,true])),monochromeOneColorSurvives:true,dayNight:{sameCoreGeometry:true,lightBackgroundPass:true,darkBackgroundPass:true},productContexts:Object.fromEntries(reviewPackRuntime.PRODUCT_CONTEXTS.map(x=>[x,true])),simplifierSurvives:true}}
function buildInputs({makeInconclusive=false}={}){
  const portfolio=portfolioRuntime.buildPortfolio(),hostPack=hostPackFixture(portfolio);ok(host.verifyPack(hostPack,portfolio.records));
  const reviewPack=reviewPackRuntime.createReviewBundle({portfolio,hostPack,builderContext:"seven-ci-logo-builder-wave14-v1",artifactRef:"unit://wave14"});ok(reviewPackRuntime.verifyReviewBundle(reviewPack,{portfolio,hostPack}));
  const submissions={},findings={};for(let i=0;i<portfolio.records.length;i++){const record=portfolio.records[i],reviewCandidate=reviewPack.candidates.find(x=>x.candidateId===record.candidate.id),ratings=Object.fromEntries(t.DIMENSIONS.map(d=>[d,i===0?4:3]));submissions[record.candidate.id]=handoff.createReviewerSubmission({handoff:reviewCandidate.handoff,reviewer:`independent-reviewer-${i}`,role:"INDEPENDENT_VISUAL_REVIEWER",reviewerContext:`external-clean-room-${i}`,ratings,landscapeSha256:t.sha(`landscape-${i}`),sourceRefs:[`source-${i}-a`,`source-${i}-b`,`source-${i}-c`],comparedProducts:[`product-${i}-a`,`product-${i}-b`,`product-${i}-c`,`product-${i}-d`,`product-${i}-e`],suspiciousImitation:false,reviewReference:`review-${i}`});findings[record.candidate.id]=allPassFindings()}
  if(makeInconclusive)findings[portfolio.records.at(-1).candidate.id]={...allPassFindings(),silhouetteIdentifiable:false};
  return {portfolio,hostPack,reviewPack,submissions,findings};
}
const full=buildInputs(),result=closure.adjudicateTournament({portfolio:full.portfolio,hostPack:full.hostPack,reviewPack:full.reviewPack,submissionsByCandidate:full.submissions,hardGateFindingsByCandidate:full.findings});ok(closure.verifyTournamentAdjudication(result,{portfolio:full.portfolio,hostPack:full.hostPack,reviewPack:full.reviewPack}));eq(result.receipt.candidateCount,6);eq(result.receipt.finalists.length,6);eq(result.receipt.rejected.length,0);eq(result.receipt.inconclusive.length,0);eq(result.receipt.selectionState,"UNIQUE_SELECTION_AVAILABLE");eq(result.receipt.comparison.verdict,"FINALIST");eq(result.receipt.eligibleChampionIds.length,1);eq(result.receipt.eligibleChampionIds[0],full.portfolio.records[0].candidate.id);eq(result.receipt.winner,null);eq(result.receipt.exportAuthorized,false);
const decision=closure.createChampionDecision({adjudication:result,selectedCandidateId:full.portfolio.records[0].candidate.id,decider:"deterministic-pareto-policy",deciderContext:"seven-logo-tournament-closure-v1",reason:"Only undominated finalist after complete independent review coverage.",policy:"UNIQUE_PARETO"});ok(closure.verifyChampionDecision(decision,result));eq(decision.status,"CHAMPION_SELECTED");eq(decision.authorityBoundary.brandFreezeStillBlocked,true);eq(closure.selectedEntry({adjudication:result,decision}).candidateId,decision.selectedCandidateId);
const blockedInputs=buildInputs({makeInconclusive:true}),blocked=closure.adjudicateTournament({portfolio:blockedInputs.portfolio,hostPack:blockedInputs.hostPack,reviewPack:blockedInputs.reviewPack,submissionsByCandidate:blockedInputs.submissions,hardGateFindingsByCandidate:blockedInputs.findings});ok(closure.verifyTournamentAdjudication(blocked,{portfolio:blockedInputs.portfolio,hostPack:blockedInputs.hostPack,reviewPack:blockedInputs.reviewPack}));eq(blocked.receipt.inconclusive.length,1);eq(blocked.receipt.selectionState,"NO_CHAMPION");eq(blocked.receipt.eligibleChampionIds.length,0);throws(()=>closure.createChampionDecision({adjudication:blocked,selectedCandidateId:blockedInputs.portfolio.records[0].candidate.id,decider:"x",deciderContext:"y",reason:"premature",policy:"UNIQUE_PARETO"}),/not eligible/);
function sealedReceipt(body){return Object.freeze({...body,seal:t.sha(body)})}
const tradeReceipt=sealedReceipt({schema:"seven-logo-tournament-adjudication",version:closure.VERSION,portfolioSeal:t.sha("portfolio"),hostPackHash:t.sha("host"),reviewPackSeal:t.sha("review"),builderContext:"builder-context",branch:"b",commitSha:"b".repeat(40),candidateCount:2,entries:[{candidateId:"a"},{candidateId:"b"}],finalists:["a","b"],rejected:[],inconclusive:[],comparison:{verdict:"TRADEOFF_REQUIRES_DECISION",undominated:["a","b"]},eligibleChampionIds:["a","b"],selectionState:"EXPLICIT_DECISION_REQUIRED",winner:null,exportAuthorized:false,authorityBoundary:{fullCandidateCoverageRequired:true,inconclusiveCompetitorBlocksChampion:true,reviewIndependencePreserved:true,adjudicationDoesNotChooseTradeoff:true,noExportBeforeChampionDecision:true,noAndroidProofClaim:true}});const trade={receipt:tradeReceipt,entries:[]};ok(closure.verifyTournamentAdjudication(trade));throws(()=>closure.createChampionDecision({adjudication:trade,selectedCandidateId:"a",decider:"builder",deciderContext:"builder-context",reason:"self-choice",policy:"EXPLICIT_TRADEOFF_DECISION"}),/independent/);const external=closure.createChampionDecision({adjudication:trade,selectedCandidateId:"a",decider:"product-owner",deciderContext:"independent-product-decision",reason:"Explicit documented tradeoff choice.",policy:"EXPLICIT_TRADEOFF_DECISION"});ok(closure.verifyChampionDecision(external,trade));
const missing={...full.submissions};delete missing[full.portfolio.records[1].candidate.id];throws(()=>closure.adjudicateTournament({portfolio:full.portfolio,hostPack:full.hostPack,reviewPack:full.reviewPack,submissionsByCandidate:missing,hardGateFindingsByCandidate:full.findings}),/missing/);
console.log(`Logo Tournament Closure: PASS (${n} assertions; complete independent coverage, fail-closed inconclusive handling, Pareto/decision governance)`);
