const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/../seven_ai-final.html','utf8');
const start=html.indexOf('        function populateFreeModelSelect(');
const end=html.indexOf('        function getRouteUiStateV1()',start);
assert.ok(start>=0&&end>start,'authoritative picker source missing');
const models=[{provider:'llm7',id:'a',label:'Alpha',free:true,contextWindow:131072},{provider:'llm7',id:'b',label:'Beta',free:true,contextWindow:131072}];
let cooling=true,blockedBy='cooldown';
const select={options:[],selectedIndex:-1,value:'llm7::a',appendChild(g){this.options.push(...g.children)}};
Object.defineProperty(select,'innerHTML',{set(){this.options=[]}});
const status={textContent:''};
const context={document:{documentElement:{lang:'en'},getElementById:id=>id==='modelSelect'?select:status,createElement:()=>({dataset:{},children:[],appendChild(x){this.children.push(x)}})},currentModel:'llm7::a',getFreeModelCatalog:()=>models,isFreePriceProofFresh:()=>true,isFreeProviderConfigured:()=>true,isFreeProviderEnabled:()=>true,modelPickerContextV3:()=>({confidence:.8}),freeModelSelectionKey:(p,id)=>p+'::'+id,formatModelReasonV3:()=>'healthy route',updateRouteStatusUiV1(){},providerDisplayName:()=> 'LLM7',scoreModelCandidateV3:model=>cooling?{eligible:false,parts:{reason:blockedBy}}:{eligible:true,score:model.id==='a'?90:80},rankModelCandidatesV3:()=>cooling?[]:models.map((model,index)=>({model,score:90-index*10}))};
vm.createContext(context);vm.runInContext(html.slice(start,end),context);
const populate=()=>vm.runInContext('populateFreeModelSelect()',context);
populate();
assert.equal(select.options.length,2,'cooldown must not erase the model catalog');
assert.ok(select.options.every(x=>x.disabled&&x.dataset.unavailableReason==='cooldown'&&x.textContent.includes('Cooling down')));
assert.match(status.textContent,/no route is ready/);
context.document.documentElement.lang='ar-IQ';populate();
assert.ok(select.options.every(x=>x.textContent.includes('تهدئة مؤقتة')));
assert.match(status.textContent,/لا يوجد مسار جاهز/);
blockedBy='context';populate();
assert.ok(select.options.every(x=>x.disabled&&x.dataset.unavailableReason==='context'));
cooling=false;populate();
assert.equal(select.options.length,2);
assert.ok(select.options.every(x=>x.disabled===false),'recovered routes become selectable');
assert.equal(select.options[0].value,'llm7::a','eligible ranking order is unchanged');
const shell=fs.readFileSync(__dirname+'/workspaces/seven-shell.js','utf8');
assert.match(shell,/b.disabled=opt.disabled===true/,'canonical menu must preserve disabled availability');
console.log('model picker availability: PASS (cooldown, Arabic, context limit, recovery, canonical disabled state)');

const css=fs.readFileSync(__dirname+'/ui-hardening.css','utf8');
const menuRule=css.match(/#seven-app \.seven-shell-model-menu:not\(\[hidden\]\)\{([^}]+)\}/);
assert.ok(menuRule);assert.match(menuRule[1],/inset-inline:8px!important/);assert.doesNotMatch(menuRule[1],/(?:left|right):auto!important/,'physical auto offsets must not cancel logical menu insets');
assert.match(css,/#seven-app\{[^}]*display:flex;[^}]*width:100%/,'the actual Seven wrapper must fill the mobile viewport');
