(function(r,f){const a=f(r);if(typeof module==='object'&&module.exports)module.exports=a;else r.SevenPerformance=a})(typeof globalThis!=='undefined'?globalThis:this,function(r){'use strict';
const D=!!(r&&r.document),d=D?r.document:null,R={lite:0,balanced:1,full:2},state={tier:'balanced',reducedMotion:false,longTasks:[],marks:[],ready:false,observer:null,visibilityBound:false,lastTierAt:0},Q=new Map();let P=false;
function n(){return r.performance&&r.performance.now?r.performance.now():Date.now()}function c(x,a,b){return Math.max(a,Math.min(b,Number(x)||0))}function m(){const a=r&&r.__sevenAndroidMotion,native=!!(a&&a.source==='ANDROID_GLOBAL_ANIMATION_SCALES'&&a.reducedMotion===true),css=!!(r.matchMedia&&r.matchMedia('(prefers-reduced-motion: reduce)').matches);return native||css}function l(ms=8000,min=50){const t=Date.now()-ms;return state.longTasks.filter(x=>(x.at||0)>=t&&x.duration>=min).length}
function rec(s){s=s||{};const b=s.batteryLevel==null?1:c(s.batteryLevel,0,1),x=Number(s.deviceMemoryGb||0),k=Number(s.cores||0),p=String(s.memoryPressure||'normal'),h=String(s.thermal||'normal'),q=Number(s.recentLongTasks||0);if(p==='critical'||h==='critical'||b<=.1)return'lite';if(p==='high'||h==='high'||s.hidden||(x&&x<=2)||(k&&k<=2)||b<=.2||q>=3)return'lite';if(q)return'balanced';return x>=6&&k>=6&&b>.35?'full':'balanced'}
function sig(e){const x=r.navigator||{};return{deviceMemoryGb:Number(x.deviceMemory||0),cores:Number(x.hardwareConcurrency||0),hidden:!!(D&&d.hidden),recentLongTasks:l(),...(e||{})}}function det(e){state.reducedMotion=m();return rec(sig(e))}
function dom(){if(!D)return;const h=d.documentElement;h.dataset.sevenPerformance=state.tier;h.dataset.sevenReducedMotion=state.reducedMotion?'1':'0';h.dataset.sevenHidden=d.hidden?'1':'0';h.classList.remove('seven-tier-lite','seven-tier-balanced','seven-tier-full');h.classList.add('seven-tier-'+state.tier)}
function app(t){const x=R[t]!=null?t:det();if(x!==state.tier)state.lastTierAt=Date.now();state.tier=x;dom();return x}function reconsider(e,o){o=o||{};state.reducedMotion=m();const x=rec(sig(e)),up=R[x]>R[state.tier],quiet=!l(12000);if(!up||o.forceUpgrade||(quiet&&(!state.lastTierAt||Date.now()-state.lastTierAt>=8000)))app(x);else dom();return state.tier}
function idle(fn,to){if(typeof fn!=='function')return()=>{};let off=false,id,run=()=>{if(!off)fn()};if(r.requestIdleCallback)id=r.requestIdleCallback(run,{timeout:to||1200});else id=r.setTimeout(run,Math.min(to||250,250));return()=>{off=true;if(r.cancelIdleCallback&&id!=null)r.cancelIdleCallback(id);else if(id!=null)r.clearTimeout(id)}}
function frame(key,fn){if(typeof fn!=='function')return;Q.set(key||fn,fn);if(P)return;P=true;(r.requestAnimationFrame||(cb=>r.setTimeout(()=>cb(n()),16)))(()=>{P=false;const jobs=[...Q.values()];Q.clear();for(const j of jobs)try{j()}catch(e){r.setTimeout(()=>{throw e},0)}})}
async function y(start,budget){if(n()-Number(start||0)<(Number(budget)||4))return false;await new Promise(ok=>{try{const p=r.scheduler&&r.scheduler.yield&&r.scheduler.yield();p&&p.then?p.then(ok,()=>r.setTimeout(ok,0)):r.setTimeout(ok,0)}catch(_){r.setTimeout(ok,0)}});return true}
function measure(name,fn){const s=n(),value=fn(),duration=n()-s;state.marks.push({name,duration,at:Date.now()});if(state.marks.length>100)state.marks.shift();return{value,duration}}
function observe(){if(!D||!r.PerformanceObserver||state.observer)return state.observer;try{const o=new r.PerformanceObserver(x=>{const at=Date.now();for(const e of x.getEntries())state.longTasks.push({duration:e.duration,startTime:e.startTime,at});if(state.longTasks.length>50)state.longTasks.splice(0,state.longTasks.length-50);reconsider()});o.observe({entryTypes:['longtask']});state.observer=o;return o}catch(_){return null}}
function suspend(){if(!D||state.visibilityBound)return;state.visibilityBound=true;d.addEventListener('visibilitychange',()=>{d.hidden?app('lite'):reconsider(null,{forceUpgrade:true})},{passive:true})}
function snap(){return{tier:state.tier,reducedMotion:state.reducedMotion,longTasks:state.longTasks.slice(),marks:state.marks.slice(),ready:state.ready}}function boot(){state.reducedMotion=m();app(det());observe();suspend();state.ready=true;dom();return snap()}
if(D){d.readyState==='loading'?d.addEventListener('DOMContentLoaded',boot,{once:true}):boot()}return{state,recommendTier:rec,detectSignals:sig,detectTier:det,applyTier:app,reconsiderTier:reconsider,scheduleIdle:idle,batchFrame:frame,yieldIfNeeded:y,measure,snapshot:snap,boot}});
