(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.SevenPerformance=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){'use strict';
const hasDOM=!!(root&&root.document),doc=hasDOM?root.document:null,R={lite:0,balanced:1,full:2};
const state={tier:'balanced',reducedMotion:false,longTasks:[],marks:[],ready:false,observer:null,visibilityBound:false,lastTierAt:0};const frameQueue=new Map();let framePending=false;
function now(){return root.performance&&root.performance.now?root.performance.now():Date.now()}function clamp(n,a,b){return Math.max(a,Math.min(b,Number(n)||0))}function reduce(){return!!(root.matchMedia&&root.matchMedia('(prefers-reduced-motion: reduce)').matches)}function recent(ms=8000,min=50){const t=Date.now()-ms;return state.longTasks.filter(x=>(x.at||0)>=t&&x.duration>=min).length}
function recommendTier(s){s=s||{};const b=s.batteryLevel==null?1:clamp(s.batteryLevel,0,1),m=Number(s.deviceMemoryGb||0),c=Number(s.cores||0),p=String(s.memoryPressure||'normal'),h=String(s.thermal||'normal'),l=Number(s.recentLongTasks||0);if(p==='critical'||h==='critical'||b<=.1)return'lite';if(p==='high'||h==='high'||s.hidden||(m&&m<=2)||(c&&c<=2)||b<=.2||l>=3)return'lite';if(l>=1)return'balanced';if(m>=6&&c>=6&&b>.35)return'full';return'balanced'}
function detectSignals(extra){const n=root.navigator||{};return{deviceMemoryGb:Number(n.deviceMemory||0),cores:Number(n.hardwareConcurrency||0),hidden:!!(hasDOM&&doc.hidden),recentLongTasks:recent(),...(extra||{})}}function detectTier(extra){state.reducedMotion=reduce();return recommendTier(detectSignals(extra))}
function dom(){if(!hasDOM)return;const h=doc.documentElement;h.dataset.sevenPerformance=state.tier;h.dataset.sevenReducedMotion=state.reducedMotion?'1':'0';h.dataset.sevenHidden=doc.hidden?'1':'0';h.classList.remove('seven-tier-lite','seven-tier-balanced','seven-tier-full');h.classList.add('seven-tier-'+state.tier)}
function applyTier(tier){const next=R[tier]!=null?tier:detectTier();if(next!==state.tier)state.lastTierAt=Date.now();state.tier=next;dom();return next}function reconsiderTier(extra,opt){opt=opt||{};state.reducedMotion=reduce();const next=recommendTier(detectSignals(extra)),up=R[next]>R[state.tier],quiet=!recent(12000);if(!up||opt.forceUpgrade||(quiet&&(!state.lastTierAt||Date.now()-state.lastTierAt>=8000)))applyTier(next);else dom();return state.tier}
function scheduleIdle(task,timeout){if(typeof task!=='function')return()=>{};let off=false,id,run=()=>{if(!off)task()};if(root.requestIdleCallback)id=root.requestIdleCallback(run,{timeout:timeout||1200});else id=root.setTimeout(run,Math.min(timeout||250,250));return()=>{off=true;if(root.cancelIdleCallback&&id!=null)root.cancelIdleCallback(id);else if(id!=null)root.clearTimeout(id)}}
function batchFrame(key,task){if(typeof task!=='function')return;frameQueue.set(key||task,task);if(framePending)return;framePending=true;(root.requestAnimationFrame||((cb)=>root.setTimeout(()=>cb(now()),16)))(()=>{framePending=false;const jobs=[...frameQueue.values()];frameQueue.clear();for(const job of jobs)try{job()}catch(e){root.setTimeout(()=>{throw e},0)}})}
async function yieldIfNeeded(start,budget){if(now()-Number(start||0)<(Number(budget)||4))return false;await new Promise(r=>{try{const y=root.scheduler&&root.scheduler.yield&&root.scheduler.yield();y&&y.then?y.then(r,()=>root.setTimeout(r,0)):root.setTimeout(r,0)}catch(_){root.setTimeout(r,0)}});return true}
function measure(name,fn){const start=now(),value=fn(),duration=now()-start;state.marks.push({name,duration,at:Date.now()});if(state.marks.length>100)state.marks.shift();return{value,duration}}
function observeLongTasks(){if(!hasDOM||!root.PerformanceObserver||state.observer)return state.observer;try{const o=new root.PerformanceObserver(list=>{const at=Date.now();for(const e of list.getEntries())state.longTasks.push({duration:e.duration,startTime:e.startTime,at});if(state.longTasks.length>50)state.longTasks.splice(0,state.longTasks.length-50);reconsiderTier()});o.observe({entryTypes:['longtask']});state.observer=o;return o}catch(_){return null}}
function suspendWhenHidden(){if(!hasDOM||state.visibilityBound)return;state.visibilityBound=true;doc.addEventListener('visibilitychange',()=>{if(doc.hidden)applyTier('lite');else reconsiderTier(null,{forceUpgrade:true})},{passive:true})}
function boot(){state.reducedMotion=reduce();applyTier(detectTier());observeLongTasks();suspendWhenHidden();state.ready=true;dom();return snapshot()}function snapshot(){return{tier:state.tier,reducedMotion:state.reducedMotion,longTasks:state.longTasks.slice(),marks:state.marks.slice(),ready:state.ready}}
if(hasDOM){if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',boot,{once:true});else boot()}return{state,recommendTier,detectSignals,detectTier,applyTier,reconsiderTier,scheduleIdle,batchFrame,yieldIfNeeded,measure,snapshot,boot};});
