"use strict";
const assert=require("assert/strict"),t=require("./release-readiness.cjs");let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++},throws=(f,re,m)=>{assert.throws(f,re,m);n++},H=x=>t.hash(x),COMMIT="c".repeat(40),ART=H("release-apk");
function rec(domain,round=1,override={}){const classes=t.POLICY[domain],ind=classes.includes(t.CLASSES.INDEPENDENT_REVIEW);return t.createReceipt({domain,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evidenceSha256:H(`${domain}:r${round}`),classes,status:"PASS",sourceRef:`evidence:${domain}:r${round}`,producer:"seven-release-ci",producerContext:`builder-r${round}`,verifier:ind?"independent-reviewer":"seven-release-verifier",verifierContext:ind?`independent-r${round}`:`ci-r${round}`,capturedAt:`2026-09-${14+round}T00:00:00.000Z`,expiresAt:`2026-09-${20+round}T00:00:00.000Z`,...override})}
const r1=t.REQUIRED_DOMAINS.map(d=>rec(d,1));for(const r of r1)ok(t.verifyReceipt(r));
let m1=t.createManifest({round:1,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-15T01:00:00.000Z",receipts:r1});ok(t.verifyManifest(m1));eq(m1.verdict,"PASS");eq(m1.missing.length,0);eq(m1.failures.length,0);
let missing=t.createManifest({round:1,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-15T01:00:00.000Z",receipts:r1.filter(x=>x.domain!=="ANDROID_RELEASE_VISUAL")});eq(missing.verdict,"INCONCLUSIVE");ok(missing.missing.includes("ANDROID_RELEASE_VISUAL"));
const wrongClass=r1.map(x=>x.domain==="PERFORMANCE_RESOURCE_DEVICE"?rec(x.domain,1,{classes:[t.CLASSES.RELEASE_DEVICE]}):x);let blocked=t.createManifest({round:1,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-15T01:00:00.000Z",receipts:wrongClass});eq(blocked.verdict,"BLOCK");ok(blocked.failures.includes("missing-class:PERFORMANCE_RESOURCE_DEVICE:PHYSICAL_DEVICE"));
const stale=r1.map(x=>x.domain==="SOURCE_INTEGRITY"?rec(x.domain,1,{expiresAt:"2026-09-15T00:30:00.000Z"}):x);blocked=t.createManifest({round:1,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-15T01:00:00.000Z",receipts:stale});eq(blocked.verdict,"BLOCK");ok(blocked.failures.includes("stale:SOURCE_INTEGRITY"));
throws(()=>rec("FINAL_RED_TEAM",1,{producerContext:"same",verifierContext:"same"}),/independent review context/);
const drift=r1.map(x=>x.domain==="REGRESSION_SUITE"?rec(x.domain,1,{artifactSha256:H("other")}):x);blocked=t.createManifest({round:1,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-15T01:00:00.000Z",receipts:drift});eq(blocked.verdict,"BLOCK");ok(blocked.failures.includes("release-identity-drift:REGRESSION_SUITE"));
const duplicate=[...r1,rec("SOURCE_INTEGRITY",1,{evidenceSha256:H("dup")})];blocked=t.createManifest({round:1,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-15T01:00:00.000Z",receipts:duplicate});eq(blocked.verdict,"BLOCK");ok(blocked.failures.includes("duplicate-domain:SOURCE_INTEGRITY"));
const r2=t.REQUIRED_DOMAINS.map(d=>rec(d,2));const m2=t.createManifest({round:2,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-16T01:00:00.000Z",receipts:r2});eq(m2.verdict,"PASS");let pair=t.createSaturationPair({round1:m1,round2:m2});ok(t.verifySaturationPair(pair));eq(pair.verdict,"SATURATION_2_OF_2");
const sameIndependent=r2.map(x=>["IDENTITY_FREEZE","SEVEN_EVALS","FINAL_RED_TEAM"].includes(x.domain)?rec(x.domain,1,{capturedAt:"2026-09-16T00:00:00.000Z",expiresAt:"2026-09-22T00:00:00.000Z"}):x);const m2weak=t.createManifest({round:2,branch:"ultimate-polish-v1",commitSha:COMMIT,artifactSha256:ART,evaluatedAt:"2026-09-16T01:00:00.000Z",receipts:sameIndependent});pair=t.createSaturationPair({round1:m1,round2:m2weak});eq(pair.verdict,"BLOCK");ok(pair.failures.some(x=>x.startsWith("independent-evidence-not-refreshed:")));ok(pair.failures.some(x=>x.startsWith("independent-context-not-refreshed:")));
const tampered={...m1,verdict:"BLOCK"};eq(t.verifyManifest(tampered),false);throws(()=>t.createReceipt({domain:"NOT_REAL"}),/unknown readiness domain/);
console.log(`Release Readiness + Saturation Gate: PASS (${n} assertions; exact release identity, evidence-class floors, freshness, independence, Saturation 2/2)`);
