(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SevenResearch=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const STATUS=Object.freeze({PASS:'PASS',INCONCLUSIVE:'INCONCLUSIVE',BLOCKED:'BLOCKED'}),STANCE=Object.freeze({SUPPORT:'support',CONTRADICT:'contradict',QUALIFY:'qualify',CONTEXT:'context'});
const A=v=>Array.isArray(v)?v:[],S=v=>typeof v==='string'?v.trim():'',T=v=>{const n=Date.parse(v||'');return Number.isFinite(n)?n:null},U=v=>{try{const u=new URL(v);if(u.protocol!=='https:'&&u.protocol!=='http:')return null;u.hash='';return u.href}catch{return null}},C=c=>{const x=c&&c.coverage;return!!(x&&x.completed&&A(x.queryPlanIds).length&&A(x.providerIds).length&&S(x.coverageHash))};
function claims(raw){const seen=new Set();return A(raw).map((x,i)=>{const c=typeof x==='string'?{text:x}:{...(x||{})};c.id=S(c.id)||'claim-'+(i+1);if(seen.has(c.id))throw Error('duplicate claim id: '+c.id);seen.add(c.id);c.text=S(c.text);if(!c.text)throw Error('claim text required: '+c.id);c.timeSensitive=!!c.timeSensitive;c.freshnessDays=Number.isFinite(+c.freshnessDays)?Math.max(0,+c.freshnessDays):null;c.minIndependentSupport=Math.max(1,Math.floor(+c.minIndependentSupport||1));c.negative=!!c.negative;c.coverage=C(c);return c})}
function sources(raw){const seen=new Set();return A(raw).map((x,i)=>{const x0=x||{},s={};s.id=S(x0.id)||'source-'+(i+1);if(seen.has(s.id))throw Error('duplicate source id: '+s.id);seen.add(s.id);s.title=S(x0.title)||s.id;s.url=S(x0.url);s.publishedAt=T(x0.publishedAt);s.updatedAt=T(x0.updatedAt);s.retrievedAt=T(x0.retrievedAt)||Date.now();s.versionId=S(x0.versionId)||[s.id,s.url,s.updatedAt||s.publishedAt||s.retrievedAt].join('@');s.clusterId=S(x0.clusterId)||'unknown';s.evidence=A(x0.evidence).map((e,n)=>({id:S(e&&e.id)||s.id+':e'+(n+1),claimId:S(e&&e.claimId),stance:Object.values(STANCE).includes(e&&e.stance)?e.stance:STANCE.CONTEXT,locator:S(e&&e.locator),clusterId:S(e&&e.clusterId)||s.clusterId,sourceVersionId:s.versionId,transformation:S(e&&e.transformation)||'extract'}));return s})}
function fresh(s,c,now,def){if(!c.timeSensitive)return{required:false,status:'NOT_REQUIRED',ageDays:null,limitDays:null};const base=s.updatedAt||s.publishedAt||s.retrievedAt,lim=c.freshnessDays==null?def:c.freshnessDays,age=Math.max(0,(now-base)/86400000);return{required:true,status:age<=lim?'FRESH':'STALE',ageDays:+age.toFixed(2),limitDays:lim}}
function createClaimEvidenceMatrix(rc,rs,o){o=o||{};const cs=claims(rc),ss=sources(rs),now=T(o.now)||Date.now(),def=Number.isFinite(+o.defaultFreshnessDays)?Math.max(0,+o.defaultFreshnessDays):30,rows=cs.map(c=>{const ev=[];for(const s of ss)for(const e of s.evidence)if(e.claimId===c.id)ev.push({evidenceId:e.id,sourceId:s.id,sourceVersionId:s.versionId,title:s.title,url:s.url,stance:e.stance,locator:e.locator,clusterId:e.clusterId,transformation:e.transformation,freshness:fresh(s,c,now,def),citable:!!U(s.url)&&!!e.locator});const sup=ev.filter(e=>e.stance===STANCE.SUPPORT),con=ev.filter(e=>e.stance===STANCE.CONTRADICT),live=sup.filter(e=>e.freshness.status!=='STALE'),cit=live.filter(e=>e.citable),ind=new Set(cit.map(e=>e.clusterId));let status='SUPPORTED';if(c.negative&&!sup.length&&!con.length)status=c.coverage?'NOT_FOUND_COVERED':'GAP';else if(!sup.length&&!con.length)status='GAP';else if(c.timeSensitive&&sup.length&&!live.length)status='STALE';else if(sup.length&&con.length)status='CONFLICT';else if(live.length&&!cit.length)status='UNCITABLE';else if(ind.size<c.minIndependentSupport)status='GAP';return{claim:{...c},status,evidence:ev,supportCount:sup.length,contradictionCount:con.length,independentSupportCount:ind.size}});return{version:3,createdAt:new Date(now).toISOString(),claims:cs,sourceCount:ss.length,rows,sources:ss}}
function analyze(m){if(!m||!Array.isArray(m.rows))throw Error('invalid research matrix');const p=s=>m.rows.filter(r=>r.status===s).map(r=>r.claim.id),gaps=p('GAP'),stale=p('STALE'),uncitable=p('UNCITABLE'),conflicts=p('CONFLICT'),coveredNotFound=p('NOT_FOUND_COVERED'),status=gaps.length||stale.length||uncitable.length||conflicts.length?STATUS.INCONCLUSIVE:STATUS.PASS;return{status,gaps,stale,uncitable,conflicts,coveredNotFound,complete:status===STATUS.PASS}}
function lockCitations(m){const an=analyze(m),out={};for(const r of m.rows){if(!['SUPPORTED','CONFLICT'].includes(r.status))continue;const refs=r.evidence.filter(e=>e.stance===STANCE.SUPPORT&&e.freshness.status!=='STALE'&&e.citable).map(e=>({evidenceId:e.evidenceId,sourceId:e.sourceId,sourceVersionId:e.sourceVersionId,url:U(e.url),title:e.title,locator:e.locator,clusterId:e.clusterId}));if(refs.length)out[r.claim.id]=refs}return{version:3,status:an.status,claims:out,lockedAt:new Date().toISOString()}}
function nextActions(m){const a=analyze(m),x=[];for(const id of a.gaps)x.push({type:'evidence-search',claimId:id});for(const id of a.stale)x.push({type:'freshness-search',claimId:id});for(const id of a.conflicts)x.push({type:'contradiction-resolution',claimId:id});for(const id of a.uncitable)x.push({type:'citation-recovery',claimId:id});return x}
function verify(c,s,o){const matrix=createClaimEvidenceMatrix(c,s,o);return{matrix,analysis:analyze(matrix),citationLock:lockCitations(matrix),nextActions:nextActions(matrix)}}
return{STATUS,STANCE,normalizeClaims:claims,normalizeSources:sources,createClaimEvidenceMatrix,analyze,lockCitations,nextActions,verify}
});
