const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const attachment=fs.readFileSync(__dirname+'/attachment-runtime.js','utf8');
assert.match(attachment,/MAX_FILE_BYTES=25\*1024\*1024/);
assert.match(attachment,/TYPE_MISMATCH/);
assert.match(attachment,/ATTACHMENT_TOTAL_TOO_LARGE/);
const loader=fs.readFileSync(__dirname+'/attachment-loader.js','utf8');
assert.match(loader,/seven-attachment-runtime-lazy/);
assert.match(loader,/\.remove\(\)/);
const rpg=fs.readFileSync(__dirname+'/workspaces/rpg.js','utf8');
assert.match(rpg,/function snapshot\(\)\{return clone/);
assert.match(rpg,/PACK_TOO_LARGE/);
assert.match(rpg,/PACK_TOO_DEEP/);
const Canon=require('./canon-simulator.js');
const engine=Canon.createEngine({id:'c',anchors:[],facts:[],sources:[],invariants:[]});
let s=engine.createSession();
let out=engine.applySceneDelta(s,{canonDebtDelta:0.1},{forceBranch:'true'});
assert.ok(out.session.branchId,'serialized forceBranch must create branch');
console.log('resilience contracts: PASS');
