"use strict";
const assert=require("assert/strict"),a=require("./android-visual-certification.cjs"),t=require("./visual-red-team.cjs");let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(x,y,m)=>{assert.equal(x,y,m);n++},throws=(f,re,m)=>{assert.throws(f,re,m);n++},H=x=>a.hash(x),COMMIT="b".repeat(40),NOW="2026-09-15T00:00:00.000Z";
const build=a.createBuildIdentity({branch:"ultimate-polish-v1",commitSha:COMMIT,applicationId:"ai.seven.app",versionName:"1.0.0",versionCode:101,artifactKind:"APK",artifactSha256:H("apk-redteam"),candidateSeal:H("candidate-redteam"),exportReceiptSeal:H("export-redteam")});
function dev(id,{api=35,width=360,env="EMULATOR"}={}){return a.createDeviceProof({environmentType:env,deviceIdentityHash:H("dev:"+id),manufacturer:"SevenLab",model:id,androidVersion:"15",apiLevel:api,widthDp:width,heightDp:800,density:2.75,proofHash:H("proof:"+id),sourceRef:"lab:"+id,capturedBy:"android-release-ci"})}
const d1=dev("compact"),d2=dev("wide",{width:412,env:"DEVICE_FARM"});
function cap(s,d){const x={build,device:d,scenario:s,captureMethod:d.environmentType==="DEVICE_FARM"?"device-farm":"adb-screencap",screenshotSha256:H(`shot:${s}:${d.model}`),width:1080,height:2400,locale:"en-US",direction:"ltr",theme:"night",reducedMotion:false,sourceRef:`android:${s}:${d.model}`};if(s==="chat-day")x.theme="day";if(s==="arabic-rtl"){x.locale="ar-IQ";x.direction="rtl"}if(s==="reduced-motion")x.reducedMotion=true;return a.createCaptureReceipt(x)}
const captures=a.SCENARIOS.map((s,i)=>cap(s,i%2?d2:d1)),cert=a.certify({build,devices:[d1,d2],captures});eq(cert.verdict,"PASS");
function att(d,method=d.environmentType==="DEVICE_FARM"?"device-farm-api":"adb-getprop"){return t.createDeviceAttestation({device:d,attestationMethod:method,buildFingerprintSha256:H("fp:"+d.model),captureSessionSha256:H("session:"+d.model),sourceEvidenceSha256:H("source:"+d.model),sourceRef:"attest:"+d.model,capturedBy:"android-release-ci",capturedAt:NOW})}
const at1=att(d1),at2=att(d2);ok(t.verifyDeviceAttestation(at1,d1));ok(t.verifyDeviceAttestation(at2,d2));throws(()=>t.createDeviceAttestation({device:d1,attestationMethod:"host-guess",buildFingerprintSha256:H("x"),captureSessionSha256:H("y"),sourceEvidenceSha256:H("z"),sourceRef:"x",capturedBy:"x",capturedAt:NOW}),/attestationMethod/);
function witness(c,i){const d=c.deviceSeal===d1.seal?d1:d2,aa=d===d1?at1:at2;return t.createCaptureWitness({build,device:d,capture:c,attestation:aa,sourceArtifactSha256:c.screenshotSha256,sourceArtifactRef:`artifact:${i}:${c.scenario}`,transportProofSha256:H(`transport:${i}`),byteSize:1000+i,capturedAt:NOW,expiresAt:"2026-09-15T12:00:00.000Z"})}
const witnesses=captures.map(witness);for(let i=0;i<witnesses.length;i++){const c=captures[i],d=c.deviceSeal===d1.seal?d1:d2,aa=d===d1?at1:at2;ok(t.verifyCaptureWitness(witnesses[i],{build,device:d,capture:c,attestation:aa}))}
let report=t.redTeamAndroidVisual({build,certification:cert,devices:[d1,d2],captures,attestations:[at1,at2],witnesses,evaluatedAt:"2026-09-15T01:00:00.000Z"});ok(t.verifyRedTeamReport(report,build,cert));eq(report.verdict,"PASS");eq(report.failures.length,0);eq(report.missing.length,0);
report=t.redTeamAndroidVisual({build,certification:cert,devices:[d1,d2],captures,attestations:[at1,at2],witnesses:witnesses.slice(1),evaluatedAt:"2026-09-15T01:00:00.000Z"});eq(report.verdict,"INCONCLUSIVE");ok(report.missing.some(x=>x.startsWith("capture-witness:")));
const stale=witnesses.map((w,i)=>i? w:t.createCaptureWitness({build,device:d1,capture:captures[0],attestation:at1,sourceArtifactSha256:captures[0].screenshotSha256,sourceArtifactRef:"artifact:stale",transportProofSha256:H("stale"),byteSize:1000,capturedAt:"2026-09-13T00:00:00.000Z",expiresAt:"2026-09-13T12:00:00.000Z"}));report=t.redTeamAndroidVisual({build,certification:cert,devices:[d1,d2],captures,attestations:[at1,at2],witnesses:stale,evaluatedAt:"2026-09-15T01:00:00.000Z"});eq(report.verdict,"BLOCK");ok(report.failures.some(x=>x.startsWith("stale-witness:")));
const dupRef=witnesses.map((w,i)=>{if(i!==1)return w;const c=captures[1],d=d2;return t.createCaptureWitness({build,device:d,capture:c,attestation:at2,sourceArtifactSha256:c.screenshotSha256,sourceArtifactRef:witnesses[0].sourceArtifactRef,transportProofSha256:H("dup-ref"),byteSize:1200,capturedAt:NOW,expiresAt:"2026-09-15T12:00:00.000Z"})});report=t.redTeamAndroidVisual({build,certification:cert,devices:[d1,d2],captures,attestations:[at1,at2],witnesses:dupRef,evaluatedAt:"2026-09-15T01:00:00.000Z"});eq(report.verdict,"BLOCK");ok(report.failures.includes("source-artifact-ref-reuse"));
const sameSession=t.createDeviceAttestation({device:d2,attestationMethod:"device-farm-api",buildFingerprintSha256:H("fp:2"),captureSessionSha256:at1.captureSessionSha256,sourceEvidenceSha256:H("src:2"),sourceRef:"attest:2",capturedBy:"ci",capturedAt:NOW});report=t.redTeamAndroidVisual({build,certification:cert,devices:[d1,d2],captures,attestations:[at1,sameSession],witnesses:[],evaluatedAt:"2026-09-15T01:00:00.000Z"});eq(report.verdict,"BLOCK");ok(report.failures.includes("cross-device-session-reuse"));
const p=dev("physical",{env:"PHYSICAL_DEVICE"});throws(()=>t.createDeviceAttestation({device:p,attestationMethod:"device-farm-api",buildFingerprintSha256:H("p1"),captureSessionSha256:H("p2"),sourceEvidenceSha256:H("p3"),sourceRef:"p",capturedBy:"p",capturedAt:NOW}),/physical device/);
report=t.redTeamAndroidVisual({build,certification:cert,devices:[d1,d2],captures,attestations:[at1,at2],witnesses,evaluatedAt:"2026-09-15T01:00:00.000Z",requirePhysical:true});eq(report.verdict,"INCONCLUSIVE");ok(report.missing.includes("physical-device-required"));
const tampered={...report,verdict:"PASS"};eq(t.verifyRedTeamReport(tampered,build,cert),false);
console.log(`Visual Red Team: PASS (${n} assertions; anti-replay, anti-evidence-laundering, freshness and device-attestation guards)`);
