const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {build}=require('./build-release.cjs');
(async()=>{
 const built=build(),html=fs.readFileSync(built.output,'utf8'),dist=path.dirname(built.output),traffic=[];
 const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://127.0.0.1').pathname;if(p!=='/'&&p!=='/index.html'){const f=path.resolve(dist,'.'+p);if(!f.startsWith(path.resolve(dist)+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end('not found')}res.setHeader('Content-Type',f.endsWith('.js')||f.endsWith('.mjs')?'text/javascript; charset=utf-8':f.endsWith('.css')?'text/css; charset=utf-8':'application/octet-stream');return fs.createReadStream(f).pipe(res)}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});
 try{const c=await browser.newContext({viewport:{width:390,height:844}});await c.addInitScript(()=>localStorage.setItem('user_name_asked','1'));await c.route('**/*',x=>x.request().url().startsWith(origin)?x.continue():x.abort());const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',x=>{if(x.url().includes('/workspaces/'))traffic.push({url:x.url(),status:x.status()})});p.on('requestfailed',x=>{if(x.url().includes('/workspaces/'))traffic.push({url:x.url(),failed:x.failure()?.errorText||'failed'})});await p.goto(origin,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.SevenBetaUI?.state.ready);assert.equal(await p.evaluate(()=>!!window.SevenWorkspaces),false);await p.evaluate(()=>document.querySelector('.seven-beta-status').click());await p.waitForTimeout(750);const state=await p.evaluate(()=>({hub:!!window.SevenWorkspaces,launcher:!!document.querySelector('.seven-ws-launcher'),scripts:[...document.scripts].map(x=>x.src).filter(x=>x.includes('/workspaces/')),styles:[...document.querySelectorAll('link[rel=stylesheet]')].map(x=>x.href).filter(x=>x.includes('/workspaces/'))}));assert.equal(traffic.some(x=>x.url.endsWith('/workspaces/hub.js')&&x.status===200),true,'hub request failed: '+JSON.stringify({traffic,errors,state}));assert.deepEqual(errors,[],'workspace loader page error: '+JSON.stringify({traffic,state,errors}));assert.equal(state.hub,true,'hub did not register: '+JSON.stringify({traffic,errors,state}));assert.equal(state.launcher,true,'launcher did not open: '+JSON.stringify({traffic,errors,state}));await c.close();console.log('workspace lazy loader: PASS');}finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exit(1)});
