const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {build}=require('./build-release.cjs');
(async()=>{
 const built=build(),html=fs.readFileSync(built.output,'utf8'),dist=path.dirname(built.output);
 for(const name of ['hub.js','hub.css','coding.js','rpg.js'])assert.ok(fs.existsSync(path.join(dist,'workspaces',name)),'missing lazy workspace asset '+name);
 assert.equal(built.workspaceLoadMode,'lazy-local');assert.ok(built.workspaceBytes>0);
 const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1').pathname;if(pathname!=='/'&&pathname!=='/index.html'){const file=path.resolve(dist,'.'+pathname);if(!file.startsWith(path.resolve(dist)+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end('not found')}res.setHeader('Content-Type',file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'application/octet-stream');return fs.createReadStream(file).pipe(res)}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});
 try{
  const c=await browser.newContext({viewport:{width:390,height:844}});await c.addInitScript(()=>localStorage.setItem('user_name_asked','1'));await c.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.SevenBetaUI?.state.ready&&window.SevenAurora);
  assert.deepEqual(await p.evaluate(()=>({hub:!!window.SevenWorkspaces,css:!!document.getElementById('seven-workspaces-style'),coding:!!window.SevenCodingWorkspace,rpg:!!window.SevenRpgWorkspace})),{hub:false,css:false,coding:false,rpg:false},'workspaces must not load during normal boot');
  await p.click('.seven-beta-status');await p.waitForFunction(()=>window.SevenWorkspaces&&document.querySelector('.seven-ws-launcher'));assert.equal(await p.evaluate(()=>SevenWorkspaces.active()),'chat');assert.equal(await p.evaluate(()=>!!document.getElementById('seven-workspaces-style')),true);
  await p.click('[data-ws="coding"]');await p.waitForFunction(()=>window.SevenCodingWorkspace&&SevenWorkspaces.active()==='coding'&&document.querySelector('.seven-workspace-root:not([hidden])'));
  let coding=await p.evaluate(()=>({workspace:document.documentElement.dataset.sevenWorkspace,root:document.querySelector('.seven-workspace-root').dataset.sevenWorkspace,chatHidden:document.getElementById('chat').hidden,inputHidden:document.querySelector('.input-area').hidden,aurora:SevenAurora.getState(),rpgLoaded:!!window.SevenRpgWorkspace,boundary:document.querySelector('[data-code-notice]').textContent}));
  assert.equal(coding.workspace,'coding');assert.equal(coding.root,'coding');assert.equal(coding.chatHidden,true);assert.equal(coding.inputHidden,true);assert.equal(coding.aurora,'coding');assert.equal(coding.rpgLoaded,false);assert.match(coding.boundary,/Direct device file writes/);
  const mapped=await p.evaluate(()=>{const m=SevenCodingWorkspace.bindProject([{path:'src/main.js',content:'console.log(1)'},{path:'README.md',content:'# Demo'}]);return{version:m.version,count:m.files.length,paths:m.files.map(x=>x.path),fp:m.files[0].fingerprint,rows:document.querySelectorAll('[data-code-files] .seven-ws-row').length,preview:document.querySelector('[data-code-preview]').textContent}});
  assert.equal(mapped.version,1);assert.equal(mapped.count,2);assert.deepEqual(mapped.paths,['src/main.js','README.md']);assert.ok(mapped.fp);assert.equal(mapped.rows,2);assert.equal(mapped.preview,'console.log(1)');
  await p.evaluate(()=>{window.__wsCalls={send:[],stop:0,retry:0};window.sendMessage=async function(){__wsCalls.send.push(document.getElementById('userInput').value);const m=document.createElement('div');m.className='message assistant';m.innerHTML='<div class="bubble">real agent reply</div>';document.getElementById('chat').appendChild(m)};window.stopGeneration=()=>__wsCalls.stop++;window.regenerateLastReply=()=>__wsCalls.retry++});
  await p.fill('[data-code-task]','inspect this project exactly');await p.click('[data-code-run]');await p.waitForFunction(()=>window.__wsCalls.send.length===1);assert.deepEqual(await p.evaluate(()=>__wsCalls.send),['inspect this project exactly']);await p.click('[data-code-retry]');assert.equal(await p.evaluate(()=>__wsCalls.retry),1);await p.evaluate(()=>document.documentElement.dataset.sevenBusy='1');await p.waitForFunction(()=>!document.querySelector('[data-code-stop]').disabled);await p.click('[data-code-stop]');assert.equal(await p.evaluate(()=>__wsCalls.stop),1);await p.waitForFunction(()=>document.querySelector('[data-code-output]').textContent.includes('real agent reply'));
  await p.evaluate(()=>SevenWorkspaces.openLauncher());await p.click('[data-ws="rpg"]');await p.waitForFunction(()=>window.SevenRpgWorkspace&&SevenWorkspaces.active()==='rpg');
  const rpg=await p.evaluate(()=>{SevenRpgWorkspace.loadWork({id:'demo-series',title:'Demo Series',continuity:'anime',sources:[{id:'official-ep1',authority:'A0'}],beats:[{id:'ep1-start',sourceRefs:['official-ep1'],anchors:['meet'],requiredFacts:['hero-arrives'],forbiddenChanges:['rewrite-origin']}],titleRules:{episode:'Case'}});SevenRpgWorkspace.loadCanon({id:'demo-work',version:'1.0.0',defaultContinuity:'anime',continuities:[{id:'anime'}],sources:[{id:'official',authority:'A0'}],entities:[{id:'hero'}],facts:[{id:'arrival',availableAt:1,sources:['official']}],anchors:[{id:'meeting',strength:'strong',continuity:'anime'}],invariants:[]},{continuity:'anime',position:1});const c=SevenRpgWorkspace.currentContract(),blocked=SevenRpgWorkspace.commitVerifiedBeat({beatId:'ep1-start',verified:false,playerAction:'enters',playerActionSource:'user'}),ok=SevenRpgWorkspace.commitVerifiedBeat({beatId:'ep1-start',verified:true,playerAction:'enters',playerActionSource:'user'}),title=SevenRpgWorkspace.recordTitle('episode',{number:1,name:'Arrival'});return{titleText:document.querySelector('[data-rpg-title]').textContent,contract:c.status,beat:c.expectedBeatId,blocked,okStatus:ok.status,beatIndex:ok.session.beatIndex,title:title.title,aurora:SevenAurora.getState(),timeline:document.querySelectorAll('[data-rpg-timeline] .seven-ws-event').length,canon:document.querySelector('[data-rpg-canon]').textContent,boundary:document.querySelector('[data-rpg-notice]').textContent}});
  assert.equal(rpg.titleText,'Demo Series');assert.equal(rpg.contract,'CANON');assert.equal(rpg.beat,'ep1-start');assert.equal(rpg.blocked.status,'BLOCKED');assert.equal(rpg.blocked.reason,'verification-required');assert.equal(rpg.okStatus,'CANON');assert.equal(rpg.beatIndex,0);assert.equal(rpg.title,'Case 1 — Arrival');assert.equal(rpg.aurora,'rpg');assert.ok(rpg.timeline>=1);assert.match(rpg.canon,/Chronology/);assert.match(rpg.boundary,/does not auto-commit canon/);
  const unsafe=await p.evaluate(()=>SevenRpgWorkspace.applyVerifiedDelta({position:2},{verified:false,id:'x'}));assert.equal(unsafe.status,'BLOCKED');assert.equal(unsafe.reason,'verification-required');
  await p.setViewportSize({width:360,height:780});let mobile=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));assert.ok(mobile.sw<=mobile.cw+2,JSON.stringify(mobile));
  await p.evaluate(()=>SevenWorkspaces.close());assert.deepEqual(await p.evaluate(()=>({active:SevenWorkspaces.active(),chat:document.getElementById('chat').hidden,input:document.querySelector('.input-area').hidden,root:document.querySelector('.seven-workspace-root').hidden,aurora:SevenAurora.getState()})),{active:'chat',chat:false,input:false,root:true,aurora:'idle'});assert.deepEqual(errors,[]);await c.close();
  const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await reduced.addInitScript(()=>localStorage.setItem('user_name_asked','1'));await reduced.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());const rp=await reduced.newPage();await rp.goto(origin,{waitUntil:'domcontentloaded'});await rp.click('.seven-beta-status');await rp.waitForFunction(()=>window.SevenWorkspaces);await rp.click('[data-ws="coding"]');await rp.waitForFunction(()=>window.SevenCodingWorkspace);const motion=await rp.evaluate(()=>getComputedStyle(document.querySelector('.seven-ws-choice')||document.createElement('div')).transitionDuration);assert.ok(motion==='0s'||parseFloat(motion)<=.001);await reduced.close();
  console.log('workspace UI browser tests: PASS');
 }finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exit(1)});
