"use strict";
const assert=require("assert");
const a=require("./acquisition-fabric.cjs");
const d=require("./acquisition-durable-fabric.cjs");
const canon=require("./canon-fabric-final.cjs");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(x,y,m)=>{assert.strictEqual(x,y,m);n++},throws=(f,r,m)=>{assert.throws(f,r,m);n++};const H=x=>a.sha(x),T="2026-09-15T10:00:00Z";
function provider(over={}){return a.createAcquisitionProviderContract({providerId:"web",revision:"1",kinds:["SEARCH_FETCH","CANON_SOURCE"],realms:["OPEN_WEB"],mediaTypes:["text/html"],maxBytes:1000000,network:true,supportsCancellation:true,requestSchemaHash:H("req-v1"),responseSchemaHash:H("resp-v1"),...over})}
function request(over={}){return a.createAcquisitionRequest({taskId:"research-1",kind:"SEARCH_FETCH",principalId:"user-1",scopeId:"project-1",target:"https://example.test/doc",realm:"OPEN_WEB",sensitivity:"PUBLIC",expectedMediaTypes:["text/html"],maxBytes:100000,allowNetwork:true,createdAt:T,...over})}
function terminal(req,p,status="COMPLETE"){let at=a.createAcquisitionAttempt(req);at=a.transitionAttempt(at,"STARTED",{at:"2026-09-15T10:00:01Z"});at=a.transitionAttempt(at,status==="COMPLETE"?"COMPLETE":"FAILED",{at:"2026-09-15T10:00:02Z"});const input={request:req,provider:p,attempt:at,status,retrievedAt:"2026-09-15T10:00:02Z"};if(status==="COMPLETE")Object.assign(input,{artifactSha256:H("artifact"),contentHash:H("content"),byteLength:200,mediaType:"text/html",sourceRef:req.target,metadataHash:H("metadata")});return {at,receipt:a.createAcquisitionReceipt(input)}}
const p=provider(),r=request();let at=a.createAcquisitionAttempt(r);
let cp=d.createAcquisitionCheckpoint({request:r,provider:p,attempt:at,committedAt:T});ok(d.verifyAcquisitionCheckpoint(cp,{request:r,provider:p}));eq(cp.revision,0);eq(cp.state.receiptSeal,null);eq(cp.rebuildable,false);eq(cp.state.grantsAuthority,false);let recovery=d.recoveryDecision(cp,{request:r,provider:p});eq(recovery.action,"START");
let journal=d.createAcquisitionJournal({principalId:"user-1",scopeId:"project-1"});ok(d.verifyAcquisitionJournal(journal));journal=d.appendAcquisitionJournal(journal,{checkpoint:cp,at:T});ok(d.verifyAcquisitionJournal(journal));eq(journal.revision,1);

at=a.transitionAttempt(at,"STARTED",{at:"2026-09-15T10:00:01Z"});const started=d.createAcquisitionCheckpoint({request:r,provider:p,attempt:at,previousCheckpoint:cp,committedAt:"2026-09-15T10:00:01Z"});ok(d.verifyAcquisitionCheckpoint(started,{request:r,provider:p}));eq(started.revision,1);recovery=d.recoveryDecision(started,{request:r,provider:p});eq(recovery.action,"RECONCILE_ATTEMPT");ok(recovery.reasons.includes("started-attempt-has-no-terminal-receipt"));
throws(()=>d.createAcquisitionCheckpoint({request:r,provider:p,attempt:a.createAcquisitionAttempt(r),previousCheckpoint:started,committedAt:"2026-09-15T10:00:02Z"}),/revision regression/);

let cancelAt=a.transitionAttempt(at,"CANCEL_REQUESTED",{at:"2026-09-15T10:00:03Z"});const cancelCp=d.createAcquisitionCheckpoint({request:r,provider:p,attempt:cancelAt,previousCheckpoint:started,committedAt:"2026-09-15T10:00:03Z"});recovery=d.recoveryDecision(cancelCp,{request:r,provider:p});eq(recovery.action,"FINISH_CANCEL");cancelAt=a.transitionAttempt(cancelAt,"CANCELLED",{at:"2026-09-15T10:00:04Z"});const cancelReceipt=a.createAcquisitionReceipt({request:r,provider:p,attempt:cancelAt,status:"CANCELLED",retrievedAt:"2026-09-15T10:00:04Z"});const cancelled=d.createAcquisitionCheckpoint({request:r,provider:p,attempt:cancelAt,receipt:cancelReceipt,previousCheckpoint:cancelCp,committedAt:"2026-09-15T10:00:04Z"});recovery=d.recoveryDecision(cancelled,{request:r,provider:p});eq(recovery.action,"DONE");throws(()=>d.createAcquisitionCheckpoint({request:r,provider:p,attempt:at,previousCheckpoint:cancelled,committedAt:"2026-09-15T10:00:05Z"}),/revision regression|terminal acquisition attempt/);

const r2=request({taskId:"research-2",target:"https://example.test/doc2"});const done=terminal(r2,p);let complete=d.createAcquisitionCheckpoint({request:r2,provider:p,attempt:done.at,receipt:done.receipt,committedAt:"2026-09-15T10:00:02Z"});ok(d.verifyAcquisitionCheckpoint(complete,{request:r2,provider:p}));eq(complete.state.receiptStatus,"COMPLETE");recovery=d.recoveryDecision(complete,{request:r2,provider:p,requiredAdmissionKinds:["RESEARCH"]});eq(recovery.action,"ADMIT");eq(recovery.missing[0],"RESEARCH");
const admission=a.admitResearchSource({receipt:done.receipt,sourceId:"doc2",versionKey:"etag-1",title:"Doc 2"});ok(a.verifyResearchAdmission(admission));const admitted=d.createAcquisitionCheckpoint({request:r2,provider:p,attempt:done.at,receipt:done.receipt,admissions:[admission],previousCheckpoint:complete,committedAt:"2026-09-15T10:00:03Z"});ok(d.verifyAcquisitionCheckpoint(admitted,{request:r2,provider:p}));eq(admitted.revision,1);recovery=d.recoveryDecision(admitted,{request:r2,provider:p,requiredAdmissionKinds:["RESEARCH"]});eq(recovery.action,"DONE");eq(recovery.reasons.length,0);
throws(()=>d.createAcquisitionCheckpoint({request:r2,provider:p,attempt:done.at,receipt:done.receipt,admissions:[],previousCheckpoint:admitted,committedAt:"2026-09-15T10:00:04Z"}),/admission cannot disappear/);
throws(()=>d.createAcquisitionCheckpoint({request:r2,provider:p,attempt:done.at,previousCheckpoint:complete,committedAt:"2026-09-15T10:00:04Z"}),/terminal acquisition attempt requires receipt|receipt cannot drift/);

let fresh=d.assessAcquisitionFreshness(admitted,{request:r2,provider:p});eq(fresh.status,"FRESH");const p2=provider({revision:"2",requestSchemaHash:H("req-v2")});fresh=d.assessAcquisitionFreshness(admitted,{request:r2,provider:p2});eq(fresh.status,"BLOCK");recovery=d.recoveryDecision(admitted,{request:r2,provider:p2});eq(recovery.action,"HALT");ok(recovery.reasons.includes("invalid-acquisition-checkpoint"));
const forgedCp={...admitted,state:{...admitted.state,attemptState:"FAILED"}};eq(d.verifyAcquisitionCheckpoint(forgedCp,{request:r2,provider:p}),false);

const cache=d.createAdmissionCacheEntry({receipt:done.receipt,admission,transformHash:H("admission-index-v1"),producerHash:H("seven-acquisition-cache-v1"),expiresAt:"2026-09-16T10:00:02Z"});ok(d.verifyAdmissionCacheEntry(cache,{receipt:done.receipt,admission}));eq(cache.authoritative,false);eq(cache.grantsAuthority,false);eq(cache.payload.admissionSeal,admission.seal);eq(cache.payload.contentHash,done.receipt.contentHash);let cacheState=d.evaluateAdmissionCacheEntry(cache,{receipt:done.receipt,admission,currentSourceVersions:{doc2:admission.sourceVersionId},now:Date.parse("2026-09-15T11:00:00Z")});eq(cacheState.status,"HIT");eq(cacheState.payload.versionId,admission.sourceVersionId);cacheState=d.evaluateAdmissionCacheEntry(cache,{receipt:done.receipt,admission,currentSourceVersions:{doc2:"new-version"},now:Date.parse("2026-09-15T11:00:00Z")});eq(cacheState.status,"STALE");eq(cacheState.payload,null);cacheState=d.evaluateAdmissionCacheEntry(cache,{receipt:done.receipt,admission,currentSourceVersions:{doc2:admission.sourceVersionId},now:Date.parse("2026-09-17T10:00:00Z")});eq(cacheState.status,"STALE");
const forgedCache={...cache,payload:{...cache.payload,contentHash:H("fake")}};eq(d.verifyAdmissionCacheEntry(forgedCache,{receipt:done.receipt,admission}),false);

const sensitive=request({taskId:"sensitive",target:"https://example.test/private",sensitivity:"SENSITIVE"});const sensitiveDone=terminal(sensitive,p);const sensitiveAdmission=a.admitResearchSource({receipt:sensitiveDone.receipt,sourceId:"private-doc",versionKey:"v1"});throws(()=>d.createAdmissionCacheEntry({receipt:sensitiveDone.receipt,admission:sensitiveAdmission,transformHash:H("t"),producerHash:H("p")}),/sensitive acquisition/);

const canonWork=canon.createCanonWork({id:"work",version:"1",title:"Work"}),continuity=canon.createContinuity(canonWork,{id:"primary",kind:"PRIMARY",label:"Primary"});const cr=request({taskId:"canon",kind:"CANON_SOURCE",target:"https://example.test/canon"});const cd=terminal(cr,p);const ca=a.admitCanonSource({receipt:cd.receipt,continuity,sourceId:"canon-source",version:"1"});const cc=d.createAdmissionCacheEntry({receipt:cd.receipt,admission:ca,transformHash:H("canon-index"),producerHash:H("producer")});ok(d.verifyAdmissionCacheEntry(cc,{receipt:cd.receipt,admission:ca}));eq(cc.payload.kind,"CANON");eq(cc.authoritative,false);

const wrongJournal=d.createAcquisitionJournal({principalId:"other",scopeId:"project-1"});throws(()=>d.appendAcquisitionJournal(wrongJournal,{checkpoint:admitted}),/identity mismatch/);
console.log(`Acquisition Durable Fabric: PASS (${n} assertions)`);
