"use strict";
const assert=require("assert");
const a=require("./acquisition-fabric.cjs");
const canon=require("./canon-fabric-final.cjs");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(x,y,m)=>{assert.strictEqual(x,y,m);n++},throws=(f,r,m)=>{assert.throws(f,r,m);n++};const H=x=>a.sha(x),T="2026-09-15T02:30:00Z";
function provider(over={}){return a.createAcquisitionProviderContract({providerId:"web-fetch",revision:"1",kinds:["SEARCH_FETCH","CANON_SOURCE"],realms:["OPEN_WEB"],mediaTypes:["text/html","image/png"],maxBytes:2_000_000,network:true,supportsCancellation:true,metadataPolicy:"MINIMIZE",requestSchemaHash:H("req"),responseSchemaHash:H("resp"),...over})}
function request(over={}){return a.createAcquisitionRequest({taskId:"task-1",kind:"SEARCH_FETCH",principalId:"user-1",scopeId:"project-1",target:"https://example.test/doc",realm:"OPEN_WEB",sensitivity:"PUBLIC",expectedMediaTypes:["text/html"],maxBytes:500000,allowNetwork:true,createdAt:T,...over})}
function completed(req=request(),p=provider(),over={}){let at=a.createAcquisitionAttempt(req);at=a.transitionAttempt(at,"STARTED",{at:T});at=a.transitionAttempt(at,"COMPLETE",{at:"2026-09-15T02:31:00Z"});const receipt=a.createAcquisitionReceipt({request:req,provider:p,attempt:at,status:"COMPLETE",artifactSha256:H("artifact"),contentHash:H("content"),byteLength:12345,mediaType:req.expectedMediaTypes[0],sourceRef:req.target,metadataHash:H("metadata"),retrievedAt:"2026-09-15T02:31:00Z",...over});return {at,receipt}}
const p=provider();ok(a.verifyAcquisitionProviderContract(p));eq(p.network,true);eq(p.kinds.includes("SEARCH_FETCH"),true);
throws(()=>a.createAcquisitionProviderContract({providerId:"x",revision:"1",kinds:[],realms:["X"],mediaTypes:["x"],maxBytes:1,requestSchemaHash:H("x"),responseSchemaHash:H("y")}),/kinds required/);
throws(()=>a.createAcquisitionProviderContract({providerId:"x",revision:"1",kinds:["SEARCH_FETCH"],realms:["X"],mediaTypes:["x"],maxBytes:1,requestSchemaHash:"bad",responseSchemaHash:H("y")}),/sha256/);
const r=request();ok(a.verifyAcquisitionRequest(r));eq(a.qualifyProvider(r,p).eligible,true);eq(r.ambient,false);eq(r.principalId,"user-1");
throws(()=>request({ambient:true}),/ambient/);throws(()=>request({kind:"FILE_IMPORT",allowNetwork:false,realm:"LOCAL",target:"content://doc",userAuthorizationRef:""}),/userAuthorizationRef/);
const oversizedReq=request({maxBytes:3_000_000});let q=a.qualifyProvider(oversizedReq,p);eq(q.eligible,false);ok(q.reasons.includes("provider-byte-limit"));
const noNetwork=request({allowNetwork:false});q=a.qualifyProvider(noNetwork,p);eq(q.eligible,false);ok(q.reasons.includes("network-not-authorized"));
const badRealm=request({realm:"PROJECT"});q=a.qualifyProvider(badRealm,p);eq(q.eligible,false);ok(q.reasons.includes("realm-unsupported"));
const badMedia=request({expectedMediaTypes:["application/pdf"]});q=a.qualifyProvider(badMedia,p);eq(q.eligible,false);ok(q.reasons.includes("media-type-unsupported"));
let attempt=a.createAcquisitionAttempt(r);ok(a.verifyAcquisitionAttempt(attempt,r));eq(attempt.state,"PLANNED");attempt=a.transitionAttempt(attempt,"STARTED",{at:T});eq(attempt.state,"STARTED");attempt=a.transitionAttempt(attempt,"CANCEL_REQUESTED",{at:"2026-09-15T02:30:10Z"});eq(attempt.state,"CANCEL_REQUESTED");throws(()=>a.transitionAttempt(attempt,"COMPLETE",{at:T}),/invalid acquisition transition/);attempt=a.transitionAttempt(attempt,"CANCELLED",{at:"2026-09-15T02:30:20Z"});eq(attempt.state,"CANCELLED");ok(a.verifyAcquisitionAttempt(attempt,r));
const cancelReceipt=a.createAcquisitionReceipt({request:r,provider:p,attempt,status:"CANCELLED",retrievedAt:"2026-09-15T02:30:20Z"});ok(a.verifyAcquisitionReceipt(cancelReceipt,{request:r,provider:p,attempt}));eq(cancelReceipt.grantsAuthority,false);eq(cancelReceipt.untrustedContent,true);
throws(()=>a.createAcquisitionReceipt({request:r,provider:p,attempt,status:"COMPLETE",artifactSha256:H("a"),contentHash:H("c"),byteLength:1,mediaType:"text/html",sourceRef:r.target,retrievedAt:T}),/COMPLETE attempt/);
const {at,receipt}=completed(r,p);ok(a.verifyAcquisitionReceipt(receipt,{request:r,provider:p,attempt:at}));eq(receipt.status,"COMPLETE");eq(receipt.metadataStripped,true);eq(receipt.grantsAuthority,false);eq(receipt.untrustedContent,true);
const receiptTamper={...receipt,grantsAuthority:true};eq(a.verifyAcquisitionReceipt(receiptTamper),false);
throws(()=>completed(r,p,{byteLength:900000}),/byte limit/);throws(()=>completed(r,p,{mediaType:"image/png"}),/outside contract/);
const forgedAt={...at,state:"FAILED"};eq(a.verifyAcquisitionAttempt(forgedAt,r),false);
const admission=a.admitResearchSource({receipt,sourceId:"source-doc",versionKey:"etag-1",title:"Doc"});ok(a.verifyResearchAdmission(admission));eq(admission.principalId,"user-1");eq(admission.source.principalId,"user-1");eq(admission.source.scopeId,"project-1");eq(admission.version.contentHash,receipt.contentHash);eq(admission.version.provenanceHash,receipt.seal);eq(admission.grantsAuthority,false);
const admissionTamper={...admission,grantsAuthority:true};eq(a.verifyResearchAdmission(admissionTamper),false);
const localProvider=provider({providerId:"local-import",kinds:["FILE_IMPORT","VISUAL_CAPTURE"],realms:["LOCAL"],mediaTypes:["image/png"],maxBytes:4_000_000,network:false});const vr=request({taskId:"visual-1",kind:"VISUAL_CAPTURE",target:"content://image/1",realm:"LOCAL",sensitivity:"PRIVATE",expectedMediaTypes:["image/png"],maxBytes:1_000_000,allowNetwork:false,userAuthorizationRef:"saf-grant-1"});eq(a.qualifyProvider(vr,localProvider).eligible,true);const visualDone=completed(vr,localProvider,{artifactSha256:H("visual-artifact"),contentHash:H("visual-content"),byteLength:120000,mediaType:"image/png",sourceRef:"content://image/1",metadataHash:H("visual-metadata")});const visualAdmission=a.admitVisualSource({receipt:visualDone.receipt,sourceId:"visual-source-1",width:1080,height:1920});ok(a.verifyVisualAdmission(visualAdmission));eq(visualAdmission.source.ambient,false);eq(visualAdmission.source.principal,"user-1");eq(visualAdmission.version.contentHash,visualDone.receipt.contentHash);eq(visualAdmission.grantsAuthority,false);
const sensitiveReq=request({taskId:"visual-2",kind:"VISUAL_CAPTURE",target:"content://image/2",realm:"LOCAL",sensitivity:"SENSITIVE",expectedMediaTypes:["image/png"],maxBytes:1_000_000,allowNetwork:false,userAuthorizationRef:"saf-grant-2"});const sensitiveDone=completed(sensitiveReq,localProvider,{artifactSha256:H("v2a"),contentHash:H("v2c"),byteLength:10,mediaType:"image/png",sourceRef:"content://image/2",metadataHash:H("v2m")});const sensitiveAdmission=a.admitVisualSource({receipt:sensitiveDone.receipt,sourceId:"visual-source-2",width:10,height:20});eq(sensitiveAdmission.source.sensitivity,"SENSITIVE");
throws(()=>a.admitVisualSource({receipt,sourceId:"x",width:1,height:1}),/cannot create visual source/);
const work=canon.createCanonWork({id:"work-1",version:"1",title:"Work"});const continuity=canon.createContinuity(work,{id:"primary",kind:"PRIMARY",label:"Primary"});const canonReq=request({taskId:"canon-1",kind:"CANON_SOURCE",target:"https://official.test/episode-1",realm:"OPEN_WEB",expectedMediaTypes:["text/html"],maxBytes:500000});const canonDone=completed(canonReq,p,{artifactSha256:H("canon-artifact"),contentHash:H("canon-content"),byteLength:5000,mediaType:"text/html",sourceRef:"https://official.test/episode-1",metadataHash:H("canon-meta")});const canonAdmission=a.admitCanonSource({receipt:canonDone.receipt,continuity,sourceId:"episode-1",sourceKind:"PRIMARY",version:"1",evidence:{id:"ev-1",locator:{section:"scene-1"},excerptHash:H("exact-observation"),claimScope:"event-order"}});ok(a.verifyCanonAdmission(canonAdmission));eq(canonAdmission.source.continuityId,continuity.id);eq(canonAdmission.source.contentHash,canonDone.receipt.contentHash);eq(canonAdmission.evidence.sourceVersionId,canonAdmission.source.id);eq(canonAdmission.grantsCanonFactAuthority,false);
const canonNoEvidence=a.admitCanonSource({receipt:canonDone.receipt,continuity,sourceId:"episode-1b",sourceKind:"PRIMARY",version:"1"});ok(a.verifyCanonAdmission(canonNoEvidence));eq(canonNoEvidence.evidence,null);eq(canonNoEvidence.grantsCanonFactAuthority,false);
const badCanon={...canonAdmission,grantsCanonFactAuthority:true};eq(a.verifyCanonAdmission(badCanon),false);
const failedReq=request({taskId:"fail-1"});let failedAt=a.createAcquisitionAttempt(failedReq);failedAt=a.transitionAttempt(failedAt,"STARTED",{at:T});failedAt=a.transitionAttempt(failedAt,"FAILED",{at:"2026-09-15T02:31:00Z"});const failedReceipt=a.createAcquisitionReceipt({request:failedReq,provider:p,attempt:failedAt,status:"FAILED",retrievedAt:"2026-09-15T02:31:00Z"});ok(a.verifyAcquisitionReceipt(failedReceipt));throws(()=>a.admitResearchSource({receipt:failedReceipt,sourceId:"x",versionKey:"1"}),/COMPLETE/);
console.log(`Acquisition Fabric: PASS (${n} assertions)`);
