"use strict";
const assert=require("assert/strict"),canon=require("./canon-fabric-passb.cjs"),titles=require("./title-fabric-passb.cjs"),rpg=require("./rpg-story-fabric-final.cjs");
let n=0;const pass=(name,fn)=>{fn();n++;console.log("PASS",name)}, H=x=>String(x).repeat(64);
const work=canon.createCanonWork({id:"w",version:"1",title:"Work"}),main=canon.createContinuity(work,{id:"main"}),src=canon.createSourceVersion(main,{id:"sv1",sourceIdentity:"episode-1",version:"1",sourceKind:"PRIMARY",contentHash:H("a")}),ev=canon.createEvidence(src,{id:"evidence-1",locator:{page:1,lineStart:2},excerptHash:H("b")}),fact=canon.createCanonFact(main,{id:"fact-1",subjectId:"door",predicate:"location",value:"tower",status:"SUPPORTED_CANON",evidenceRefs:[ev.id]}),derived=canon.createCanonFact(main,{id:"derived-1",subjectId:"door",predicate:"reachable",value:true,status:"SUPPORTED_DERIVATION",derivation:{inputFactIds:[fact.id],rule:"path"}}),event1=canon.createCanonEvent(main,{id:"event-1",factRefs:[fact.id],evidenceRefs:[ev.id]}),event2=canon.createCanonEvent(main,{id:"event-2",factRefs:[fact.id]}),rel=canon.createEventRelation({fromEventId:event1.id,toEventId:event2.id,type:"BEFORE"}),anchor1=canon.createAnchor(main,{id:"anchor-1",kind:"FACT",targetId:fact.id,hard:true}),anchor2=canon.createAnchor(main,{id:"anchor-2",kind:"EVENT",targetId:event2.id,hard:true,dependsOn:[anchor1.id]});
const corpus=canon.createCorpus({id:"corpus",work,continuity:main,sources:[src],evidence:[ev],facts:[fact,derived],events:[event1,event2],relations:[rel],anchors:[anchor1,anchor2],knowledge:[]});
const freshHeads={"episode-1":src.sourceVersionHash}, staleHeads={"episode-1":H("f")};
pass("PassB corpus verifies",()=>assert.equal(canon.verifyCorpus(corpus).valid,true));
pass("source revision drift is detected",()=>assert.equal(canon.auditSourceFreshness(corpus,staleHeads).status,"STALE"));
pass("stale source invalidates directly supported fact",()=>assert.ok(canon.auditSourceFreshness(corpus,staleHeads).invalidatedFactIds.includes(fact.id)));
pass("source invalidation propagates through derivation lineage",()=>assert.ok(canon.auditSourceFreshness(corpus,staleHeads).invalidatedFactIds.includes(derived.id)));
const coverage=canon.createCoverageContract({id:"coverage",continuityId:main.id,requiredFactIds:[fact.id],requiredAnchorIds:[anchor1.id]});
pass("fresh source-backed coverage passes",()=>assert.equal(canon.evaluateCoverage(corpus,coverage,{activeSourceHeads:freshHeads}).status,"PASS"));
pass("stale source-backed coverage becomes CANON_GAP",()=>assert.equal(canon.evaluateCoverage(corpus,coverage,{activeSourceHeads:staleHeads}).status,"CANON_GAP"));
pass("unknown source head can fail closed",()=>assert.equal(canon.evaluateCoverage(corpus,coverage,{activeSourceHeads:{},requireCompleteSourceHeads:true}).status,"CANON_GAP"));
pass("anchor dependency cycles are rejected",()=>{const cyc1=canon.createAnchor(main,{id:"c1",kind:"FACT",targetId:fact.id,dependsOn:["c2"]}),cyc2=canon.createAnchor(main,{id:"c2",kind:"EVENT",targetId:event2.id,dependsOn:["c1"]});assert.throws(()=>canon.createCorpus({id:"bad",work,continuity:main,sources:[src],evidence:[ev],facts:[fact],events:[event1,event2],relations:[rel],anchors:[cyc1,cyc2]}),/anchor-cycle/)});
const scene=canon.createSceneContract(corpus,{id:"scene",currentEventId:event2.id,requiredFactIds:[fact.id],protectedAnchorIds:[anchor1.id],activeSourceHeads:freshHeads,requireCompleteSourceHeads:true});
pass("scene binds source-head fingerprint",()=>assert.ok(scene.sourceHeadFingerprint));
pass("scene fails after source-head drift",()=>assert.equal(canon.verifySceneContract(corpus,scene,{activeSourceHeads:staleHeads,requireCompleteSourceHeads:true}).valid,false));
pass("stale scene blocks insertion",()=>assert.equal(canon.analyzeInsertion(corpus,scene,{activeSourceHeads:staleHeads,requireCompleteSourceHeads:true}).status,"BLOCKED"));
pass("fresh hard-anchor edit requires divergence",()=>assert.equal(canon.analyzeInsertion(corpus,scene,{activeSourceHeads:freshHeads,touchedAnchorIds:[anchor1.id]}).status,"DIVERGENCE_REQUIRED"));
const world=rpg.createWorldDefinition({id:"world",version:"1",principal:"user",locations:["hall"],relationshipDimensions:[],invariants:["PLAYER_AGENCY_LOCK"],entities:[{id:"player",kind:"CHARACTER",isPlayer:true,locationId:"hall",resources:{}}]}),session=rpg.createWorldSession(world,{id:"session"}),action=rpg.createPlayerAction(world,session,{actorId:"player",action:"wait",args:{},source:"USER"});
pass("player-caused divergence cannot use a loose hash",()=>assert.throws(()=>canon.createDivergenceEvent(corpus,{id:"div-bad",baseEventId:event2.id,invalidatedAnchorIds:[anchor1.id],reason:"choice",playerCaused:true,playerActionLineage:{actionId:action.id,actionHash:action.actionHash}}),/authoritative RPG/));
const div=canon.createDivergenceEvent(corpus,{id:"div",baseEventId:event2.id,invalidatedAnchorIds:[anchor1.id],reason:"choice",playerCaused:true,rpgDefinition:world,rpgSession:session,playerAction:action});
pass("player divergence binds authentic RPG action boundary",()=>assert.equal(canon.verifyDivergenceLineage(div,{rpgDefinition:world,rpgSession:session,playerAction:action}).valid,true));
pass("forged player action cannot validate divergence",()=>assert.equal(canon.verifyDivergenceLineage(div,{rpgDefinition:world,rpgSession:session,playerAction:{...action,actionHash:H("0")}}).valid,false));
pass("Canon to RPG bridge verifies exact session seal",()=>assert.equal(canon.createRpgConstraintSet(corpus,scene,session,world).verifiedSessionSeal,session.sessionSeal));
pass("forged RPG session is refused",()=>assert.throws(()=>canon.createRpgConstraintSet(corpus,scene,{...session,sessionSeal:H("0")},world),/RPG session invalid/));

const ne=titles.createNamingEvidenceRef({id:"name-evidence",sourceVersionId:"sv1",sourceVersionHash:src.sourceVersionHash,locator:{page:1,lineStart:2}}),profile=titles.createWorldLanguageProfile({id:"profile",worldId:"w",locale:"ar",evidence:[ne],numbering:{digits:"ARABIC_INDIC"}}),headsById={sv1:src.sourceVersionHash};
pass("profile evidence is source-version sealed",()=>assert.equal(titles.verifyProfile(profile,{activeSourceHeads:headsById}),true));
pass("profile becomes stale when source version changes",()=>assert.equal(titles.verifyProfile(profile,{activeSourceHeads:{sv1:H("9")}}),false));
pass("unsafe naming regex is rejected before runtime",()=>assert.throws(()=>titles.createWorldLanguageProfile({id:"redos",worldId:"w",locale:"en",evidence:[ne],forbiddenPatterns:["(a+)+$"]}),/unsafe forbidden pattern/));
const grammar=titles.createNamingGrammar(profile,{id:"grammar",domain:"EPISODE",templates:["الحلقة {number}: {theme}"],requiredTokens:["الحلقة"],maxLength:80}),req=titles.createNamingRequest(profile,grammar,{id:"req",subjectId:"ep7",seed:"7",context:{number:12,theme:"الباب"}}),candidate=titles.generateDeterministic(profile,grammar,req);
pass("request/profile/grammar are sealed together",()=>assert.equal(titles.verifyRequest(req,profile,grammar),true));
pass("Arabic digits are deterministic",()=>assert.match(candidate.text,/١٢/));
pass("generated candidate integrity verifies",()=>assert.equal(titles.verifyCandidate(candidate,profile,grammar,req),true));
pass("candidate status spoof cannot turn generated into official",()=>assert.equal(titles.verifyCandidate({...candidate,status:"OFFICIAL",evidenceRefs:[ne.id]},profile,grammar,req),false));
pass("candidate text tamper is detected",()=>assert.equal(titles.verifyCandidate({...candidate,text:"Official"},profile,grammar,req),false));
const empty=titles.TitleRegistry({id:"registry"}),decision=titles.decideNaming(profile,grammar,req,[candidate],empty),identity=titles.createTitleIdentity(profile,grammar,req,decision,{id:"title-main"}),registry=titles.appendIdentity(empty,identity);
pass("decision and identity carry provenance seals",()=>{assert.equal(titles.verifyDecision(decision,req),true);assert.equal(titles.verifyTitleIdentity(identity),true)});
const branchReq=titles.createNamingRequest(profile,grammar,{id:"branch-req",subjectId:"branch-ep",branchId:"what-if",seed:"7",context:{number:12,theme:"الباب"}}),branchCandidate=titles.generateDeterministic(profile,grammar,branchReq);
pass("generated names are branch-scoped",()=>assert.equal(titles.detectCollisions(registry,branchCandidate).length,0));
const officialReq=titles.createNamingRequest(profile,grammar,{id:"official-req",subjectId:"official-ep",branchId:"other",seed:"1",context:{number:1,theme:"x"},desiredStatus:"OFFICIAL"});
pass("raw evidence id cannot establish official status",()=>assert.throws(()=>titles.createOfficialCandidate(profile,grammar,officialReq,{text:identity.text,evidenceRefs:[ne.id]}),/verified naming evidence/));
const official=titles.createOfficialCandidate(profile,grammar,officialReq,{text:identity.text,evidence:[ne]});
pass("official identity collision is global across branches",()=>assert.equal(titles.detectCollisions(registry,official).length,1));
pass("stale official evidence blocks candidate",()=>assert.equal(titles.validateCandidate(profile,grammar,officialReq,official,empty,{activeSourceHeads:{sv1:H("8")}}).status,"BLOCKED"));
pass("Arabic collision key folds diacritics tatweel and Arabic digits",()=>assert.equal(titles.linguisticCollisionKey("إلـباب ١٢","ar"),titles.linguisticCollisionKey("الباب 12","ar")));
pass("official localization needs verified evidence object",()=>assert.throws(()=>titles.createLocalizationVariant(identity,{locale:"en",text:"The Door",status:"OFFICIAL_LOCALIZED",evidenceRefs:[ne.id]}),/verified naming evidence/));
const loc=titles.createLocalizationVariant(identity,{locale:"en",text:"The Door",status:"OFFICIAL_LOCALIZED",evidence:[ne]});pass("official localization is evidence sealed",()=>assert.ok(loc.localizationSeal));
const manifest=titles.createNamingManifest(profile,grammar,req,decision,empty,{id:"manifest"});pass("manifest binds exact registry and dependencies",()=>assert.equal(titles.verifyManifest(manifest,profile,grammar,req,decision,empty),true));pass("registry drift invalidates naming replay",()=>assert.equal(titles.verifyManifest(manifest,profile,grammar,req,decision,registry),false));
pass("no generated-to-official promotion API exists",()=>assert.equal(typeof titles.promoteGeneratedToOfficial,"undefined"));
console.log(`canon/title PassB adversarial: PASS (${n} assertions)`);