"use strict";
const crypto=require("crypto");
const FACT_STATUS=Object.freeze({SUPPORTED_CANON:"SUPPORTED_CANON",SUPPORTED_DERIVATION:"SUPPORTED_DERIVATION",CANON_GAP:"CANON_GAP",CONFLICT:"CONFLICT",VARIANT_ONLY:"VARIANT_ONLY",UNKNOWN:"UNKNOWN"});
const COVERAGE_STATUS=Object.freeze({PASS:"PASS",CANON_GAP:"CANON_GAP",CONFLICT:"CONFLICT",BLOCKED:"BLOCKED"});
const INSERTION_STATUS=Object.freeze({CANON_PRESERVING:"CANON_PRESERVING",DIVERGENCE_REQUIRED:"DIVERGENCE_REQUIRED",CANON_GAP:"CANON_GAP",BLOCKED:"BLOCKED"});
const RELATION=Object.freeze({BEFORE:"BEFORE",CAUSES:"CAUSES",ENABLES:"ENABLES",SAME_EVENT:"SAME_EVENT"});
const SOURCE_KIND=Object.freeze({PRIMARY:"PRIMARY",OFFICIAL_REFERENCE:"OFFICIAL_REFERENCE",LOCALIZATION:"LOCALIZATION",ADAPTATION:"ADAPTATION",SECONDARY:"SECONDARY"});
const A=v=>Array.isArray(v)?v:[], C=v=>v==null?v:JSON.parse(JSON.stringify(v)), F=Object.freeze;
function R(v,n){const s=String(v??"").trim();if(!s)throw new Error(`${n} required`);return s}
function S(v){if(Array.isArray(v))return v.map(S);if(v&&typeof v==="object"){const o={};for(const k of Object.keys(v).sort())if(v[k]!==undefined)o[k]=S(v[k]);return o}return v}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(S(v))).digest("hex")}
function U(v){return [...new Set(A(v).map(String))]}
function E(v,set,n){const s=String(v??"").toUpperCase();if(!Object.values(set).includes(s))throw new Error(`${n} invalid:${v}`);return s}
function M(xs,n){const o={};for(const x of A(xs)){if(!x?.id)throw new Error(`${n} id required`);if(o[x.id])throw new Error(`${n} duplicate:${x.id}`);o[x.id]=C(x)}return o}
function createCanonWork(i={}){const b={id:R(i.id,"work.id"),version:R(i.version??"1","work.version"),title:String(i.title??i.id),kind:String(i.kind??"WORK").toUpperCase()};return F({...b,workHash:hash(b)})}
function verifyCanonWork(w){return !!w?.workHash&&w.workHash===hash({id:w.id,version:w.version,title:w.title,kind:w.kind})}
function createContinuity(w,i={}){if(!verifyCanonWork(w))throw new Error("valid CanonWork required");const b={id:R(i.id,"continuity.id"),workId:w.id,workHash:w.workHash,kind:String(i.kind??"PRIMARY").toUpperCase(),label:String(i.label??i.id),parentContinuityId:i.parentContinuityId?String(i.parentContinuityId):null,variantKey:i.variantKey?String(i.variantKey):null};return F({...b,continuityHash:hash(b)})}
function verifyContinuity(c,w=null){if(!c?.continuityHash||c.continuityHash!==hash({id:c.id,workId:c.workId,workHash:c.workHash,kind:c.kind,label:c.label,parentContinuityId:c.parentContinuityId??null,variantKey:c.variantKey??null}))return false;return !w||(verifyCanonWork(w)&&c.workId===w.id&&c.workHash===w.workHash)}
function createSourceVersion(c,i={}){if(!verifyContinuity(c))throw new Error("valid ContinuityRef required");const ch=R(i.contentHash,"source.contentHash");if(!/^[a-f0-9]{32,128}$/i.test(ch))throw new Error("source.contentHash must be a strong digest");const b={id:R(i.id,"source.id"),continuityId:c.id,continuityHash:c.continuityHash,sourceKind:E(i.sourceKind??SOURCE_KIND.PRIMARY,SOURCE_KIND,"sourceKind"),sourceIdentity:R(i.sourceIdentity??i.id,"source.sourceIdentity"),version:R(i.version??"1","source.version"),contentHash:ch.toLowerCase(),publishedAt:i.publishedAt?String(i.publishedAt):null};return F({...b,sourceVersionHash:hash(b)})}
function verifySourceVersion(s,c=null){if(!s?.sourceVersionHash)return false;const b={id:s.id,continuityId:s.continuityId,continuityHash:s.continuityHash,sourceKind:s.sourceKind,sourceIdentity:s.sourceIdentity,version:s.version,contentHash:s.contentHash,publishedAt:s.publishedAt??null};return s.sourceVersionHash===hash(b)&&(!c||(verifyContinuity(c)&&s.continuityId===c.id&&s.continuityHash===c.continuityHash))}
function createEvidence(s,i={}){if(!verifySourceVersion(s))throw new Error("valid CanonSourceVersion required");const locator=C(i.locator);if(!locator||typeof locator!=="object"||!Object.keys(locator).length)throw new Error("evidence.locator required");if(locator.page==null&&locator.lineStart==null&&locator.timestampStart==null&&locator.section==null&&locator.anchor==null)throw new Error("evidence.locator must be reconstructable");const eh=R(i.excerptHash??i.observationHash,"evidence.excerptHash");if(!/^[a-f0-9]{32,128}$/i.test(eh))throw new Error("evidence.excerptHash must be a strong digest");const b={id:R(i.id,"evidence.id"),sourceVersionId:s.id,sourceVersionHash:s.sourceVersionHash,continuityId:s.continuityId,locator,excerptHash:eh.toLowerCase(),claimScope:i.claimScope?String(i.claimScope):null};return F({...b,evidenceHash:hash(b)})}
function verifyEvidence(e,s=null){if(!e?.evidenceHash)return false;const b={id:e.id,sourceVersionId:e.sourceVersionId,sourceVersionHash:e.sourceVersionHash,continuityId:e.continuityId,locator:e.locator,excerptHash:e.excerptHash,claimScope:e.claimScope??null};return e.evidenceHash===hash(b)&&(!s||(verifySourceVersion(s)&&e.sourceVersionId===s.id&&e.sourceVersionHash===s.sourceVersionHash&&e.continuityId===s.continuityId))}
function createCanonFact(c,i={}){if(!verifyContinuity(c))throw new Error("valid ContinuityRef required");const status=E(i.status??FACT_STATUS.UNKNOWN,FACT_STATUS,"fact.status"),evidenceRefs=U(i.evidenceRefs),derivation=C(i.derivation??null);if(status===FACT_STATUS.SUPPORTED_CANON&&!evidenceRefs.length)throw new Error("SUPPORTED_CANON requires evidence");if(status===FACT_STATUS.SUPPORTED_DERIVATION&&(!derivation||!A(derivation.inputFactIds).length))throw new Error("SUPPORTED_DERIVATION requires derivation lineage");if(status===FACT_STATUS.CANON_GAP&&evidenceRefs.length)throw new Error("CANON_GAP cannot claim positive supporting evidence");const b={id:R(i.id,"fact.id"),continuityId:c.id,continuityHash:c.continuityHash,subjectId:R(i.subjectId,"fact.subjectId"),predicate:R(i.predicate,"fact.predicate"),value:C(i.value),status,evidenceRefs,derivation,branchId:i.branchId?String(i.branchId):null};return F({...b,factHash:hash(b)})}
function verifyCanonFact(f,c=null){if(!f?.factHash)return false;const b={id:f.id,continuityId:f.continuityId,continuityHash:f.continuityHash,subjectId:f.subjectId,predicate:f.predicate,value:f.value,status:f.status,evidenceRefs:f.evidenceRefs,derivation:f.derivation??null,branchId:f.branchId??null};return f.factHash===hash(b)&&(!c||(verifyContinuity(c)&&f.continuityId===c.id&&f.continuityHash===c.continuityHash))}
function createCanonEvent(c,i={}){if(!verifyContinuity(c))throw new Error("valid ContinuityRef required");const b={id:R(i.id,"event.id"),continuityId:c.id,continuityHash:c.continuityHash,label:String(i.label??i.id),factRefs:U(i.factRefs),evidenceRefs:U(i.evidenceRefs),branchId:i.branchId?String(i.branchId):null};return F({...b,eventHash:hash(b)})}
function verifyCanonEvent(e,c=null){if(!e?.eventHash)return false;const b={id:e.id,continuityId:e.continuityId,continuityHash:e.continuityHash,label:e.label,factRefs:e.factRefs,evidenceRefs:e.evidenceRefs,branchId:e.branchId??null};return e.eventHash===hash(b)&&(!c||(verifyContinuity(c)&&e.continuityId===c.id&&e.continuityHash===c.continuityHash))}
function createEventRelation(i={}){const type=E(i.type??RELATION.BEFORE,RELATION,"relation.type"),fromEventId=R(i.fromEventId,"relation.fromEventId"),toEventId=R(i.toEventId,"relation.toEventId");if(fromEventId===toEventId&&type!==RELATION.SAME_EVENT)throw new Error("self relation invalid");const b={id:R(i.id??`${fromEventId}:${type}:${toEventId}`,"relation.id"),fromEventId,toEventId,type,evidenceRefs:U(i.evidenceRefs)};return F({...b,relationHash:hash(b)})}
function adjacency(events,relations){const ids=new Set(Object.keys(events)),g={};for(const id of ids)g[id]=[];for(const r of Object.values(relations)){if(!ids.has(r.fromEventId)||!ids.has(r.toEventId))throw new Error(`relation event unknown:${r.id}`);if(r.type!==RELATION.SAME_EVENT)g[r.fromEventId].push(r.toEventId)}return g}
function auditChronology(events,relations){let g;const issues=[];try{g=adjacency(events,relations)}catch(e){return F({status:"FAIL",issues:[e.message]})}const color={};function dfs(x){color[x]=1;for(const y of g[x]){if(color[y]===1)issues.push(`chronology-cycle:${x}->${y}`);else if(!color[y])dfs(y)}color[x]=2}for(const id of Object.keys(g))if(!color[id])dfs(id);return F({status:issues.length?"FAIL":"PASS",issues})}
function reaches(events,relations,a,b){if(a===b)return true;let g;try{g=adjacency(events,relations)}catch{return false}const q=[a],seen=new Set(q);while(q.length){const x=q.shift();for(const y of g[x]||[]){if(y===b)return true;if(!seen.has(y)){seen.add(y);q.push(y)}}}return false}
function createKnowledgeEdge(c,i={}){if(!verifyContinuity(c))throw new Error("valid ContinuityRef required");const b={id:R(i.id??`${i.characterId}:${i.factId}`,"knowledge.id"),continuityId:c.id,characterId:R(i.characterId,"knowledge.characterId"),factId:R(i.factId,"knowledge.factId"),acquiredAtEventId:R(i.acquiredAtEventId,"knowledge.acquiredAtEventId"),sourceEventId:R(i.sourceEventId??i.acquiredAtEventId,"knowledge.sourceEventId"),evidenceRefs:U(i.evidenceRefs)};return F({...b,knowledgeHash:hash(b)})}
function createAnchor(c,i={}){if(!verifyContinuity(c))throw new Error("valid ContinuityRef required");const b={id:R(i.id,"anchor.id"),continuityId:c.id,kind:String(i.kind??"FACT").toUpperCase(),targetId:R(i.targetId,"anchor.targetId"),hard:i.hard!==false,dependsOn:U(i.dependsOn),evidenceRefs:U(i.evidenceRefs)};return F({...b,anchorHash:hash(b)})}
function createCorpus(i={}){if(!verifyCanonWork(i.work)||!verifyContinuity(i.continuity,i.work))throw new Error("invalid corpus identity");const b={id:R(i.id??`${i.work.id}:${i.continuity.id}`,"corpus.id"),work:C(i.work),continuity:C(i.continuity),sources:M(i.sources,"source"),evidence:M(i.evidence,"evidence"),facts:M(i.facts,"fact"),events:M(i.events,"event"),relations:M(i.relations,"relation"),knowledge:M(i.knowledge,"knowledge"),anchors:M(i.anchors,"anchor"),revision:Number.isInteger(i.revision)?i.revision:1};return F({...b,integrityHash:hash(b)})}
function verifyCorpus(c){const issues=[];if(!c?.integrityHash)return F({valid:false,issues:["missing-integrity-hash"]});const b={id:c.id,work:c.work,continuity:c.continuity,sources:c.sources,evidence:c.evidence,facts:c.facts,events:c.events,relations:c.relations,knowledge:c.knowledge,anchors:c.anchors,revision:c.revision};if(hash(b)!==c.integrityHash)issues.push("corpus-integrity-drift");if(!verifyCanonWork(c.work)||!verifyContinuity(c.continuity,c.work))issues.push("identity-invalid");for(const s of Object.values(c.sources||{}))if(!verifySourceVersion(s,c.continuity))issues.push(`source-invalid:${s.id}`);for(const e of Object.values(c.evidence||{})){const s=c.sources[e.sourceVersionId];if(!s||!verifyEvidence(e,s))issues.push(`evidence-invalid:${e.id}`)}for(const f of Object.values(c.facts||{})){if(!verifyCanonFact(f,c.continuity))issues.push(`fact-invalid:${f.id}`);for(const x of f.evidenceRefs||[])if(!c.evidence[x])issues.push(`fact-evidence-missing:${f.id}:${x}`)}for(const e of Object.values(c.events||{})){if(!verifyCanonEvent(e,c.continuity))issues.push(`event-invalid:${e.id}`);for(const x of e.factRefs||[])if(!c.facts[x])issues.push(`event-fact-missing:${e.id}:${x}`)}issues.push(...auditChronology(c.events||{},c.relations||{}).issues);for(const k of Object.values(c.knowledge||{})){if(!c.facts[k.factId])issues.push(`knowledge-fact-missing:${k.id}`);if(!c.events[k.acquiredAtEventId]||!c.events[k.sourceEventId])issues.push(`knowledge-event-missing:${k.id}`)}for(const a of Object.values(c.anchors||{})){const ok=a.kind==="EVENT"?c.events[a.targetId]:c.facts[a.targetId];if(!ok)issues.push(`anchor-target-missing:${a.id}`);for(const d of a.dependsOn||[])if(!c.anchors[d])issues.push(`anchor-dependency-missing:${a.id}:${d}`)}return F({valid:!issues.length,issues})}
function factConflicts(a,b){if(!a||!b||a.id===b.id||a.continuityId!==b.continuityId||a.branchId!==b.branchId||a.subjectId!==b.subjectId||a.predicate!==b.predicate)return false;if([FACT_STATUS.CANON_GAP,FACT_STATUS.UNKNOWN].includes(a.status)||[FACT_STATUS.CANON_GAP,FACT_STATUS.UNKNOWN].includes(b.status))return false;return hash(a.value)!==hash(b.value)}
function createCoverageContract(i={}){const b={id:R(i.id,"coverage.id"),continuityId:R(i.continuityId,"coverage.continuityId"),requiredFactIds:U(i.requiredFactIds),requiredAnchorIds:U(i.requiredAnchorIds),requiredKnowledge:A(i.requiredKnowledge).map(x=>({characterId:R(x.characterId,"coverage.characterId"),factId:R(x.factId,"coverage.factId")})),allowDerivations:i.allowDerivations===true};return F({...b,coverageHash:hash(b)})}
function evaluateCoverage(c,k){const cv=verifyCorpus(c);if(!cv.valid)return F({status:COVERAGE_STATUS.BLOCKED,issues:cv.issues});if(k.continuityId!==c.continuity.id)return F({status:COVERAGE_STATUS.BLOCKED,issues:["continuity-mismatch"]});const issues=[];let gap=false,conflict=false;for(const id of k.requiredFactIds){const f=c.facts[id];if(!f||[FACT_STATUS.CANON_GAP,FACT_STATUS.UNKNOWN].includes(f.status)){gap=true;issues.push(`fact-gap:${id}`)}else if(f.status===FACT_STATUS.CONFLICT){conflict=true;issues.push(`fact-conflict:${id}`)}else if(f.status===FACT_STATUS.SUPPORTED_DERIVATION&&!k.allowDerivations){gap=true;issues.push(`derivation-not-accepted:${id}`)}}for(const id of k.requiredAnchorIds)if(!c.anchors[id]){gap=true;issues.push(`anchor-missing:${id}`)}for(const n of k.requiredKnowledge)if(!Object.values(c.knowledge).some(x=>x.characterId===n.characterId&&x.factId===n.factId)){gap=true;issues.push(`knowledge-gap:${n.characterId}:${n.factId}`)}return F({status:conflict?COVERAGE_STATUS.CONFLICT:gap?COVERAGE_STATUS.CANON_GAP:COVERAGE_STATUS.PASS,issues})}
function canCharacterKnow(c,charId,factId,atEventId){const cv=verifyCorpus(c);if(!cv.valid)return F({allowed:false,reason:"corpus-invalid"});if(!c.events[atEventId])return F({allowed:false,reason:"scene-event-unknown"});for(const k of Object.values(c.knowledge).filter(x=>x.characterId===charId&&x.factId===factId))if(k.acquiredAtEventId===atEventId||reaches(c.events,c.relations,k.acquiredAtEventId,atEventId))return F({allowed:true,reason:"knowledge-acquired",edgeId:k.id});return F({allowed:false,reason:"knowledge-not-yet-acquired"})}
function createSceneContract(c,i={}){const cv=verifyCorpus(c);if(!cv.valid)throw new Error(`invalid canon corpus:${cv.issues.join(",")}`);const b={id:R(i.id,"scene.id"),corpusId:c.id,corpusIntegrityHash:c.integrityHash,continuityId:c.continuity.id,currentEventId:R(i.currentEventId,"scene.currentEventId"),participants:U(i.participants),requiredFactIds:U(i.requiredFactIds),protectedAnchorIds:U(i.protectedAnchorIds),playerAgencyLocked:i.playerAgencyLocked!==false,spoilerHorizonEventId:i.spoilerHorizonEventId?String(i.spoilerHorizonEventId):i.currentEventId};if(!c.events[b.currentEventId]||!c.events[b.spoilerHorizonEventId])throw new Error("scene event boundary unknown");return F({...b,sceneHash:hash(b)})}
function branchImpact(c,ids){const inv=new Set(U(ids));let changed=true;while(changed){changed=false;for(const a of Object.values(c.anchors)){if(!inv.has(a.id)&&(a.dependsOn||[]).some(d=>inv.has(d))){inv.add(a.id);changed=true}}}const out=[...inv].sort();return F({invalidatedAnchorIds:out,impactHash:hash(out)})}
function analyzeInsertion(c,s,i={}){const cv=verifyCorpus(c);if(!cv.valid)return F({status:INSERTION_STATUS.BLOCKED,issues:cv.issues});if(s.corpusIntegrityHash!==c.integrityHash)return F({status:INSERTION_STATUS.BLOCKED,issues:["scene-corpus-drift"]});const issues=[];let gap=false,div=false;if(s.playerAgencyLocked&&i.overridePlayerChoice===true){div=true;issues.push("player-agency-conflict")}for(const id of U(i.requiredFactIds??s.requiredFactIds)){const f=c.facts[id];if(!f||[FACT_STATUS.CANON_GAP,FACT_STATUS.UNKNOWN,FACT_STATUS.CONFLICT].includes(f.status)){gap=true;issues.push(`canon-gap:${id}`)}}const touched=U(i.touchedAnchorIds);for(const id of touched){const a=c.anchors[id];if(!a){gap=true;issues.push(`anchor-unknown:${id}`)}else if(a.hard){div=true;issues.push(`hard-anchor-touched:${id}`)}}return F({status:div?INSERTION_STATUS.DIVERGENCE_REQUIRED:gap?INSERTION_STATUS.CANON_GAP:INSERTION_STATUS.CANON_PRESERVING,issues,impact:branchImpact(c,touched)})}
function createDivergenceEvent(c,i={}){const ids=U(i.invalidatedAnchorIds);if(!ids.length)throw new Error("divergence requires invalidated anchor");for(const id of ids)if(!c.anchors[id])throw new Error(`divergence anchor unknown:${id}`);if(i.playerCaused===true&&!i.playerActionLineage)throw new Error("player-caused divergence requires PlayerAction lineage");const b={id:R(i.id,"divergence.id"),corpusId:c.id,corpusIntegrityHash:c.integrityHash,baseEventId:R(i.baseEventId,"divergence.baseEventId"),invalidatedAnchorIds:ids,reason:R(i.reason,"divergence.reason"),playerCaused:i.playerCaused===true,playerActionLineage:i.playerActionLineage?C(i.playerActionLineage):null};if(!c.events[b.baseEventId])throw new Error("divergence base event unknown");return F({...b,divergenceHash:hash(b),impact:branchImpact(c,ids)})}
function createCanonBranch(c,d,i={}){if(!d?.divergenceHash||d.corpusIntegrityHash!==c.integrityHash)throw new Error("valid divergence required");const b={id:R(i.id,"branch.id"),parentContinuityId:c.continuity.id,corpusIntegrityHash:c.integrityHash,divergenceId:d.id,divergenceHash:d.divergenceHash,baseEventId:d.baseEventId,label:String(i.label??i.id)};return F({...b,branchHash:hash(b)})}
function createRpgConstraintSet(c,s,r){const cv=verifyCorpus(c);if(!cv.valid)throw new Error("valid canon corpus required");if(!r?.sessionSeal)throw new Error("sealed RPG WorldSession required");if(s.corpusIntegrityHash!==c.integrityHash)throw new Error("scene corpus drift");const b={id:`canon:${c.id}:${s.id}:${r.id}`,canonCorpusId:c.id,canonCorpusHash:c.integrityHash,sceneId:s.id,sceneHash:s.sceneHash,rpgSessionId:r.id,rpgSessionSeal:r.sessionSeal,protectedFactIds:U(s.requiredFactIds),protectedAnchorIds:U(s.protectedAnchorIds),rule:"CONSTRAINT_ONLY_NO_WORLD_OWNERSHIP"};return F({...b,constraintHash:hash(b)})}
function auditCanon(c){const cv=verifyCorpus(c),facts=Object.values(c?.facts||{}),conflicts=[];for(let i=0;i<facts.length;i++)for(let j=i+1;j<facts.length;j++)if(factConflicts(facts[i],facts[j]))conflicts.push([facts[i].id,facts[j].id]);const gaps=facts.filter(f=>[FACT_STATUS.CANON_GAP,FACT_STATUS.UNKNOWN].includes(f.status)).map(f=>f.id);return F({status:cv.valid&&!conflicts.length?"PASS":"REVIEW",issues:[...(cv.issues||[]),...conflicts.map(x=>`fact-conflict:${x.join(":")}`)],gaps,conflicts,corpusIntegrityHash:c?.integrityHash||null})}
module.exports=F({FACT_STATUS,COVERAGE_STATUS,INSERTION_STATUS,RELATION,SOURCE_KIND,hash,createCanonWork,verifyCanonWork,createContinuity,verifyContinuity,createSourceVersion,verifySourceVersion,createEvidence,verifyEvidence,createCanonFact,verifyCanonFact,createCanonEvent,verifyCanonEvent,createEventRelation,auditChronology,reaches,createKnowledgeEdge,createAnchor,createCorpus,verifyCorpus,factConflicts,createCoverageContract,evaluateCoverage,canCharacterKnow,createSceneContract,branchImpact,analyzeInsertion,createDivergenceEvent,createCanonBranch,createRpgConstraintSet,auditCanon});