"use strict";
const assert=require("assert");
const x=require("./execution-integration-fabric.cjs");
const n=require("./native-execution-fabric-final.cjs");
const d=require("./durable-fabric-state.cjs");
const s=require("./side-effect-ledger.cjs");
const f=require("./project-file-fabric-passb.cjs");
let count=0;const ok=(v,m)=>{assert.ok(v,m);count++},eq=(a,b,m)=>{assert.strictEqual(a,b,m);count++},throws=(fn,re,m)=>{assert.throws(fn,re,m);count++};const H=v=>n.sha(v),T="2026-09-15T09:00:00Z",NOW=Date.parse(T),M1=H("manifest-1"),M2=H("manifest-2");

const root=f.createProjectRoot({rootId:"root",backendId:"local",backendRootRef:"workspace",grantEpoch:1,policyEpoch:1});
const grant=f.createProjectGrant({grantId:"grant",principalId:"user",projectRootId:root.id,actions:["READ","PATCH","EXECUTE"],prefixes:["src","tests"],epoch:1,policyEpoch:1,sourceEventId:"grant-event"});
const backend=f.createBackendCapabilityProfile({backendId:"local",backendKind:"LOCAL",readOnly:false,atomicSingleWrite:true,atomicMultiWrite:true,atomicRename:true,checkpoints:true,nativeVersionTokens:true});
const profile=n.createExecutorProfile({executorId:"android",revision:"3",platform:"android",allowedExecutables:["node"],allowedEnvKeys:["CI"],maxRuntimeMs:60000,maxOutputBytes:4096,maxArgBytes:2048,supportsCancellation:true,networkAllowed:false});
const att=n.createAdapterAttestation({profile,adapterId:"android-adapter",adapterRevision:"9",executableIdentities:[{name:"node",resolvedPath:"/usr/bin/node",sha256:H("node-bin")}],producer:"platform-verifier",evidenceHashes:[H("binary-evidence")],attestedAt:T,expiresAt:"2026-09-16T09:00:00Z"});
function checkpoint({revision=0,previousSeal=null,manifest=M1,state={ready:true},committedAt=T}={}){return d.createFabricCheckpoint({fabricId:"execution-control",principalId:"user",scopeId:root.id,revision,previousSeal,state,dependencyHeads:{projectManifestHash:manifest,grantEpoch:"1",policyEpoch:"1"},committedAt});}
const preCp=checkpoint();ok(d.verifyFabricCheckpoint(preCp));

const read=n.createCommandContract({profile,root,grant,principalId:"user",taskId:"tests",executable:"node",argv:["tests/all.cjs"],cwd:"tests",env:{CI:"1"},effectClass:"READ_ONLY",reads:[{action:"READ",path:"tests/all.cjs"}],timeoutMs:30000,now:NOW,currentGrantEpoch:1,currentPolicyEpoch:1});
const readPre=n.createExecutionPreflight({contract:read,profile,attestation:att,projectManifestHash:M1,grantSnapshotHash:H("grant-snap"),policySnapshotHash:H("policy-snap"),fileVersions:[{path:"tests/all.cjs",state:"PRESENT",versionHash:H("tests-v1")}],issuedAt:T,expiresAt:"2026-09-15T09:05:00Z"});
const readRetries=n.createRetryLedger({id:"read-retries",commandSeal:read.seal});
const env=x.createExecutionEnvelope({runId:"read-run",contract:read,profile,preflight:readPre,attestation:att,preCheckpoint:preCp,currentHeads:{projectManifestHash:M1,grantEpoch:"1",policyEpoch:"1"},effectLedgerSnapshot:null,retryLedger:readRetries,preparedAt:"2026-09-15T09:00:00Z"});
ok(x.verifyExecutionEnvelope(env));eq(env.effectClass,"READ_ONLY");eq(env.effectJournalBaselineHash,null);eq(env.projectManifestHash,M1);eq(env.grantsAuthority,false);
throws(()=>x.createExecutionEnvelope({runId:"stale",contract:read,profile,preflight:readPre,attestation:att,preCheckpoint:preCp,currentHeads:{projectManifestHash:H("drift"),grantEpoch:"1",policyEpoch:"1"},retryLedger:readRetries,preparedAt:T}),/stale|manifest drift/);
throws(()=>x.createExecutionEnvelope({runId:"effect-smuggle",contract:read,profile,preflight:readPre,attestation:att,preCheckpoint:preCp,currentHeads:{projectManifestHash:M1,grantEpoch:"1",policyEpoch:"1"},effectLedgerSnapshot:s.createEffectLedger().snapshot(),retryLedger:readRetries,preparedAt:T}),/read-only envelope cannot bind effect ledger/);
const forgedRetry={...readRetries,revision:1};throws(()=>x.createExecutionEnvelope({runId:"bad-retry",contract:read,profile,preflight:readPre,attestation:att,preCheckpoint:preCp,currentHeads:{projectManifestHash:M1,grantEpoch:"1",policyEpoch:"1"},retryLedger:forgedRetry,preparedAt:T}),/retry ledger/);

const rr=n.createExecutionReceipt({contract:read,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"PASS",stderr:"",startedAt:"2026-09-15T09:00:01Z",endedAt:"2026-09-15T09:00:02Z",adapterId:"android-adapter",outputTruncated:false});
const ro=n.createObservedExecutionReceipt({contract:read,profile,executionReceipt:rr,preflight:readPre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:[],producedStdoutBytes:4,producedStderrBytes:0});
const obs=x.recordObservedExecution({envelope:env,contract:read,profile,preflight:readPre,attestation:att,executionReceipt:rr,observedReceipt:ro});ok(x.verifyExecutionObservation(obs,env));eq(obs.observedVerdict,"PASS");
const rv=n.createExecutionVerification({executionReceipt:rr,contract:read,status:"PASS",evidenceHashes:[H("read-proof")],checker:"tests",checkedAt:"2026-09-15T09:00:03Z"});
const out=x.createExecutionOutcome({envelope:env,observation:obs,contract:read,profile,preflight:readPre,attestation:att,executionReceipt:rr,observedReceipt:ro,verification:rv,completedAt:"2026-09-15T09:00:03Z"});ok(x.verifyExecutionOutcome(out,env,obs));eq(out.verdict,"SUCCESS");eq(out.reasons.length,0);
let rec=x.recoveryDecision({envelope:env,observation:obs,outcome:out,contract:read});eq(rec.action,"CHECKPOINT_ONLY");ok(rec.reasons.includes("execution-already-successful-never-reexecute"));
const postCp=checkpoint({revision:1,previousSeal:preCp.seal,manifest:M1,state:{executionOutcomeSeal:out.seal,executionVerdict:out.verdict},committedAt:"2026-09-15T09:00:04Z"});const close=x.closeExecutionRun({envelope:env,outcome:out,preCheckpoint:preCp,postCheckpoint:postCp});ok(x.verifyExecutionCloseReceipt(close,env,out));eq(close.status,"COMMITTED_SUCCESS");eq(close.postCheckpointRevision,1);
const wrongPost=checkpoint({revision:1,previousSeal:preCp.seal,manifest:M1,state:{executionOutcomeSeal:H("fake"),executionVerdict:out.verdict},committedAt:"2026-09-15T09:00:04Z"});throws(()=>x.closeExecutionRun({envelope:env,outcome:out,preCheckpoint:preCp,postCheckpoint:wrongPost}),/exact execution outcome/);
rec=x.recoveryDecision({envelope:env,contract:read});eq(rec.action,"EXECUTE_PREPARED");

// Build a real project mutation transaction before the command so transactionRef is exact.
const mut=f.createMutation({op:"PATCH",path:"src/a.js",expectedVersionTokenId:"v1",patchHash:H("patch"),resultContentHash:H("new-content"),reason:"repair"});
let tx=f.createProjectTransaction({root,grant,principalId:"user",baselineManifestHash:M1,intentId:"repair-a",mutations:[mut]});tx=f.captureBaseline(tx,{manifestHash:M1,proofHash:H("baseline-proof")});tx=f.beginStaging(tx);tx=f.finishStaging(tx);
let validated=f.validateTransaction(tx,{root,backendProfile:backend,grant,principalId:"user",currentManifestHash:M1,currentVersions:{"src/a.js":{id:"v1",contentHash:H("old-content")}},existingPaths:["src/a.js"],currentGrantEpoch:1,currentPolicyEpoch:1});ok(validated.ok);tx=validated.transaction;
const auth=f.createTransactionAuthorizationReceipt({transaction:tx,validationReceipt:validated.validationReceipt,root,grant,principalId:"user",sourceAuthorizationReceiptId:"tool-auth",sourceAuthorizationReceiptHash:H("tool-auth"),grantEpoch:1,policyEpoch:1});tx=f.authorizeTransaction(tx,validated.validationReceipt,auth);tx=f.beginCommit(tx);

const ledger=s.createEffectLedger();const planned=ledger.planEffect({principalId:"user",taskId:"repair",runId:"mut-run",action:"PATCH",target:{path:"src/a.js"},payloadFingerprint:H("patch-payload"),bindingRevisionId:"native-node-v1",schemaFingerprint:H("command-schema"),authorizationReceipt:{decision:"ALLOW",id:"tool-auth"},toolCallContractId:"tool-call-1",effectClass:"REVERSIBLE_WRITE",idempotencyClass:"DO_NOT_REPEAT",maxReconciliationAttempts:3,at:T});const baselineEffects=ledger.snapshot();
const cmd=n.createCommandContract({profile,root,grant,principalId:"user",taskId:"repair",executable:"node",argv:["fix.js"],cwd:"src",effectClass:"PROJECT_MUTATION",effectKey:planned.key,transactionRef:tx.id,reads:[{action:"READ",path:"src/a.js"}],writes:[{action:"PATCH",path:"src/a.js"}],timeoutMs:30000,now:NOW,currentGrantEpoch:1,currentPolicyEpoch:1});
const p=n.createExecutionPreflight({contract:cmd,profile,attestation:att,projectManifestHash:M1,grantSnapshotHash:H("grant-snap2"),policySnapshotHash:H("policy-snap2"),fileVersions:[{path:"src/a.js",state:"PRESENT",versionHash:H("old-content")}],effectJournalHead:baselineEffects.journalHash,issuedAt:T,expiresAt:"2026-09-15T09:05:00Z"});const retries=n.createRetryLedger({id:"mut-retries",commandSeal:cmd.seal});
const menv=x.createExecutionEnvelope({runId:"mut-run",contract:cmd,profile,preflight:p,attestation:att,preCheckpoint:preCp,currentHeads:{projectManifestHash:M1,grantEpoch:"1",policyEpoch:"1"},effectLedgerSnapshot:baselineEffects,retryLedger:retries,preparedAt:T});ok(x.verifyExecutionEnvelope(menv));eq(menv.effectJournalBaselineHash,baselineEffects.journalHash);eq(menv.effectKey,planned.key);
throws(()=>x.createExecutionEnvelope({runId:"wrong-effect",contract:cmd,profile,preflight:p,attestation:att,preCheckpoint:preCp,currentHeads:{projectManifestHash:M1,grantEpoch:"1",policyEpoch:"1"},effectLedgerSnapshot:s.createEffectLedger().snapshot(),retryLedger:retries,preparedAt:T}),/effect journal baseline drift|effect key absent/);

const er=n.createExecutionReceipt({contract:cmd,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"changed",stderr:"",startedAt:"2026-09-15T09:00:01Z",endedAt:"2026-09-15T09:00:02Z",adapterId:"android-adapter",outputTruncated:false});const eo=n.createObservedExecutionReceipt({contract:cmd,profile,executionReceipt:er,preflight:p,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["src/a.js"],actualWrites:["src/a.js"],observedDomains:[],producedStdoutBytes:7,producedStderrBytes:0});const mobs=x.recordObservedExecution({envelope:menv,contract:cmd,profile,preflight:p,attestation:att,executionReceipt:er,observedReceipt:eo});ok(x.verifyExecutionObservation(mobs,menv));
// Complete file transaction and side-effect truth from observed postconditions.
tx=f.markCommitted(tx,{effectKey:planned.key,backendReceiptHash:H("backend-receipt"),resultManifestHash:M2});tx=f.beginVerification(tx);const verified=f.verifyCommittedTransaction(tx,{observedManifestHash:M2,observedFiles:{"src/a.js":{exists:true,contentHash:H("new-content")}}});ok(verified.ok);tx=verified.transaction;eq(tx.state,"VERIFIED");const txSnap=f.snapshotTransaction(tx);ok(f.restoreTransaction(txSnap).state==="VERIFIED");
ledger.beginAttempt(planned.key,{attemptId:"attempt-1",authorizationReceiptId:"tool-auth",toolCallContractId:"tool-call-1",at:"2026-09-15T09:00:01Z"});ledger.markDispatch(planned.key,"attempt-1","CONFIRMED",{at:"2026-09-15T09:00:01Z"});ledger.recordTransport(planned.key,"attempt-1",{ok:true,status:200,resultRef:"native-receipt",at:"2026-09-15T09:00:02Z"});ledger.verifyEffect(planned.key,{verdict:"PRESENT",evidence:{sourceRef:"project-postcondition",transactionRef:tx.id},at:"2026-09-15T09:00:03Z"});const finalEffects=ledger.snapshot();const effectRecord=ledger.get(planned.key);eq(effectRecord.effectCertainty,"PRESENT_VERIFIED");eq(effectRecord.lifecycle,"CLOSED");
const ev=n.createExecutionVerification({executionReceipt:er,contract:cmd,status:"PASS",evidenceHashes:[H("mutation-proof")],checker:"project-postcondition",checkedAt:"2026-09-15T09:00:03Z",reconciliation:{transactionRef:tx.id,status:"VERIFIED",postconditionHash:n.sha(tx.verificationReceipt)}});
const mout=x.createExecutionOutcome({envelope:menv,observation:mobs,contract:cmd,profile,preflight:p,attestation:att,executionReceipt:er,observedReceipt:eo,verification:ev,baselineEffectLedgerSnapshot:baselineEffects,finalEffectLedgerSnapshot:finalEffects,projectTransactionSnapshot:txSnap,completedAt:"2026-09-15T09:00:03Z"});ok(x.verifyExecutionOutcome(mout,menv,mobs));eq(mout.verdict,"SUCCESS");eq(mout.resultManifestHash,M2);eq(mout.effectJournalFinalHash,finalEffects.journalHash);
const mpost=checkpoint({revision:1,previousSeal:preCp.seal,manifest:M2,state:{executionOutcomeSeal:mout.seal,executionVerdict:mout.verdict},committedAt:"2026-09-15T09:00:04Z"});const mclose=x.closeExecutionRun({envelope:menv,outcome:mout,preCheckpoint:preCp,postCheckpoint:mpost});eq(mclose.status,"COMMITTED_SUCCESS");
const staleManifestPost=checkpoint({revision:1,previousSeal:preCp.seal,manifest:M1,state:{executionOutcomeSeal:mout.seal,executionVerdict:mout.verdict},committedAt:"2026-09-15T09:00:04Z"});throws(()=>x.closeExecutionRun({envelope:menv,outcome:mout,preCheckpoint:preCp,postCheckpoint:staleManifestPost}),/project manifest/);
const fakeEv=n.createExecutionVerification({executionReceipt:er,contract:cmd,status:"PASS",evidenceHashes:[H("mutation-proof")],checker:"project-postcondition",checkedAt:"2026-09-15T09:00:03Z",reconciliation:{transactionRef:tx.id,status:"VERIFIED",postconditionHash:H("fabricated-postcondition")}});throws(()=>x.createExecutionOutcome({envelope:menv,observation:mobs,contract:cmd,profile,preflight:p,attestation:att,executionReceipt:er,observedReceipt:eo,verification:fakeEv,baselineEffectLedgerSnapshot:baselineEffects,finalEffectLedgerSnapshot:finalEffects,projectTransactionSnapshot:txSnap}),/not bound to transaction verification receipt/);
const weakOut=x.createExecutionOutcome({envelope:menv,observation:mobs,contract:cmd,profile,preflight:p,attestation:att,executionReceipt:er,observedReceipt:eo,verification:ev,baselineEffectLedgerSnapshot:baselineEffects,finalEffectLedgerSnapshot:baselineEffects,projectTransactionSnapshot:txSnap});eq(weakOut.verdict,"RECOVERY_REQUIRED");ok(weakOut.reasons.includes("effect-not-present-verified-closed"));

// Crash/timeout recovery: effectful work cannot blind-retry until exact absence proof exists.
const fail=n.createExecutionReceipt({contract:cmd,profile,transportStatus:"TIMED_OUT",exitCode:null,stdout:"",stderr:"",startedAt:"2026-09-15T09:00:01Z",endedAt:"2026-09-15T09:00:31Z",adapterId:"android-adapter",outputTruncated:false});const fo=n.createObservedExecutionReceipt({contract:cmd,profile,executionReceipt:fail,preflight:p,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["src/a.js"],actualWrites:["src/a.js"],observedDomains:[],producedStdoutBytes:0,producedStderrBytes:0});const fobs=x.recordObservedExecution({envelope:menv,contract:cmd,profile,preflight:p,attestation:att,executionReceipt:fail,observedReceipt:fo});rec=x.recoveryDecision({envelope:menv,observation:fobs,contract:cmd,executionReceipt:fail,observedReceipt:fo,now:Date.parse("2026-09-15T09:00:32Z")});eq(rec.action,"RECONCILE_EFFECT");
const absence=n.createAbsenceReconciliation({contract:cmd,executionReceipt:fail,observedReceipt:fo,evidenceHashes:[H("no-commit")],verifier:"transaction-ledger",checkedAt:"2026-09-15T09:00:32Z"});const permit=n.createRetryPermit({contract:cmd,executionReceipt:fail,observedReceipt:fo,absenceReconciliation:absence,attempt:2,issuedAt:"2026-09-15T09:00:33Z",expiresAt:"2026-09-15T09:05:00Z"});rec=x.recoveryDecision({envelope:menv,observation:fobs,contract:cmd,retryPermit:permit,retryLedger:retries,executionReceipt:fail,observedReceipt:fo,now:Date.parse("2026-09-15T09:01:00Z")});eq(rec.action,"RETRY_ALLOWED");
const consumed=n.consumeRetryPermit(retries,permit,{contract:cmd,executionReceipt:fail,observedReceipt:fo,now:Date.parse("2026-09-15T09:01:00Z")});rec=x.recoveryDecision({envelope:menv,observation:fobs,contract:cmd,retryPermit:permit,retryLedger:consumed,executionReceipt:fail,observedReceipt:fo,now:Date.parse("2026-09-15T09:01:01Z")});eq(rec.action,"HALT");ok(rec.reasons.includes("retry-already-consumed"));

const blockedObserved={...eo,verdict:"BLOCK"}; // tampering must fail before it can become an integration observation.
throws(()=>x.recordObservedExecution({envelope:menv,contract:cmd,profile,preflight:p,attestation:att,executionReceipt:er,observedReceipt:blockedObserved}),/verified observed execution receipt/);
console.log(`Execution Integration Fabric: PASS (${count} assertions)`);
