"use strict";
const assert=require("assert");
const e=require("./native-execution-fabric-passb.cjs");
const f=require("./project-file-fabric.cjs");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.strictEqual(a,b,m);n++},throws=(fn,re,m)=>{assert.throws(fn,re,m);n++};const H=x=>e.sha(x),T="2026-09-15T03:00:00.000Z",NOW=Date.parse(T);

const root=f.createProjectRoot({rootId:"root-1",backendId:"local",backendRootRef:"workspace",grantEpoch:2});
const grant=f.createProjectGrant({grantId:"grant-1",principalId:"user-1",projectRootId:root.id,actions:["READ","LIST","PATCH","CREATE","REPLACE","DELETE","RENAME","EXECUTE"],prefixes:["src","tests"],epoch:2,policyEpoch:3,sourceEventId:"user-grant-event"});
const profile=e.createExecutorProfile({executorId:"android-local-exec",revision:"2",platform:"android",allowedExecutables:["node","npm","git"],allowedEnvKeys:["CI"],maxRuntimeMs:120000,maxOutputBytes:65536,maxArgBytes:4096,supportsCancellation:true,networkAllowed:false});
const att=e.createAdapterAttestation({profile,adapterId:"android-exec-adapter",adapterRevision:"7",executableIdentities:[{name:"node",resolvedPath:"/usr/bin/node",sha256:H("node-bin")},{name:"npm",resolvedPath:"/usr/bin/npm",sha256:H("npm-bin")},{name:"git",resolvedPath:"/usr/bin/git",sha256:H("git-bin")}],producer:"native-platform-verifier",evidenceHashes:[H("package-manager-scan"),H("binary-digest-log")],attestedAt:T,expiresAt:"2026-09-16T03:00:00Z"});
ok(e.verifyAdapterAttestation(att,profile,NOW));eq(att.grantsAuthority,false);eq(att.executableIdentities.length,3);eq(att.executableIdentities.find(x=>x.name==="node").sha256,H("node-bin"));
throws(()=>e.createAdapterAttestation({profile,adapterId:"x",adapterRevision:"1",executableIdentities:[{name:"node",resolvedPath:"/usr/bin/node",sha256:H("n")}],producer:"x",evidenceHashes:[H("e")],attestedAt:T,expiresAt:"2026-09-16T03:00:00Z"}),/cover every allowed executable/);
throws(()=>e.createAdapterAttestation({profile,adapterId:"x",adapterRevision:"1",executableIdentities:[{name:"node",resolvedPath:"node",sha256:H("n")},{name:"npm",resolvedPath:"/usr/bin/npm",sha256:H("p")},{name:"git",resolvedPath:"/usr/bin/git",sha256:H("g")}],producer:"x",evidenceHashes:[H("e")],attestedAt:T,expiresAt:"2026-09-16T03:00:00Z"}),/absolute and canonical/);
throws(()=>e.createAdapterAttestation({profile,adapterId:"x",adapterRevision:"1",executableIdentities:[{name:"node",resolvedPath:"/usr/bin/node",sha256:H("n")},{name:"npm",resolvedPath:"/usr/bin/npm",sha256:H("p")},{name:"git",resolvedPath:"/usr/bin/git",sha256:H("g")}],producer:"x",evidenceHashes:[],attestedAt:T,expiresAt:"2026-09-16T03:00:00Z"}),/requires evidence/);
throws(()=>e.createAdapterAttestation({profile,adapterId:"x",adapterRevision:"1",executableIdentities:[{name:"node",resolvedPath:"/usr/bin/node",sha256:H("n")},{name:"npm",resolvedPath:"/usr/bin/npm",sha256:H("p")},{name:"git",resolvedPath:"/usr/bin/git",sha256:H("g")}],producer:"x",evidenceHashes:[H("e")],attestedAt:T,expiresAt:"2026-10-01T03:00:00Z"}),/freshness window/);
const forgedAtt={...att,adapterRevision:"forged"};eq(e.verifyAdapterAttestation(forgedAtt,profile,NOW),false);eq(e.verifyAdapterAttestation(att,profile,Date.parse("2026-09-17T03:00:00Z")),false);

const read=e.createCommandContract({profile,root,grant,principalId:"user-1",taskId:"tests",executable:"node",argv:["tests/all.cjs"],cwd:"tests",env:{CI:"1"},effectClass:"READ_ONLY",reads:[{action:"READ",path:"tests/all.cjs"}],timeoutMs:60000,now:NOW,currentGrantEpoch:2,currentPolicyEpoch:3});
const pre=e.createExecutionPreflight({contract:read,profile,attestation:att,adapterId:"android-exec-adapter",projectManifestHash:H("manifest"),grantSnapshotHash:H("grant"),policySnapshotHash:H("policy"),fileVersions:[{path:"tests/all.cjs",state:"PRESENT",versionHash:H("tests-v1")}],issuedAt:T,expiresAt:"2026-09-15T03:05:00Z"});
ok(e.verifyExecutionPreflight(pre,{contract:read,profile,attestation:att,now:NOW}));eq(pre.effectJournalHead,null);eq(pre.fileVersions[0].path,"tests/all.cjs");
throws(()=>e.createExecutionPreflight({contract:read,profile,attestation:att,projectManifestHash:H("m"),grantSnapshotHash:H("g"),policySnapshotHash:H("p"),fileVersions:[],issuedAt:T,expiresAt:"2026-09-15T03:05:00Z"}),/missing declared file/);
throws(()=>e.createExecutionPreflight({contract:read,profile,attestation:att,projectManifestHash:H("m"),grantSnapshotHash:H("g"),policySnapshotHash:H("p"),fileVersions:[{path:"tests/all.cjs",state:"PRESENT",versionHash:H("v")},{path:"tests/all.cjs",state:"PRESENT",versionHash:H("v")}],issuedAt:T,expiresAt:"2026-09-15T03:05:00Z"}),/duplicate file preflight/);
throws(()=>e.createExecutionPreflight({contract:read,profile,attestation:att,projectManifestHash:H("m"),grantSnapshotHash:H("g"),policySnapshotHash:H("p"),fileVersions:[{path:"tests/all.cjs",state:"PRESENT",versionHash:H("v")}],issuedAt:T,expiresAt:"2026-09-15T03:20:00Z"}),/freshness window/);

const receipt=e.createExecutionReceipt({contract:read,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"PASS",stderr:"",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:00:02Z",adapterId:"android-exec-adapter",outputTruncated:false});
const obs=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:receipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:[],producedStdoutBytes:4,producedStderrBytes:0});
ok(e.verifyObservedExecutionReceipt(obs,{contract:read,executionReceipt:receipt,preflight:pre,attestation:att}));eq(obs.verdict,"PASS");eq(obs.failures.length,0);eq(obs.durationMs,1000);eq(obs.grantsAuthority,false);
const verify=e.createExecutionVerification({executionReceipt:receipt,contract:read,status:"PASS",evidenceHashes:[H("tests-log")],checker:"test-runner",checkedAt:"2026-09-15T03:00:03Z"});let decision=e.successDecisionPassB({contract:read,executionReceipt:receipt,verification:verify,observedReceipt:obs,preflight:pre,attestation:att});eq(decision.success,true);eq(decision.reasons.length,0);

let bad=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:receipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/tmp/node",sha256:H("evil-node")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:[],producedStdoutBytes:4,producedStderrBytes:0});eq(bad.verdict,"BLOCK");ok(bad.failures.includes("executable-identity-drift"));decision=e.successDecisionPassB({contract:read,executionReceipt:receipt,verification:verify,observedReceipt:bad,preflight:pre,attestation:att});eq(decision.success,false);ok(decision.reasons.includes("observation:executable-identity-drift"));
bad=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:receipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:["tests/pwned.txt"],observedDomains:[],producedStdoutBytes:4,producedStderrBytes:0});eq(bad.verdict,"BLOCK");ok(bad.failures.includes("undeclared-write:tests/pwned.txt"));ok(bad.failures.includes("read-only-observed-write"));
bad=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:receipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["src/secret.js"],actualWrites:[],observedDomains:[],producedStdoutBytes:4,producedStderrBytes:0});eq(bad.verdict,"BLOCK");ok(bad.failures.includes("undeclared-read:src/secret.js"));
bad=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:receipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:["evil.example"],producedStdoutBytes:4,producedStderrBytes:0});eq(bad.verdict,"BLOCK");ok(bad.failures.includes("undeclared-domain:evil.example"));ok(bad.failures.includes("network-observed-while-disabled"));
const truncated=e.createExecutionReceipt({contract:read,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"PASS",stderr:"",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:00:02Z",adapterId:"android-exec-adapter",outputTruncated:false});bad=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:truncated,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:[],producedStdoutBytes:100,producedStderrBytes:0});eq(bad.verdict,"BLOCK");ok(bad.failures.includes("output-truncation-claim-mismatch"));
const slow=e.createExecutionReceipt({contract:read,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"",stderr:"",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:01:02Z",adapterId:"android-exec-adapter",outputTruncated:false});bad=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:slow,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:[],producedStdoutBytes:0,producedStderrBytes:0});eq(bad.verdict,"BLOCK");ok(bad.failures.includes("completed-after-timeout-window"));
const tamperObs={...obs,verdict:"BLOCK"};eq(e.verifyObservedExecutionReceipt(tamperObs,{contract:read,executionReceipt:receipt}),false);

const mutation=e.createCommandContract({profile,root,grant,principalId:"user-1",taskId:"fix",executable:"node",argv:["fix.cjs"],cwd:"src",effectClass:"PROJECT_MUTATION",effectKey:"effect-1",transactionRef:"tx-1",reads:[{action:"READ",path:"src/a.js"}],writes:[{action:"PATCH",path:"src/a.js"}],timeoutMs:30000,now:NOW});
const mpre=e.createExecutionPreflight({contract:mutation,profile,attestation:att,projectManifestHash:H("manifest2"),grantSnapshotHash:H("grant2"),policySnapshotHash:H("policy2"),fileVersions:[{path:"src/a.js",state:"PRESENT",versionHash:H("a-v1")}],effectJournalHead:H("journal-head"),issuedAt:T,expiresAt:"2026-09-15T03:05:00Z"});eq(mpre.effectJournalHead,H("journal-head"));
throws(()=>e.createExecutionPreflight({contract:mutation,profile,attestation:att,projectManifestHash:H("m"),grantSnapshotHash:H("g"),policySnapshotHash:H("p"),fileVersions:[{path:"src/a.js",state:"ABSENT"}],effectJournalHead:H("j"),issuedAt:T,expiresAt:"2026-09-15T03:05:00Z"}),/non-CREATE write target cannot be absent/);
const mfail=e.createExecutionReceipt({contract:mutation,profile,transportStatus:"TIMED_OUT",exitCode:null,stdout:"",stderr:"",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:00:31Z",adapterId:"android-exec-adapter",outputTruncated:false});const mobs=e.createObservedExecutionReceipt({contract:mutation,profile,executionReceipt:mfail,preflight:mpre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["src/a.js"],actualWrites:["src/a.js"],observedDomains:[],producedStdoutBytes:0,producedStderrBytes:0});eq(mobs.verdict,"PASS");
throws(()=>e.createRetryPermit({contract:mutation,executionReceipt:mfail,observedReceipt:mobs,attempt:2,issuedAt:"2026-09-15T03:00:32Z",expiresAt:"2026-09-15T03:05:00Z"}),/verified absence reconciliation/);
const absent=e.createAbsenceReconciliation({contract:mutation,executionReceipt:mfail,observedReceipt:mobs,evidenceHashes:[H("transaction-proves-no-commit")],verifier:"transaction-ledger",checkedAt:"2026-09-15T03:00:32Z"});ok(e.verifyAbsenceReconciliation(absent,{contract:mutation,executionReceipt:mfail,observedReceipt:mobs}));eq(absent.status,"VERIFIED_ABSENT");eq(absent.grantsAuthority,false);
const retry=e.createRetryPermit({contract:mutation,executionReceipt:mfail,observedReceipt:mobs,absenceReconciliation:absent,attempt:2,issuedAt:"2026-09-15T03:00:32Z",expiresAt:"2026-09-15T03:05:00Z"});ok(e.verifyRetryPermit(retry,{contract:mutation,executionReceipt:mfail,observedReceipt:mobs,now:Date.parse("2026-09-15T03:01:00Z")}));eq(retry.attempt,2);eq(retry.effectKey,"effect-1");eq(retry.transactionRef,"tx-1");eq(retry.grantsAuthority,false);eq(e.verifyRetryPermit(retry,{now:Date.parse("2026-09-15T03:06:00Z")}),false);
throws(()=>e.createRetryPermit({contract:mutation,executionReceipt:mfail,observedReceipt:mobs,absenceReconciliation:absent,attempt:4,issuedAt:"2026-09-15T03:00:32Z",expiresAt:"2026-09-15T03:05:00Z"}),/bounded policy/);
const readFail=e.createExecutionReceipt({contract:read,profile,transportStatus:"FAILED",exitCode:1,stdout:"",stderr:"x",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:00:02Z",adapterId:"android-exec-adapter",outputTruncated:false});const readFailObs=e.createObservedExecutionReceipt({contract:read,profile,executionReceipt:readFail,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node-bin")},actualReads:["tests/all.cjs"],actualWrites:[],observedDomains:[],producedStdoutBytes:0,producedStderrBytes:1});const readRetry=e.createRetryPermit({contract:read,executionReceipt:readFail,observedReceipt:readFailObs,attempt:2,issuedAt:"2026-09-15T03:00:03Z",expiresAt:"2026-09-15T03:05:00Z"});ok(e.verifyRetryPermit(readRetry,{contract:read,now:Date.parse("2026-09-15T03:01:00Z")}));eq(readRetry.absenceReconciliationSeal,null);
throws(()=>e.createRetryPermit({contract:read,executionReceipt:receipt,observedReceipt:obs,attempt:2,issuedAt:"2026-09-15T03:00:03Z",expiresAt:"2026-09-15T03:05:00Z"}),/not retryable/);
const forgedAbsent={...absent,effectKey:"other"};eq(e.verifyAbsenceReconciliation(forgedAbsent,{contract:mutation}),false);
console.log(`Native Execution Fabric Pass B: PASS (${n} assertions)`);
