"use strict";
const assert=require("assert");
const e=require("./native-execution-fabric-final.cjs");
const f=require("./project-file-fabric.cjs");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.strictEqual(a,b,m);n++},throws=(fn,re,m)=>{assert.throws(fn,re,m);n++};const H=x=>e.sha(x),T="2026-09-15T03:00:00Z",NOW=Date.parse(T);
const root=f.createProjectRoot({rootId:"r",backendId:"local",backendRootRef:"workspace",grantEpoch:1});const grant=f.createProjectGrant({grantId:"g",principalId:"u",projectRootId:root.id,actions:["READ","PATCH","EXECUTE"],prefixes:["src"],sourceEventId:"event"});const profile=e.createExecutorProfile({executorId:"exec",revision:"1",platform:"android",allowedExecutables:["node"],allowedEnvKeys:[],maxRuntimeMs:60000,maxOutputBytes:4096,maxArgBytes:1024,supportsCancellation:true,networkAllowed:false});const att=e.createAdapterAttestation({profile,adapterId:"adapter",adapterRevision:"1",executableIdentities:[{name:"node",resolvedPath:"/usr/bin/node",sha256:H("node")}],producer:"platform",evidenceHashes:[H("att")],attestedAt:T,expiresAt:"2026-09-16T03:00:00Z"});
const cmd=e.createCommandContract({profile,root,grant,principalId:"u",taskId:"mut",executable:"node",argv:["fix.js"],cwd:"src",effectClass:"PROJECT_MUTATION",effectKey:"effect",transactionRef:"tx",reads:[{action:"READ",path:"src/a.js"}],writes:[{action:"PATCH",path:"src/a.js"}],timeoutMs:30000,now:NOW});const pre=e.createExecutionPreflight({contract:cmd,profile,attestation:att,projectManifestHash:H("m"),grantSnapshotHash:H("g"),policySnapshotHash:H("p"),fileVersions:[{path:"src/a.js",state:"PRESENT",versionHash:H("v1")}],effectJournalHead:H("j"),issuedAt:T,expiresAt:"2026-09-15T03:05:00Z"});
function failed(start="2026-09-15T03:00:01Z",end="2026-09-15T03:00:05Z"){return e.createExecutionReceipt({contract:cmd,profile,transportStatus:"TIMED_OUT",exitCode:null,stdout:"",stderr:"",startedAt:start,endedAt:end,adapterId:"adapter",outputTruncated:false})}
function observed(r,writes=["src/a.js"]){return e.createObservedExecutionReceipt({contract:cmd,profile,executionReceipt:r,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node")},actualReads:["src/a.js"],actualWrites:writes,observedDomains:[],producedStdoutBytes:0,producedStderrBytes:0})}
const r1=failed(),o1=observed(r1);eq(o1.verdict,"PASS");const a1=e.createAbsenceReconciliation({contract:cmd,executionReceipt:r1,observedReceipt:o1,evidenceHashes:[H("absent")],verifier:"tx-ledger",checkedAt:"2026-09-15T03:00:06Z"});const p1=e.createRetryPermit({contract:cmd,executionReceipt:r1,observedReceipt:o1,absenceReconciliation:a1,attempt:2,issuedAt:"2026-09-15T03:00:07Z",expiresAt:"2026-09-15T03:05:00Z"});ok(e.verifyRetryPermit(p1,{contract:cmd,now:Date.parse("2026-09-15T03:01:00Z")}));
const blocked=observed(r1,["src/a.js","src/extra.js"]);eq(blocked.verdict,"BLOCK");throws(()=>e.createRetryPermit({contract:cmd,executionReceipt:r1,observedReceipt:blocked,absenceReconciliation:a1,attempt:2,issuedAt:"2026-09-15T03:00:07Z",expiresAt:"2026-09-15T03:05:00Z"}),/blocked observed execution/);
const earlyAbs=e.createAbsenceReconciliation({contract:cmd,executionReceipt:r1,observedReceipt:o1,evidenceHashes:[H("early")],verifier:"tx-ledger",checkedAt:"2026-09-15T03:00:04Z"});throws(()=>e.createRetryPermit({contract:cmd,executionReceipt:r1,observedReceipt:o1,absenceReconciliation:earlyAbs,attempt:2,issuedAt:"2026-09-15T03:00:07Z",expiresAt:"2026-09-15T03:05:00Z"}),/chronology invalid/);
throws(()=>e.createRetryPermit({contract:cmd,executionReceipt:r1,observedReceipt:o1,absenceReconciliation:a1,attempt:2,issuedAt:"2026-09-15T03:00:04Z",expiresAt:"2026-09-15T03:05:00Z"}),/before prior execution ended/);
let ledger=e.createRetryLedger({id:"run-retries",commandSeal:cmd.seal});ok(e.verifyRetryLedger(ledger));eq(ledger.revision,0);ledger=e.consumeRetryPermit(ledger,p1,{contract:cmd,executionReceipt:r1,observedReceipt:o1,now:Date.parse("2026-09-15T03:01:00Z")});ok(e.verifyRetryLedger(ledger));eq(ledger.revision,1);eq(ledger.consumed[0].attempt,2);throws(()=>e.consumeRetryPermit(ledger,p1,{contract:cmd,executionReceipt:r1,observedReceipt:o1,now:Date.parse("2026-09-15T03:01:10Z")}),/already consumed|replay/);
const forgedLedger={...ledger,revision:9};eq(e.verifyRetryLedger(forgedLedger),false);
const other=e.createRetryLedger({id:"other",commandSeal:H("other")});throws(()=>e.consumeRetryPermit(other,p1,{contract:cmd,executionReceipt:r1,observedReceipt:o1,now:NOW}),/command mismatch/);
const okReceipt=e.createExecutionReceipt({contract:cmd,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"ok",stderr:"",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:00:02Z",adapterId:"adapter",outputTruncated:false});const okObs=e.createObservedExecutionReceipt({contract:cmd,profile,executionReceipt:okReceipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node")},actualReads:["src/a.js"],actualWrites:["src/a.js"],observedDomains:[],producedStdoutBytes:2,producedStderrBytes:0});const okVerify=e.createExecutionVerification({executionReceipt:okReceipt,contract:cmd,status:"PASS",evidenceHashes:[H("post")],checker:"tx",checkedAt:"2026-09-15T03:00:03Z",reconciliation:{transactionRef:"tx",status:"VERIFIED",postconditionHash:H("postcondition")}});let d=e.successDecisionFinal({contract:cmd,executionReceipt:okReceipt,verification:okVerify,observedReceipt:okObs,preflight:pre,attestation:att});eq(d.success,true);
const truncReceipt=e.createExecutionReceipt({contract:cmd,profile,transportStatus:"COMPLETED",exitCode:0,stdout:"ok",stderr:"",startedAt:"2026-09-15T03:00:01Z",endedAt:"2026-09-15T03:00:02Z",adapterId:"adapter",outputTruncated:true});const truncObs=e.createObservedExecutionReceipt({contract:cmd,profile,executionReceipt:truncReceipt,preflight:pre,attestation:att,observedExecutable:{resolvedPath:"/usr/bin/node",sha256:H("node")},actualReads:["src/a.js"],actualWrites:["src/a.js"],observedDomains:[],producedStdoutBytes:9,producedStderrBytes:0});const truncVerify=e.createExecutionVerification({executionReceipt:truncReceipt,contract:cmd,status:"PASS",evidenceHashes:[H("post2")],checker:"tx",checkedAt:"2026-09-15T03:00:03Z",reconciliation:{transactionRef:"tx",status:"VERIFIED",postconditionHash:H("postcondition2")}});d=e.successDecisionFinal({contract:cmd,executionReceipt:truncReceipt,verification:truncVerify,observedReceipt:truncObs,preflight:pre,attestation:att});eq(d.success,false);ok(d.reasons.includes("truncated-output-cannot-establish-final-success"));
console.log(`Native Execution Fabric Final Guard: PASS (${n} assertions)`);
