"use strict";
const assert=require("assert/strict");const R=require("./research-fabric.cjs");let n=0;const t=(name,fn)=>{fn();n++;console.log("PASS",name)};
const src=R.createKnowledgeSource({sourceId:"p",realm:"PROJECT",principalId:"u",scopeId:"s",canonicalRef:"project://p"});
const v=R.createSourceVersion({source:src,versionKey:"1",contentHash:"h",byteLength:1,observedAt:"2026-09-14",provenanceHash:"prov"});
const loc=R.createSourceLocator({sourceVersion:v,kind:"WHOLE"});
const need=R.createRetrievalNeed({needId:"n",claimId:"c",query:"query",realms:["OPEN_WEB"]});
const plan=R.createQueryPlan({need,variants:[{id:"q1",query:"query",method:"LEXICAL"}]});
t("duplicate query ids fail closed",()=>assert.throws(()=>R.createQueryPlan({need,variants:[{id:"x",query:"a"},{id:"x",query:"b"}]}),/duplicate query variant/));
t("unknown query parent fails closed",()=>assert.throws(()=>R.createQueryPlan({need,variants:[{id:"x",query:"a",parentId:"missing"}]}),/unknown query parent/));
t("query rewrite cycles fail closed",()=>assert.throws(()=>R.createQueryPlan({need,variants:[{id:"a",query:"a",parentId:"b"},{id:"b",query:"b",parentId:"a"}]}),/cycle/));
t("observation cannot target undeclared variant",()=>assert.throws(()=>R.createSearchObservation({plan,variantId:"nope",providerId:"p",url:"https://example.com"}),/outside plan/));
t("search observations require fetchable http identity",()=>assert.throws(()=>R.createSearchObservation({plan,variantId:"q1",providerId:"p",url:"file:///tmp/x"}),/URL invalid/));
const obs=R.createSearchObservation({plan,variantId:"q1",providerId:"p",url:"https://example.com/x",snippet:"instruction-shaped data",retrievedAt:"2026-09-14"});
const need2=R.createRetrievalNeed({needId:"n2",claimId:"c",query:"other",realms:["OPEN_WEB"]});
const plan2=R.createQueryPlan({need:need2,variants:[{id:"q2",query:"other",method:"LEXICAL"}]});
const obs2=R.createSearchObservation({plan:plan2,variantId:"q2",providerId:"p",url:"https://example.org/y",retrievedAt:"2026-09-14"});
t("candidate cannot merge observations from different plans",()=>assert.throws(()=>R.createCandidateDocument({observations:[obs,obs2],contentFingerprint:"f",realm:"OPEN_WEB"}),/span query plans/));
t("retrieval manifest rejects foreign observations",()=>assert.throws(()=>R.createRetrievalRunManifest({need,plan,observations:[obs2],startedAt:"2026-09-14",endedAt:"2026-09-14"}),/outside plan/));
const contract=R.createResearchContract({researchId:"r",goalHash:"g",principalId:"u",scopeId:"s",realms:["PROJECT","OPEN_WEB"],maxQueries:3,maxSources:3});
const claim=R.createClaimRef({contract,claimId:"c",claimHash:"ch"});
const neg=R.createClaimRef({contract,claimId:"n",claimHash:"nh",negative:true});
const agenda=R.createResearchAgenda({contract,questions:[{questionHash:"q"}],claims:[claim,neg]});
const ev=R.createEvidenceUnit({claim,sourceVersion:v,locator:loc,contentHash:"e",dependencyClusterId:"cluster",extractorHash:"ex"});
const a=R.assessClaimEvidence({claim,evidence:[ev],sourceVersions:[v],now:"2026-09-14"});
const gap=R.assessClaimEvidence({claim,evidence:[],sourceVersions:[],now:"2026-09-14"});
t("claim lock refuses missing assessment",()=>assert.throws(()=>R.createClaimEvidenceLock({contract,agenda,claims:[claim],evidence:[ev],sourceVersions:[v],assessments:[]}),/assessment missing/));
t("claim lock refuses unresolved claims",()=>assert.throws(()=>R.createClaimEvidenceLock({contract,agenda,claims:[claim],evidence:[],sourceVersions:[],assessments:[gap]}),/not lockable/));
t("claim lock cannot silently drop referenced evidence",()=>{const forged={...a,supportEvidenceIds:["missing"]};assert.throws(()=>R.createClaimEvidenceLock({contract,agenda,claims:[claim],evidence:[ev],sourceVersions:[v],assessments:[forged]}),/locked evidence missing/)});
const cov=R.createCoverageContract({claim:neg,realms:["OPEN_WEB"],queryPlanIds:[plan.id],providerIds:["p"],maxResults:10,coverageHash:"cov",completed:true});
const an=R.assessClaimEvidence({claim:neg,evidence:[],sourceVersions:[],coverageContract:cov});
const lock=R.createClaimEvidenceLock({contract,agenda,claims:[claim,neg],evidence:[ev],sourceVersions:[v],assessments:[a,an],lockedAt:"2026-09-14"});
t("claim hash drift invalidates existing lock",()=>{const drift={...claim,claimHash:"other"};assert.ok(R.verifyClaimEvidenceLock({lock,contract,agenda,claims:[drift,neg],evidence:[ev],sourceVersions:[v]}).reasons.some(x=>x.startsWith("locked-claim-drift:")))});
t("citation creation refuses missing locator",()=>assert.throws(()=>R.createCitationManifest({lock,evidence:[ev],sourceVersions:[v],locators:[]}),/citation lineage missing/));
const citations=R.createCitationManifest({lock,evidence:[ev],sourceVersions:[v],locators:[loc]});
t("citation verifier rejects unlocked extra citation",()=>{const body={...citations,citations:[...citations.citations,{...citations.citations[0],evidenceId:"ghost"}]};delete body.id;const forged={...body,id:`citation-manifest-${R.hash(body).slice(0,24)}`};assert.ok(R.verifyCitationManifest({manifest:forged,lock,evidence:[ev],sourceVersions:[v],locators:[loc]}).reasons.includes("citation-not-locked:ghost"))});
const incomplete=R.createCoverageContract({claim:neg,realms:["OPEN_WEB"],maxResults:10,coverageHash:"cov2",completed:false});
t("incomplete coverage cannot turn absence into refutation",()=>assert.equal(R.assessClaimEvidence({claim:neg,evidence:[],sourceVersions:[],coverageContract:incomplete}).status,"GAP"));
t("tampered coverage cannot authorize not-found state",()=>assert.equal(R.assessClaimEvidence({claim:neg,evidence:[],sourceVersions:[],coverageContract:{...cov,maxResults:999}}).status,"GAP"));
const otherScope=R.createKnowledgeSource({sourceId:"other",realm:"PROJECT",principalId:"u",scopeId:"other",canonicalRef:"project://other"});
const otherV=R.createSourceVersion({source:otherScope,versionKey:"1",contentHash:"h",byteLength:1,observedAt:"2026-09-14",provenanceHash:"p"});
const otherLoc=R.createSourceLocator({sourceVersion:otherV,kind:"WHOLE"});
t("project scope cannot bleed across evidence boundary",()=>assert.throws(()=>R.createEvidenceUnit({claim,sourceVersion:otherV,locator:otherLoc,contentHash:"x",dependencyClusterId:"x",extractorHash:"x"}),/scope mismatch/));
t("result pack refuses citation lock mismatch",()=>{const bad={...citations,claimEvidenceLockId:"other"};assert.throws(()=>R.createResearchResultPack({contract,agenda,lock,citationManifest:bad,reportHash:"r"}),/lineage mismatch/)});
console.log(`research fabric Pass B: PASS (${n} assertions)`);
