"use strict";
const crypto=require("crypto");
const TITLE_STATUS=Object.freeze({OFFICIAL:"OFFICIAL",OFFICIAL_LOCALIZED:"OFFICIAL_LOCALIZED",USER_DEFINED:"USER_DEFINED",SEVEN_GENERATED:"SEVEN_GENERATED",IN_WORLD_GENERATED:"IN_WORLD_GENERATED",PLACEHOLDER:"PLACEHOLDER",UNKNOWN:"UNKNOWN"});
const DOMAIN=Object.freeze({WORK:"WORK",SEASON:"SEASON",ARC:"ARC",CHAPTER:"CHAPTER",EPISODE:"EPISODE",SCENE:"SCENE",SIDE_STORY:"SIDE_STORY",SPECIAL:"SPECIAL",WHAT_IF:"WHAT_IF",QUEST:"QUEST",LOCATION:"LOCATION",ITEM:"ITEM",ABILITY:"ABILITY",FACTION:"FACTION",CHARACTER_EPITHET:"CHARACTER_EPITHET",GAME:"GAME"});
const A=v=>Array.isArray(v)?v:[],C=v=>v==null?v:JSON.parse(JSON.stringify(v)),F=Object.freeze;
function R(v,n){const s=String(v??"").trim();if(!s)throw new Error(`${n} required`);return s}
function S(v){if(Array.isArray(v))return v.map(S);if(v&&typeof v==="object"){const o={};for(const k of Object.keys(v).sort())if(v[k]!==undefined)o[k]=S(v[k]);return o}return v}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(S(v))).digest("hex")}
function U(v){return [...new Set(A(v).map(String))]}
function E(v,set,n){const s=String(v??"").toUpperCase();if(!Object.values(set).includes(s))throw new Error(`${n} invalid:${v}`);return s}
function normalizeText(v){return String(v??"").normalize("NFKC").trim().replace(/\s+/g," ").toLocaleLowerCase("und")}
function collisionKey(text,locale="und"){return `${String(locale).toLowerCase()}:${normalizeText(text).replace(/[\p{P}\p{S}\s]+/gu,"")}`}
function toArabicIndicDigits(s){const d="٠١٢٣٤٥٦٧٨٩";return String(s).replace(/\d/g,x=>d[Number(x)])}
function createWorldLanguageProfile(i={}){const evidenceRefs=U(i.evidenceRefs);if(!evidenceRefs.length)throw new Error("WorldLanguageProfile requires source-bound evidence");const b={id:R(i.id,"profile.id"),worldId:R(i.worldId,"profile.worldId"),version:R(i.version??"1","profile.version"),locale:R(i.locale??"en","profile.locale"),direction:String(i.direction??(String(i.locale||"").startsWith("ar")?"RTL":"LTR")).toUpperCase(),evidenceRefs,lexicalRules:C(i.lexicalRules??{}),punctuation:C(i.punctuation??{}),numbering:C(i.numbering??{}),forbiddenPatterns:U(i.forbiddenPatterns),styleConstraints:U(i.styleConstraints)};if(!["LTR","RTL"].includes(b.direction))throw new Error("profile.direction invalid");return F({...b,profileHash:hash(b)})}
function verifyProfile(p){if(!p?.profileHash)return false;const b={id:p.id,worldId:p.worldId,version:p.version,locale:p.locale,direction:p.direction,evidenceRefs:p.evidenceRefs,lexicalRules:p.lexicalRules,punctuation:p.punctuation,numbering:p.numbering,forbiddenPatterns:p.forbiddenPatterns,styleConstraints:p.styleConstraints};return p.profileHash===hash(b)&&A(p.evidenceRefs).length>0}
function createNamingGrammar(p,i={}){if(!verifyProfile(p))throw new Error("valid WorldLanguageProfile required");const domain=E(i.domain,DOMAIN,"grammar.domain"),templates=A(i.templates).map(String).filter(Boolean);if(!templates.length)throw new Error("NamingGrammar requires deterministic template");const b={id:R(i.id,"grammar.id"),profileId:p.id,profileHash:p.profileHash,domain,version:R(i.version??"1","grammar.version"),templates,requiredTokens:U(i.requiredTokens),forbiddenTokens:U(i.forbiddenTokens),maxLength:Number.isInteger(i.maxLength)?i.maxLength:96,allowModelAssist:i.allowModelAssist===true,numbering:C(i.numbering??p.numbering??{})};if(b.maxLength<1||b.maxLength>256)throw new Error("grammar.maxLength invalid");return F({...b,grammarHash:hash(b)})}
function verifyGrammar(g,p=null){if(!g?.grammarHash)return false;const b={id:g.id,profileId:g.profileId,profileHash:g.profileHash,domain:g.domain,version:g.version,templates:g.templates,requiredTokens:g.requiredTokens,forbiddenTokens:g.forbiddenTokens,maxLength:g.maxLength,allowModelAssist:g.allowModelAssist,numbering:g.numbering};return g.grammarHash===hash(b)&&(!p||(verifyProfile(p)&&g.profileId===p.id&&g.profileHash===p.profileHash))}
function createNamingEvidenceRef(i={}){const b={id:R(i.id,"evidence.id"),sourceVersionId:R(i.sourceVersionId,"evidence.sourceVersionId"),sourceVersionHash:R(i.sourceVersionHash,"evidence.sourceVersionHash"),locator:C(i.locator)};if(!b.locator||typeof b.locator!=="object"||!Object.keys(b.locator).length)throw new Error("naming evidence locator required");return F({...b,evidenceHash:hash(b)})}
function createNamingRequest(p,g,i={}){if(!verifyProfile(p)||!verifyGrammar(g,p))throw new Error("profile/grammar binding invalid");const b={id:R(i.id,"request.id"),worldId:p.worldId,profileId:p.id,profileHash:p.profileHash,grammarId:g.id,grammarHash:g.grammarHash,domain:g.domain,subjectId:R(i.subjectId,"request.subjectId"),branchId:i.branchId?String(i.branchId):null,locale:String(i.locale??p.locale),context:C(i.context??{}),seed:R(i.seed??"0","request.seed"),desiredStatus:E(i.desiredStatus??TITLE_STATUS.SEVEN_GENERATED,TITLE_STATUS,"request.desiredStatus")};return F({...b,requestHash:hash(b)})}
function verifyRequest(r,p,g){if(!r?.requestHash)return false;const b={id:r.id,worldId:r.worldId,profileId:r.profileId,profileHash:r.profileHash,grammarId:r.grammarId,grammarHash:r.grammarHash,domain:r.domain,subjectId:r.subjectId,branchId:r.branchId??null,locale:r.locale,context:r.context,seed:r.seed,desiredStatus:r.desiredStatus};return r.requestHash===hash(b)&&verifyProfile(p)&&verifyGrammar(g,p)&&r.profileHash===p.profileHash&&r.grammarHash===g.grammarHash}
function seededIndex(seed,n){const h=crypto.createHash("sha256").update(String(seed)).digest();return n?h.readUInt32BE(0)%n:0}
function render(t,c){return String(t).replace(/\{([A-Za-z0-9_.-]+)\}/g,(_,k)=>{let v=c;for(const p of k.split(".")){if(v==null||!Object.prototype.hasOwnProperty.call(v,p))return "";v=v[p]}return String(v??"")}).replace(/\s+/g," ").trim()}
function generateDeterministic(p,g,r){if(!verifyRequest(r,p,g))throw new Error("request binding invalid");let text=render(g.templates[seededIndex(`${r.requestHash}:${r.seed}`,g.templates.length)],r.context);if((g.numbering?.digits??p.numbering?.digits)==="ARABIC_INDIC"||((r.locale||"").startsWith("ar")&&g.numbering?.arabicIndic===true))text=toArabicIndicDigits(text);const c={id:`cand:${hash({request:r.requestHash,text}).slice(0,16)}`,requestId:r.id,requestHash:r.requestHash,text,status:r.desiredStatus,locale:r.locale,branchId:r.branchId,origin:"DETERMINISTIC",evidenceRefs:[],modelRevision:null};return F({...c,candidateHash:hash(c)})}
function createModelCandidate(p,g,r,i={}){if(!verifyRequest(r,p,g))throw new Error("request binding invalid");if(!g.allowModelAssist)throw new Error("model-assisted naming disabled by grammar");const text=R(i.text,"candidate.text"),modelRevision=R(i.modelRevision,"candidate.modelRevision"),c={id:R(i.id??`cand:${hash({request:r.requestHash,text,modelRevision}).slice(0,16)}`,"candidate.id"),requestId:r.id,requestHash:r.requestHash,text,status:r.desiredStatus,locale:r.locale,branchId:r.branchId,origin:"MODEL",evidenceRefs:U(i.evidenceRefs),modelRevision};return F({...c,candidateHash:hash(c)})}
function createOfficialCandidate(p,g,r,i={}){if(!verifyRequest(r,p,g))throw new Error("request binding invalid");const status=E(i.status??TITLE_STATUS.OFFICIAL,TITLE_STATUS,"official.status"),evidenceRefs=U(i.evidenceRefs);if(![TITLE_STATUS.OFFICIAL,TITLE_STATUS.OFFICIAL_LOCALIZED].includes(status))throw new Error("official candidate status invalid");if(!evidenceRefs.length)throw new Error("official title requires evidence");const c={id:R(i.id??`official:${hash({request:r.requestHash,text:i.text}).slice(0,16)}`,"candidate.id"),requestId:r.id,requestHash:r.requestHash,text:R(i.text,"candidate.text"),status,locale:r.locale,branchId:r.branchId,origin:"OFFICIAL_EVIDENCE",evidenceRefs,modelRevision:null};return F({...c,candidateHash:hash(c)})}
function TitleRegistry(i={}){const identities={};for(const x of A(i.identities)){if(!x?.id)throw new Error("registry identity id required");if(identities[x.id])throw new Error(`registry duplicate:${x.id}`);identities[x.id]=C(x)}const b={id:R(i.id??"titles","registry.id"),identities,revision:Number.isInteger(i.revision)?i.revision:0};return F({...b,registryHash:hash(b)})}
function verifyRegistry(r){return !!r?.registryHash&&r.registryHash===hash({id:r.id,identities:r.identities,revision:r.revision})}
function aliases(x){return [x.text,...A(x.aliases).map(a=>typeof a==="string"?a:a.text),...A(x.localizations).map(a=>a.text)].filter(Boolean)}
function detectCollisions(reg,c){if(!verifyRegistry(reg))throw new Error("registry invalid");const key=collisionKey(c.text,c.locale),out=[];for(const x of Object.values(reg.identities)){if((x.branchId??null)!==(c.branchId??null)&&x.branchId&&c.branchId)continue;for(const text of aliases(x))if(collisionKey(text,c.locale)===key){out.push(F({identityId:x.id,text,collisionKey:key,branchId:x.branchId??null}));break}}return out}
function validateCandidate(p,g,r,c,reg=TitleRegistry()){const issues=[];if(!verifyRequest(r,p,g))issues.push("request-binding");if(c.requestHash!==r.requestHash)issues.push("candidate-request-drift");const text=String(c.text??"").trim();if(!text)issues.push("empty-title");if([...text].length>g.maxLength)issues.push("title-too-long");for(const t of g.requiredTokens)if(!normalizeText(text).includes(normalizeText(t)))issues.push(`required-token:${t}`);for(const t of g.forbiddenTokens)if(normalizeText(text).includes(normalizeText(t)))issues.push(`forbidden-token:${t}`);for(const q of p.forbiddenPatterns){try{if(new RegExp(q,"iu").test(text))issues.push(`forbidden-pattern:${q}`)}catch{issues.push(`invalid-profile-pattern:${q}`)}}if([TITLE_STATUS.OFFICIAL,TITLE_STATUS.OFFICIAL_LOCALIZED].includes(c.status)&&!A(c.evidenceRefs).length)issues.push("official-without-evidence");if(c.origin==="MODEL"&&!g.allowModelAssist)issues.push("model-assist-disabled");const collisions=detectCollisions(reg,c);if(collisions.length)issues.push("collision");return F({status:issues.length?"BLOCKED":"PASS",issues,collisions,candidateHash:c.candidateHash})}
function decideNaming(p,g,r,candidates,reg=TitleRegistry()){const evaluated=A(candidates).map(c=>({candidate:c,validation:validateCandidate(p,g,r,c,reg)})),viable=evaluated.filter(x=>x.validation.status==="PASS");if(!viable.length)return F({status:"BLOCKED",reason:"no-valid-candidate",evaluated});viable.sort((a,b)=>{const rank=x=>[TITLE_STATUS.OFFICIAL,TITLE_STATUS.OFFICIAL_LOCALIZED].includes(x.candidate.status)?0:1;return rank(a)-rank(b)||a.candidate.text.length-b.candidate.text.length||a.candidate.candidateHash.localeCompare(b.candidate.candidateHash)});const chosen=viable[0].candidate,b={requestId:r.id,requestHash:r.requestHash,candidateId:chosen.id,candidateHash:chosen.candidateHash,status:chosen.status};return F({status:"PASS",chosen,decisionHash:hash(b),evaluated})}
function createTitleIdentity(p,g,r,d,i={}){if(d?.status!=="PASS")throw new Error("passing naming decision required");const c=d.chosen;if([TITLE_STATUS.OFFICIAL,TITLE_STATUS.OFFICIAL_LOCALIZED].includes(c.status)&&!A(c.evidenceRefs).length)throw new Error("official title evidence missing");const b={id:R(i.id??`title:${r.subjectId}:${r.domain}`,"identity.id"),worldId:r.worldId,subjectId:r.subjectId,domain:r.domain,text:c.text,status:c.status,locale:c.locale,branchId:c.branchId??null,evidenceRefs:U(c.evidenceRefs),requestHash:r.requestHash,candidateHash:c.candidateHash,decisionHash:d.decisionHash,aliases:A(i.aliases).map(C),localizations:[]};return F({...b,identityHash:hash(b)})}
function createLocalizationVariant(x,i={}){const status=E(i.status??TITLE_STATUS.SEVEN_GENERATED,TITLE_STATUS,"localization.status"),evidenceRefs=U(i.evidenceRefs);if(status===TITLE_STATUS.OFFICIAL_LOCALIZED&&!evidenceRefs.length)throw new Error("official localization requires evidence");if(status===TITLE_STATUS.OFFICIAL)throw new Error("localization cannot use OFFICIAL primary status");const b={id:R(i.id??`${x.id}:${i.locale}`,"localization.id"),titleIdentityId:x.id,titleIdentityHash:x.identityHash,locale:R(i.locale,"localization.locale"),text:R(i.text,"localization.text"),status,evidenceRefs,branchId:x.branchId??null,direction:String(i.direction??(String(i.locale||"").startsWith("ar")?"RTL":"LTR")).toUpperCase()};return F({...b,localizationHash:hash(b)})}
function appendIdentity(reg,x){if(!verifyRegistry(reg))throw new Error("registry invalid");if(reg.identities[x.id])throw new Error("identity already exists");if(detectCollisions(reg,{text:x.text,locale:x.locale,branchId:x.branchId}).length)throw new Error("identity collision");return TitleRegistry({id:reg.id,revision:reg.revision+1,identities:[...Object.values(reg.identities),x]})}
function createNamingManifest(p,g,r,d,i={}){if(!verifyProfile(p)||!verifyGrammar(g,p)||!verifyRequest(r,p,g)||d?.status!=="PASS")throw new Error("manifest dependencies invalid");const b={id:R(i.id??`manifest:${r.id}`,"manifest.id"),profileId:p.id,profileHash:p.profileHash,grammarId:g.id,grammarHash:g.grammarHash,requestId:r.id,requestHash:r.requestHash,seed:r.seed,modelRevision:d.chosen.modelRevision??null,candidateHash:d.chosen.candidateHash,decisionHash:d.decisionHash,outputText:d.chosen.text,outputStatus:d.chosen.status};return F({...b,manifestHash:hash(b)})}
function verifyManifest(m,p,g,r,d){if(!m?.manifestHash)return false;const b={id:m.id,profileId:m.profileId,profileHash:m.profileHash,grammarId:m.grammarId,grammarHash:m.grammarHash,requestId:m.requestId,requestHash:m.requestHash,seed:m.seed,modelRevision:m.modelRevision??null,candidateHash:m.candidateHash,decisionHash:m.decisionHash,outputText:m.outputText,outputStatus:m.outputStatus};return m.manifestHash===hash(b)&&m.profileHash===p.profileHash&&m.grammarHash===g.grammarHash&&m.requestHash===r.requestHash&&m.candidateHash===d.chosen.candidateHash&&m.decisionHash===d.decisionHash}
module.exports=F({TITLE_STATUS,DOMAIN,hash,normalizeText,collisionKey,toArabicIndicDigits,createWorldLanguageProfile,verifyProfile,createNamingGrammar,verifyGrammar,createNamingEvidenceRef,createNamingRequest,verifyRequest,generateDeterministic,createModelCandidate,createOfficialCandidate,TitleRegistry,verifyRegistry,detectCollisions,validateCandidate,decideNaming,createTitleIdentity,createLocalizationVariant,appendIdentity,createNamingManifest,verifyManifest});