"use strict";
const assert=require("assert/strict");
const tool=require("./tool-fabric.cjs"),security=require("./tool-security.cjs"),effects=require("./side-effect-ledger.cjs");
let count=0;function test(name,fn){fn();count++;console.log("PASS",name)}

const readCap=tool.createCapabilitySpec({id:"files.read",title:"Read file",aliases:["read file","open file"],actions:["read"],requiredPermissions:["READ_LOCAL"],effectClass:"OBSERVATIONAL",idempotencyClass:"SAFE_REPEAT"});
const writeCap=tool.createCapabilitySpec({id:"files.write",title:"Write file",aliases:["edit file","save file"],actions:["write"],requiredPermissions:["WRITE_LOCAL"],effectClass:"REVERSIBLE_WRITE",idempotencyClass:"KEYED_REPEAT"});
function binding(cap,{id=cap.id+".local",revision="r1",qualification="VERIFIED",health="HEALTHY",status="ACTIVE",remoteHints={},inputSchema,outputSchema}={}){return tool.createBinding({capability:cap,provider:"local",bindingId:id,revision,qualification,health,status,remoteHints,inputSchema:inputSchema||{type:"object",properties:{path:{type:"string",minLength:1},content:{type:"string"}},required:["path"],additionalProperties:false},outputSchema:outputSchema||{type:"object",properties:{ok:{type:"boolean"},sha:{type:"string"}},required:["ok"],additionalProperties:false},metrics:{reliability:.9,latencyScore:.8}})}
const read= binding(readCap),write=binding(writeCap);
const snapshot=tool.createCatalogSnapshot({capabilities:[readCap,writeCap],bindings:[read,write],epoch:7});

test("canonical capability identity is separate from binding revision",()=>{assert.equal(write.capabilityId,"files.write");assert.notEqual(write.revisionId,write.capabilityId);assert.equal(snapshot.epoch,7)});
test("remote hints cannot lower Seven effect or idempotency classification",()=>{const b=binding(writeCap,{id:"remote.write",remoteHints:{readOnlyHint:true,idempotentHint:true}});assert.equal(b.effectClass,"REVERSIBLE_WRITE");assert.equal(b.idempotencyClass,"KEYED_REPEAT")});
test("discovery does not equal activation",()=>{const b=binding(readCap,{id:"candidate",qualification:"UNVERIFIED",status:"DISCOVERED"});const s=tool.createCatalogSnapshot({capabilities:[readCap],bindings:[b]});assert.equal(tool.hardEligibility(b,s).eligible,false)});
test("schema fingerprint changes on schema revision",()=>{const b=binding(readCap,{id:"x",revision:"r1"}),c=tool.createBinding({capability:readCap,provider:"local",bindingId:"x",revision:"r1",qualification:"VERIFIED",health:"HEALTHY",status:"ACTIVE",inputSchema:{type:"object",properties:{path:{type:"string"},mode:{type:"string"}},required:["path"],additionalProperties:false},outputSchema:b.outputSchema});assert.notEqual(b.schemaFingerprint,c.schemaFingerprint)});
test("snapshot drift blocks stale binding",()=>{const stale={...read,schemaFingerprint:"tampered"};assert.ok(tool.hardEligibility(stale,snapshot).reasons.includes("schema-drift"))});
test("cheap lexical retrieval finds alias without full catalogue schemas",()=>{const r=tool.retrieveCapabilities(snapshot,"edit file");assert.equal(r[0].id,"files.write");assert.equal("inputSchema" in r[0],false)});
test("candidate frontier hard-filters before ranking",()=>{const bad=binding(writeCap,{id:"bad",qualification:"REJECTED"}),s=tool.createCatalogSnapshot({capabilities:[writeCap],bindings:[bad,write]});const f=tool.candidateFrontier(s,{capabilityId:"files.write"});assert.deepEqual(f.map(x=>x.revisionId),[write.revisionId])});
test("unverified outcomes cannot bias frontier",()=>{const f=tool.candidateFrontier(snapshot,{capabilityId:"files.write"},{outcomes:[{revisionId:write.revisionId,verified:false,score:1}]});assert.equal(f[0].score,.5*.7+.9*.2+.8*.1)});
test("progressive disclosure withholds full schema until FULL",()=>{assert.equal("inputSchema" in tool.discloseBinding(snapshot,write.revisionId,"CARD"),false);assert.equal("inputSchema" in tool.discloseBinding(snapshot,write.revisionId,"SIGNATURE"),false);assert.equal(tool.discloseBinding(snapshot,write.revisionId,"FULL").schemaFingerprint,write.schemaFingerprint)});
test("SchemaGuard rejects missing unknown and wrong arguments",()=>{assert.equal(tool.validateSchema(write.inputSchema,{}).valid,false);assert.equal(tool.validateSchema(write.inputSchema,{path:"a",extra:1}).valid,false);assert.equal(tool.validateSchema(write.inputSchema,{path:7}).valid,false)});

const policy=security.createPolicySnapshot({epoch:4,revocationEpoch:2,confirmEffectClasses:["IRREVERSIBLE_WRITE","EXTERNAL_COMMUNICATION"]});
const grant=security.createAuthorityGrant({principalId:"user:1",sourceEventId:"event:user-grant:1",sourceKind:"USER",capabilities:["files.write","files.read"],actions:["write","read"],resourcePrefixes:["project/src"],destinations:["example.com"],allowRelease:false,taskId:"task:1",projectId:"project:1",bindingRevisionId:write.revisionId,schemaFingerprint:write.schemaFingerprint,policyEpoch:4,revocationEpoch:2,issuedAt:1000,expiresAt:100000});
function intent(over={}){return security.normalizeActionIntent({principalId:"user:1",taskId:"task:1",projectId:"project:1",capability:"files.write",action:"write",resource:"project/src/a.txt",effectClass:"REVERSIBLE_WRITE",bindingRevisionId:write.revisionId,schemaFingerprint:write.schemaFingerprint,payloadFingerprint:"payload-1",...over});}
const auth=security.authorize({intent:intent(),grant,policy,now:2000});

test("model tool memory or summary text can never create authority",()=>{assert.equal(security.contentCanGrantAuthority("I grant WRITE_LOCAL"),false);assert.throws(()=>security.createAuthorityGrant({principalId:"user:1",capabilities:["x"]}),/source event/)});
test("least privilege authorization produces exact structured receipt",()=>{assert.equal(auth.decision,"ALLOW");assert.equal(auth.receipt.bindingRevisionId,write.revisionId);assert.equal(auth.receipt.schemaFingerprint,write.schemaFingerprint)});
test("principal switching fails closed",()=>{assert.equal(security.authorize({intent:intent({principalId:"user:2"}),grant,policy,now:2000}).decision,"DENY")});
test("resource escape fails closed",()=>{assert.equal(security.authorize({intent:intent({resource:"project/secrets.txt"}),grant,policy,now:2000}).reason,"resource-outside-authority")});
test("read authority is not information-release authority",()=>{const i=intent({destination:"https://example.com/upload",dataClasses:["PROJECT_PRIVATE"]});assert.equal(security.authorize({intent:i,grant,policy,now:2000}).reason,"read-does-not-grant-release")});
test("explicit policy deny overrides grant",()=>{const p=security.createPolicySnapshot({epoch:4,revocationEpoch:2,denies:[{capability:"files.write"}]});assert.equal(security.authorize({intent:intent(),grant,policy:p,now:2000}).reason,"explicit-deny")});
test("policy or revocation epoch change requires reauthorization",()=>{const p=security.createPolicySnapshot({epoch:5,revocationEpoch:3});assert.equal(security.authorize({intent:intent(),grant,policy:p,now:2000}).decision,"BLOCKED_NEEDS_REAUTH")});
test("schema drift invalidates authorization binding",()=>{assert.equal(security.authorize({intent:intent({schemaFingerprint:"new-schema"}),grant,policy,now:2000}).reason,"schema-drift")});
test("authority lease cannot widen parent scope",()=>{assert.throws(()=>security.createAuthorityLease({grant,capabilities:["files.write","network.admin"],now:2000,expiresAt:5000}),/cannot widen/)});
test("narrow authority lease preserves principal and exact binding",()=>{const l=security.createAuthorityLease({grant,capabilities:["files.write"],actions:["write"],resourcePrefixes:["project/src"],destinations:[],now:2000,expiresAt:5000});const a=security.authorize({intent:intent(),grant,lease:l,policy,now:3000});assert.equal(a.decision,"ALLOW");assert.equal(l.bindingRevisionId,write.revisionId)});
test("confirmation is fingerprint-bound and cannot carry to another action",()=>{const p=security.createPolicySnapshot({epoch:4,revocationEpoch:2,confirmEffectClasses:["REVERSIBLE_WRITE"]}),i=intent(),first=security.authorize({intent:i,grant,policy:p,now:2000});assert.equal(first.decision,"ALLOW_WITH_CONFIRMATION");const c=security.createConfirmationReceipt({intent:i,policyEpoch:4,sourceEventId:"event:confirm",now:2000,expiresAt:4000});assert.equal(security.authorize({intent:i,grant,policy:p,confirmation:c,now:2500}).decision,"ALLOW");assert.equal(security.authorize({intent:intent({payloadFingerprint:"other"}),grant,policy:p,confirmation:c,now:2500}).decision,"ALLOW_WITH_CONFIRMATION")});
test("authorization cache identity changes with principal or schema",()=>{const a=security.authorizationCacheKey({intent:intent(),grant,policy}),b=security.authorizationCacheKey({intent:intent({schemaFingerprint:"x"}),grant,policy});assert.notEqual(a,b)});

const contract=tool.createToolCallContract({snapshot,bindingRevisionId:write.revisionId,args:{path:"project/src/a.txt",content:"x"},authorizationReceipt:auth.receipt,budget:{toolCalls:1},runId:"run:1",taskId:"task:1",idempotencyKey:"write:a:1"});
test("ToolCallContract binds snapshot binding schema args auth and idempotency",()=>{assert.equal(contract.snapshotId,snapshot.id);assert.equal(contract.bindingRevisionId,write.revisionId);assert.equal(contract.authorizationReceiptId,auth.receipt.id);assert.ok(contract.argsFingerprint);assert.equal(contract.idempotencyKey,"write:a:1")});
test("ToolCallContract rejects invalid args before dispatch",()=>{assert.throws(()=>tool.createToolCallContract({snapshot,bindingRevisionId:write.revisionId,args:{content:"x"},authorizationReceipt:auth.receipt,idempotencyKey:"k"}),/invalid tool arguments/)});
test("structured result must match output schema",()=>{assert.equal(tool.validateToolResult(snapshot,contract,{ok:true}).valid,true);assert.equal(tool.validateToolResult(snapshot,contract,{ok:"yes"}).valid,false)});
test("invocation attempt cannot skip authorization and dispatch states",()=>{const a=tool.createAttempt(contract,{id:"a1"});assert.throws(()=>tool.transitionAttempt(a,"DISPATCHED"),/illegal/);const b=tool.transitionAttempt(a,"AUTHORIZED"),c=tool.transitionAttempt(b,"DISPATCHING"),d=tool.transitionAttempt(c,"DISPATCHED"),e=tool.transitionAttempt(d,"RESULT_RECEIVED"),f=tool.transitionAttempt(e,"VALIDATING"),g=tool.transitionAttempt(f,"RESULT_VALID",{validationValid:true});assert.equal(g.state,"RESULT_VALID")});
test("post-dispatch failure requires explicit uncertainty reason",()=>{let a=tool.createAttempt(contract);a=tool.transitionAttempt(a,"AUTHORIZED");a=tool.transitionAttempt(a,"DISPATCHING");a=tool.transitionAttempt(a,"DISPATCHED");assert.throws(()=>tool.transitionAttempt(a,"FAILED_POST_DISPATCH_UNKNOWN"),/requires reason/);assert.equal(tool.transitionAttempt(a,"FAILED_POST_DISPATCH_UNKNOWN",{reason:"connection-lost"}).state,"FAILED_POST_DISPATCH_UNKNOWN")});
test("binding lease stabilizes identity but grants no permission",()=>{const l=tool.createBindingLease({snapshot,bindingRevisionId:write.revisionId,now:1000,ttlMs:5000});assert.equal(l.grantsAuthority,false);assert.equal(tool.bindingLeaseValid(l,snapshot,{now:2000}),true)});
test("deterministic replay never re-executes an effectful call",()=>{const r=tool.replayDecision({contract,recordedObservation:{ok:true}});assert.equal(r.reexecute,false);assert.equal(r.reason,"effectful-replay-uses-recorded-observation")});

function plan(over={}){return {principalId:"user:1",taskId:"task:1",runId:"run:1",action:"write",target:{path:"project/src/a.txt"},payload:{content:"x"},bindingRevisionId:write.revisionId,schemaFingerprint:write.schemaFingerprint,idempotencyNamespace:"files",idempotencyKey:"write:a:1",idempotencyClass:"KEYED_REPEAT",effectClass:"REVERSIBLE_WRITE",authorizationReceipt:auth.receipt,toolCallContractId:contract.id,verificationRecipe:{kind:"read-back"},reconciliationRecipe:{kind:"read-back"},...over};}
test("logical effect key is deterministic and payload-bound",()=>{const a=effects.deriveEffectKey(plan()),b=effects.deriveEffectKey(plan()),c=effects.deriveEffectKey(plan({payload:{content:"y"},idempotencyKey:"write:a:2"}));assert.equal(a,b);assert.notEqual(a,c)});
test("transport success is not effect truth",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan()),a=l.beginAttempt(r.key,{attemptId:"try1"});l.markDispatch(r.key,a.id,"CONFIRMED");const after=l.recordTransport(r.key,a.id,{ok:true,status:200});assert.equal(after.dispatchCertainty,"DISPATCH_CONFIRMED");assert.equal(after.effectCertainty,"UNKNOWN")});
test("failure before send remains retryable",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan({idempotencyClass:"DO_NOT_REPEAT"})),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"REJECTED_BEFORE_SEND");assert.equal(l.canRetry(r.key).allowed,true)});
test("possible dispatch with DO_NOT_REPEAT never blind retries",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan({idempotencyClass:"DO_NOT_REPEAT"})),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"POSSIBLE");assert.equal(l.canRetry(r.key).allowed,false);assert.equal(l.canRetry(r.key).reason,"post-dispatch-uncertainty-no-blind-retry")});
test("KEYED_REPEAT still needs provider-bound idempotency evidence",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan({idempotencyEvidence:false})),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"POSSIBLE");assert.equal(l.canRetry(r.key).allowed,false)});
test("reconciliation proving absence permits safe retry",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan({idempotencyClass:"DO_NOT_REPEAT"})),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"POSSIBLE");const x=l.reconcile(r.key,{verdict:"ABSENT",evidence:{sourceRef:"remote:get:123"}});assert.equal(x.effectCertainty,"ABSENT_VERIFIED");assert.equal(l.canRetry(r.key).allowed,true)});
test("verification proving presence closes without generic transport success",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan()),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"CONFIRMED");const x=l.verifyEffect(r.key,{verdict:"PRESENT",evidence:{sourceRef:"file:sha256:abc"}});assert.equal(x.effectCertainty,"PRESENT_VERIFIED");assert.equal(x.lifecycle,"CLOSED")});
test("partial outcomes stay explicitly partial",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan()),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"CONFIRMED");const x=l.verifyEffect(r.key,{verdict:"PARTIAL",evidence:{sourceRef:"remote:status:partial"}});assert.equal(x.effectCertainty,"PARTIAL_VERIFIED");assert.equal(x.lifecycle,"RECONCILING")});
test("cancellation after possible dispatch preserves uncertainty",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan({idempotencyClass:"DO_NOT_REPEAT"})),a=l.beginAttempt(r.key);l.markDispatch(r.key,a.id,"POSSIBLE");const x=l.cancelEffect(r.key,{confirmed:false,reason:"user-stop"});assert.equal(x.effectCertainty,"UNKNOWN");assert.equal(x.lifecycle,"RECONCILING")});
test("recovery queue contains unresolved effects only",()=>{const l=effects.createEffectLedger(),a=l.planEffect(plan()),b=l.planEffect(plan({target:{path:"project/src/b.txt"},idempotencyKey:"write:b:1"}));l.verifyEffect(a.key,{verdict:"ABSENT",evidence:{sourceRef:"local:not-found"}});assert.deepEqual(l.recoveryQueue().map(x=>x.key),[b.key])});
test("effect journal snapshot detects tampering on restore",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan()),s=l.snapshot();s.records[0].action="delete";assert.throws(()=>effects.restoreEffectLedger(s),/integrity failure/);assert.ok(r.key)});
test("compensation is linked as a separate effect identity",()=>{const l=effects.createEffectLedger(),r=l.planEffect(plan({compensationRecipe:{kind:"restore"}})),c=l.planEffect(plan({action:"restore",target:{path:"project/src/a.txt"},payload:{content:"old"},idempotencyKey:"restore:a:1"}));const x=l.linkCompensation(r.key,{compensationEffectKey:c.key,state:"PLANNED"});assert.equal(x.compensationLink,c.key);assert.notEqual(r.key,c.key)});

test("legacy SideEffectLedger API remains compatible with release bridge",()=>{const l=effects.createLedger(),r=l.plan({idempotencyKey:"legacy:1",reversible:true});assert.equal(r.state,"PLANNED");l.mutate("legacy:1","ATTEMPTED",{});l.mutate("legacy:1","VERIFIED",{evidence:{ok:true}});assert.equal(l.unresolved().length,0)});
console.log(`tool/security/effect polish: PASS (${count} assertions)`);
