"use strict";
const assert = require("assert/strict");
const v = require("./vision-fabric.cjs");
let n = 0;
function pass(name, fn) { fn(); n++; console.log("PASS", name); }
const source = v.createVisualSource({ id:"img-1", principal:"user", project:"seven", origin:"upload:1", originKind:"UPLOAD", sensitivity:"PRIVATE", createdAt:"2026-09-14T17:00:00Z" });
const version = v.createVisualVersion({ source, contentHash:"a".repeat(64), width:1080, height:2400, capturedAt:"2026-09-14T17:00:00Z" });
const frame = v.createVisualFrame(version,{sequence:1,viewport:{width:1080,height:2400,scale:1}});
const region = v.createVisualRegion(version,{frameId:frame.id,box:{x:.1,y:.1,width:.4,height:.2},role:"text"});
pass("source identity is principal scoped",()=>assert.equal(source.principal,"user"));
pass("ambient visual capture is rejected",()=>assert.throws(()=>v.createVisualSource({id:"x",principal:"u",origin:"camera",ambient:true}),/ambient/));
pass("invalid sensitivity fails closed",()=>assert.throws(()=>v.createVisualSource({id:"x",principal:"u",origin:"x",sensitivity:"mystery"}),/sensitivity/));
pass("version binds exact source",()=>assert.equal(version.sourceId,source.id));
pass("version identity is deterministic",()=>assert.equal(v.createVisualVersion({source,contentHash:"a".repeat(64),width:1080,height:2400,capturedAt:"2026-09-14T17:00:00Z"}).id,version.id));
pass("bad visual hash is rejected",()=>assert.throws(()=>v.createVisualVersion({source,contentHash:"xyz",width:1,height:1}),/hex/));
const crop=v.deriveVisualVersion(version,{contentHash:"b".repeat(64),width:400,height:400,transform:{kind:"crop",box:{x:.1,y:.1,width:.4,height:.2}}});
pass("crop is derived not authoritative original",()=>assert.equal(crop.authoritativeOriginal,false));
pass("derived version preserves parent lineage",()=>assert.equal(crop.parentVersionId,version.id));
pass("derived representation must differ by content hash",()=>assert.throws(()=>v.deriveVisualVersion(version,{contentHash:version.contentHash,transform:{kind:"crop"}}),/distinct/));
pass("unsupported transform fails closed",()=>assert.throws(()=>v.deriveVisualVersion(version,{contentHash:"c".repeat(64),transform:{kind:"paint"}}),/unsupported/));
pass("frame binds viewport hash",()=>assert.ok(frame.viewportHash));
pass("region requires normalized box",()=>assert.throws(()=>v.createVisualRegion(version,{box:{x:.8,y:.8,width:.4,height:.4}}),/normalized/));
pass("region binds exact version",()=>assert.equal(region.versionId,version.id));
const ocr=v.createOCRArtifact({version,region,engine:"platform-ocr",engineVersion:"1",text:"Seven",languages:["en"],quality:.9,lines:[{text:"Seven",box:{x:.1,y:.1,width:.1,height:.03}}]});
pass("OCR is explicitly derived",()=>assert.equal(ocr.derived,true));
pass("OCR never grants action authority",()=>assert.equal(ocr.grantsAuthority,false));
pass("OCR binds exact region",()=>assert.equal(ocr.regionId,region.id));
pass("cross-version OCR region is rejected",()=>{const r2=v.createVisualRegion(crop,{box:{x:0,y:0,width:1,height:1}});assert.throws(()=>v.createOCRArtifact({version,region:r2,engine:"x",engineVersion:"1",text:"x"}),/mismatch/)});
const layout=v.createLayoutArtifact({version,engine:"layout-local",blocks:[{id:"a",kind:"paragraph",box:{x:.1,y:.1,width:.5,height:.2},readingOrder:0}]});
pass("layout reading order remains hypothesis",()=>assert.equal(layout.readingOrderIsHypothesis,true));
pass("duplicate layout ids are rejected",()=>assert.throws(()=>v.createLayoutArtifact({version,blocks:[{id:"a",box:{x:0,y:0,width:.2,height:.2}},{id:"a",box:{x:.2,y:.2,width:.2,height:.2}}]}),/duplicate/));
const obsOcr=v.createVisualObservation({version,regions:[region],frameId:frame.id,subject:"label",predicate:"text",value:"Seven",method:"OCR",state:"VERIFIED",precise:true});
const obsVlm=v.createVisualObservation({version,regions:[region],frameId:frame.id,subject:"label",predicate:"text",value:"Seven",method:"VLM",model:"vision-x",state:"PROPOSED"});
pass("visual observation requires grounding region",()=>assert.throws(()=>v.createVisualObservation({version,predicate:"x",value:1,method:"VLM"}),/region/));
pass("observation never grants authority",()=>assert.equal(obsVlm.grantsAuthority,false));
pass("observation binds method identity",()=>assert.equal(obsVlm.model,"vision-x"));
pass("grounded set detects no unresolved consistent observations",()=>assert.equal(v.createGroundedObservationSet({version,observations:[obsOcr,obsVlm]}).unresolved.length,0));
pass("cross-version observation set is rejected",()=>{const r2=v.createVisualRegion(crop,{box:{x:0,y:0,width:.2,height:.2}}),o2=v.createVisualObservation({version:crop,regions:[r2],predicate:"x",value:1,method:"OCR"});assert.throws(()=>v.createGroundedObservationSet({version,observations:[o2]}),/mismatch/)});
const request=v.createPerceptionRequest({taskId:"t1",principal:"user",version,needs:["text","ui"],allowRemote:true,maxRemoteRegions:1,privacyMode:"MINIMIZE",createdAt:"2026-09-14T17:01:00Z"});
pass("perception request rejects principal bleed",()=>assert.throws(()=>v.createPerceptionRequest({taskId:"x",principal:"other",version,needs:["text"]}),/principal/));
pass("perception request rejects ambient mode",()=>assert.throws(()=>v.createPerceptionRequest({taskId:"x",principal:"user",version,needs:["text"],ambient:true}),/ambient/));
pass("remote requires minimized region",()=>assert.equal(v.canRemotePerceive(request,{regionCount:0}).allowed,false));
pass("remote region budget is enforced",()=>assert.equal(v.canRemotePerceive(request,{regionCount:2}).reason,"remote-region-budget-exceeded"));
pass("explicit minimized remote route can pass",()=>assert.equal(v.canRemotePerceive(request,{regionCount:1}).allowed,true));
const sensitiveSource=v.createVisualSource({id:"secret",principal:"user",origin:"camera-explicit",sensitivity:"SENSITIVE"});
const sensitiveVersion=v.createVisualVersion({source:sensitiveSource,contentHash:"d".repeat(64),width:100,height:100});
const sensitiveReq=v.createPerceptionRequest({taskId:"s",principal:"user",version:sensitiveVersion,needs:["semantic"],allowRemote:true,maxRemoteRegions:1});
pass("sensitive content blocks remote perception",()=>assert.equal(v.canRemotePerceive(sensitiveReq,{regionCount:1}).reason,"sensitive-source"));
const lite=v.createPerceptionPlan(request,{tier:"LITE",localVlmAvailable:true,plannedRemoteRegions:1});
pass("Lite may use minimized remote VLM without loading local heavy VLM",()=>{assert.equal(lite.stages.includes(v.STAGE.VLM),true);assert.equal(lite.vlmRoute,"REMOTE")});
pass("plan never enables continuous polling",()=>assert.equal(lite.continuousPolling,false));
pass("plan is cancellable between stages",()=>assert.equal(lite.cancellableBetweenStages,true));
const localOnly=v.createPerceptionRequest({taskId:"lo",principal:"user",version,needs:["semantic"],allowRemote:false});
const liteLocal=v.createPerceptionPlan(localOnly,{tier:"LITE",localVlmAvailable:true});
pass("Lite without remote route stays VLM cold",()=>assert.equal(liteLocal.stages.includes(v.STAGE.VLM),false));
const full=v.createPerceptionPlan(localOnly,{tier:"FULL",localVlmAvailable:true});
pass("Full may use available local VLM selectively",()=>assert.equal(full.stages.includes(v.STAGE.VLM),true));
const manifest=v.createPerceptionManifest({request,plan:lite,artifacts:[ocr,layout],observations:[obsOcr,obsVlm],completedStages:lite.stages});
pass("manifest binds request and plan",()=>assert.equal(manifest.requestId,request.id));
pass("manifest rejects foreign artifact versions",()=>assert.throws(()=>v.createPerceptionManifest({request,plan:lite,artifacts:[{id:"x",versionId:crop.id}]}),/artifact version/));
const version2=v.createVisualVersion({source,contentHash:"e".repeat(64),width:1080,height:2400,frameIndex:2,capturedAt:"2026-09-14T17:02:00Z"});
const frame2=v.createVisualFrame(version2,{sequence:2,viewport:{width:1080,height:2400,scale:1}});
pass("duplicate frame suppression detects exact hash",()=>assert.equal(v.createFrameDelta(frame,frame,{changedRegions:[]}).duplicate,true));
pass("changed frame without regions requests keyframe",()=>assert.equal(v.createFrameDelta(frame,frame2,{}).keyframeRequired,true));
pass("cross-source frame delta is rejected",()=>{const s2=v.createVisualSource({id:"z",principal:"user",origin:"z"}),vv=v.createVisualVersion({source:s2,contentHash:"f".repeat(64),width:1,height:1}),ff=v.createVisualFrame(vv);assert.throws(()=>v.createFrameDelta(frame,ff),/boundary/)});
const proposal={frameId:frame.id,viewportHash:frame.viewportHash,box:{x:.1,y:.1,width:.1,height:.1}};
pass("current-frame coordinate proposal validates",()=>assert.equal(v.validateFrameTarget({proposal,currentFrame:frame}).valid,true));
pass("stale frame coordinates fail closed",()=>assert.equal(v.validateFrameTarget({proposal,currentFrame:frame2}).reason,"stale-frame"));
pass("viewport drift invalidates coordinates",()=>assert.equal(v.validateFrameTarget({proposal:{...proposal,viewportHash:"wrong"},currentFrame:frame}).reason,"viewport-drift"));
const obsConflict=v.createVisualObservation({version,regions:[region],predicate:"text",value:"Sevan",method:"VLM",state:"PROPOSED"});
pass("OCR VLM disagreement remains conflict",()=>assert.equal(v.reconcileObservations([obsOcr,obsConflict]).state,"CONFLICT"));
pass("consistent methods do not manufacture VERIFIED",()=>assert.equal(v.reconcileObservations([obsOcr,obsVlm]).state,"PROPOSED"));
pass("precise values require verified precise evidence",()=>assert.equal(v.requirePreciseVisualValue({versionId:version.id,observations:[obsVlm]}).state,"UNRESOLVED"));
pass("verified precise visual evidence can resolve exact value",()=>assert.equal(v.requirePreciseVisualValue({versionId:version.id,observations:[obsOcr]}).state,"VERIFIED"));
const evidence=v.createVisualEvidenceRef({version,observation:obsOcr,regions:[region],artifacts:[ocr],property:"label.text"});
pass("visual evidence is version and region bound",()=>assert.deepEqual(evidence.regionIds,[region.id]));
pass("visual evidence cannot grant permission",()=>assert.equal(evidence.grantsAuthority,false));
pass("evidence rejects missing observation region",()=>assert.throws(()=>v.createVisualEvidenceRef({version,observation:obsOcr,regions:[v.createVisualRegion(version,{box:{x:.6,y:.6,width:.1,height:.1}})]}),/missing observation region/));
pass("derivative reuse requires exact visual version",()=>assert.equal(v.shouldReuseDerivative(ocr,version),true));
pass("stale derivative is not reused",()=>assert.equal(v.shouldReuseDerivative(ocr,version2),false));
pass("vision fabric never grants authority",()=>assert.equal(v.grantsAuthority(),false));
pass("vision fabric never performs actions",()=>assert.equal(v.canPerformAction(),false));
console.log(`vision fabric foundation: PASS (${n} assertions)`);
