"use strict";
const assert=require("assert/strict"),file=require("../hardening/project-file-fabric-passb.cjs"),code=require("./coding-agent-fabric-passb.cjs"),judge=require("./judge-fabric.cjs");
let n=0;const test=(x,f)=>{f();n++;console.log("PASS",x)};
const backend=file.createBackendCapabilityProfile({backendId:"b",backendKind:"ANDROID_SAF"}),root=file.createProjectRoot({rootId:"r",backendId:"b",grantEpoch:1,policyEpoch:2});
const grant=file.createProjectGrant({grantId:"g",principalId:"u",projectRootId:root.id,actions:["READ","LIST","CREATE","PATCH","REPLACE","DELETE","RENAME"],prefixes:["src","tests"],epoch:1,policyEpoch:2,sourceEventId:"evt"});
const ref=file.createFileRef({root,path:"src/a.js"}),ver=file.createFileVersionToken({fileRef:ref,contentHash:"old",size:3});
function staged(ms){let x=file.createProjectTransaction({root,grant,principalId:"u",baselineManifestHash:"m1",intentId:"i",mutations:ms});x=file.captureBaseline(x,{manifestHash:"m1",proofHash:"bp"});x=file.beginStaging(x);return file.finishStaging(x)}
function valid(x,extra={}){return file.validateTransaction(x,{root,backendProfile:backend,grant,principalId:"u",currentManifestHash:"m1",currentVersions:{"src/a.js":ver},existingPaths:["src/a.js"],currentGrantEpoch:1,currentPolicyEpoch:2,...extra})}
function auth(x,v){return file.createTransactionAuthorizationReceipt({transaction:x,validationReceipt:v,root,grant,principalId:"u",sourceAuthorizationReceiptId:"upstream",sourceAuthorizationReceiptHash:"uph"})}
function verified(){let x=staged([file.createMutation({op:"REPLACE",path:"src/a.js",expectedVersionTokenId:ver.id,contentHash:"new"})]),v=valid(x);x=file.authorizeTransaction(v.transaction,v.validationReceipt,auth(v.transaction,v.validationReceipt));x=file.beginCommit(x);x=file.markCommitted(x,{effectKey:"e",backendReceiptHash:"br",resultManifestHash:"m2"});x=file.beginVerification(x);return file.verifyCommittedTransaction(x,{observedManifestHash:"m2",observedFiles:{"src/a.js":{exists:true,contentHash:"new"}}}).transaction}
test("backend profile is mandatory",()=>{const x=staged([file.createMutation({op:"PATCH",path:"src/a.js",expectedVersionTokenId:ver.id,patchHash:"p",resultContentHash:"new"})]),r=valid(x,{backendProfile:null});assert.ok(r.errors.includes("backend-profile-missing"))});
test("read only backend blocks mutation",()=>{const ro=file.createBackendCapabilityProfile({backendId:"b",readOnly:true}),x=staged([file.createMutation({op:"PATCH",path:"src/a.js",expectedVersionTokenId:ver.id,patchHash:"p",resultContentHash:"new"})]);assert.ok(valid(x,{backendProfile:ro}).errors.includes("read-only-backend"))});
test("PATCH requires result truth",()=>assert.throws(()=>file.createMutation({op:"PATCH",path:"src/a.js",expectedVersionTokenId:ver.id,patchHash:"p"}),/resultContentHash/));
test("RENAME requires result truth",()=>assert.throws(()=>file.createMutation({op:"RENAME",path:"src/a.js",newPath:"src/b.js",expectedVersionTokenId:ver.id}),/resultContentHash/));
test("duplicate source mutation conflicts",()=>{const x=staged([file.createMutation({op:"PATCH",path:"src/a.js",expectedVersionTokenId:ver.id,patchHash:"1",resultContentHash:"n1"}),file.createMutation({op:"PATCH",path:"src/a.js",expectedVersionTokenId:ver.id,patchHash:"2",resultContentHash:"n2"})]);assert.ok(valid(x).errors.includes("duplicate-source:src/a.js"))});
test("rename destination cannot also mutate",()=>{const rb=file.createFileRef({root,path:"src/b.js"}),vb=file.createFileVersionToken({fileRef:rb,contentHash:"b",size:1}),x=staged([file.createMutation({op:"RENAME",path:"src/a.js",newPath:"src/b.js",expectedVersionTokenId:ver.id,resultContentHash:"old"}),file.createMutation({op:"PATCH",path:"src/b.js",expectedVersionTokenId:vb.id,patchHash:"p",resultContentHash:"b2"})]);assert.ok(valid(x,{currentVersions:{"src/a.js":ver,"src/b.js":vb},existingPaths:["src/a.js"]}).errors.includes("destination-also-mutated:src/b.js"))});
test("authorization requires upstream authority proof",()=>{const x=staged([file.createMutation({op:"REPLACE",path:"src/a.js",expectedVersionTokenId:ver.id,contentHash:"n"})]),v=valid(x);assert.throws(()=>file.createTransactionAuthorizationReceipt({transaction:v.transaction,validationReceipt:v.validationReceipt,root,grant,principalId:"u"}),/source authorization/)});
test("arbitrary receipt cannot authorize",()=>{const x=staged([file.createMutation({op:"REPLACE",path:"src/a.js",expectedVersionTokenId:ver.id,contentHash:"n"})]),v=valid(x);assert.throws(()=>file.authorizeTransaction(v.transaction,v.validationReceipt,{id:"fake"}),/transaction-bound/)});
test("verified transaction keeps auth lineage",()=>assert.ok(verified().commitReceipt.authorizationReceiptId));
test("delete requires explicit absence observation",()=>{let x=staged([file.createMutation({op:"DELETE",path:"src/a.js",expectedVersionTokenId:ver.id})]),v=valid(x);x=file.authorizeTransaction(v.transaction,v.validationReceipt,auth(v.transaction,v.validationReceipt));x=file.beginCommit(x);x=file.markCommitted(x,{effectKey:"d",backendReceiptHash:"b",resultManifestHash:"m2"});x=file.beginVerification(x);assert.equal(file.verifyCommittedTransaction(x,{observedManifestHash:"m2",observedFiles:{}}).ok,false)});
const req=code.createRequirementLedger({taskId:"t",items:[{id:"r1",kind:"BUG",sourceRef:"user",sourceHash:"s",statement:"fix",hard:true}]});
const env=code.createDevEnvironment({environmentId:"env",projectRootId:root.id,toolSnapshotId:"tools"});
test("high risk contract requires builder identity",()=>assert.throws(()=>code.createChangeContract({taskId:"t",goalHash:"goal",projectRootId:root.id,baselineManifestHash:"m1",requirementsId:req.id,environmentId:env.id,risk:"HIGH",allowedPaths:["src"]}),/builder/));
const change=code.createChangeContract({taskId:"t",goalHash:"goal",projectRootId:root.id,baselineManifestHash:"m1",requirementsId:req.id,environmentId:env.id,risk:"HIGH",allowedPaths:["src","tests"],forbiddenPaths:["src/locked"],builderId:"builder",builderContextFingerprint:"ctx-builder",requiredVerificationLayers:["TARGETED","REGRESSION"]});
const bp=code.createBaselineProof({changeContract:change,manifestHash:"m1",fileVersionsHash:"fv",testManifestHash:"tm",environmentId:env.id,toolSnapshotId:"tools"}),ws=code.createCandidateWorkspace({changeContract:change,baselineProof:bp,workspaceId:"ws",isolationProofHash:"iso"});
const sel=code.createTestSelectionRecord({changeContract:change,baselineProof:bp,candidateWorkspace:ws,baselineTestManifestHash:"tm",tests:[{id:"a",commandHash:"ca",reason:"target",layer:"TARGETED",requirementIds:["r1"]},{id:"b",commandHash:"cb",reason:"reg",layer:"REGRESSION",requirementIds:["r1"]}]});
const review=code.createReviewConstraintSet({changeContract:change,baselineTestManifestHash:"tm",requiredGates:["tests"],mustPreserveTestIds:["legacy"],evalPathPrefixes:["evals"],allowTestChanges:true,allowEvalChanges:false,minReviewers:1});
function run(over={}){return code.createVerificationRunRecord({testSelection:sel,testResults:[{testId:"a",status:"PASS",artifactHash:"aa",exitCode:0,commandHash:"ca"},{testId:"b",status:"PASS",artifactHash:"bb",exitCode:0,commandHash:"cb"}],reviewResults:[{reviewerId:"reviewer",status:"PASS",evidenceHash:"rv",independent:true,independenceProofHash:"ip",reviewerContextFingerprint:"ctx-r"}],gateResults:[{gateId:"TESTS",status:"PASS",evidenceHash:"g"}],changedPaths:["src/a.js"],baselineTestManifestHash:"tm",currentTestManifestHash:"tm2",currentTestIds:["legacy","a","b"],...over})}
test("coding scope uses canonical file path rules",()=>assert.equal(code.validateCandidateScope({changeContract:change,changedPaths:["src/../secret"]}).pass,false));
test("required verification layers execute",()=>{const r=run({testResults:[{testId:"a",status:"PASS",artifactHash:"a",exitCode:0,commandHash:"ca"}]});assert.ok(code.assessVerification({changeContract:change,requirementLedger:req,baselineProof:bp,testSelection:sel,reviewConstraints:review,verificationRun:r}).reasons.includes("required-verification-layer-missing:REGRESSION"))});
test("required gate executes",()=>{const r=run({gateResults:[]});assert.ok(code.assessVerification({changeContract:change,requirementLedger:req,baselineProof:bp,testSelection:sel,reviewConstraints:review,verificationRun:r}).reasons.includes("required-gate-missing:TESTS"))});
test("preserved tests cannot vanish",()=>{const r=run({currentTestIds:["a","b"]});assert.ok(code.assessVerification({changeContract:change,requirementLedger:req,baselineProof:bp,testSelection:sel,reviewConstraints:review,verificationRun:r}).reasons.includes("required-test-removed:legacy"))});
test("builder is not independent reviewer",()=>{const r=run({reviewResults:[{reviewerId:"builder",status:"PASS",evidenceHash:"r",independent:true,independenceProofHash:"ip",reviewerContextFingerprint:"other"}]});assert.ok(code.assessVerification({changeContract:change,requirementLedger:req,baselineProof:bp,testSelection:sel,reviewConstraints:review,verificationRun:r}).reasons.includes("insufficient-independent-review"))});
test("shared builder context is not independent",()=>{const r=run({reviewResults:[{reviewerId:"x",status:"PASS",evidenceHash:"r",independent:true,independenceProofHash:"ip",reviewerContextFingerprint:"ctx-builder"}]});assert.ok(code.assessVerification({changeContract:change,requirementLedger:req,baselineProof:bp,testSelection:sel,reviewConstraints:review,verificationRun:r}).reasons.includes("insufficient-independent-review"))});
const vr=run(),assessment=code.assessVerification({changeContract:change,requirementLedger:req,baselineProof:bp,testSelection:sel,reviewConstraints:review,verificationRun:vr});
test("complete strengthened verification passes",()=>assert.equal(assessment.pass,true));
const evidence=code.createChangeEvidenceBundle({changeContract:change,requirementLedger:req,baselineProof:bp,candidateWorkspace:ws,projectTransaction:verified(),verificationRun:vr,verificationAssessment:assessment,diffHash:"diff",projectMapHash:"map",toolSnapshotId:"tools"});
test("evidence bundle is judgeable and exact",()=>{assert.equal(evidence.eligible,true);assert.ok(evidence.bundleHash)});
const jc=judge.createAcceptanceContract({taskId:"t",goalHash:"jg",subjectHash:evidence.bundleHash,risk:"HIGH",checks:[{id:"integrity",layer:"L1_DETERMINISTIC",hard:true}],dependencyFingerprints:{baseline:"m1",bundle:evidence.bundleHash}}),cand=judge.createCandidateResult({taskId:"t",candidateId:"c",subjectHash:evidence.bundleHash,builderId:"builder",builderContextFingerprint:"ctx-builder",artifacts:[{id:evidence.id,hash:evidence.bundleHash,kind:"CHANGE_EVIDENCE",sourceRef:"coding"}]}),jr=judge.adjudicate({contract:jc,candidate:cand,observations:[{checkId:"integrity",status:"PASS"}],adversarialJudge:{judgeId:"judge",qualified:true,promotionStatus:"QUALIFIED",contextFingerprint:"ctx-j",verdict:"PASS"}});
const deps={baseline:"m1",bundle:evidence.bundleHash};
test("Wave06 receipt is authentic fixture",()=>assert.equal(judge.verifyReceipt({receipt:jr.receipt,contract:jc,candidate:cand}),true));
test("fabricated judge receipt cannot promote",()=>{const p=code.createPromotionRequest({changeContract:change,evidenceBundle:evidence,judgeResult:{...jr,receipt:{...jr.receipt,id:"fake"}},judgeContract:jc,judgeCandidate:cand,currentBaselineManifestHash:"m1",currentDependencies:deps});assert.ok(p.reasons.includes("judge-receipt-invalid"))});
test("judge must target exact evidence bundle",()=>{const wrong=judge.createAcceptanceContract({taskId:"t",goalHash:"jg",subjectHash:"other",checks:[{id:"integrity",layer:"L1_DETERMINISTIC"}]});const p=code.createPromotionRequest({changeContract:change,evidenceBundle:evidence,judgeResult:jr,judgeContract:wrong,judgeCandidate:cand,currentBaselineManifestHash:"m1",currentDependencies:deps});assert.ok(p.reasons.includes("judge-contract-subject-mismatch"))});
test("judge dependency drift blocks promotion",()=>{const p=code.createPromotionRequest({changeContract:change,evidenceBundle:evidence,judgeResult:jr,judgeContract:jc,judgeCandidate:cand,currentBaselineManifestHash:"m1",currentDependencies:{baseline:"m2",bundle:evidence.bundleHash}});assert.ok(p.reasons.some(x=>x.includes("dependency-changed")))});
test("baseline drift blocks promotion",()=>assert.equal(code.createPromotionRequest({changeContract:change,evidenceBundle:evidence,judgeResult:jr,judgeContract:jc,judgeCandidate:cand,currentBaselineManifestHash:"m2",currentDependencies:deps}).eligible,false));
test("authentic evidence-bound judge can request promotion",()=>assert.equal(code.createPromotionRequest({changeContract:change,evidenceBundle:evidence,judgeResult:jr,judgeContract:jc,judgeCandidate:cand,currentBaselineManifestHash:"m1",currentDependencies:deps}).eligible,true));
console.log(`coding/file Pass B: PASS (${n} assertions)`);