"use strict";

const crypto=require("crypto");
const VERDICTS=Object.freeze(["ACCEPT","REJECT","REPAIR","INCONCLUSIVE"]);
const LAYERS=Object.freeze(["L0_INVARIANT","L1_DETERMINISTIC","L2_EVIDENCE","L3_SEMANTIC","L4_ADVERSARIAL"]);
function text(v){return typeof v==="string"?v.trim():"";}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};for(const k of Object.keys(v).sort())if(v[k]!==undefined)o[k]=stable(v[k]);return o;}return v;}
function hash(v){return crypto.createHash("sha256").update(typeof v==="string"?v:JSON.stringify(stable(v))).digest("hex");}
function uniq(v){return [...new Set((Array.isArray(v)?v:[]).map(text).filter(Boolean))].sort();}
function risk(v){const x=String(v||"MEDIUM").toUpperCase();return ["LOW","MEDIUM","HIGH","CRITICAL"].includes(x)?x:"MEDIUM";}
function layer(v){const x=String(v||"L1_DETERMINISTIC").toUpperCase();if(!LAYERS.includes(x))throw new Error("invalid verification layer");return x;}
function freeze(v){return Object.freeze(v);}
function normalizeCheck(c={}){const id=text(c.id);if(!id)throw new Error("verification check id required");return freeze({id,layer:layer(c.layer),kind:text(c.kind)||"predicate",hard:c.hard!==false,requiredEvidence:uniq(c.requiredEvidence),repairable:c.repairable===true,description:text(c.description)});}
function createAcceptanceContract(input={}){const taskId=text(input.taskId),goalHash=text(input.goalHash);if(!taskId||!goalHash)throw new Error("taskId and goalHash required");const checks=(input.checks||[]).map(normalizeCheck);if(!checks.length)throw new Error("acceptance contract requires checks");const ids=new Set(checks.map(c=>c.id));if(ids.size!==checks.length)throw new Error("duplicate verification check");const body={schemaVersion:1,taskId,goalHash,risk:risk(input.risk),scopeFingerprint:text(input.scopeFingerprint)||null,authorityFingerprint:text(input.authorityFingerprint)||null,checks,requiredArtifactHashes:uniq(input.requiredArtifactHashes),forbiddenArtifactHashes:uniq(input.forbiddenArtifactHashes),effectRequirement:input.effectRequirement?clone(input.effectRequirement):null,independentJudgeRequired:input.independentJudgeRequired===true||["HIGH","CRITICAL"].includes(risk(input.risk)),maxRepairCycles:Math.max(0,Math.min(10,Number(input.maxRepairCycles) || 2))};return freeze({...body,id:`accept-${hash(body).slice(0,24)}`});}
function createCandidateResult(input={}){const taskId=text(input.taskId),candidateId=text(input.candidateId);if(!taskId||!candidateId)throw new Error("candidate task/id required");const artifacts=(input.artifacts||[]).map(a=>({id:text(a.id),hash:text(a.hash),kind:text(a.kind),sourceRef:text(a.sourceRef)}));if(artifacts.some(a=>!a.id||!a.hash))throw new Error("candidate artifacts require id/hash");const body={schemaVersion:1,taskId,candidateId,scopeFingerprint:text(input.scopeFingerprint)||null,authorityFingerprint:text(input.authorityFingerprint)||null,builderId:text(input.builderId)||null,artifacts,claims:clone(input.claims||[]),effectKeys:uniq(input.effectKeys)};return freeze({...body,resultHash:hash(body)});}
function createVerificationPlan(contract,{availableDeterministicChecks=[]}={}){if(!contract||!contract.id)throw new Error("acceptance contract required");const available=new Set(availableDeterministicChecks),checks=contract.checks.map(c=>({...c,executor:["L0_INVARIANT","L1_DETERMINISTIC"].includes(c.layer)?(available.has(c.id)?"DETERMINISTIC":"MISSING"):c.layer==="L2_EVIDENCE"?"EVIDENCE":c.layer==="L3_SEMANTIC"?"SEMANTIC":"ADVERSARIAL"}));return freeze({schemaVersion:1,contractId:contract.id,checks,requiredLayers:[...new Set(checks.map(c=>c.layer))],semanticNeeded:checks.some(c=>c.layer==="L3_SEMANTIC"),adversarialNeeded:checks.some(c=>c.layer==="L4_ADVERSARIAL")});}
function normalizeObservation(o={}){const status=String(o.status||"INCONCLUSIVE").toUpperCase();if(!["PASS","FAIL","INCONCLUSIVE"].includes(status))throw new Error("invalid observation status");const evidence=(o.evidence||[]).map(e=>({type:text(e.type),sourceRef:text(e.sourceRef),hash:text(e.hash),authority:Number.isFinite(Number(e.authority))?Number(e.authority):null}));return {checkId:text(o.checkId),status,evidence,reason:text(o.reason)||null,observerId:text(o.observerId)||null,artifactHash:text(o.artifactHash)||null};}
function evidenceSatisfies(check,obs){for(const required of check.requiredEvidence){if(!obs.evidence.some(e=>e.type===required&&e.sourceRef&&e.hash))return false;}return true;}
function artifactGate(contract,candidate){const hashes=new Set(candidate.artifacts.map(a=>a.hash)),reasons=[];for(const h of contract.requiredArtifactHashes)if(!hashes.has(h))reasons.push(`required_artifact_missing:${h}`);for(const h of contract.forbiddenArtifactHashes)if(hashes.has(h))reasons.push(`forbidden_artifact_present:${h}`);return reasons;}
function effectGate(requirement,effectRecords=[]){if(!requirement)return {status:"PASS",reason:"no-effect-requirement"};const key=text(requirement.effectKey),record=effectRecords.find(r=>r&&r.key===key);if(!record)return {status:"INCONCLUSIVE",reason:"effect-record-missing"};if(record.lifecycle!=="CLOSED")return {status:"INCONCLUSIVE",reason:"effect-not-closed"};const expected=String(requirement.expectedCertainty||"PRESENT_VERIFIED").toUpperCase();if(record.effectCertainty!==expected)return {status:"FAIL",reason:`effect-certainty:${record.effectCertainty}`};return {status:"PASS",reason:"effect-verified"};}
function adjudicate({contract,candidate,observations=[],semanticJudge=null,adversarialJudge=null,effectRecords=[],repairCycle=0}={}){if(!contract||!candidate)return {verdict:"INCONCLUSIVE",reason:"missing-contract-or-candidate",receipt:null};const hardReasons=[],repairReasons=[],inconclusive=[],obsMap=new Map(observations.map(o=>{const n=normalizeObservation(o);return [n.checkId,n];}));if(candidate.taskId!==contract.taskId)hardReasons.push("task-identity-mismatch");if(contract.scopeFingerprint&&candidate.scopeFingerprint!==contract.scopeFingerprint)hardReasons.push("scope-mismatch");if(contract.authorityFingerprint&&candidate.authorityFingerprint!==contract.authorityFingerprint)hardReasons.push("authority-mismatch");hardReasons.push(...artifactGate(contract,candidate));
  for(const check of contract.checks){const obs=obsMap.get(check.id);if(!obs){inconclusive.push(`missing-check:${check.id}`);continue;}if(obs.status==="PASS"&&!evidenceSatisfies(check,obs)){inconclusive.push(`evidence-incomplete:${check.id}`);continue;}if(obs.status==="FAIL"){if(check.hard){if(check.repairable)repairReasons.push(check.id);else hardReasons.push(`hard-fail:${check.id}`);}else repairReasons.push(check.id);}else if(obs.status==="INCONCLUSIVE")inconclusive.push(`inconclusive:${check.id}`);}
  const effect=effectGate(contract.effectRequirement,effectRecords);if(effect.status==="FAIL")hardReasons.push(effect.reason);else if(effect.status==="INCONCLUSIVE")inconclusive.push(effect.reason);
  const semanticChecks=contract.checks.filter(c=>c.layer==="L3_SEMANTIC"),adversarialChecks=contract.checks.filter(c=>c.layer==="L4_ADVERSARIAL");
  if(semanticChecks.length){if(!semanticJudge||semanticJudge.verdict==="INCONCLUSIVE")inconclusive.push("semantic-judge-inconclusive");else if(semanticJudge.verdict==="FAIL")repairReasons.push("semantic-judge-fail");}
  if(adversarialChecks.length||contract.independentJudgeRequired){if(!adversarialJudge)inconclusive.push("independent-adjudication-missing");else{if(candidate.builderId&&adversarialJudge.judgeId===candidate.builderId)hardReasons.push("builder-is-independent-judge");if(adversarialJudge.verdict==="FAIL")hardReasons.push("adversarial-judge-fail");if(adversarialJudge.verdict==="INCONCLUSIVE")inconclusive.push("adversarial-judge-inconclusive");}}
  let verdict="ACCEPT",reason="all-required-verification-passed";if(hardReasons.length){verdict="REJECT";reason=hardReasons.join(",");}else if(repairReasons.length&&repairCycle<contract.maxRepairCycles){verdict="REPAIR";reason=repairReasons.join(",");}else if(repairReasons.length){verdict="REJECT";reason="repair-budget-exhausted:"+repairReasons.join(",");}else if(inconclusive.length){verdict="INCONCLUSIVE";reason=inconclusive.join(",");}
  const receiptBody={schemaVersion:1,contractId:contract.id,candidateHash:candidate.resultHash,verdict,reason,observationHashes:[...obsMap.values()].map(hash).sort(),semanticJudgeHash:semanticJudge?hash(semanticJudge):null,adversarialJudgeHash:adversarialJudge?hash(adversarialJudge):null,effectGate:effect};return {verdict,reason,hardReasons,repairReasons,inconclusive,receipt:freeze({...receiptBody,id:`judge-${hash(receiptBody).slice(0,24)}`})};}
function verifyReceipt({receipt,contract,candidate}={}){if(!receipt||!contract||!candidate)return false;return receipt.contractId===contract.id&&receipt.candidateHash===candidate.resultHash&&VERDICTS.includes(receipt.verdict);}
module.exports={VERDICTS,LAYERS,hash,createAcceptanceContract,createCandidateResult,createVerificationPlan,adjudicate,verifyReceipt,effectGate};
