"use strict";
const assert=require("assert/strict");
const registry=require("./model-registry.cjs"),model=require("./model-fabric.cjs"),compute=require("./adaptive-compute.cjs");
let count=0;const test=(name,fn)=>{fn();count++;console.log("PASS",name)};
const verifiedAt="2026-09-14T12:00:00.000Z",now="2026-09-14T14:00:00.000Z";
function record(overrides={}){return registry.normalizeModelRecord({provider:"P",model:"M",status:"ACTIVE",contextWindow:16000,capabilities:{chat:true,coding:true,tools:true,json:true},freeProof:{class:"FREE_API_TIER",status:"VERIFIED",evidence:["official free tier"],verifiedAt,verifier:{id:"v",method:"official-source-check"}},...overrides});}
function deployment(overrides={}){const r=overrides.record||record();return model.createDeployment({record:r,family:overrides.family||"M-family",revision:overrides.revision||"r1",endpoint:{id:overrides.endpoint||"ep1",pricing:overrides.pricing||"FREE",health:overrides.health||{status:"HEALTHY",observedAt:now},quota:overrides.quota||{status:"AVAILABLE",remaining:100},qualification:overrides.qualification||"VERIFIED",contextWindow:overrides.contextWindow||16000,maxOutputTokens:overrides.maxOutputTokens||4096,tokenizerId:overrides.tokenizerId||"tok-1",capabilities:overrides.capabilities}});}

test("family revision and endpoint identities are distinct and deterministic",()=>{const a=deployment(),b=deployment({endpoint:"ep2"});assert.equal(a.family.id,b.family.id);assert.equal(a.revision.id,b.revision.id);assert.notEqual(a.endpoint.id,b.endpoint.id)});
test("strict free proof rejects stale proof",()=>{const d=deployment();const g=model.hardEligibility(d,{requiredCapabilities:["chat"]},{now:"2026-10-14T14:00:00Z",freeProofMaxAgeMs:24*60*60*1000});assert.equal(g.eligible,false);assert.ok(g.reasons.includes("free_proof_stale"))});
test("paid endpoint is ineligible even with valid free model proof",()=>{const g=model.hardEligibility(deployment({pricing:"PAID"}),{}, {now});assert.equal(g.eligible,false);assert.ok(g.reasons.includes("paid_endpoint"))});
test("unknown pricing fails closed",()=>{const g=model.hardEligibility(deployment({pricing:"UNKNOWN"}),{}, {now});assert.equal(g.eligible,false);assert.ok(g.reasons.includes("pricing_unknown"))});
test("unknown quota is not mislabeled unlimited",()=>{const g=model.hardEligibility(deployment({quota:{status:"UNKNOWN"}}),{}, {now});assert.equal(g.eligible,true);assert.ok(g.uncertainties.includes("quota_unknown"));assert.equal(g.unlimited,false)});
test("exhausted external quota blocks route",()=>{const g=model.hardEligibility(deployment({quota:{status:"EXHAUSTED"}}),{}, {now});assert.equal(g.eligible,false);assert.ok(g.reasons.includes("quota_exhausted"))});
test("capability and context requirements are hard filters",()=>{const g=model.hardEligibility(deployment({contextWindow:4000,capabilities:{vision:false}}),{requiredCapabilities:["vision"],requiredContextTokens:8000},{now});assert.ok(g.reasons.includes("missing_capability:vision"));assert.ok(g.reasons.includes("context_window_insufficient"))});
test("unqualified endpoint cannot route",()=>{assert.equal(model.hardEligibility(deployment({qualification:"UNVERIFIED"}),{}, {now}).eligible,false)});
test("unverified outcomes cannot influence route score",()=>{const d=deployment();assert.equal(model.aggregateVerifiedOutcomes([{revisionId:d.revision.id,verified:false,quality:1}],d.revision.id),null)});
test("verified outcomes influence deterministic ranking",()=>{const a=deployment({endpoint:"a",revision:"r1"}),b=deployment({endpoint:"b",revision:"r2"});const out=[{revisionId:a.revision.id,verified:true,quality:.4,reliability:.5,efficiency:.6,latencyScore:.5},{revisionId:b.revision.id,verified:true,quality:.95,reliability:.95,efficiency:.9,latencyScore:.8}];const r=model.selectRoute({deployments:[a,b],task:{requiredCapabilities:["chat"]},outcomes:out,now});assert.equal(r.selected.revision.id,b.revision.id)});
test("champion remains baseline for immaterial score differences",()=>{const a=deployment({endpoint:"a",revision:"r1"}),b=deployment({endpoint:"b",revision:"r2"});const r=model.selectRoute({deployments:[a,b],task:{},championRevisionId:a.revision.id,outcomes:[],now});assert.equal(r.selected.revision.id,a.revision.id);assert.equal(r.reason,"champion-retained")});
test("route lease prevents needless thrash while still eligible",()=>{const a=deployment({endpoint:"a"}),first=model.selectRoute({deployments:[a],task:{},now}),lease=model.createRouteLease(first,{now,ttlMs:60000}),again=model.selectRoute({deployments:[a],task:{},lease,now:"2026-09-14T14:00:30Z"});assert.equal(again.reason,"lease-retained")});
test("same revision endpoint failover is preferred",()=>{const a=deployment({endpoint:"a"}),b=deployment({endpoint:"b"});const f=model.failoverEndpoint({failed:a,deployments:[a,b],task:{},now});assert.equal(f.status,"PASS");assert.equal(f.selected.revision.id,a.revision.id);assert.equal(f.reason,"same-revision-endpoint-failover")});
test("no eligible model is explicit terminal route state",()=>{const r=model.selectRoute({deployments:[deployment({pricing:"PAID"})],task:{},now});assert.equal(r.status,"NO_ELIGIBLE_MODEL");assert.equal(r.selected,null)});
test("model switch forces context recompile",()=>{const d=deployment();const h=model.contextHandshake({manifest:{modelProfileId:"other",tokenizerId:"tok-1"},deployment:d,requiredContextTokens:100});assert.equal(h.status,"RECOMPILE");assert.equal(h.reason,"model-profile-changed")});
test("tokenizer switch forces context recompile",()=>{const d=deployment();assert.equal(model.contextHandshake({manifest:{modelProfileId:d.revision.id,tokenizerId:"old"},deployment:d,requiredContextTokens:100}).status,"RECOMPILE")});
test("oversized mandatory context blocks before inference",()=>{const d=deployment({contextWindow:4000});assert.equal(model.contextHandshake({manifest:{modelProfileId:d.revision.id,tokenizerId:"tok-1"},deployment:d,requiredContextTokens:8000}).status,"BLOCKED")});
test("provider errors normalize bounded retry semantics",()=>{assert.equal(model.normalizeProviderError({status:429,message:"quota"}).retryable,true);assert.equal(model.normalizeProviderError({status:400}).retryable,false)});

test("high consequence raises verification floor independently of difficulty",()=>{const p=compute.allocateCompute({task:{difficulty:.05,consequence:.9,risk:"low"},resource:{tier:"lite"}});assert.equal(p.status,"PASS");assert.ok(p.floor.verificationPasses>=2)});
test("critical risk keeps verification floor under lite resources",()=>{const p=compute.allocateCompute({task:{risk:"critical",difficulty:.1},resource:{tier:"lite"}});assert.equal(p.status,"PASS");assert.ok(p.budget.verificationPasses>=3)});
test("resource ceiling cannot silently erase mandatory floor",()=>{const p=compute.allocateCompute({task:{risk:"critical",sideEffects:true},resource:{max:{reasoningUnits:1,retrievalUnits:1,contextTokens:1000,toolCalls:1,verificationPasses:1,candidates:1,retries:0,concurrency:1,recoveryReserve:0}}});assert.equal(p.status,"BLOCKED");assert.equal(p.reason,"mandatory-floor-exceeds-resource-ceiling")});
test("FAST preference reduces optional compute but not verification floor",()=>{const a=compute.allocateCompute({task:{difficulty:.9,risk:"high"},resource:{tier:"full"},preference:"FAST"}),b=compute.allocateCompute({task:{difficulty:.9,risk:"high"},resource:{tier:"full"},preference:"MAX_QUALITY"});assert.ok(a.budget.reasoningUnits<=b.budget.reasoningUnits);assert.ok(a.budget.verificationPasses>=a.floor.verificationPasses)});
test("compute pool prevents child budget minting",()=>{const pool=compute.createBudgetPool(compute.vector({reasoningUnits:4,retrievalUnits:2,contextTokens:1000,toolCalls:2,verificationPasses:2,candidates:2,retries:1,concurrency:1,recoveryReserve:1}));assert.equal(pool.allocate({reasoningUnits:3},{purpose:"a"}).allowed,true);assert.equal(pool.allocate({reasoningUnits:2},{purpose:"b"}).allowed,false)});
test("compute lease release never exceeds parent capacity",()=>{const cap=compute.vector({reasoningUnits:4});const pool=compute.createBudgetPool(cap),x=pool.allocate({reasoningUnits:3});pool.release(x.lease);pool.release(x.lease);assert.equal(pool.snapshot().remaining.reasoningUnits,4)});
test("verified success can early exit",()=>{const p=compute.allocateCompute({task:{},resource:{tier:"balanced"}}),d=compute.nextComputeAction({plan:p,checkpoint:{successCriteriaMet:true,verificationPassed:true,sideEffectsResolved:true}});assert.equal(d.action,"EARLY_EXIT")});
test("apparent success cannot early exit before verification",()=>{const p=compute.allocateCompute({task:{},resource:{tier:"balanced"}}),d=compute.nextComputeAction({plan:p,checkpoint:{successCriteriaMet:true,verificationPassed:false}});assert.equal(d.action,"VERIFY_NOW")});
test("cancel with unresolved side effects reconciles before exit",()=>{const p=compute.allocateCompute({task:{sideEffects:true},resource:{tier:"balanced"}}),d=compute.nextComputeAction({plan:p,checkpoint:{cancelRequested:true,sideEffectsResolved:false}});assert.equal(d.action,"VERIFY_NOW")});
test("bounded no-progress abandons as inconclusive",()=>{const p=compute.allocateCompute({task:{},resource:{tier:"balanced"}}),d=compute.nextComputeAction({plan:p,checkpoint:{noProgressCount:3,retriesLeft:0}});assert.equal(d.action,"ABANDON_AS_INCONCLUSIVE")});
test("resource plan never enables speculative background compute",()=>{const p=compute.allocateCompute({task:{difficulty:1},resource:{tier:"full"},preference:"MAX_QUALITY"});assert.equal(p.backgroundAllowed,false)});
test("marginal utility rewards verified gain per bounded cost",()=>{const good=compute.marginalUtility({before:{verifiedSuccess:.2,uncertainty:.8},after:{verifiedSuccess:.8,uncertainty:.3},cost:{reasoningUnits:2}}),bad=compute.marginalUtility({before:{verifiedSuccess:.2,uncertainty:.8},after:{verifiedSuccess:.25,uncertainty:.75},cost:{reasoningUnits:5}});assert.ok(good>bad)});
console.log(`model/compute polish: PASS (${count} assertions)`);
