const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const assert=require('assert/strict');
const ROOT=path.resolve(__dirname,'..');
const APK=path.join(ROOT,'android','app','build','outputs','apk','debug','app-debug.apk');
assert.ok(fs.existsSync(APK),'debug APK missing');
const bytes=fs.statSync(APK).size;
assert.ok(bytes<35*1024*1024,`APK too large: ${bytes}`);
const listing=spawnSync('unzip',['-l',APK],{encoding:'utf8'});
assert.equal(listing.status,0,listing.stderr);
assert.match(listing.stdout,/assets\/public\/index\.html/);
assert.match(listing.stdout,/assets\/public\/ultimate-app\.js/);
assert.match(listing.stdout,/assets\/public\/ultimate-build\.json/);
assert.match(listing.stdout,/assets\/public\/seven-packaging\.json/);
assert.match(listing.stdout,/classes(?:\d*)?\.dex/);
const html=spawnSync('unzip',['-p',APK,'assets/public/index.html'],{encoding:'utf8',maxBuffer:8*1024*1024});
assert.equal(html.status,0,html.stderr);
assert.ok(html.stdout.includes('SEVEN_ULTIMATE_RELEASE_V1'),'Ultimate release marker missing from APK');
assert.ok(html.stdout.includes('ultimate-app.js'),'Ultimate app bundle is not loaded by APK');
const manifest=spawnSync('unzip',['-p',APK,'assets/public/seven-packaging.json'],{encoding:'utf8'});
assert.equal(manifest.status,0,manifest.stderr);
const payload=JSON.parse(manifest.stdout);
assert.equal(payload.format,'seven-android-ultimate-payload');
assert.equal(payload.build,'seven-ultimate-integrated-v1');
console.log(`Ultimate APK package gate: PASS (${bytes} bytes)`);
