const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const assert=require('assert/strict');
const ROOT=path.resolve(__dirname,'..');
const DEFAULT_APK=path.join(ROOT,'android','app','build','outputs','apk','debug','app-debug.apk');
const APK=path.resolve(process.env.SEVEN_APK_PATH||process.argv[2]||DEFAULT_APK);
assert.ok(fs.existsSync(APK),`APK missing: ${APK}`);
const bytes=fs.statSync(APK).size;
assert.ok(bytes<30*1024*1024,`APK too large: ${bytes}`);
const listing=spawnSync('unzip',['-l',APK],{encoding:'utf8'});
assert.equal(listing.status,0,listing.stderr);
assert.match(listing.stdout,/assets\/public\/index\.html/);
assert.match(listing.stdout,/assets\/public\/vendor\/pdfjs\/pdf\.min\.mjs/);
assert.match(listing.stdout,/assets\/public\/workspaces\/remake\.css/);
assert.match(listing.stdout,/assets\/public\/workspaces\/remake\.js/);
assert.match(listing.stdout,/assets\/public\/workspaces\/intelligence\.js/);
assert.match(listing.stdout,/assets\/public\/workspaces\/research-v2\.js/);
assert.match(listing.stdout,/classes(?:\d*)?\.dex/);
const html=spawnSync('unzip',['-p',APK,'assets/public/index.html'],{encoding:'utf8',maxBuffer:8*1024*1024});
assert.equal(html.status,0,html.stderr);
assert.ok(html.stdout.includes('SEVEN_FINAL_RELEASE_LAYER_V1'),'release marker missing from APK');
assert.ok(html.stdout.includes('id="seven-app"')&&html.stdout.includes('data-seven-remake="1"'),'modern Seven UI root missing from APK');
assert.ok(html.stdout.includes('./workspaces/remake.css')&&html.stdout.includes('./workspaces/remake.js')&&html.stdout.includes('./workspaces/intelligence.js'),'modern Seven UI wiring missing from APK');
assert.ok(!html.stdout.includes('cdnjs.cloudflare.com/ajax/libs/pdf.js'),'APK still references remote PDF runtime');
assert.ok(html.stdout.includes('Seven 2.4.2 Zero-Key UX'),'zero-key marker missing from APK');
assert.ok(!html.stdout.includes('id="apiKeyInput"')&&!html.stdout.includes('id="nvidiaApiKeyInput"')&&!html.stdout.includes('id="openrouterApiKeyInput"')&&!html.stdout.includes('id="geminiApiKeyInput"')&&!html.stdout.includes('id="llm7TokenInput"'),'APK still contains manual API-key fields');
const bundledRemakeCss=spawnSync('unzip',['-p',APK,'assets/public/workspaces/remake.css'],{encoding:'utf8',maxBuffer:4*1024*1024});
assert.equal(bundledRemakeCss.status,0,bundledRemakeCss.stderr);
assert.ok(bundledRemakeCss.stdout.includes('--seven-ui-hardening-v242:1'),'APK missing bundled UI hardening layer');
const bundledRemakeJs=spawnSync('unzip',['-p',APK,'assets/public/workspaces/remake.js'],{encoding:'utf8',maxBuffer:4*1024*1024});
assert.equal(bundledRemakeJs.status,0,bundledRemakeJs.stderr);
assert.ok(!bundledRemakeJs.stdout.includes('s-brave-key'),'APK still contains manual Brave key control');
assert.ok(!bundledRemakeJs.stdout.includes('Brave API key'),'APK still asks for a Brave API key');
assert.ok(!bundledRemakeJs.stdout.includes('Enter API key'),'APK still contains manual API-key prompt');

console.log(`apk package gate: PASS (${path.basename(APK)}, ${bytes} bytes)`);
